### ISSUE TITLE
Problems parsing the field applicationName / $PROGNAME

### ISSUE THREAD

**Issue by jpereira** [syslog-ng/syslog-ng#1022]
Hi,

I have a nginx server pointing to a local syslog-ng instance.

```
server {
  ...
  access_log syslog:server=unix:/var/run/syslog-ng_nginx.sock,facility=local7,tag=www_myhost_com,severity=info cache_with_fingerprint;
  ...
}
```

My local syslog-ng receive and re-transmit to a remote collector.

```
source s_nginx {
    unix_dgram("/var/run/syslog-ng_nginx.sock");
};

destination d_collector {
    tcp("collector01-syslog-ng.intranet.lan" port(514)
    );
};

log {
    source(s_nginx);
    destination(d_collector);
};
```

My remote collector running in another node with the below setup.

```
options {
    flush_lines(0);
    chain_hostnames(off); 
    stats_freq(0);
};
source s_net {
    tcp(ip(0.0.0.0) port(514));
};
destination d_net_nginx {
    file("/var/log/syslog-ng/${HOST}/${PROGRAM}-${HOSTNAME}_nginx_access-${YEAR}${MONTH}${DAY}.log" 
         create_dirs(yes)
    );
};

log {
    source(s_net);
    destination(d_net_nginx);
};
```

The server receives correctly the logs sent by nginx, but make a wrong parser of directory destination as below example.

```
#tail -1 /var/log/syslog-ng/15.23.6.2/-_nginx_access-20160413.log 
Apr 13 22:31:38 15.23.6.2 node01-syslog-ng www_myhost_com: { "@timestamp": "2016-04-13T22:31:38+00:00", "clientip": "19.15.4.11", "auth": "-", "timestamp": "13/Apr/2016:22:31:38 +0000", "verb": "GET", "request": "/?1234", "__server_protocol__": "HTTP/1.1", "response": 502, "bytes": 1965, "referrer": "-", "agent": "curl/7.43.0", "hostname": "www.myhost.com", "host": "node01-syslog-ng", "upstream": "-" }
#
```

Notice the wrong parser of the directory.

```
#tail -1 /var/log/syslog-ng/15.23.6.2/-_nginx_access-20160413.log 
```

In which case it would be expected:

```
/var/log/syslog-ng/15.23.6.2/www_myhost_com-node01-syslog_nginx_access-20160413.log 
```

p.s: It was tried with the version 3.5.3-1 and latest 3.7.3.

**Comment by divious1** [comment]
+1 same issue here

**Comment by pasztor** [comment]
I created a reproduction environment, to test what is this.
On the nginx machine side, I experienced this:
[2016-04-14T16:02:03.837078] Incoming log entry; line='<190>Apr 14 16:02:03 debian www_myhost_com: 10.20.0.34 - - [14/Apr/2016:16:02:03 +0200] "GET / HTTP/1.1" 200 867 "-" "Wget/1.16.1 (linux-gnu)"'
[2016-04-14T16:02:03.837852] Outgoing message; message='<190>Apr 14 16:02:03 debian debian www_myhost_com: 10.20.0.34 - - [14/Apr/2016:16:02:03 +0200] "GET / HTTP/1.1" 200 867 "-" "Wget/1.16.1 (linux-gnu)"\x0a'

I used your simplified version of config.
I do not understand yet, why is this doubles the hostname. But, I think, the source of problem is this.
I hope, this helps.
Test environment:
* Debian 8.0,
* nginx-extras package 1.9.10 from jessie backports repo,
* syslog-ng 3.7.3 from obs repo

**Comment by jpereira** [comment]
Hi @pasztor,

This macro is internally used in my setup. the problem is with nginx, in special in this peace of code at nginx-1.9.7/src/core/ngx_syslog.c

```
ngx_syslog_add_header(ngx_syslog_peer_t *peer, u_char *buf)
{
    ngx_uint_t  pri;

    pri = peer->facility * 8 + peer->severity;

    if (peer->nohostname) {
        return ngx_sprintf(buf, "<%ui>%V %V: ", pri, &ngx_cached_syslog_time,
                           &peer->tag);
    }

    return ngx_sprintf(buf, "<%ui>%V %V %V: ", pri, &ngx_cached_syslog_time,
                       &ngx_cycle->hostname, &peer->tag);
}
```

They have the option 'nohostname' that should remove the hostname avoiding repeated values. but, the syslog-ng ignore add append the field two times.
