### ISSUE TITLE
Python destination module and the documents are out of sync.

### ISSUE THREAD

**Issue by knoguchi** [syslog-ng/syslog-ng#1036]
It seems the Python destination module and the documents are out of sync.  syslong-ng failed to start up when I put the arguments for the init method in the `python()` by following the documents.    My work-around was to put the arguments inside of `python(options(...))`.  

Is the document outdated or the Python destination module incomplete?  Here is the detail.

I'm using syslog-ng 3.7.3 on Ubuntu 15.10.  The binary package was downloaded from [Laszlo's repo ](http://download.opensuse.org/repositories/home:/laszlo_budai:/syslog-ng/xUbuntu_15.10/amd64/)

Following the [syslog-ng gitbooks](https://syslog-ng.gitbooks.io/getting-started/content/chapters/chapter_5/section_3.html) I created the python destination however syslog-ng failed to startup.

```
destination python_to_kafka {
            python(
                class("pythonkafka.KafkaDestination")
                on-error("fallback-to-string")

                host("127.0.0.1")
                port("9092")
                topic("testtopic")
                value-pairs(scope(rfc5424))
            );
};
```

Here is the error message:

> Apr 30 16:41:10 lx syslog-ng[14179]: Error parsing python, inner-dest plugin host not found in /etc/syslog-ng/conf.d/python-example.conf at line 10
> Apr 30 16:41:10 lx syslog-ng[14179]: included from /etc/syslog-ng/syslog-ng.conf line 163, column 1
> Apr 30 16:41:10 lx syslog-ng[14179]: host("127.0.0.1")
> Apr 30 16:41:10 lx syslog-ng[14179]: ^^^^

The `host`, `port`, and `topic` and other keys and values are supposed to be passed as dict to the `init` method of the KafkaDestination class.  I found the work around after reading the source of the Python module.  This configuration works fine.

```
destination python_to_kafka {
            python(
                class("pythonkafka.KafkaDestination")
                on-error("fallback-to-string")
                options(
                    host("127.0.0.1")
                    port("9092")
                    topic("testtopic")
                )
                value-pairs(scope(rfc5424))
            );
};
```

**Comment by MrAnno** [comment]
The Python module has undergone many improvements recently, thanks to which the interface has been documented with code.

https://syslog-ng-future.blog/syslog-ng-4-improves-python-support/

https://github.com/syslog-ng/syslog-ng/tree/master/modules/python-modules/syslogng
