### ISSUE TITLE
Enhancement: json-parser and arrays

### ISSUE THREAD

**Issue by faxm0dem** [syslog-ng/syslog-ng#1073]
Currently, `json-parser` will parse an array into key-values with an index in the key: `{"foo":["bar","baz"]}` → `{"foo[0]": "bar","foo[1]":"baz"}`. IMHO as long as there is no array support in syslog-ng, it would be saner and more consistent (see `$TAGS`)  to yield a coma-separated list instead: `{"foo":"bar,baz"}`

**Comment by faxm0dem** [comment]
I realize the proposed change would break nested objects like `{"foo":[{"a":"b"},"c"]}`.
I guess there is no good solution as long as syslog-ng doesn't support arrays internally.

**Comment by faxm0dem** [comment]
one way to handle this would be to have `format-json` do the symmetric operation, *i.e.* `{"foo[0]": "bar","foo[1]":"baz"}` → `{"foo":["bar","baz"]}` what do you think?

**Comment by bazsi** [comment]
I am working on list support by using comma separation like in the first
example.

That would make it pretty easy to integrate arrays as a concept. I'll try
to publish that branch in the coming days.

**Comment by erempel** [comment]
While you are in this cde, can you please fix issue #999 for unicode log lines.

**Comment by du291** [comment]
Any progress on this? Are there plans to support JSON arrays (somehow) in syslog-ng?

**Comment by nzlosh** [comment]
Will this issue add support for the _null_ and _object_ data types too?

**Comment by pradipkumarr** [comment]
Is this functionality added, I am facing the same issue while parsing the array using JSON parser, it is like 
`data.minions[0]', value='minion-1', data.minions[1]', value='minion-2', data.minions[2]', value='win-minion108'`
the arraylist is unpredictable, it would be good if it can be like this:
`data.minions, value='minion-1, minion-2, win-minion108'`

**Comment by gaborznagy** [comment]
@pradipkumarr Thank you for your interest!
Arrays as comma-separated list is not supported currently in json-parser (it works as an indexed, separate keys, see description).

I cannot give you any deadline when we will pick up this feature request, but we always welcome and support any community pull request with high priority.

**Comment by gaborznagy** [comment]
Array support is added in #3885. See details in b7364f240296bc14513356099a3d44438df08ede.

Consider the following input:
```
{    
    "array": [ 1, 2, 3 ],    
}
```
An example output with config `json-parser(prefix(".json.")) and $(format-json .json.*)` output BEFORE #3885:
```
{    
    "_json": { 
        "array[2]": "3",    
        "array[1]": "2",    
        "array[0]": "1"    
    }    
}    
```
after #3885:
```
{    
    "_json": {    
        "array": "1,2,3"    
    }    
}    
```
With type-support after #3885 json array automatically created from a previously parsed array (using `@version: 4.0`):
(or from any other list, e.g. created by the list-handling template functions)
```
{    
    "_json": { 
        "array": [ "1", "2", "3" ] 
    }
}  
```

You can use the list-handling [template functions](https://www.syslog-ng.com/technical-documents/doc/syslog-ng-open-source-edition/3.33/administration-guide/68#TOPIC-1663419) to handle the parsed arrays, for example with `$(implode)`, `$(list-nth)`
