### ISSUE TITLE
Create SCL for sumologic

### ISSUE THREAD

**Issue by fekete-robert** [syslog-ng/syslog-ng#1077]
Similarly to the Loggly and Logmatic, we could create an SCL for sumologic as well:

https://help.sumologic.com/Beta/Beta_-_Sources/Beta_-_Cloud_Syslog_Source#Configuring_a_Cloud_Syslog_Source_for_Syslog-NG

(on an unrelated note, we should update the scls to use the network driver instead of the outdated tcp driver)

**Comment by chawlanikhil24** [comment]
Hi, can i work on this issue?

**Comment by fekete-robert** [comment]
Sure, many thanks for it!
