### ISSUE TITLE
Segfault libsyslog-ng-3.7.so.0

### ISSUE THREAD

**Issue by radanliska** [syslog-ng/syslog-ng#1089]
When I start the syslog-ng daemon, it immediately stop working with segfault error.

The syslog message is:
Jun 14 16:37:58 XXXXXXXX kernel: : syslog-ng-app[26286]: **segfault at 6ba000 ip 00007f1c2a228780 sp 00007f1c2953b3a0 error 4 in libsyslog-ng-3.7.so.0[7f1c2a1cc000+a0000]**
Jun 14 16:37:58 XXXXXXXX supervise/syslog-ng[26284]: Daemon exited due to a deadlock/signal/failure, restarting; exitcode='11'

My configuration is:

```
#############################################################################
# Default syslog-ng.conf file which collects all local logs into a
# single file called /var/log/xxxxxxxxx.
#

@version: 3.7
#@include "scl.conf"

options {
#        time_sleep(20);
        time_reopen (600);
        use_fqdn (no);
        use_dns(no);
        stats_freq(3600);
        #stats_level(0);
        mark_freq(600);
#        log_iw_size(800);
#        log_fifo_size(250000);
        keep_hostname (no);
        chain_hostnames(no);
#        flush_lines (400);
#        flush_timeout(200);
        log_msg_size(32768);
#        log_fetch_limit(400);


        };

source s_logs {
file("/xxxxxxxxxxxxxxx"  flags(no-parse)  follow_freq(1)  );
file("/xxxxxxxxxxxxxxx.log"  flags(no-parse)  follow_freq(1)  );
file("/xxxxxxxxxxxxxxx.log"  flags(no-parse)  follow_freq(1)  );
file("/xxxxxxxxxxxxxxx.log"  flags(no-parse)  follow_freq(1)  );
file("/xxxxxxxxxxxxxxx.log"  flags(no-parse)  follow_freq(1)  );
file("/xxxxxxxxxxxxxxx.log"  flags(no-parse)  follow_freq(1)  );
file("/xxxxxxxxxxxxxxx.log"  flags(no-parse)  follow_freq(1)  );
file("/xxxxxxxxxxxxxxx.log"  flags(no-parse)  follow_freq(1)  );
file("/xxxxxxxxxxxxxxx.log"  flags(no-parse)  follow_freq(1)  );
};

source s_local {
        internal();
};
rewrite r_add_filename { set("$FILE_NAME $PID" value("PID"));};


# Destinations: local files, the console, and the remote syslog server

destination d_local {
          file ( "/xxxxxxxxxxxxxxx.log" );
};



destination d_cl1_tcp {
                syslog("xxxxxxxxxxxxxxx.xx"
                port(5153)
                throttle(1000)
                so_keepalive(no)
                );};

destination d_cl2_tcp {
                syslog("xxxxxxxxxxxxxxx.xx"
                port(5153)
                throttle(1000)
                so_keepalive(no)
                );};
log {
        source(s_local);
        destination(d_local);
        flags(flow-control);
};
log {
        source(s_logs);
        rewrite(r_add_filename);
        destination(d_cl1_tcp);
};
log {
        source(s_logs);
        rewrite(r_add_filename);
        destination(d_cl2_tcp);
};
```

**Comment by bazsi** [comment]
Hi,

Isnt it possible that you happen to have two libsyslog-ng.so files in the
syslog-ng lib directory?

How did you install the syslog-ng binaries? From source?

**Comment by Radan16** [comment]
Hello,

I have compiled the syslog-ng from source.
I have about 1000 instances of syslog-ng in our company and only 3 instances have this error.


Path is:
```
[root@xxxxxxxx sbin]# pwd
/opt/syslog-ng-os-3.7.1/sbin
```


Shared library dependencies are:
```
[root@xxxxxxxx sbin]# ldd /opt/syslog-ng-os-3.7.1/sbin/syslog-ng
 linux-vdso.so.1 =>  (0x00007ffe37556000)
 libsyslog-ng-3.7.so.0 => /opt/syslog-ng-os-3.7.1/lib/libsyslog-ng-3.7.so.0 (0x00007f114322f000)
 libnsl.so.1 => /lib64/libnsl.so.1 (0x0000003a9fc00000)
 libgmodule-2.0.so.0 => /lib64/libgmodule-2.0.so.0 (0x0000003aa1c00000)
 libgthread-2.0.so.0 => /lib64/libgthread-2.0.so.0 (0x0000003aa0000000)
 librt.so.1 => /lib64/librt.so.1 (0x0000003a9e400000)
 libglib-2.0.so.0 => /lib64/libglib-2.0.so.0 (0x0000003a9f400000)
 libevtlog.so.0 => /opt/syslog-ng-os-3.7.1/lib/libevtlog.so.0 (0x00007f114301e000)
 libpcre.so.0 => /lib64/libpcre.so.0 (0x0000003a9dc00000)
 libdl.so.2 => /lib64/libdl.so.2 (0x0000003a9e000000)
 libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f1142e00000)
 libc.so.6 => /lib64/libc.so.6 (0x0000003a9d800000)
 libssl.so.10 => /usr/lib64/libssl.so.10 (0x0000003aa8c00000)
 libcrypto.so.10 => /usr/lib64/libcrypto.so.10 (0x0000003aa4800000)
 /lib64/ld-linux-x86-64.so.2 (0x0000003a9d400000)
 libgssapi_krb5.so.2 => /lib64/libgssapi_krb5.so.2 (0x0000003aa6800000)
 libkrb5.so.3 => /lib64/libkrb5.so.3 (0x0000003aa7c00000)
 libcom_err.so.2 => /lib64/libcom_err.so.2 (0x0000003aa0800000)
 libk5crypto.so.3 => /lib64/libk5crypto.so.3 (0x0000003aa7000000)
 libz.so.1 => /lib64/libz.so.1 (0x0000003a9ec00000)
 libkrb5support.so.0 => /lib64/libkrb5support.so.0 (0x0000003aa6400000)
 libkeyutils.so.1 => /lib64/libkeyutils.so.1 (0x0000003aa6000000)
 libresolv.so.2 => /lib64/libresolv.so.2 (0x0000003a9f800000)
 libselinux.so.1 => /lib64/libselinux.so.1 (0x0000003a9f000000)
```


I have only one library libsyslog-ng.so
```
[root@xxxxxxxx ~]# find / -name 'libsyslog-ng.so'
/opt/syslog-ng-os-3.7.1/lib/libsyslog-ng.so
```


Libraries in the lib folder are:
```
[root@xxxxxxxx ~]# ls -l /opt/syslog-ng-os-3.7.1/lib/
total 8996
-rwxr-xr-x. 1 root root    5075 Aug 17  2015 init-functions
-rwxr-xr-x. 1 root root   51072 Jan 13 14:29 libevtlog.so.0
-rwxr-xr-x. 1 root root  656770 Jan 13 14:29 librdkafka.so.1
-rwxr-xr-x. 1 root root 2825612 Jan  5 10:28 libsyslog-ng-3.7.so.0
-rwxr-xr-x. 1 root root 2825612 Jan  5 10:28 libsyslog-ng-3.7.so.0.0.0
-rwxr-xr-x. 1 root root    1135 Jan  5 10:28 libsyslog-ng.la
-rwxr-xr-x. 1 root root 2825612 Jan  5 10:28 libsyslog-ng.so
drwxr-xr-x. 2 root root    4096 Jun  9 23:55 pkgconfig
drwxr-xr-x. 3 root root    4096 Jun  9 23:55 syslog-ng
```

**Comment by bazsi** [comment]
Hi,

can you please post a backtrace? if you compiled syslog-ng from source, you
probably have debug symbols, so a backtrace would be helpful finding out
the root cause of the problem.

Can you either run syslog-ng under gdb & wait for it to crash or enable
core files (using --enable-core command line option or ulimit -c) and then

gdb <path/to/syslog-ng> <path/to/core>

And then in the gdb prompt, invoke the command: "bt full" and post the
results.

Thanks.


-- 
Bazsi

**Comment by Radan16** [comment]
Hello,

here is the result.


Thank you very much for your help.


[root@XXXXXXXX ~]# gdb /opt/syslog-ng-os-3.7.1/sbin/syslog-ng /opt/syslog-ng-os-3.7.1/var/run/core.12700
GNU gdb (GDB) Red Hat Enterprise Linux (7.2-83.el6)
Copyright (C) 2010 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /opt/syslog-ng-os-3.7.1/sbin/syslog-ng...(no debugging symbols found)...done.

warning: core file may not match specified executable file.
[New Thread 12703]
[New Thread 12700]
[New Thread 12715]
Reading symbols from /opt/syslog-ng-os-3.7.1/lib/libsyslog-ng-3.7.so.0...done.
Loaded symbols for /opt/syslog-ng-os-3.7.1/lib/libsyslog-ng-3.7.so.0
Reading symbols from /lib64/libnsl-2.12.so...Reading symbols from /usr/lib/debug/lib64/libnsl-2.12.so.debug...done.
done.
Loaded symbols for /lib64/libnsl-2.12.so
Reading symbols from /lib64/libgmodule-2.0.so.0.2800.8...Reading symbols from /usr/lib/debug/lib64/libgmodule-2.0.so.0.2800.8.debug...done.
done.
Loaded symbols for /lib64/libgmodule-2.0.so.0.2800.8
Reading symbols from /lib64/libgthread-2.0.so.0.2800.8...Reading symbols from /usr/lib/debug/lib64/libgthread-2.0.so.0.2800.8.debug...done.
done.
Loaded symbols for /lib64/libgthread-2.0.so.0.2800.8
Reading symbols from /lib64/librt-2.12.so...Reading symbols from /usr/lib/debug/lib64/librt-2.12.so.debug...done.
done.
Loaded symbols for /lib64/librt-2.12.so
Reading symbols from /lib64/libglib-2.0.so.0.2800.8...Reading symbols from /usr/lib/debug/lib64/libglib-2.0.so.0.2800.8.debug...done.
done.
Loaded symbols for /lib64/libglib-2.0.so.0.2800.8
Reading symbols from /opt/syslog-ng-os-3.7.1/lib/libevtlog.so.0...done.
Loaded symbols for /opt/syslog-ng-os-3.7.1/lib/libevtlog.so.0
Reading symbols from /lib64/libpcre.so.0.0.1...Reading symbols from /usr/lib/debug/lib64/libpcre.so.0.0.1.debug...done.
done.
Loaded symbols for /lib64/libpcre.so.0.0.1
Reading symbols from /lib64/libdl-2.12.so...Reading symbols from /usr/lib/debug/lib64/libdl-2.12.so.debug...done.
done.
Loaded symbols for /lib64/libdl-2.12.so
Reading symbols from /lib64/libpthread-2.12.so...Reading symbols from /usr/lib/debug/lib64/libpthread-2.12.so.debug...done.
[Thread debugging using libthread_db enabled]
done.
Loaded symbols for /lib64/libpthread-2.12.so
Reading symbols from /lib64/libc-2.12.so...Reading symbols from /usr/lib/debug/lib64/libc-2.12.so.debug...done.
done.
Loaded symbols for /lib64/libc-2.12.so
Reading symbols from /usr/lib64/libssl.so.1.0.1e...Reading symbols from /usr/lib/debug/usr/lib64/libssl.so.1.0.1e.debug...done.
done.
Loaded symbols for /usr/lib64/libssl.so.1.0.1e
Reading symbols from /usr/lib64/libcrypto.so.1.0.1e...Reading symbols from /usr/lib/debug/usr/lib64/libcrypto.so.1.0.1e.debug...done.
done.
Loaded symbols for /usr/lib64/libcrypto.so.1.0.1e
Reading symbols from /lib64/ld-2.12.so...Reading symbols from /usr/lib/debug/lib64/ld-2.12.so.debug...done.
done.
Loaded symbols for /lib64/ld-2.12.so
Reading symbols from /lib64/libgssapi_krb5.so.2.2...Reading symbols from /usr/lib/debug/lib64/libgssapi_krb5.so.2.2.debug...done.
done.
Loaded symbols for /lib64/libgssapi_krb5.so.2.2
Reading symbols from /lib64/libkrb5.so.3.3...Reading symbols from /usr/lib/debug/lib64/libkrb5.so.3.3.debug...done.
done.
Loaded symbols for /lib64/libkrb5.so.3.3
Reading symbols from /lib64/libcom_err.so.2.1...Reading symbols from /usr/lib/debug/lib64/libcom_err.so.2.1.debug...done.
done.
Loaded symbols for /lib64/libcom_err.so.2.1
Reading symbols from /lib64/libk5crypto.so.3.1...Reading symbols from /usr/lib/debug/lib64/libk5crypto.so.3.1.debug...done.
done.
Loaded symbols for /lib64/libk5crypto.so.3.1
Reading symbols from /lib64/libz.so.1.2.3...Reading symbols from /usr/lib/debug/lib64/libz.so.1.2.3.debug...done.
done.
Loaded symbols for /lib64/libz.so.1.2.3
Reading symbols from /lib64/libkrb5support.so.0.1...Reading symbols from /usr/lib/debug/lib64/libkrb5support.so.0.1.debug...done.
done.
Loaded symbols for /lib64/libkrb5support.so.0.1
Reading symbols from /lib64/libkeyutils.so.1.3...Reading symbols from /usr/lib/debug/lib64/libkeyutils.so.1.3.debug...done.
done.
Loaded symbols for /lib64/libkeyutils.so.1.3
Reading symbols from /lib64/libresolv-2.12.so...Reading symbols from /usr/lib/debug/lib64/libresolv-2.12.so.debug...done.
done.
Loaded symbols for /lib64/libresolv-2.12.so
Reading symbols from /lib64/libselinux.so.1...Reading symbols from /usr/lib/debug/lib64/libselinux.so.1.debug...done.
done.
Loaded symbols for /lib64/libselinux.so.1
Reading symbols from /lib64/libnss_files-2.12.so...Reading symbols from /usr/lib/debug/lib64/libnss_files-2.12.so.debug...done.
done.
Loaded symbols for /lib64/libnss_files-2.12.so
Reading symbols from /opt/syslog-ng-os-3.7.1/lib/syslog-ng/libaffile.so...done.
Loaded symbols for /opt/syslog-ng-os-3.7.1/lib/syslog-ng/libaffile.so
Reading symbols from /opt/syslog-ng-os-3.7.1/lib/syslog-ng/libafsocket.so...done.
Loaded symbols for /opt/syslog-ng-os-3.7.1/lib/syslog-ng/libafsocket.so
Reading symbols from /opt/syslog-ng-os-3.7.1/lib/syslog-ng/libsyslogformat.so...done.
Loaded symbols for /opt/syslog-ng-os-3.7.1/lib/syslog-ng/libsyslogformat.so
Core was generated by `/opt/syslog-ng-os-3.7.1/sbin/syslog-ng-app -p /opt/syslog-ng/var/run/syslog-ng-'.
Program terminated with signal 11, Segmentation fault.
#0  __strlen_sse42 () at ../sysdeps/x86_64/multiarch/strlen-sse4.S:32
32              pcmpeqb (%rdi), %xmm1












(gdb) bt full
#0  __strlen_sse42 () at ../sysdeps/x86_64/multiarch/strlen-sse4.S:32
No locals.
#1  0x00007ffff7d8c7e0 in log_msg_set_value (self=0x7ffdf7fe1010, handle=3, value=0x6b6071 <Address 0x6b6071 out of bounds>, value_len=-70294) at lib/logmsg.c:511
        name = 0x628db0 "MESSAGE"
        name_len = <value optimized out>
        new_entry = 0
        __PRETTY_FUNCTION__ = "log_msg_set_value"
#2  0x00007ffff70ca7e3 in syslog_format_handler (parse_options=0x650790, data=0x6b6071 <Address 0x6b6071 out of bounds>, length=18446744073709481322, self=0x7ffdf7fe1010)
    at modules/syslogformat/syslog-format.c:1093
        success = <value optimized out>
        p = <value optimized out>
#3  0x00007ffff7d8c8d5 in log_msg_new (msg=0x6b6071 <Address 0x6b6071 out of bounds>, length=-9911, saddr=0x0, parse_options=0x650790) at lib/logmsg.c:1126
        self = 0x7ffdf7fe1010
#4  0x00007ffff7d90380 in log_reader_handle_line (self=0x64fe90) at lib/logreader.c:311
        m = <value optimized out>
#5  log_reader_fetch_log (self=0x64fe90) at lib/logreader.c:380
        bookmark = <value optimized out>
        msg = 0x6b6071 <Address 0x6b6071 out of bounds>
        msg_len = 18446744073709541705
        status = <value optimized out>
        msg_count = 6
        may_read = 1
        aux = {peer_addr = 0x0, data =
    "\000\000\000\000\000\000\000\000\220\t\000\360\377\177\000\000@Jj\000\000\000\000\000\200\300b\000\000\000\000\000\000%\f\367\377\177\000\000\220\t\000\360\377\177\000\000\000\000\000\000\000\000\000\000\003\000\000\000\000\000\000\000$\023\334\367\377\177\000\000\260'\f\367\377\177\000\000xJj\000\000\000\000\000\060\n\000\360\377\177\000\000_\001\334\367\377\177\000\000\000%\f\367\377\177\000\000\000%\f\367\377\177\000\000\260'\f\367\377\177\000\000\b\000\000\000\000\000\000\000\230\t\000\360\377\177\000\000\250\t\000\360\377\177\000\000\320\t\000\360\377\177\000\000\t\031\334\367\377\177\000\000\001\000\000\000\000\000\000\000\266'\f\367\377\177\000\000\267'\f\367\377\177\000\000\260'\f\367\377\177\000\000\267'\f\367\377\177", '\000' <repeats 42 times>, "\\\346\325\367\004\000\000\000\340%\f\367\377\177\000\000\300\063j\000\000\000\000\000\320&\f\367\377\177\000\000\001\000\000\000\000\000\000\000P'\f\367\377\177\000\000"..., end_ptr = 0}
        __PRETTY_FUNCTION__ = "log_reader_fetch_log"
#6  0x00007ffff7d904c9 in log_reader_work_perform (s=<value optimized out>) at lib/logreader.c:86
        self = 0x64fe90
#7  0x00007ffff7d97fad in _work (self=<value optimized out>) at lib/mainloop-io-worker.c:52
No locals.
#8  0x00007ffff7dc11ca in iv_work_thread_do_work (_thr=0x6a4a40) at iv_work.c:118
        work = 0x650020
        thr = 0x6a4a40
        pool = 0x62c080
        last_seq = 8435
#9  0x00007ffff7dc052a in iv_run_tasks (st=0x7ffff00008c0) at iv_task.c:48
        t = <value optimized out>
        tasks = {next = 0x7ffff70c2970, prev = 0x7ffff70c2970}
#10 0x00007ffff7dc274c in iv_main () at iv_main_posix.c:106
        to = {tv_sec = 0, tv_nsec = 0}
        st = 0x7ffff00008c0
#11 0x00007ffff7dc0fe1 in iv_work_thread (_thr=0x6a4a40) at iv_work.c:200
        thr = 0x6a4a40
        pool = 0x62c080
#12 0x00007ffff7dc31b8 in iv_thread_handler (_thr=0x6a46b0) at iv_thread_posix.c:142
        __cancel_buf = {__cancel_jmp_buf = {{__cancel_jmp_buf = {140737338169088, -1730941263188842535, 140737349157728, 140737338169792, 0, 3, 1730956825264662489,
    1730958612779902937}, __mask_was_saved = 0}}, __pad = {0x7ffff70c2b10, 0x0, 0x7ffff70c5700, 0x7ffff70c5700}}
        __cancel_routine = 0x7ffff7dc3130 <iv_thread_cleanup_handler>
        __cancel_arg = 0x6a46b0
        not_first_call = <value optimized out>
        thr = 0x6a46b0
#13 0x00007ffff792baa1 in start_thread (arg=0x7ffff70c5700) at pthread_create.c:301
        __res = <value optimized out>
        pd = 0x7ffff70c5700
        now = <value optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140737338169088, -1730941263188842535, 140737349157728, 140737338169792, 0, 3, 1730956825300314073, 1730958075650648025},
              mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <value optimized out>
        pagesize_m1 = <value optimized out>
        sp = <value optimized out>
        freesize = <value optimized out>
#14 0x0000003a9d8e893d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:115
No locals.

**Comment by Kokan** [comment]
It seems like the length variable is unreasonable large value:
```
#2 0x00007ffff70ca7e3 in syslog_format_handler (parse_options=0x650790, data=0x6b6071 <Address 0x6b6071 out of bounds>, length=18446744073709481322, self=0x7ffdf7fe1010)
```
See length is equal 18446744073709481322, that is interpreted at some point as negative number. Causing `log_msg_set_value` to check the input size, which possible is not `\0` terminated. Causing the crash.

If you could possibly provide the message that could trigger such an event would be really good.
Possibly fuzzing the logproto could find this, I guess.

But as this is kinda an old issue, reproduced in an old version of syslog-ng I am closing it. Please feel free to open if you have additional information about the issue.
