### ISSUE TITLE
systemd-journal: Add option to specify start position

### ISSUE THREAD

**Issue by matwey** [syslog-ng/syslog-ng#1091]
Hello,

In order to avoid issues like the following:
https://lists.balabit.hu/pipermail/syslog-ng/2016-June/023030.html

There should be a way to set up initial journald cursor position in syslog-ng configuration.

**Comment by HofiOne** [comment]
i guess the new [matches()](https://syslog-ng.github.io/admin-guide/060_Sources/190_systemd-journal/000_systemd-journal_options#matches) option solves this
