### ISSUE TITLE
tcp-keepalive-time() is set but no TCP_KEEPIDLE setsockopt on this platform;

### ISSUE THREAD

**Issue by ryansch** [syslog-ng/syslog-ng#1146]
I'm getting this message with linux kernel version 4.4.10 with syslog-ng 3.7 using both the official docker container running debian and another one running alpine (installed via apk).  I can't figure out how this compile time option would be unset and I haven't been able to build syslog-ng with the instructions here: https://github.com/balabit/syslog-ng-docker/tree/master/syslog-ng-dev

I'm using syslog-ng with papertrail and I'd really like to have some control over the keepalive settings without changing the defaults for the entire host.

**Comment by kkirsche** [comment]
I'm encountering the same issue on CentOS 7.4 using the epel-release version (3.5.6-3.el7). Did you find a fix for this other than manual compilation of syslog-ng?

**Comment by algernon** [comment]
The only way I can see is that `TCP_KEEPIDLE` is set in a file other than the ones we include - which I'd find surprising, and is something a recompile wouldn't fix.

**Comment by ryansch** [comment]
@kkirsche I honestly don't remember how I got around this.  This is what we're using in production: https://github.com/outstand/docker-syslog-ng-papertrail

**Comment by MrAnno** [comment]
We have improved the `tcp-keepalive-time()`, `tcp-keepalive-intvl()`, and `tcp-keepalive-probes()` detection since then. Closing.
