### ISSUE TITLE
syslog-ng3.7.3: Can't find class; class_name='org.syslog_ng.kafka.KafkaDestination'

### ISSUE THREAD

**Issue by GrantZheng** [syslog-ng/syslog-ng#1151]
I want to use kafka in syslog-ng3.7.3, so I build syslog-ng3.7.3  with --enable-java option:
./configure --enable-java
After make & make install
I start syslog-ng3.7.3 ,it through a panic:

```
Starting syslog-ng: [2016-08-05T18:13:17.340115] Error: org/apache/kafka/clients/producer/Callback;
java.lang.NoClassDefFoundError: org/apache/kafka/clients/producer/Callback
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:278)
    at org.syslog_ng.SyslogNgClassLoader.loadClass(SyslogNgClassLoader.java:66)
Caused by: java.lang.ClassNotFoundException: org.apache.kafka.clients.producer.Callback
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    ... 3 more
[2016-08-05T18:13:17.341404] Can't find class; class_name='org.syslog_ng.kafka.KafkaDestination'
[2016-08-05T18:13:17.341766] Error initializing message pipeline;
```

## my syslog-ng.conf

```
@version: 3.7
@module mod-java
@include "scl.conf"

source s_local {
    system();
    internal();
};

source s_network {
    udp();
};

destination d_local {
    file("/var/log/messages");
};

log {
    source(s_local);
    destination(d_local);
};

template nginx_format { template("$PROGRAM $MSG\n"); template_escape(no); };
parser nginx { db_parser(file("/home/server_config/syslog-ng/patterndb.d/nginx.xml")); };

include "include/*.ngx";

source s_nginx_access {
    pipe("/usr/local/nginx/logs/access_log");
};
destination d_nginx_access {file("/usr/local/nginx/logs/${N.vhost}/$YEAR$MONTH/$DAY/access_$HOUR.log" perm(0644) dir_perm(0755) create_dirs(yes) template(nginx_format));};
destination d_kafka {
  kafka(
    client_lib_dir("/usr/local/syslog-ng-3.7.3/lib/syslog-ng/java-modules/_.jar:/usr/share/kafka/libs/_.jar")
    kafka_bootstrap_servers("*****")
    topic("beta-nginx-accesslog")
  );
};

log {source(s_nginx_access);parser(nginx);destination(d_nginx_access);destination(d_kafka);flags(final);};
```

I can not find KafkaDestination.jar  in /usr/local/syslog-ng-3.7.3/lib/syslog-ng/java-modules/  , I only can find Kafka.jar

So, what is the problem?

**Comment by lbudai** [comment]
Hi,

`class KafkaDestination` is part of `kafka.jar`.
The error message is confusing here, Can't *load* would be better as syslog-ng cannot load `KafkaDestination` because you got a `java.lang.NoClassDefFoundError: org/apache/kafka/clients/producer/Callback` error.

That class should be part of one of the jars in `/usr/share/kafka/libs/*.jar`

**Comment by kub1x** [comment]
@lbudai Hey, I tried to use https://hub.docker.com/r/balabit/syslog-ng/ and it doesn't conatin `/usr/share/kafka` directory. Where should I get the jars?

**Comment by czanik** [comment]
Read the related documentation at https://www.balabit.com/sites/default/files/documents/syslog-ng-ose-latest-guides/en/syslog-ng-ose-guide-admin/html-single/index.html#configuring-destinations-kafka which also lists prerequisites

**Comment by bazsi** [comment]
I guess the docker images don't contain the kafka jars. I am not sure we
want to (cc @mitzkia), but even in the meanwhile, you can add the kafka
jars either by creating a derived docker image, or by bind mounting the
kafka jars from the outside when running docker.

-- 
Bazsi

**Comment by Kokan** [comment]
Now you could alternatively use the native kafka, and no such setup issue would come up.
