### ISSUE TITLE
Diskq buffer location can not be changed 

### ISSUE THREAD

**Issue by ashishrv** [syslog-ng/syslog-ng#1406]
# syslog-ng

## Version of syslog-ng

```
syslog-ng 3.9.1
Installer-Version: 3.9.1
Revision:
Module-Directory: /disk/syslog-ng/lib/syslog-ng
Module-Path: /disk/syslog-ng/lib/syslog-ng
Available-Modules: syslogformat,graphite,csvparser,geoip-plugin,dbparser,disk-buffer,system-source,confgen,pseudofile,add-contextual-data,linux-kmsg-format,basicfuncs,date,mod-python,curl,afprog,afstomp,afmongodb,cryptofuncs,affile,kvformat,cef,afsocket,afuser,json-plugin
```

## Platform

Red Hat Enterprise Linux Server release 6.8

# Issue

## Failure

Diskq buffer are always created under <syslog-ng path>/var/syslog-ng-00000.rqf
It does not respect the "dir" configuration mentioned in disk-buffer.
How do I configure syslog-ng to create the reliable queue at /disk1/buffer/syslog-ng-00000.rqf ?

Here is the configuration that does not work - 

```
destination d_net {
network( "127.0.0.1"
         port(12345)
         disk-buffer(
              reliable(yes)
              mem-buf-size(1000)
              disk-buf-size(3M)
              qout-size(64)
              dir("/disk1/buffer")
          );
        );
  };

log { source(s_test3);
      destination(d_net);
    };
```

**Comment by faxm0dem** [comment]
I am successfully using this option in 3.8.1
I'll try to reproduce using 3.9.1 ASAP

**Comment by LarryWax** [comment]
Reply on this because had the same problem.
You need to add "/" at the end of your path like this
`dir("/disk1/buffer"/)`

Path is not well handled in "dir" option

**Comment by juhaszviktor** [comment]
It looks to me, that it works using syslog-ng version 3.11.1
If you start your syslog-ng in foreground mode enabling debug messages(-Fedtv),
what is the output of the starting process?

**Comment by shastah** [comment]
Doesn't work for me with 3.12.1. Debug says:
```
# syslog-ng -Fedtv
[2017-10-22T13:59:18.102477] Reading path for candidate modules; path='/usr/lib64/syslog-ng'
(...)
[2017-10-22T13:59:18.112998] Starting to read include file; filename='/etc/syslog-ng/remotelogging.conf', depth='1'
[2017-10-22T13:59:18.113138] Module loaded and initialized successfully; module='disk-buffer'
[2017-10-22T13:59:18.113207] Finishing include; filename='/etc/syslog-ng/remotelogging.conf', depth='1'
(...)
[2017-10-22T13:59:18.113895] Module loaded and initialized successfully; module='syslogformat'
[2017-10-22T13:59:18.114110] Disk-buffer state loaded; filename='/var/syslog-ng-00001.qf', qout_length='0', qbacklog_length='0', qoverflow_length='0', qdisk_length='0'
```
despite my configuration:
```
         disk-buffer(mem-buf-length(10000) disk-buf-size(8388608) reliable(no) dir("/var/lib/syslog-ng/"))
```
Looks like it hardcoded whatever `--localstatedir` was set to during compilation.

Furthermore, OSE documentation mentions (in a couple of places) that `disk-buffer()` option `dir()` "has priority over `--qdisk-dir=`", but I can't find any reference to `qdisk-dir` anywhere else - is this supposed to be `./configure` option?

**Comment by MrAnno** [comment]
Hi,

The `--qdisk-dir` flag is not available in syslog-ng OSE, this is a documentation bug.

Regarding your issue, you have to reset syslog-ng's persist to create a new disk buffer inside the new directory you specified:

```
rm /var/syslog-ng.persist
syslog-ng -Fedtv
```

**Comment by shastah** [comment]
Thanks! Removing `syslog-ng.persist` indeed made it work. Should I open another bug for the documentation issue?

**Comment by MrAnno** [comment]
We'll fix it, thanks. :)

**Comment by Kokan** [comment]
Since https://github.com/syslog-ng/syslog-ng/pull/2855 it is possible to relocate diskq location without removing the persist file.
