### ISSUE TITLE
syslog-ng 3.9.1 wont compile under CygWin

### ISSUE THREAD

**Issue by marukka** [syslog-ng/syslog-ng#1492]
## Version of syslog-ng
3.9.1

## Platform
Windows Server 2016 Core, CygWin x86 2.879 with the following packages (dependencies omitted): 
- libglib2.0-devel 2.50.3-1
- gcc-core 5.4.0-1
- make 4.2.1-2
- autoconf-archive 2017.03.21-1
- flex 2.6.4-1
- bison 3.0.4-1
- libpcre-devel 8.40-3
- libcurl-devel 7.54.0-1
- libnet6-devel 1.3.14-2
- libesmtp-devel 1.0.6-2
- libwrap-devel 7.6-22
- libdbi-devel 0.9.0-1
- openssl-devel 1.0.2k-1

# Issue

## Failure
syslog-ng fails to compile due to multiple errors. The first was ivykis (and eventlog) failing to produce a dynamic library. This was resolved by editing ./lib/ivykis/Makefile and ./lib/ivykis/src/Makefile to include `-no-undefined` in `LDFLAGS`, although possibly only the former needed to be edited. The second was it being unable to find glib, this was resolved by passing `GLIB_LIBS="-L/usr/lib -lglib-2.0 -lgthread-2.0 -lgmodule-2.0"` to the configure script. The present issue is that it complains that there are undefined references to various symbols such as `g_strdup`, `g_snprintf` and others which should be present in /usr/lib/libglib-2.0.dll.a.

I am unable to use the version of syslog-ng included with CygWin as it was not compiled with support for SQL servers.

## Input and output logs (if possible)
Here is the relevant excerpt, full copies of the output from the configure and make commands are attached.

```
  CCLD   modules/syslogformat/libsyslogformat.la
modules/syslogformat/.libs/modules_syslogformat_libsyslogformat_la-syslog-format.o: In function `log_msg_parse_legacy':
/cygdrive/c/syslog-ng-3.9.1/modules/syslogformat/syslog-format.c:1029: undefined reference to `g_utf8_validate'
/cygdrive/c/syslog-ng-3.9.1/modules/syslogformat/syslog-format.c:1042: undefined reference to `g_assertion_message_expr'
/cygdrive/c/syslog-ng-3.9.1/modules/syslogformat/syslog-format.c:1053: undefined reference to `g_utf8_validate'
modules/syslogformat/.libs/modules_syslogformat_libsyslogformat_la-syslog-format.o: In function `log_msg_parse_syslog_proto':
/cygdrive/c/syslog-ng-3.9.1/modules/syslogformat/syslog-format.c:1156: undefined reference to `g_utf8_validate'
modules/syslogformat/.libs/modules_syslogformat_libsyslogformat_la-syslog-parser-grammar.o: In function `syslog_parser_parse':
/cygdrive/c/syslog-ng-3.9.1/syslog-parser-grammar.y:722: undefined reference to `g_strdup'
/cygdrive/c/syslog-ng-3.9.1/syslog-parser-grammar.y:665: undefined reference to `g_snprintf'
/cygdrive/c/syslog-ng-3.9.1/syslog-parser-grammar.y:389: undefined reference to `g_snprintf'
/cygdrive/c/syslog-ng-3.9.1/syslog-parser-grammar.y:678: undefined reference to `g_snprintf'
/cygdrive/c/syslog-ng-3.9.1/syslog-parser-grammar.y:678: undefined reference to `g_clear_error'
modules/syslogformat/.libs/modules_syslogformat_libsyslogformat_la-syslog-parser.o: In function `syslog_parser_new':
/cygdrive/c/syslog-ng-3.9.1/modules/syslogformat/syslog-parser.c:76: undefined reference to `g_malloc0'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:7057: modules/syslogformat/libsyslogformat.la] Error 1
make[1]: *** [Makefile:14116: all-recursive] Error 1
make: *** [Makefile:5463: all] Error 2
```

[configure.txt](https://github.com/balabit/syslog-ng/files/1020576/configure.txt)
[make.txt](https://github.com/balabit/syslog-ng/files/1020577/make.txt)

**Comment by Kokan** [comment]
Compilling on windows with cygwin was never something that the project did. You could try out WSL (windows subsystem for linux), that should be able to compile on "windows".
