### ISSUE TITLE
Enhancement: conditional `set-tag()`

### ISSUE THREAD

**Issue by faxm0dem** [syslog-ng/syslog-ng#1521]
It would be nice to have this in our toolbox, together with conditional `set()`.

Cheers

**Comment by mehul-m-prajapati** [comment]
Hi @faxm0dem,

I can see KW_SET_TAG is already there in ```lib/rewrite/rewrite-expr-grammar.ym```.
Can you give me a brief idea about what enhancement is required for set-tag() ?

**Comment by furiel** [comment]
Some rewrite rules already accept a `condition` option. Though `set-tag` does not accept it yet. In the meantime, grammar level if statement was introduced, that can cover this use case as well.

Still, I think `set-tag("tag" condition(filter-expression));` is a neat syntax, and I would happy to see it implemented.
With a little code reorganization and a well placed `rewrite_condition_opt` in the grammar, this can work.
 
```
@version: 3.26

log {
  source { example-msg-generator(num(1) template("test message")); };
  rewrite { set-tag("matching-tag" condition(match("test" value("MSG")))); };
  rewrite { set-tag("non-matching-tag" condition(match("donotmatch" value("MSG")))); };
  destination { file("/dev/stdout" template("${TAGS}\n")); };
};
```

outputting:
```
[2020-03-17T09:36:01.797268] syslog-ng starting up; version='3.26.1.43.g0b84be1.dirty'
matching-tag,.source.#anon-source0
```
