### ISSUE TITLE
inconsistency when parsing a non-RFC-compliant log message

### ISSUE THREAD

**Issue by fekete-robert** [syslog-ng/syslog-ng#1652]
# syslog-ng

There is an inconsistency when parsing a non-RFC-compliant log message. 
The result is different if when using the default parser and when using flags(no-parse) and then the syslog-parser. For details, see  https://serverfault.com/questions/868767/syslog-ng-parses-msg-oddly/868879

## Version of syslog-ng

```
3.8.1
```

**Comment by MrAnno** [comment]
I can't reproduce this issue with v3.25.1.

`network(flags(no-parse))` + `syslog-parser()` has the same output as `network()`:

Input:
```
<14>Aug 14 21:28:49 pa01.foo.com 1,2017/08/14 21:28:49,009401031978,THREAT,url,...
```

```
$MSG = 21:28:49,009401031978,THREAT,url,...\x0a
```
