### ISSUE TITLE
version 3.12 does not compile on FreeBSD 11-1 p1

### ISSUE THREAD

**Issue by redtorinogt** [syslog-ng/syslog-ng#1726]
# syslog-ng

## Version of syslog-ng

3.12 from freshports  sysutils/syslog-ng312

## Platform

FreeBSD 11.1 p1

# Issue

Trying to build syslog-ng with support for ElasticSearch.  Failure to compile with following configuration options: 
     DOCS=on 
     IPV6=on
     JAVA=on
     JAVA_MOD=on
     JSON=on
     CURL=off
     GEOIP=off 
     GEOIP2=off
     MONGO=off
     PYTHON=off
     REDIS=off
     SMTP=off
     SPOOF=off
     SQL=off
     TCP_WRAPPERS=off

## Failure

Could not resolve all files for configuration ':common:compileClasspath'.
> Could not resolve log4j:log4j:1.2.16.
  Required by:
      project :common
   > Could not resolve log4j:log4j:1.2.16.
      > Could not get resource 'https://repo1.maven.org/maven2/log4j/log4j/1.2.16/log4j-1.2.16.pom'.
         > Could not GET 'https://repo1.maven.org/maven2/log4j/log4j/1.2.16/log4j-1.2.16.pom'.
            > repo1.maven.org
   > Could not resolve log4j:log4j:1.2.16.
      > Could not get resource 'http://maven.elasticsearch.org/releases/log4j/log4j/1.2.16/log4j-1.2.16.pom'.
         > Could not GET 'http://maven.elasticsearch.org/releases/log4j/log4j/1.2.16/log4j-1.2.16.pom'.
            > maven.elasticsearch.org

Am able to resolve both maven.elasticsearch.org and repo1.maven.org.  Can manually download log4j-1.2.16.pom from https://repo1.maven.org/maven2/log4j/log4j/1.2.16/log4j-1.2.16.pom

second URL prompts for user credentials.

**Comment by Kokan** [comment]
In the #2047 the issue was identified, which is not related to syslog-ng: https://bugs.openjdk.java.net/browse/JDK-8196141
