### ISSUE TITLE
Cannot allocate memory on reload for rewrite context

### ISSUE THREAD

**Issue by HardcoreWR** [syslog-ng/syslog-ng#1780]
## Version of syslog-ng

```
syslog-ng 3 (3.12.1)
Installer-Version: 3.12.1
Revision:
Compile-Date: Nov  3 2017 15:15:50
Module-Directory: //usr/lib64/syslog-ng
Module-Path: //usr/lib64/syslog-ng
Available-Modules: afuser,cef,linux-kmsg-format,sdjournal,confgen,map-value-pairs,json-plugin,affile,kvformat,tfgetent,date,afstomp,csvparser,add-contextual-data,cryptofuncs,system-source,syslogformat,afsocket,afprog,pseudofile,afamqp,snmptrapd-parser,dbparser,xml,stardate,tags-parser,graphite,basicfuncs,di
sk-buffer
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: on
Enable-TCP-Wrapper: on
Enable-Linux-Caps: on
Enable-Systemd: on
```

## Platform

CentOS 7.4.1708

# Issue

I defined a rewrite confgen which works when you start syslog-ng.
But when performing a reload it's complaining about 'Cannot allocate memory (12)'.

## Failure

```
syslog-ng[32427]: confgen: Error executing generator program; context='rewrite', block='r_myself', exec='/bin/hostname', error='Cannot allocate memory (12)'
syslog-ng[32427]: Error parsing configuration; filename='/etc/syslog-ng/syslog-ng.conf'
syslog-ng[32427]: Error parsing rewrite expression, syntax error, unexpected LL_ERROR, expecting LL_IDENTIFIER or LL_STRING in /etc/syslog-ng/conf.d/to_remote.conf at line 4, column 9:
syslog-ng[32427]: included from /etc/syslog-ng/syslog-ng.conf line 77, column 1
syslog-ng[32427]: set(r_myself(), value(".SDATA.meta.hostname") );
syslog-ng[32427]: ^^^^^^^^
syslog-ng[32427]: syslog-ng documentation: https://www.balabit.com/support/documentation?product=syslog-ng-ose
syslog-ng[32427]: mailing list: https://lists.balabit.hu/mailman/listinfo/syslog-ng
```

## Steps to reproduce

1. start syslog-ng

2. reload syslog-ng (or kill -HUP <pid>)

## Configuration

```
@module confgen context(rewrite) name(r_myself) exec("/bin/hostname")
rewrite r_hostname {
    set(r_myself(), value(".SDATA.meta.hostname") );
};

@module confgen context(rewrite) name(r_setname_exec) exec("/bin/hostname | /usr/bin/awk -F'-' '{ print $1 }'")
rewrite r_setname {
    set(r_setname_exec(), value(".SDATA.meta.setname") );
};

```

**Comment by bazsi** [comment]
Hmm.. can it be because of SELinux? Please strace the syslog-ng process
when it is reloading, we are popen()-ing the process and that returns this
error.

btw: there's a $LOGHOST macro that returns the name of the hostname that
syslog-ng is running on.

-- 
Bazsi

**Comment by HardcoreWR** [comment]
That's the first thing I thought of as well, but that is disabled.

```
# getenforce
Disabled
```

Strace is attached (hopefully :) )
[syslog-ng.strace.out.txt](https://github.com/balabit/syslog-ng/files/1513175/syslog-ng.strace.out.txt)

I didn't know about the $LOGHOST macro (but I did know about $HOST and $HOSTNAME).
The problem I had with $HOST is that for 1 out of 1000 logs it comes with an IP address instead of the hostname so logs wouldn't end up in the right files.
I know we should have our PTR's correct, but I don't want to rely on people updating PTR's.
Also, I do need the r_setname send as well to create another directory for grouping hosts.

**Comment by bazsi** [comment]
LOGHOST is always the local hostname that syslog-ng runs on.  I was just
mentioning that because you were using the hostname command to determine
just that.

You can choose not to trust DNS by using a local hosts file to fix that.
You can also use add-contextual-data() to map ip addresses to hostnames.
Will check the strace in a minute

**Comment by bazsi** [comment]
In the strace you have provided, the hostname related scripts work
properly, no error is indicated.

However the script  "/usr/share/syslog-ng/include/scl/streamlog/streamlog"
generates no output and that casues a syntax error.

I have also tried to run your configuration sample in the initial post, and
it does work for me, even through reloads.

I used this config:

```
@version: 3.13


@module confgen context(rewrite) name(r_myself) exec("/bin/hostname")
rewrite r_hostname {
    set(r_myself(), value(".SDATA.meta.hostname") );
};

@module confgen context(rewrite) name(r_setname_exec) exec("/bin/hostname |
/usr/bin/awk -F'-' '{ print $1 }'")
rewrite r_setname {
    set(r_setname_exec(), value(".SDATA.meta.setname") );
};

log {
    source { unix-stream("log"); };
    rewrite(r_hostname);
    rewrite(r_setname);
    destination { file("messages" template("$(format-welf *)\n")); };
};
```

So it seems that the more complicated script generates the issue, but only
sometimes. I didn't troubleshoot that piece, however I wrote a patch that
should help you troubleshooting by logging the exact output of the script
in the debug log.

https://github.com/balabit/syslog-ng/pull/1781

Also, the original intent behind confgen() is that it should generate the
entire rewrite operation and not just one parameter, so you are not using
it according to my initial intent. It does work though, but I would do it
differently. Mayge generate a few @defines in the top and then use those
values in the rewrites, or really delegate the entire set() statement to
the script. That way the resulting config should be more readable.




-- 
Bazsi

**Comment by HardcoreWR** [comment]
Thanks for your feedback.
I'll take a look at your patch and see if I can figure out what the real problem is :)

After I get this working I'll look into creating defines rather then confgen.
Thanks!

**Comment by HardcoreWR** [comment]
I'm not sure what else changed between 3.12.1 and 3.13.1, but it doesn't like my streamlog plugin at all..

```Error parsing source, source plugin  not found in source generator streamlog at line 1, column 1:
                                    included from /etc/syslog-ng/conf.d/to_streamlog_remote.conf line 1, column 31
                                    included from /usr/local/etc/syslog-ng.conf line 77, column 1```

If I run the command by hand ( exec("/bin/bash `scl-root`/streamlog/streamlog") ), grab the output and throw it into my config it works no problem.
Running an strace does show me that it get's the same output as running it by hand.

**Comment by HardcoreWR** [comment]
plugin.conf:
```
@module confgen context(source) name(streamlog) exec("/bin/bash `scl-root`/streamlog/streamlog")
```

streamlog:
```
#!/bin/bash

. $( dirname $0 )/logs.scan

if (( ${#logs[@]} > 0 )); then
    echo "channel { "
    for(( l=0; l<${#logs[@]}; l++ )); do
        if [[ "${type[$l]}" == "directory" ]]; then
            [[ "${recursive[$l]:-false}" == "false" ]] && MAXDEPTH="-maxdepth 1 " || MAXDEPTH=" "
            [[ "${wildcard[$l]:-undef}" != "undef" ]] && WILDCARD="-name ${wildcard[$l]} " || WILDCARD=" "
            singlestrip=${logs[$l]%/*}
            while read line; do
                [[ "${custom[$l]:-undef}" != "undef" ]] && CUSTOM="/${custom[$l]}/${line##*/}" || CUSTOM="${line##*${singlestrip}}"
                CUSTOM="${CUSTOM%%.*}"
                echo "    source{ file(\"${line}\" flags(no-parse) program-override(\"custom-${CUSTOM}\") follow-freq(0.1)); };"
            done < <( find ${logs[$l]} ${MAXDEPTH} -type f ${WILDCARD} )
        else
            [[ "${custom[$l]:-undef}" != "undef" ]] && CUSTOM="/${custom[$l]}/${logs[$l]##*/}" || CUSTOM="${logs[$l]##*${singlestrip}}"
            CUSTOM="${CUSTOM%%.*}"
            echo "    source{ file(\"${logs[$l]}\" flags(no-parse) program-override(\"custom-${CUSTOM}\") follow-freq(0.1)); };"
        fi
    done
    echo "};"
fi
```

logs.scan:
```
logs[0]="/var/log/sssd"
recursive[0]="true"
type[0]="directory"
custom[0]="undef"
wildcard[0]="*.log"

logs[1]="/var/log/zabbix"
recursive[1]="true"
type[1]="directory"
custom[1]="undef"
wildcard[1]="*.log"

logs[2]="/var/log/httpd"
recursive[2]="true"
type[2]="directory"
custom[2]="undef"
wildcard[2]="*.log"

logs[3]="/var/log/maxscale"
recursive[3]="false"
type[3]="directory"
custom[3]="undef"
wildcard[3]="*.log"
```

It's probably a bit hacky, but I want to create a single 'plugin' I can use to deploy on all of our servers and fill the logs.scan file with puppet.

**Comment by bazsi** [comment]
This may be related to #2108 

I broke the confgen functionality in 3.13.1
