### ISSUE TITLE
Port elastic-v2 http client_mode from Jest to RestClient

### ISSUE THREAD

**Issue by faxm0dem** [syslog-ng/syslog-ng#1877]
We should probably port the elastic-v2 http mode to the new [RestClient](https://www.elastic.co/guide/en/elasticsearch/client/java-rest/current/java-rest-overview.html) library.

**Comment by lbudai** [comment]
@faxm0dem : +1
It's already on my list ;)

**Comment by faxm0dem** [comment]
I guess this has to be done before Elastic 7.x as types will be removed

**Comment by LAVEEN** [comment]
Is anyone working on this,can i take up this enhancement?

**Comment by faxm0dem** [comment]
In my understanding the transport protocol is deprecated. This change only concerns the HTTP(S) client-modes.

**Comment by Kokan** [comment]
@LAVEEN hello. The http mode has both Jest in the http client and the message processor. If you could replace that much, it should work.

**Comment by LAVEEN** [comment]
@Kokan  @faxm0dem  thanks for the input

**Comment by MrAnno** [comment]
Closing as we have a native `elasticsearch-http()` destination.
