### ISSUE TITLE
Problem with Java destinations JDK9 and above

### ISSUE THREAD

**Issue by sergio-limone** [syslog-ng/syslog-ng#1943]
# syslog-ng

## Version of syslog-ng

syslog-ng 3 (3.14.1)
Config version: 3.14
Installer-Version: 3.14.1
Revision: 
Compile-Date: Feb 28 2018 07:34:20
Module-Directory: //usr/lib64/syslog-ng
Module-Path: //usr/lib64/syslog-ng
Available-Modules: afsocket,json-plugin,cef,stardate,graphite,disk-buffer,sdjournal,afuser,afamqp,afprog,date,linux-kmsg-format,system-source,map-value-pairs,tags-parser,affile,cryptofuncs,xml,dbparser,appmodel,kvformat,snmptrapd-parser,basicfuncs,add-contextual-data,confgen,mod-java,afstomp,syslogformat,pseudofile,csvparser,tfgetent
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: on
Enable-TCP-Wrapper: on
Enable-Linux-Caps: on
Enable-Systemd: on

## Platform

Linux statia 3.10.0-693.5.2.el7.x86_64 #1 SMP Fri Oct 20 20:32:50 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Centos 7.4

# Issue

I tried to start elasticsearch2 with jre 9.0.4 , seems the elastic2 destination is not jdk9 ready yet.
Same configuration works perfect with jre1.8.0_161-b12
RPMs are from https://copr-be.cloud.fedoraproject.org/results/czanik/syslog-ng314/

## Failure

Fails to start with java exception on stdout:

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.syslog_ng.SyslogNgClassLoader (file:/usr/lib64/syslog-ng/java-modules/syslog-ng-core.jar) to method java.net.URLClassLoader.addURL(java.net.URL)
WARNING: Please consider reporting this to the maintainers of org.syslog_ng.SyslogNgClassLoader
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[2018-03-27T17:01:53.585521] Error while expanding path list: object is not an instance of declaring class;
java.lang.IllegalArgumentException: object is not an instance of declaring class
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.syslog_ng.SyslogNgClassLoader.expandClassPath(SyslogNgClassLoader.java:144)
	at org.syslog_ng.SyslogNgClassLoader.loadClass(SyslogNgClassLoader.java:65)
[2018-03-27T17:01:53.586889] Can't find class; class_name='org.syslog_ng.elasticsearch_v2.ElasticSearchDestination'
[2018-03-27T17:01:53.589907] Error initializing message pipeline; plugin name='java', location='#buffer:2:3'

## Steps to reproduce

1. LD_LIBRARY_PATH=<JRE9_DIR>/lib/server:${LD_LIBRARY_PATH}
2. export LD_LIBRARY_PATH
3. start syslog-ng

## Configuration
<stipped down snippet>

source s_global_raw {
	channel {
		source {
			systemd-journal(
				log-fetch-limit(1000)
				default-level("info")
			);
			internal();
			udp(ip(127.0.0.1) port(514));
		};
	};
};

destination d_elastic_local {
	elasticsearch2(
		index("logs-${YEAR}.${MONTH}.${DAY}")
		type("my-log")
		cluster("elasticsearch")
		persist_name("elastic-local")
		template("$(format-json --scope nv-pairs @timestamp=${S_ISODATE})")
		client-lib-dir("/usr/share/elasticsearch/lib")
		flush-limit(2000)
		client-mode("http")
		cluster-url("http://localhost:9200")
	);
};

log {
	source(s_global_raw);
	destination(d_elastic_local);
};

**Comment by gaborznagy** [comment]
Hi @sergehauser!
Thanks for reporting the above issue.
I have installed jdk 9.0.4 and I have the same problem too.

As searching on the Internet it seems there are major changes about API access and about reflective access.
https://blogs.oracle.com/java/get-ready-jdk9

**Comment by czanik** [comment]
Just a heads up: lack of JDK 9 support came up both with colleagues and externally as a problem during the past few days. And in openSUSE some architectures skipped JDK 8 all together and went from 7 to 9 with the upcoming Leap 15 release (and thus most likely also SLES 15, but I have yet to verify that).

**Comment by Kokan** [comment]
I've checked this issue, and I've tracked as far as the following thread: https://community.oracle.com/thread/4011800

That offers a possible *solution*, but I was not confident about that.
As far as I could investigate, this was a hack in the first place(explained in the link), and possible the 'fix' is going to be another hack ...

**Comment by nambrosch** [comment]
I have a similar issue with java 10.

```
Jun 15 01:51:39 centos3 syslog-ng[55366]: WARNING: An illegal reflective access operation has occurred
Jun 15 01:51:39 centos3 syslog-ng[55366]: WARNING: Illegal reflective access by org.syslog_ng.SyslogNgClassLoader (file:/usr/lib64/syslog-ng/java-modules/syslog-ng-core.jar) to method java.net.URLClassLoader.addURL(java.net.URL)
Jun 15 01:51:39 centos3 syslog-ng[55366]: WARNING: Please consider reporting this to the maintainers of org.syslog_ng.SyslogNgClassLoader
Jun 15 01:51:39 centos3 syslog-ng[55366]: WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
Jun 15 01:51:39 centos3 syslog-ng[55366]: WARNING: All illegal access operations will be denied in a future release
Jun 15 01:51:39 centos3 syslog-ng[55366]: [2018-06-15T01:51:39.333858] Error while expanding path list: object is not an instance of declaring class;
Jun 15 01:51:39 centos3 syslog-ng[55366]: java.lang.IllegalArgumentException: object is not an instance of declaring class
Jun 15 01:51:39 centos3 syslog-ng[55366]: at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Jun 15 01:51:39 centos3 syslog-ng[55366]: at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
Jun 15 01:51:39 centos3 syslog-ng[55366]: at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Jun 15 01:51:39 centos3 syslog-ng[55366]: at java.base/java.lang.reflect.Method.invoke(Method.java:564)
Jun 15 01:51:39 centos3 syslog-ng[55366]: at org.syslog_ng.SyslogNgClassLoader.expandClassPath(SyslogNgClassLoader.java:144)
Jun 15 01:51:39 centos3 syslog-ng[55366]: at org.syslog_ng.SyslogNgClassLoader.loadClass(SyslogNgClassLoader.java:65)
Jun 15 01:51:39 centos3 syslog-ng[55366]: [2018-06-15T01:51:39.335187] Can't find class; class_name='org.syslog_ng.elasticsearch_v2.ElasticSearchDestination'
Jun 15 01:51:39 centos3 syslog-ng[55366]: [2018-06-15T01:51:39.337627] Error initializing message pipeline; plugin_name='java', location='#buffer:2:3'
```

Oracle has stated the upcoming EOL dates for Java 7, 8, 9, and 10, so it's probably not something to be ignored.

http://www.oracle.com/technetwork/java/eol-135779.html

**Comment by faxm0dem** [comment]
Can be closed a elasticsearch-http is now the way go go

**Comment by gaborznagy** [comment]
I would reopen this ticket, as this affects every java destination, and we would like to solve this issue.
