### ISSUE TITLE
Invalid json Kafka

### ISSUE THREAD

**Issue by yctn** [syslog-ng/syslog-ng#2048]
# syslog-ng

## Version of syslog-ng
3.15.1

## Platform
Debian 9 and64

## Debug bundle

Create a debug bundle on your system with the syslog-ng-debun script which is included in the syslog-ng package.

# Issue

Im using syslog-ng to forward json messages to kafka.
but i noticed unvalid json in kafka. this is strange cause im using json-parser before it goes to kafka.

nginx -> syslog-ng -> kafka -> file result:
{"time": "2018-05-18 22:07:26", "server_addr": "185.70.212.101", "hostname": "nl1-web213-21", "remote_addr": "185.151.150.200", "request_time": "0.262", "scheme": "http", "server_protocol": "", "status": "400", "request": "\u0016\u0003\u0001\u0000Ð\u0001\u0000\u0000Ì\u0003\u0003fF¿\u0008/m4\u001Chí¨/|sâ¼E®BÐh*ݤÓÈ0nì¼BJ\u0000\u0000\u001EÀ+À/̨̩À,À0À", "request_method": "", "http_referer": "", "http_user_agent"

nginx -> syslog-ng -> file result:

{"time": "2018-05-18 22:07:26", "server_addr": "185.70.212.101", "hostname": "nl1-web213-21", "remote_addr": "185.151.150.200", "request_time": "0.262", "scheme": "http", "server_protocol": "", "status": "400", "request": "\u0016\u0003\u0001\u0000?\u0001\u0000\u0000?\u0003\u0003fF?\u0008/m4\u001Ch??/|s?E?B?h*ݤ??0n?BJ\u0000\u0000\u001E?+?/̨̩?,?0?", "request_method": "", "http_referer": "", "http_user_agent": ""}

So in this case. Invalid json reached kafka messages. 

## Steps to reproduce

i was unable to reproduce this issue. 
i tryed with sending this message with php to syslog-ng result was correct.
i tryed sending it with kafka-console-producer. result was correct

## Configuration

cat /etc/syslog-ng/conf.d/05loghost.conf
log {source(s_net); 
parser(p_json);
destination(d_prog); 
destination(d_kafka);
};

parser p_json { json-parser(); };

@module mod-java

destination d_kafka {
  kafka(
    client-lib-dir("/opt/syslog-ng/lib/syslog-ng/java-modules/")
    kafka-bootstrap-servers("10.1.214.220:9092")
    topic("syslog-ng")
    template("${MESSAGE}")
  );
};

destination d_prog  { file("/var/logs/syslog.json" template("${MESSAGE}\n") ); };

cat /etc/syslog-ng/syslog-ng.conf
@version: 3.15
@include "scl.conf"
@include "`scl-root`/system/tty10.conf"
# Syslog-ng configuration file, compatible with default Debian syslogd
# installation.

# First, set some global options.
options { chain_hostnames(off); flush-lines(1000); use_dns(no); use_fqdn(no);
	  owner("root"); group("adm"); perm(0640); stats_freq(0);
	  bad_hostname("^gconfd$");

flush-timeout(10);
};

########################
# Sources
########################
# This is the default behavior of sysklogd package
# Logs may come from unix stream, but not from another machine.
#
source s_src {
       system();
       internal();
};

# If you wish to get logs from remote machine you should uncomment
# this and comment the above source line.
#

#source s_net { tcp(ip(127.0.0.1) port(1000) encrypt(allow)); };
#source s_network { syslog(ip(127.0.0.1) transport("tcp")); };
#source s_demo_tcp { network(ip(10.1.2.3) port(1999)); };

#source s_net { tcp(port (500) ); udp(); };
#source s_net { tcp((ip(127.0.0.1) port(1000) max-connections 5000)); udp (); };

########################
# Destinations
########################
# First some standard logfile
#
destination d_auth { file("/var/log/auth.log"); };
destination d_cron { file("/var/log/cron.log"); };
destination d_daemon { file("/var/log/daemon.log"); };
destination d_kern { file("/var/log/kern.log"); };
destination d_lpr { file("/var/log/lpr.log"); };
destination d_mail { file("/var/log/mail.log"); };
destination d_syslog { file("/var/log/syslog"); };
destination d_user { file("/var/log/user.log"); };
destination d_uucp { file("/var/log/uucp.log"); };

# This files are the log come from the mail subsystem.
#
destination d_mailinfo { file("/var/log/mail.info"); };
destination d_mailwarn { file("/var/log/mail.warn"); };
destination d_mailerr { file("/var/log/mail.err"); };

# Logging for INN news system
#
destination d_newscrit { file("/var/log/news/news.crit"); };
destination d_newserr { file("/var/log/news/news.err"); };
destination d_newsnotice { file("/var/log/news/news.notice"); };

# Some 'catch-all' logfiles.
#
destination d_debug { file("/var/log/debug"); };
destination d_error { file("/var/log/error"); };
destination d_messages { file("/var/log/messages"); };

#destination d_net { file("/var/log/tcp"); };
# The root's console.
#
destination d_console { usertty("root"); };

# Virtual console.
#
destination d_console_all { file(`tty10`); };

# The named pipe /dev/xconsole is for the nsole' utility.  To use it,
# you must invoke nsole' with the -file' option:
#
#    $ xconsole -file /dev/xconsole [...]
#
destination d_xconsole { pipe("/dev/xconsole"); };

# Send the messages to an other host
#
#destination d_net { tcp("127.0.0.1" port(1000) authentication(on) encrypt(on) log_fifo_size(1000)); };

# Debian only
destination d_ppp { file("/var/log/ppp.log"); };

########################
# Filters
########################
# Here's come the filter options. With this rules, we can set which 
# message go where.

filter f_dbg { level(debug); };
filter f_info { level(info); };
filter f_notice { level(notice); };
filter f_warn { level(warn); };
filter f_err { level(err); };
filter f_crit { level(crit .. emerg); };

filter f_debug { level(debug) and not facility(auth, authpriv, news, mail); };
filter f_error { level(err .. emerg) ; };
filter f_messages { level(info,notice,warn) and 
                    not facility(auth,authpriv,cron,daemon,mail,news); };

filter f_auth { facility(auth, authpriv) and not filter(f_debug); };
filter f_cron { facility(cron) and not filter(f_debug); };
filter f_daemon { facility(daemon) and not filter(f_debug); };
filter f_kern { facility(kern) and not filter(f_debug); };
filter f_lpr { facility(lpr) and not filter(f_debug); };
filter f_local { facility(local0, local1, local3, local4, local5,
                        local6, local7) and not filter(f_debug); };
filter f_mail { facility(mail) and not filter(f_debug); };
filter f_news { facility(news) and not filter(f_debug); };
filter f_syslog3 { not facility(auth, authpriv, mail) and not filter(f_debug); };
filter f_user { facility(user) and not filter(f_debug); };
filter f_uucp { facility(uucp) and not filter(f_debug); };

filter f_cnews { level(notice, err, crit) and facility(news); };
filter f_cother { level(debug, info, notice, warn) or facility(daemon, mail); };

filter f_ppp { facility(local2) and not filter(f_debug); };
filter f_console { level(warn .. emerg); };

########################
# Log paths
########################
log { source(s_src); filter(f_auth); destination(d_auth); };
log { source(s_src); filter(f_cron); destination(d_cron); };
log { source(s_src); filter(f_daemon); destination(d_daemon); };
log { source(s_src); filter(f_kern); destination(d_kern); };
log { source(s_src); filter(f_lpr); destination(d_lpr); };
log { source(s_src); filter(f_syslog3); destination(d_syslog); };
log { source(s_src); filter(f_user); destination(d_user); };
log { source(s_src); filter(f_uucp); destination(d_uucp); };

log { source(s_src); filter(f_mail); destination(d_mail); };
#log { source(s_src); filter(f_mail); filter(f_info); destination(d_mailinfo); };
#log { source(s_src); filter(f_mail); filter(f_warn); destination(d_mailwarn); };
#log { source(s_src); filter(f_mail); filter(f_err); destination(d_mailerr); };

log { source(s_src); filter(f_news); filter(f_crit); destination(d_newscrit); };
log { source(s_src); filter(f_news); filter(f_err); destination(d_newserr); };
log { source(s_src); filter(f_news); filter(f_notice); destination(d_newsnotice); };
#log { source(s_src); filter(f_cnews); destination(d_console_all); };
#log { source(s_src); filter(f_cother); destination(d_console_all); };

#log { source(s_src); filter(f_ppp); destination(d_ppp); };

log { source(s_src); filter(f_debug); destination(d_debug); };
log { source(s_src); filter(f_error); destination(d_error); };
log { source(s_src); filter(f_messages); destination(d_messages); };

log { source(s_src); filter(f_console); destination(d_console_all);
				    destination(d_xconsole); };
log { source(s_src); filter(f_crit); destination(d_console); };

# All messages send to a remote site
#
#log { source(s_src); destination(d_net); };

###
# Include all config files in /etc/syslog-ng/conf.d/
###
@include "/etc/syslog-ng/conf.d/"

```

(or gist URL)

## Input and output logs (if possible)

**Comment by bazsi** [comment]
In what way is it invalid? Is it the missing closing brace or something
else?

**Comment by yctn** [comment]
Yes it is invalid because of the missing closing brace.
cause the brace is missing its an invalid json row. and the kafka consumer crashes on it.
but the point is i dont know how it is possible. cause the syslog-ng output seems to be fine. only syslog-ng -> kafka is not fine.

**Comment by algernon** [comment]
I have a suspicion. This might be an encoding issue, where a literal zero char gets into the string somewhere, and we may not treat that the way we should.

I'll see if I can reproduce this. My suspicion is that this would happen with any Java destination.

**Comment by MrAnno** [comment]
This is a consequence of #2096. Closing this one.
