### ISSUE TITLE
elasticsearch2 / jest load balancing

### ISSUE THREAD

**Issue by nambrosch** [syslog-ng/syslog-ng#2116]
i haven't been able to find much documentation on this, but is it possible to do active/failover load balancing with the elasticsearch2 destination?

**Comment by nambrosch** [comment]
i was under the impression that it's round robin, not a failover pool.

**Comment by faxm0dem** [comment]
I guess we have to read the source in order to be sure https://github.com/searchbox-io/Jest/tree/master/jest

**Comment by alltilla** [comment]
From the `Jest` code, I saw round-robin load balancing with the URLs from `cluster-url()` options. So I do not think active/failover is possible.
I am closing this issue, as it is pretty old now, please reopen, if you need any more help with this :)
