### ISSUE TITLE
increased CPU usage with elasticsearch2 destination

### ISSUE THREAD

**Issue by meierfra-ergon** [syslog-ng/syslog-ng#2131]
# syslog-ng

## Version of syslog-ng
3.15.1-2

output of syslog-ng --version
syslog-ng 3 (3.15.1)
Config version: 3.15
Installer-Version: 3.15.1
Revision: 
Compile-Date: May 16 2018 07:23:22
Module-Directory: //usr/lib64/syslog-ng
Module-Path: //usr/lib64/syslog-ng
Error opening plugin module; module='mod-java', error='libjvm.so: cannot open shared object file: No such file or directory'
Available-Modules: hook-commands,stardate,kvformat,add-contextual-data,tfgetent,affile,afamqp,snmptrapd-parser,appmodel,afprog,disk-buffer,cef,confgen,afsocket,basicfuncs,pseudofile,afstomp,graphite,csvparser,syslogformat,cryptofuncs,linux-kmsg-format,system-source,xml,sdjournal,tags-parser,afuser,map-value-pairs,dbparser,date,json-plugin
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: on
Enable-TCP-Wrapper: on
Enable-Linux-Caps: on
Enable-Systemd: on

## Platform
CentOS 7.5

## Debug bundle

# Issue
We are using Syslog-NG to write our Logs into Files and also into an Elasticsearch DB. Before we were using Syslog-NG version 3.11.1-2 and since the Update to 3.15.1-2 we experience a substantial increase in CPU usage. The increase does only exists, if the elasticsearch2 destination is active, so I think the the Problem exists in this component.

## Failure
20% higher CPU usage

## Steps to reproduce
1. use elasticsearch2 destination
2. start a load-test with 3.11.1-2 
3. start a load-test with 3.15.1-2
4. compare CPU usages

## Configuration
(only elastcsearch2)
```
destination d_elastic_local {
        elasticsearch2(
                index("logs-${YEAR}.${MONTH}.${DAY}")
                type("log")
                cluster("elasticsearch")
                persist_name("elastic-local")
                template("$(format-json --scope nv-pairs --exclude 0*,1*,2*,3*,4*,5*,6*,7*,8*,9*,A*,B*,C*,D*,E*,F*,G*,H*,I*,J*,K*,L*,N*,M*,O*,P*,Q*,R*,S*,T*,U*,V*,W*,X*,Y*,Z* @timestamp=${S_ISODATE})")
                client-lib-dir("/usr/share/elasticsearch/lib")
                flush-limit(2000)
                client-mode("http")
                cluster-url("http://localhost:9200")
        );
};


log {
        source(s_global_json);
        destination(d_elastic_local);
};
```

**Comment by meierfra-ergon** [comment]
I made some further inverstigations and found out, that the strategy of writing the messages as bulk operation to the Elasticsearch has changed radically. I made a tcpdump for 3min on the Elasticsearch port (9200) and saw that with 3.11.1-2 there are a lot less POST Requests done but the Requests are larger than with 3.15.1-2, but the traffic total is about the same.
In numbers: 
* Requests: ~110 vs ~2700 POST Requests in the same timeperiod
* Request-Size: ~2MB vs 20-100kB (strong variation)

I think this increased amount of smaller requests does put a larger strain on the System (System I/O and the participating Processes syslog-ng and Elasticsearch).

**Comment by lbudai** [comment]
@meierfra-ergon : Thanks for the investigations! 
Could you validate that all the messages are received both with 3.11 and 3.15?
Just because we had a bug, https://github.com/balabit/syslog-ng/pull/1800/commits/3e5ec6c33fd994214e2829e821cef21bc398fcd2 . So maybe with 3.11 you have message loss, with 3.15 you don't, but it's need more CPU time (as it's not dropping the messages...).

**Comment by lbudai** [comment]
(and I'd still recommend to use `flags(flow-control)` )

**Comment by meierfra-ergon** [comment]
@lbudai I compared the logfiles with the ES entries and found that with the 3.11 there were no messages lost. BUT with 3.15 I found *duplicate entries!* Not that many in comparison to all the messages though (126 duplicates in 372919 messages), so I don't think this is the source for the performance problems, but it is definitely something we do not want to have either, maybe this is another bug?
I also tried the flow-control flag, but it did not change anything

**Comment by lbudai** [comment]
@meierfra-ergon : Well... I still think this could related to the referenced code chunk.

I can create a branch where I do some changes (revert this patch, or something similar), if you have the time for trying it out.

Then I'll setup a test environment and check in details what's going on here.

**Comment by lbudai** [comment]
@meierfra-ergon : here is a branch where I reverted the patch

https://github.com/lbudai/syslog-ng/tree/elastic-http-perf-issue

**Comment by meierfra-ergon** [comment]
@lbudai Thanks I built your branch. Since your branch is 3.16 and because I didn't want to mess with my system I only replaced the  "elastic-v2.jar", hope this is enough to further investigate, otherwise let me know.
Unfortunately the result stays the same, with the newly compiled jar.

**Comment by lbudai** [comment]
@meierfra-ergon : unfortunately I made a mistake during the revert, now it's fine.
Could you fetch the latest changes? (It is enough to replace the `elastic-v2.jar`.)

**Comment by faxm0dem** [comment]
I'm sorry but we still use 3.9.1 in production so we didn't see this behaviour.

**Comment by meierfra-ergon** [comment]
@lbudai unfortunately there was no change with the second build either. 

A new strange fact I just found out, is that the phenomenon seems to be depending on the load we are putting on the System. When I did double the load on the test system, I could not see a difference between two versions anymore.

Another fact that I was missing before, is that the increased CPU usage is due to "I/O wait"

**Comment by faxm0dem** [comment]
Did you enable disk-buffer?

**Comment by meierfra-ergon** [comment]
No we do not use any disk-buffer statements in our config.

**Comment by MrAnno** [comment]
> I made a tcpdump for 3min on the Elasticsearch port (9200) and saw that with 3.11.1-2 there are a lot less POST Requests done but the Requests are larger than with 3.15.1-2, but the traffic total is about the same.

This might be the side effect of #1668.

**Comment by bazsi** [comment]
I think you might be right.

On a related note, in the new batching framework the model is very similar.
It will flush whenever the input queue is empty, which might cause a
less-than-ideal batch size if the incoming message rate is slow.

setting throttle() on the destination might be a workaround (if the java
destination supports it). If you set it to your assumed data rate,
syslog-ng would accumulate incoming messages and only send at the
designated rate. This should cause the destination to bundle more items
into the same batch.

I've checked, the java() destination does support throttle(), and the scl
wrapper in scl/elasticsearch/plugin.conf seems to properly pass this on.

So just add a throttle() value with your anticipated message rate into your
elasticsearch2() destination and see if it helps. The setting should be
roughly your message incoming message rate per second.



-- 
Bazsi

**Comment by MrAnno** [comment]
Calling `flush()` every time the queue becomes empty is really expensive. I think this explains the increased "I/O wait" CPU usage as well.

**Comment by bazsi** [comment]
Well, the idea was that if the flush is expensive, we would have time to
accumulate input. :)

Hmm.. we used to have a flush-timeout() parameter, which originally
controlled how much time we would wait for flush-lines() amount of lines to
be received. But that was dropped for a reason I cannot recall, when we
converted to the threaded operation.

If we wanted to introduce a "minumum batch size" parameter, that
immediately has timing implications as well, as you don't want to wait
forever.

-- 
Bazsi

**Comment by meierfra-ergon** [comment]
I can not see, what the throttle option would help here, it limits messages sent to the elasticsearch destination, which in turn does not wait for a flush limit and just sends out the messages right?

Nevertheless I tried out the setting, set it to the expected amount of messages per second we are testing with, but it did not change the behavior.

As a good "flush strategy" I would expect, there is a limit of accumulated messages at which they need to be flushed (flush-limit() i guess) and a time after which the accumulated messages are flushed regardless of their amount, to not "wait forever" as you put it. So it would be interesting to know why the flush-timeout() parameter was dropped.

**Comment by bazsi** [comment]
The throttle option would help because it artificially suspends the
destination thread to match the message rate, in which time more messages
would be accumulated. But it's not ideal, I agree, I just hoped it'd help
at least a bit. Maybe if you decrease it somewhat below the average message
rate.

The dropping of the flush_timeout() option was for a good reason, but I'd
have to delve into code changes roughly 10 years ago. I do have an
alternate idea though:

- if we add a parameter of flush-pace() that would specify the amount of
time we would like to keep between flushes. This would basically affect the
real-timeness of the destination.
- if we set it to 5 seconds, then if the queue becomes empty and the last
flush was 1 second ago, we would wait for 4 seconds. Add all accumulated
messages into the batch and flush.
- as long as we have enough data, we would continue to flush as data comes
in.

This means that when data is flowing, we would be producing complete
batches. If it is not, we would pace them apart to roughly 5 seconds.

What do you think?

-- 
Bazsi

**Comment by meierfra-ergon** [comment]
@bazsi Sounds great, so messages would be written (as bulk) either if the flush-limit() is reached or the flush-pace-time since the last flush() has expired.

**Comment by meierfra-ergon** [comment]
hi there, just wana ask, if there are any plans to bring the flush-timeout() feature to the elasticsearch2 destination? 
As I see it was implemented in the http destination, but I think it seems not to be feasible to use it with elasticsearch, since as far as I understand, the http destination, can not feed the elasticsearch bulk API, where multiple log messages are posted in one request. Without the bulk API, performance will be quite bad I guess.

**Comment by furiel** [comment]
@meierfra-ergon flush-timeout was added in https://github.com/balabit/syslog-ng/pull/2478/commits/b37e75c864ba7a617f9ef37224275e74afcc2d88 for `client_mode("http")`. The change will be available in the next release: 3.20.

**Comment by meierfra-ergon** [comment]
@furiel thanks for the info, looking forward to test it :-)

**Comment by alltilla** [comment]
@meierfra-ergon 
Hi Frank,
Did you have a chance to test `flush-timeout`? :)

**Comment by meierfra-ergon** [comment]
@alltilla we use it for some time now and are happy with it. just the directive is called 'batch-timeout' in the 'http' destination. cheers

**Comment by alltilla** [comment]
I am glad! :) Closing the issue, then.
