### ISSUE TITLE
SEQNUM behavior is inconsistent

### ISSUE THREAD

**Issue by bazsi** [syslog-ng/syslog-ng#2152]
syslog-ng processes sequence numbers from Cisco routers (https://www.cisco.com/c/en/us/td/docs/routers/access/wireless/software/guide/SysMsgLogging.html#wp1054751)

It also extracts sequence numbers from RFC5424 messages:

   The "sequenceId" parameter tracks the sequence in which the
   originator submits messages to the syslog transport for sending.  It
   is an integer that MUST be set to 1 when the syslog function is
   started and MUST be increased with every message up to a maximum
   value of 2147483647.  If that value is reached, the next message MUST
   be sent with a sequenceId of 1.

The inconsistency is in how we relay these values. Currently, at least in LogWriter based destinations,
we assign sequenceId to local messages and leave the original sequenceId for relayed messages.

In SQL and logthrdestdrv based destinations, we always use our own sequenceId as $SEQNUM, regardless if it was relayed or generated locally.

I think SEQNUM is seldomly if ever used in actual template strings. In RFC5424 we would reproduce sequenceId in the SDATA block. In RFC3164, we never generate a SEQNUM, unless someone uses a template.

A decision is needed along these lines:
1) consider sequenceId a hop-by-hop value and _always_ generate it at the specific destination, overwriting the original value in the incoming message
2) consider sequenceId a property of the log message and associate SEQNUM to incoming messages at the source (sounds backwards).
3) drop SEQNUM support, as noone cares. Be able to extract it from log messages, but leave it in a name-value pair (e.g. .cisco.seq_num), and nothing else. Never generate it on output.
4) something else.

Once the decision is set, probably any of the above is easy to implement.

**Comment by alltilla** [comment]
This issue is referenced in #3036. There is no point leaving this open, we can discuss this there.
