### ISSUE TITLE
MESSAGE in systemd-journal when used with format-json seen as string

### ISSUE THREAD

**Issue by rightaway** [syslog-ng/syslog-ng#2284]
## Version of syslog-ng

```
syslog-ng 3 (3.17.2)
Config version: 3.17
Installer-Version: 3.17.2
Revision: 3.17.2-1
Compile-Date: Aug  9 2018 12:54:37
Module-Directory: /usr/lib/syslog-ng/3.17
Module-Path: /usr/lib/syslog-ng/3.17
Available-Modules: syslogformat,tags-parser,affile,json-plugin,disk-buffer,confgen,date,linux-kmsg-format,csvparser,pseudofile,cryptofuncs,kvformat,afprog,basicfuncs,hook-commands,system-source,afsocket,appmodel,dbparser,cef,afuser,xml,sdjournal
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: on
Enable-TCP-Wrapper: on
Enable-Linux-Caps: on
Enable-Systemd: on
```

## Platform

archlinux

# Issue

With this configuration, the file gets the value `{"HOST":"...","FACILITY":"...","DATE":"...",{"MESSAGE":"{\"key\":\"value\"}}`. MESSAGE isn't seen as a json object but as a string, so the values are being escaped as a string within json. So when I try to put the destination to somewhere that expects MESSAGE to be json as well, it just gets a string so further parsing can't be done on it.

```
	source s_journal {
		systemd-journal();
	};

	destination d_journal_json {
		file('/var/log/journal.json' template("$(format_json --scope rfc5424)\n"));
	};

```

**Comment by lbudai** [comment]
Well, we have kv-parser... so one can write a config like this:
```
@version: 3.17

@include "scl.conf"

source s_journal {
    systemd-journal();
  };

destination d_journal_json {
    file('/tmp/journal.json' template("$(format_json --scope rfc5424 --scope dot-nv-pairs)\n"));
};

parser p_kv {
    kv-parser (value-separator(":") prefix(".kv.") template($MESSAGE));
};

log {
  source(s_journal);
  parser(p_kv);
  destination(d_journal_json);
};
```

but this won't work as `$MESSAGE` can contain several kinds of logs.

for exmaple:
```
"MESSAGE":"Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x300000a (autorxvt-1)"
```

the result will be:

```
"_kv":{"warning":"Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x300000a (autorxvt-1)"}
```

I guess you want to parse *all* the systemd messages.

**Comment by rightaway** [comment]
That's right I'd like to parse all systemd messages. Is there any way to do this with syslog-ng? For example with the `@cee: ` string? The documentation gave an example somewhere with `cee` but that only worked for me when the whole message was json.

**Comment by MrAnno** [comment]
This is an old question.

Since then, syslog-ng has been supporting if statements, which makes it easier to create configurations where multiple parsers are tried on each message, for example:

https://github.com/syslog-ng/syslog-ng/blob/88b0a02aa9a8e5048cb516f28c5c2c8ba2cf1520/scl/default-network-drivers/plugin.conf#L49-L60

With that, it is possible to parse `$MESSAGE` with either `kv-parser()` or `json-parser()`; or in worst case, keeping the original string representation.
