### ISSUE TITLE
Segmentation fault during reload

### ISSUE THREAD

**Issue by navrev** [syslog-ng/syslog-ng#2450]
# syslog-ng

## Version of syslog-ng

syslog-ng 3 (3.11.1)
Installer-Version: 3.11.1
Revision: 3.11.1-2ubuntu1+pure20
Compile-Date: Sep 13 2018 22:55:45
Module-Directory: /usr/lib/syslog-ng/3.11
Module-Path: /usr/lib/syslog-ng/3.11
Available-Modules: http,confgen,basicfuncs,sdjournal,disk-buffer,date,system-source,syslogformat,linux-kmsg-format,cryptofuncs,kvformat,afuser,pseudofile,affile,cef,afsocket,afprog,dbparser,csvparser
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: on
Enable-TCP-Wrapper: on
Enable-Linux-Caps: on
Enable-Systemd: on

## Platform

Ubuntu 16

# Issue

## Failure

(Backtrace, error messages or detailed description of failure comes here.)
#0  g_slice_alloc (mem_size=mem_size@entry=40) at /build/buildd/glib2.0-2.40.2/./glib/gslice.c:998
#1  0x00007f0db50aec45 in g_array_sized_new (zero_terminated=zero_terminated@entry=0, clear=clear@entry=1, elt_size=elt_size@entry=16,
    reserved_size=reserved_size@entry=0) at /build/buildd/glib2.0-2.40.2/./glib/garray.c:193
#2  0x00007f0db50aed1b in g_array_new (zero_terminated=zero_terminated@entry=0, clear=clear@entry=1, elt_size=elt_size@entry=16)
    at /build/buildd/glib2.0-2.40.2/./glib/garray.c:164
#3  0x00007f0db53c1f7f in cfg_token_block_new () at ../../lib/cfg-lexer.c:1161
#4  0x00007f0db53c1f9f in cfg_lexer_unput_token (self=self@entry=0x7f5e70, yylval=yylval@entry=0x7ffd7d4ff600) at ../../lib/cfg-lexer.c:770
#5  0x00007f0db53f0c63 in filter_expr_parse (lexer=0x7f5e70, result=0x7ffd7d501988, arg=0x0) at lib/filter/filter-expr-grammar.y:395
#6  0x00007f0db53e428b in cfg_parser_parse (arg=0x0, instance=0x7ffd7d501988, lexer=0x7f5e70, self=<optimized out>) at ../../lib/cfg-parser.h:83
#7  main_parse (lexer=0x7f5e70, dummy=0x7ffd7d503cd8, arg=0x0) at ../../lib/cfg-grammar.y:627
#8  0x00007f0db53bf8e0 in cfg_parser_parse (arg=0x0, instance=0x7ffd7d503cd8, lexer=0x7f5e70, self=0x7f0db563bea0 <main_parser>) at ../../lib/cfg-parser.h:83
#9  cfg_run_parser (self=0x7b8120, lexer=0x7f5e70, parser=0x7f0db563bea0 <main_parser>, result=result@entry=0x7ffd7d503cd8, arg=arg@entry=0x0) at ../../lib/cfg.c:372
#10 0x00007f0db53bfaaa in cfg_read_config (self=0x7b8120, fname=0x78ae10 "/etc/syslog-ng/syslog-ng.conf", syntax_only=syntax_only@entry=0,
    preprocess_into=preprocess_into@entry=0x0) at ../../lib/cfg.c:437
#11 0x00007f0db53d4575 in main_loop_reload_config_initiate (user_data=0x7f0db563eec0 <main_loop>) at ../../lib/mainloop.c:285
#12 0x00007f0db3a4ac03 in ?? () from /usr/lib/x86_64-linux-gnu/libivykis.so.0
#13 0x00007f0db3a48dc3 in ?? () from /usr/lib/x86_64-linux-gnu/libivykis.so.0
#14 0x00007f0db3a49440 in ?? () from /usr/lib/x86_64-linux-gnu/libivykis.so.0
#15 0x00007f0db3a4a404 in iv_main () from /usr/lib/x86_64-linux-gnu/libivykis.so.0
#16 0x00007f0db53d4d28 in main_loop_run (self=0x7f0db563eec0 <main_loop>) at ../../lib/mainloop.c:531
#17 0x000000000040190b in main (argc=1, argv=0x7ffd7d504398) at ../../syslog-ng/main.c:303

## Steps to reproduce

We have a software stack based out of Ubuntu 16 with a few patches of our own to syslog-ng. I am not sure how easy it will be to reproduce outside of our stack.

1. Configure a remote syslog server 
2. service syslog-ng reload
< reload happens fine>
3.  service syslog-ng reload
<crashes with the above stack trace> 

I am looking for any inputs on what could be going wrong. I will be actively debugging this on my end. Appreciate any help from anyone whom might have seen this before or might have a clue what could be causing this. At first it appeared to me like a glib problem. Googling told me that applications somehow are responsible for this.

**Comment by alltilla** [comment]
Hi @navrev 
Are you planning to continue to work on the async DNS resolution?

Regards,
Attila

**Comment by navrev** [comment]
Hi Attila,

I worked on async resolution. I haven't sent the patch upstream yet. Let me
get to it in a few days.

**Comment by navrev** [comment]
@alltilla I am new to github, can you help me with documentation to create a pull request. I'll submit my patch.

**Comment by alltilla** [comment]
@navrev 
Sure, here it is: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork

When you opened the PR, most probably there will be changes needed. When you did some change, you can push it to your branch on your fork, and it will automatically update the PR, too.

**Comment by MrAnno** [comment]
We were unable to reproduce this issue, which seems to be a heap corruption in a modified syslog-ng 3.11 version.
As you mentioned, you have had a few patches of your own on top of the v3.11 release, which may have caused the problem.

Please share those patches and reopen this issue, if you still experience this problem in a recent version.
