### ISSUE TITLE
LD_LIBRARY_PATH not taken into account

### ISSUE THREAD

**Issue by Wernfried** [syslog-ng/syslog-ng#2456]
I am referring to this topic: https://github.com/balabit/syslog-ng/issues/2424

In order to use latest SQLite features I replaced file /usr/lib64/libsqlite3.so.0.8.6 with latest compiled version of sqlite source code. In general everything is working fine.

Problem is shared object /usr/lib64/libsqlite3.so.0.8.6 might be replaced again by outdated version if the admin applies any standard Linux patches. So I decided to move the latest shared object to private location /opt/mediation/lib and change `LD_LIBRARY_PATH` accordingly. However, syslog-ng does not use the new version, it seems to be hard-linked to /usr/lib64/libsqlite3.so.0.8.6

```
[mediation@t-mipmed-as-01 ~]$ echo $LD_LIBRARY_PATH
/opt/mediation/lib:/opt/app/oracle/product/11.2.0/client_1/lib

[mediation@t-mipmed-as-01 ~]$ ls -l /opt/mediation/lib/libsqlite3*
lrwxrwxrwx. 1 mediation mediation     19 Dec 10 08:20 /opt/mediation/lib/libsqlite3.so -> libsqlite3.so.0.8.6
lrwxrwxrwx. 1 mediation mediation     19 Dec 10 08:20 /opt/mediation/lib/libsqlite3.so.0 -> libsqlite3.so.0.8.6
-rwxr-xr-x. 1 mediation mediation 959345 Dec 10 07:59 /opt/mediation/lib/libsqlite3.so.0.8.6

[mediation@t-mipmed-as-01 ~]$ lsof -p 27965 | grep libsqlite3*
syslog-ng 27965 mediation  mem       REG              253,0   753232   83909662 /usr/lib64/libsqlite3.so.0.8.6
```

I run also a Perl script which uses SQLite, This perl script uses correct version `/opt/mediation/lib/libsqlite3.so.0.8.6`, so `LD_LIBRARY_PATH` is set properly.

I can force the correct file with `LD_PRELOAD=/opt/mediation/lib/libsqlite3.so`, however I wonder if this behavior is intended by syslog-ng or whether it should work with `LD_LIBRARY_PATH` only.

My impression is that `LD_PRELOAD` is more used for debugging and developing but less suitable for production code (but I might be wrong)

Best Regards

**Comment by bazsi** [comment]
Hmm, syslog-ng might be compiled in a mode where it does change
LD_LIBRARY_PATH, the PE version uses that, but unless you are using that,
you shouldn't be affected.

If that's not the case, LD_LIBRARY_PATH should be taken into account.

To troubleshoot you could always check /proc/<pid>/env like this:

```
$ cat /proc/<pid>/env | xargs -0 echo
```

And check if the environment variable is there.

**Comment by Wernfried** [comment]
Yes, `cat /proc/<pid>/env | xargs -0 echo` show environment as expected:

`LD_LIBRARY_PATH=/opt/mediation/lib:/opt/app/oracle/product/11.2.0/client_1/lib`

**Comment by MrAnno** [comment]
`LD_LIBRARY_PATH` should work in general, but syslog-ng does not depend on libsqlite3 directly, it uses `libdbi` instead.
`libdbi-dbd-sqlite` is responsible for loading libsqlite3.

I would check whether /usr/lib64/dbd/libdbdsqlite3.so is force-linked to /usr/lib64/libsqlite3.so.0.8.6, for example:
```
LD_LIBRARY_PATH=/... ldd /usr/lib64/dbd/libdbdsqlite3.so
```

Please reopen this issue if you think it's an issue with syslog-ng, or you have further questions.
