### ISSUE TITLE
Weird value sometimes for queued stats

### ISSUE THREAD

**Issue by polak785** [syslog-ng/syslog-ng#2474]
# syslog-ng

## Version of syslog-ng

Edit: Still occurs with syslog-ng 3 (3.25.1).

```
syslog-ng 3 (3.19.1)
Config version: 3.19
Installer-Version: 3.19.1
Revision: 3.19.1-1
Compile-Date: Dec 13 2018 15:13:38
Module-Directory: /usr/lib/syslog-ng/3.19
Module-Path: /usr/lib/syslog-ng/3.19
Include-Path: /usr/share/syslog-ng/include
Available-Modules: disk-buffer,sdjournal,tags-parser,hook-commands,dbparser,json-plugin,date,afsocket,cef,xml,kvformat,syslogformat,basicfuncs,afuser,linux-kmsg-format,system-source,cryptofuncs,csvparser,affile,pseudofile,confgen,afprog,appmodel
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: on
Enable-TCP-Wrapper: on
Enable-Linux-Caps: on
Enable-Systemd: on
```

## Platform

Edit: Still occurs with Ubuntu 20.04

`Ubuntu 16.04.5` and `Ubuntu 14.04.5`

# Issue

## Failure

We have a monitoring that check every 30s the value of the stats: processed, written, dropped and queued.

It often happened that a weird value is retrieve for the stats `queued` only. Here are some example of values:
- 623114166329008768.000000
- 616167067881942784.000000
- 602754809439916928.000000
- 617238611323253888.000000

That's always this same format.

## Steps to reproduce

The command used to retrieve the info is: `/usr/sbin/syslog-ng-ctl query get "*d_logstash*queued" | cut -d "=" -f2`

## Configuration

```
@version: 3.19
@include "scl.conf"

# Syslog-ng configuration file, compatible with default Debian syslogd
# installation.

# First, set some global options.
options { chain_hostnames(off); flush_lines(0); use_dns(no); use_fqdn(no);
	  owner("root"); group("adm"); perm(0640); stats_freq(0);
	  bad_hostname("^gconfd$");
};

########################
# Sources
########################
# This is the default behavior of sysklogd package
# Logs may come from unix stream, but not from another machine.
#
source s_src {
       system();
       internal();
};

# If you wish to get logs from remote machine you should uncomment
# this and comment the above source line.
#
#source s_net { tcp(ip(127.0.0.1) port(1000)); };

########################
# Destinations
########################
# First some standard logfile
#
destination d_auth { file("/var/log/auth.log"); };
destination d_cron { file("/var/log/cron.log"); };
destination d_daemon { file("/var/log/daemon.log"); };
destination d_kern { file("/var/log/kern.log"); };
destination d_lpr { file("/var/log/lpr.log"); };
destination d_mail { file("/var/log/mail.log"); };
destination d_syslog { file("/var/log/syslog"); };
destination d_user { file("/var/log/user.log"); };
destination d_uucp { file("/var/log/uucp.log"); };

# This files are the log come from the mail subsystem.
#
destination d_mailinfo { file("/var/log/mail.info"); };
destination d_mailwarn { file("/var/log/mail.warn"); };
destination d_mailerr { file("/var/log/mail.err"); };

# Logging for INN news system
#
destination d_newscrit { file("/var/log/news/news.crit"); };
destination d_newserr { file("/var/log/news/news.err"); };
destination d_newsnotice { file("/var/log/news/news.notice"); };

# Some 'catch-all' logfiles.
#
destination d_debug { file("/var/log/debug"); };
destination d_error { file("/var/log/error"); };
destination d_messages { file("/var/log/messages"); };

# The root's console.
#
destination d_console { usertty("root"); };

# Virtual console.
#
destination d_console_all { file(`tty10`); };

# The named pipe /dev/xconsole is for the nsole' utility.  To use it,
# you must invoke nsole' with the -file' option:
#
#    $ xconsole -file /dev/xconsole [...]
#
destination d_xconsole { pipe("/dev/xconsole"); };

# Send the messages to an other host
#
#destination d_net { tcp("127.0.0.1" port(1000) log_fifo_size(1000)); };

# Debian only
destination d_ppp { file("/var/log/ppp.log"); };

########################
# Filters
########################
# Here's come the filter options. With this rules, we can set which 
# message go where.

filter f_dbg { level(debug); };
filter f_info { level(info); };
filter f_notice { level(notice); };
filter f_warn { level(warn); };
filter f_err { level(err); };
filter f_crit { level(crit .. emerg); };

filter f_debug { level(debug) and not facility(auth, authpriv, news, mail); };
filter f_error { level(err .. emerg) ; };
filter f_messages { level(info,notice,warn) and 
                    not facility(auth,authpriv,cron,daemon,mail,news); };

filter f_auth { facility(auth, authpriv) and not filter(f_debug); };
filter f_cron { facility(cron) and not filter(f_debug); };
filter f_daemon { facility(daemon) and not filter(f_debug); };
filter f_kern { facility(kern) and not filter(f_debug); };
filter f_lpr { facility(lpr) and not filter(f_debug); };
filter f_local { facility(local0, local1, local3, local4, local5,
                        local6, local7) and not filter(f_debug); };
filter f_mail { facility(mail) and not filter(f_debug); };
filter f_news { facility(news) and not filter(f_debug); };
filter f_syslog3 { not facility(auth, authpriv, mail) and not filter(f_debug); };
filter f_user { facility(user) and not filter(f_debug); };
filter f_uucp { facility(uucp) and not filter(f_debug); };

filter f_cnews { level(notice, err, crit) and facility(news); };
filter f_cother { level(debug, info, notice, warn) or facility(daemon, mail); };

filter f_ppp { facility(local2) and not filter(f_debug); };
filter f_console { level(warn .. emerg); };

########################
# Log paths
########################
log { source(s_src); filter(f_auth); destination(d_auth); };
log { source(s_src); filter(f_cron); destination(d_cron); };
log { source(s_src); filter(f_daemon); destination(d_daemon); };
log { source(s_src); filter(f_kern); destination(d_kern); };
log { source(s_src); filter(f_lpr); destination(d_lpr); };
log { source(s_src); filter(f_syslog3); destination(d_syslog); };
log { source(s_src); filter(f_user); destination(d_user); };
log { source(s_src); filter(f_uucp); destination(d_uucp); };

log { source(s_src); filter(f_mail); destination(d_mail); };
#log { source(s_src); filter(f_mail); filter(f_info); destination(d_mailinfo); };
#log { source(s_src); filter(f_mail); filter(f_warn); destination(d_mailwarn); };
#log { source(s_src); filter(f_mail); filter(f_err); destination(d_mailerr); };

log { source(s_src); filter(f_news); filter(f_crit); destination(d_newscrit); };
log { source(s_src); filter(f_news); filter(f_err); destination(d_newserr); };
log { source(s_src); filter(f_news); filter(f_notice); destination(d_newsnotice); };
#log { source(s_src); filter(f_cnews); destination(d_console_all); };
#log { source(s_src); filter(f_cother); destination(d_console_all); };

#log { source(s_src); filter(f_ppp); destination(d_ppp); };

log { source(s_src); filter(f_debug); destination(d_debug); };
log { source(s_src); filter(f_error); destination(d_error); };
log { source(s_src); filter(f_messages); destination(d_messages); };

log { source(s_src); filter(f_console); destination(d_console_all);
				    destination(d_xconsole); };
log { source(s_src); filter(f_crit); destination(d_console); };

# All messages send to a remote site
#
#log { source(s_src); destination(d_net); };

###
# Include all config files in /etc/syslog-ng/conf.d/
###
@include "/etc/syslog-ng/conf.d/*.conf"

```

**Comment by faxm0dem** [comment]
we also periodically see unusually high values, although I'd have to check the scale when back at `$WORK`

**Comment by szemere** [comment]
Hello @polak785 , @faxm0dem ,
 I started to work on this problem, I would like to share my results.

 Unfortunately there is some incoherence with the sign/unsigned handling along the execution path of the query. I am working on a patch to solve it out, but I doubt that this is causing the problem right now. (The examples are far away from the extremal values.)
The strange thing is that we use G_GSIZE_FORMAT for printing those statistics, so we should not get decimal points at all.
 @polak785: It would be very helpfull if you can also share the config of the `d_logstash` destination. (It is included by the copied one, and the problem might be related to diskq, or other storage options.)
@faxm0dem : I would approciate if you can share your values (and the relevant config).

 Currently I am trying to reproduce the problem, no results yet.

Br,
Laci

**Comment by polak785** [comment]
Hello @szemere, 

Thanks for the follow of this problem.

On our instances, the logs are sent to 2 destinations : to a syslog and a logtash server.

The problem happen on these 2 destinations but it appears that this is a bit more often for logstash queue metric. The metrics are pulled every 30 seconds, and a strange value is retrieves around between 5 and 25 times per instances per day (total of both destinations).

Here are the config for the destinations:
```

destination d_server {
    syslog(
        "syslog.xxx.com"
        transport("tcp")
        disk-buffer(
            reliable(yes)
            mem-buf-size(100M)
            disk-buf-size(1G)
            dir("/var/syslog-ng/disk-buffer")
        )
    );
};

rewrite r_host {
    set("hostname.blob", value("HOST"));
};

log {
    source(s_src);
    rewrite(r_host);
    destination(d_server);
};

log {
	source(s_external);
	rewrite(r_host);
	destination(d_server);
};

destination d_logstash {
    tcp(
        "logstash.xxx.com"
        port(9000)
        template("$(format_json --scope selected_macros \
                                --scope nv_pairs \
                                --pair ENVIRONMENT=\"tools\" \
                                --pair HUMANNAME=\"hostname.blob.com\" \
                                --pair PROFILE=\"foo\" \
                                --pair ROLES=\"['bar']\")\n")
        disk-buffer(
            reliable(yes)
            mem-buf-size(100M)
            disk-buf-size(1G)
            dir("/var/syslog-ng/disk-buffer")
        )
    );
};

filter remove_tests_for_logstash {
    not (
        message("GET /test => generated")
        or message("root: AuthRolePlugin: route /test, method GET ANON allowed, no access token")
        or message("application.plugins.auth_role_plugin: Route /test, method GET ANON allowed, no access token")
        or message("\"GET /test HTTP/1.1\" 200")
        or message("\"GET /_health HTTP/1.1\" 200")
    );
};

log {
    source(s_src);
    destination(d_logstash);
};

log {
    source(s_external);
    filter(remove_tests_for_logstash);
    destination(d_logstash);
};
```

**Comment by szemere** [comment]
Hello @polak785,
 Using disk buffers, I was able to reproduce an underflow incident at the weekend, but the method is not stable, and my values are far away from yours (Those were proper near "MAX_INT" values.).

 Working on the issue, I will report my findings.

Br,
Laci

**Comment by polak785** [comment]
I found new things:

- It appears that this problem appears less on Ubuntu 14.04. We have only 3 servers (of around 60) on Ubuntu 14.04 and a weird value has been detected only 44 times (total of the 3 servers) during 3 last months.

- The same weird value `18446744073709551616.000000` comes back very often and on differents servers.

- The weird values like `610018022897693696` seems to be unique.

I hope it will help you.

**Comment by polak785** [comment]
Hello,

I add additonnal information, the "weird" value is not a float value (therefore without `.000000`).
I thought that, because my monitoring tool is configured to receive float values and it displays the error with the float value.

**Comment by polak785** [comment]
Hello,

We still have this issue on Ubuntu 20.04 with syslog-ng 3 (3.25.1).

I confirm that when this occurs, the value is still the same : `18446744073709551615`

You have no hint to fix this ? I can provide other informations if required

**Comment by faxm0dem** [comment]
FWIW 18446744073709551616 is exactly 16 Exabytes

**Comment by polak785** [comment]
Rectification, the value is either 18446744073709551615 or 18446744073709551616 when this happens

**Comment by gaborznagy** [comment]
Hi @polak785!

Unfortunately, we haven't made any progress on this issue, but we have received reports about the same issue from others as well.
While I can't guarantee any deadline, we plan to look into this in the near future.
We have no reproduction steps so far, in the meantime if you can add any more detail about the context when this happens (e.g. are there any internal errors reported in syslog-ng, or what is the value of `processed` counter at the same time), that would help a lot.

**Comment by MrAnno** [comment]
@polak785 @faxm0dem Do you have, by any chance, error messages about corrupt disk-buffer files from the time this happens?

It seems we don't reset queue counters after we detect a corrupt disk buffer. In such a case, the queue file is dropped and an empty one is created.

**Comment by faxm0dem** [comment]
I just checked, and the last weird value (about 6 exabytes) corresponds to a `Configuration reload`, and no disk buffer error

**Comment by MrAnno** [comment]
@faxm0dem Thanks for the quick response. This is a really good clue for us.

It's probably not the case, but I just want to make sure:
Suppose the disk-buffer remains empty after detecting the weird value. Does the underflown value disappear if you repeat the syslog-ng-ctl statistic query?

Based on my theory, the answer is no, and I guess this only disappears when you execute another reload or restart, right?

**Comment by faxm0dem** [comment]
I'm not sure what you mean. Here's the values around the "failure" in csv format. The way this is collected is using collectd (exec syslog-ng-ctl) then sent to elasticsearch. There are a few time aggregations at hand here, explaining the non-integer values, so this ain't raw data unfortunately. But it might help you anyway, I hope.
[syslog-ng-data-2021-09-23 13 20 23.csv](https://github.com/syslog-ng/syslog-ng/files/7217173/syslog-ng-data-2021-09-23.13.20.23.csv)

**Comment by MrAnno** [comment]
Thank you.

**Comment by MrAnno** [comment]
I've finally reproduced one of the mentioned weird "queued" counter overflows.
I'm now trying to find the root cause.

**Comment by MrAnno** [comment]
I think I got it. I'm opening a PR that hopefully fixes this issue completely.
If not, feel free to reopen the issue.
