### ISSUE TITLE
SEQNUM resets on syslog-ng reload, destination network

### ISSUE THREAD

**Issue by rohitranahsr** [syslog-ng/syslog-ng#2504]
# syslog-ng
## Version of syslog-ng

/usr/sbin/syslog-ng --version
syslog-ng 3.5.6
Installer-Version: 3.5.6
Revision: 
Compile-Date: Dec 30 2015 19:57:24
Available-Modules: affile,afprog,afsocket-notls,afsocket-tls,afsocket,afstomp,afuser,basicfuncs,confgen,cryptofuncs,csvparser,dbparser,linux-kmsg-format,syslogformat,system-source
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: on
Enable-TCP-Wrapper: on
Enable-Linux-Caps: on
Enable-Pcre: on

## Platform

CentOS 7

## Configuration

options {
    flush_lines (0);
    time_reopen (10);
    log_fifo_size (1000);
    chain_hostnames (off);
    use_dns (no);
    use_fqdn (no);
    create_dirs (no);
    keep_hostname (yes);
};

source s_sys {
    system();
    internal();
};

template "t_1" { template("<${PRI}>1 ${ISODATE} ${HOST} ${PROGRAM} ${PID} SN:${SEQNUM} RC:${RCPTID} ${SDATA} ${MESSAGE}\n"); };
destination "d_1_udp" { network("10.10.10.101" transport(udp) port(514) template("t_1")); };
log { source(s_sys);  destination("d_1_udp"); };

# Issue

SEQNUM is lost when syslog-ng is reloaded. 
As per documentation it should not be lost on reload

reload command : 
/usr/sbin/syslog-ng-ctl reload
OK Config reload initiated

## Steps to reproduce

1. start syslog-ng

2. configure destination log forwarding to network destination on udp port, as in above configs

3. reload syslog-ng (/usr/sbin/syslog-ng-ctl reload)

4. try to send some syslog, using a dummy user addition/removal

.........syslog at destination.......
AUTHPRIV.INFO: 1 2019-01-20T22:57:19-05:00 localhost useradd 29763 SN:3 RC: [meta sequenceId="3"] new user: name=abc, UID=1001, GID=100, home=/home/abc, shell=/bin/bash\n
AUTHPRIV.INFO: 1 2019-01-20T22:57:20-05:00 localhost userdel 29774 SN:4 RC: [meta sequenceId="4"] delete user 'abc'\n
..

5. observe SEQNUM at destination server, its pointing to 4 now.

6. reload syslog-ng(/usr/sbin/syslog-ng-ctl reload) and try again to send some syslog, using a dummy user addition/removal.
Observe logs at destination
 
/usr/sbin/syslog-ng-ctl reload
OK Config reload initiated

.........syslog at destination.......
SYSLOG.NOTICE: 1 2019-01-20T23:01:03-05:00 localhost syslog-ng 29639 SN:1 RC: [meta sequenceId="1"] Configuration reload request received, reloading configuration;\n
SYSLOG.NOTICE: 1 2019-01-20T23:01:03-05:00 localhost syslog-ng 29639 SN:2 RC: [meta sequenceId="2"] EOF on control channel, closing connection;\n
AUTHPRIV.INFO: 1 2019-01-20T23:03:27-05:00 localhost useradd 29869 SN:3 RC: [meta sequenceId="3"] new user: name=abc, UID=1001, GID=100, home=/home/abc, shell=/bin/bash\n
..

Issue : reloading has reset the SEQNUM to 1.

Please suggest, if this is bug in syslog-ng or something is missing here.
Checked this in latest versions of syslog-ng, observed same behavior.

**Comment by alltilla** [comment]
Hi Rohit,

Thank you for your finding!

I am observing the same behavior on 3.19. It seems, that syslog-ng misses the implementation of storing the sequenceId during a reload, where I think it should be stored. Whether we should load this value after stop & start is a different question.

From [RFC 5424](https://tools.ietf.org/html/rfc5424#section-7.3.1):
7.3.1.  sequenceId
The "sequenceId" parameter tracks the sequence in which the originator submits messages to the syslog transport for sending. It is an integer that MUST be set to 1 when the syslog function is started and MUST be increased with every message up to a maximum value of 2147483647. If that value is reached, the next message MUST be sent with a sequenceId of 1.

From a technical perspective, sequence number is stored in:
 * `gint32 shared_seq_num` in `LogThreadedDestDriver`
 * `gint32 seq_num` in `LogWriter`

If we want to implement this, the `sequenceId` should possibly be stored in the persist file, and `LogWriter` and `LogThreadedDestDriver` should be initialized with that value after reload.

Although this is my opinion, we will have a discussion about this proposal.

Best regards,
Attila

**Comment by alltilla** [comment]
We could not decide, whether we want to store and load the `sequenceId` during reload.

@bazsi: Could you kindly give your opinion about this proposal? Thanks!

PS: another SEQNUM related question, which might bring up some arguments: #2152

**Comment by alltilla** [comment]
In threaded-destinations (e.g.: http), it seems to work, In LogWriter, it does not. I believe it should provide the same behavior.

test config:
```
@version: 3.19
@include "scl.conf"

options {
  flush_lines (0);
  time_reopen (10);
  log_fifo_size (1000);
  chain_hostnames (off);
  use_dns (no);
  use_fqdn (no);
  create_dirs (no);
  keep_hostname (yes);
};

source s_sys {
  system();
  internal();
};

destination d_http {
  http(
    url("http://localhost:8880")
    method("POST")
    headers("Content-Type: application/x-ndjson")
    body-suffix("\n")
    body("http-destination: $SEQNUM")
  );
};

destination d_file {
  file(
    "/tmp/seqnum.log"
    template("file-destination: $SEQNUM\n")
  );
};

log {
  source(s_sys);
  destination(d_http);
  destination(d_file);
};
```
run log:
```
attilaszakacs[14:58][ ~/install ]$ sudo ./sbin/syslog-ng -f /home/attilaszakacs/seq.conf -Fedtv |& grep "\-destination\|syslog-ng-ctl reload"

[2019-01-21T14:58:55.238863] Outgoing message; message='file-destination: 1\x0a'
[2019-01-21T14:58:55.238895] Outgoing message; message='file-destination: 2\x0a'
[2019-01-21T14:58:55.240658] Outgoing message; message='file-destination: 3\x0a'
[2019-01-21T14:58:55.243158] cURL debug; worker='0', type='data_out', data='http-destination: 1.'
[2019-01-21T14:58:55.243413] cURL debug; worker='0', type='data_out', data='http-destination: 2.'
[2019-01-21T14:58:55.243631] cURL debug; worker='0', type='data_out', data='http-destination: 3.'
[2019-01-21T14:58:56.022654] Outgoing message; message='file-destination: 4\x0a'
[2019-01-21T14:58:56.022680] Outgoing message; message='file-destination: 5\x0a'
[2019-01-21T14:58:56.022787] cURL debug; worker='0', type='data_out', data='http-destination: 4.'
[2019-01-21T14:58:56.022946] cURL debug; worker='0', type='data_out', data='http-destination: 5.'
[2019-01-21T14:58:56.024238] Outgoing message; message='file-destination: 6\x0a'
[2019-01-21T14:58:56.024398] cURL debug; worker='0', type='data_out', data='http-destination: 6.'
[2019-01-21T14:58:56.972294] Outgoing message; message='file-destination: 7\x0a'
[2019-01-21T14:58:56.972444] cURL debug; worker='0', type='data_out', data='http-destination: 7.'

#### RELOAD ####
[2019-01-21T14:58:57.158095] Incoming log entry; line='<85>Jan 21 14:58:57 sudo: attilaszakacs : TTY=pts/11 ; PWD=/home/attilaszakacs/install ; USER=root ; COMMAND=./sbin/syslog-ng-ctl reload'
[2019-01-21T14:58:57.158132] Setting value; name='MESSAGE', value='attilaszakacs : TTY=pts/11 ; PWD=/home/attilaszakacs/install ; USER=root ; COMMAND=./sbin/syslog-ng-ctl reload', msg='0x7f41d802ba20'
[2019-01-21T14:58:57.158137] Setting value; name='.unix.cmdline', value='sudo ./sbin/syslog-ng-ctl reload ', msg='0x7f41d802ba20'
[2019-01-21T14:58:57.158212] json-parser message processing started; input='attilaszakacs : TTY=pts/11 ; PWD=/home/attilaszakacs/install ; USER=root ; COMMAND=./sbin/syslog-ng-ctl reload', prefix='.cim.', marker='@cim:', msg='0x7f41d802ba20'
[2019-01-21T14:58:57.158216] json-parser(): no marker at the beginning of the message, skipping JSON parsing ; input='attilaszakacs : TTY=pts/11 ; PWD=/home/attilaszakacs/install ; USER=root
; COMMAND=./sbin/syslog-ng-ctl reload', marker='@cim:'
[2019-01-21T14:58:57.158257] kv-parser message processing started; input='attilaszakacs : TTY=pts/11 ; PWD=/home/attilaszakacs/install ; USER=root ; COMMAND=./sbin/syslog-ng-ctl reload', prefix='.sudo.', msg='0x7f41d802a220'
[2019-01-21T14:58:57.158281] Setting value; name='.sudo.COMMAND', value='./sbin/syslog-ng-ctl reload', msg='0x7f41d802a220'
[2019-01-21T14:58:57.158315] match() evaluation started; input='./sbin/syslog-ng-ctl reload', pattern='', value='.sudo.COMMAND', msg='0x7f41d802a220'
[2019-01-21T14:58:57.158422] Setting value; name='.unix.cmdline', value='sudo ./sbin/syslog-ng-ctl reload ', msg='0x7f41d802c9a0'
[2019-01-21T14:58:57.158686] cURL debug; worker='0', type='data_out', data='http-destination: 8.'
[2019-01-21T14:58:57.158735] Outgoing message; message='file-destination: 8\x0a'
[2019-01-21T14:58:57.158761] Outgoing message; message='file-destination: 9\x0a'
[2019-01-21T14:58:57.158918] cURL debug; worker='0', type='data_out', data='http-destination: 9.'
[2019-01-21T14:58:57.173052] Setting value; name='.unix.cmdline', value='sudo ./sbin/syslog-ng-ctl reload ', msg='0x7f41d8028200'

#### RELOAD DONE ####

[2019-01-21T14:58:57.173293] Outgoing message; message='file-destination: 1\x0a'
[2019-01-21T14:58:57.177638] cURL debug; worker='0', type='data_out', data='http-destination: 10.'
[2019-01-21T14:58:59.142702] Outgoing message; message='file-destination: 2\x0a'
[2019-01-21T14:58:59.142729] Outgoing message; message='file-destination: 3\x0a'
[2019-01-21T14:58:59.142828] cURL debug; worker='0', type='data_out', data='http-destination: 11.'
[2019-01-21T14:58:59.143033] cURL debug; worker='0', type='data_out', data='http-destination: 12.'
[2019-01-21T14:58:59.144381] cURL debug; worker='0', type='data_out', data='http-destination: 13.'
```

**Comment by bazsi** [comment]
Well, I already wanted to eliminate SEQNUM in that proposal :) The current
SEQNUM support is somewhat broken, and I think we should enumerate the
alternatives and come up with a decision how we want to cope with it.

I think not surviving the reload still meets the letter of the RFC as the
primary reason is to identify ordering of messages within the same second:
https://www.cisco.com/c/en/us/td/docs/routers/access/wireless/software/guide/SysMsgLogging.html#wp1054751

**Comment by alltilla** [comment]
@rohitranahsr:

Hi Rohit,

It seems, that the function of `sequenceId` is to provide the sequence of log messages sent from the same timestamp, and not to provide a unique ID for that particular log message.

From CISCO documentation, mentioned above:
"Because there is a chance that more than one log message can have the same timestamp, you can display messages with sequence numbers so that you can unambiguously refer to a single message."

If we follow this logic, we could reset the `sequenceId` to 1, every time a log message arrives with a new timestamp, so keeping it between reloads seems unnecessary. Also `sequenceId` would be interesting if the timestamp is given with only "sec" precision.

Depending on your use-case, I could advise to use the `$UNIQID` macro, which is generated from the `$HOSTID` and `$RCPTID`, and gives an absolutely unique ID for that log message. Would that suit your needs?

Best regards,
Attila

**Comment by rohitranahsr** [comment]
Thanks all for looking into this use case. Apologies for late reply.

Going by the cisco device behavior, It seems this functionality is to enable sequence number for display.
It seems sequence number is always there, but it will be displayed after configuring this command.
Correct me if I assumed it incorrectly, but I believe this should be the intent behind this behavior here in cisco.

Thinking from a monitoring system point of view, it looks odd to watch two(timestamp and seq num) attributes for unambiguous filtering. It should be either timestamp or seq num, and more precisely just seq num.

But I am concerned about locally sourced messages, not on cisco devices, there are three situation mentioned in syslog-ng doc for SEQNUM.
https://www.syslog-ng.com/technical-documents/doc/syslog-ng-open-source-edition/3.16/administration-guide/58#TOPIC-956606

….snippet…
For locally generated messages (that is, for messages that are received from a local source, and not from the network), syslog-ng OSE calculates a sequence number when sending the message to a destination (it is not calculated for relayed messages).
•	The sequence number is not global, but per-destination. Essentially, it counts the number of messages sent to the destination.
•	This sequence number increases by one for every message sent to the destination. It not lost when syslog-ng OSE is reloaded, but it is reset when syslog-ng OSE is restarted.
o	This sequence number is added to every message that uses the IETF-syslog protocol (${.SDATA.meta.sequenceId}), and can be added to BSD-syslog messages using the ${SEQNUM}macro.
……….
I think this behavior mentioned in the documents seems appropriate, SEQNUM should be per destination and unique-incremental  for this destination.
However if team is deciding to remove the scope of SEQNUM here, then these global documentation needs to be updated accordingly for behavioral references.

$UNIQID seems to be based on source machine running syslog-ng.
It is fine to use this if there is only 1 destination configured. if there are two destinations, and if each is configured to send different severities.
Then both destination would be having some random incremental UNIQIDs.

**Comment by bazsi** [comment]
Hi,


On Wed, Jan 23, 2019 at 10:55 AM Rohit Rana <notifications@github.com>
wrote:

> Thanks all for looking into this use case. Apologies for late reply.
>
> Going by the cisco device behavior, It seems this functionality is to
> enable sequence number for display.
> It seems sequence number is always there, but it will be displayed after
> configuring this command.
> Correct me if I assumed it incorrectly, but I believe this should be the
> intent behind this behavior here in cisco.
>
> Thinking from a monitoring system point of view, it looks odd to watch
> two(timestamp and seq num) attributes for unambiguous filtering. It should
> be either timestamp or seq num, and more precisely just seq num.
>
> But I am concerned about locally sourced messages, not on cisco devices,
> there are three situation mentioned in syslog-ng doc for SEQNUM.
>
> https://www.syslog-ng.com/technical-documents/doc/syslog-ng-open-source-edition/3.16/administration-guide/58#TOPIC-956606
>
> ….snippet…
> For locally generated messages (that is, for messages that are received
> from a local source, and not from the network), syslog-ng OSE calculates a
> sequence number when sending the message to a destination (it is not
> calculated for relayed messages).
> • The sequence number is not global, but per-destination. Essentially, it
> counts the number of messages sent to the destination.
> • This sequence number increases by one for every message sent to the
> destination. It not lost when syslog-ng OSE is reloaded, but it is reset
> when syslog-ng OSE is restarted.
> o This sequence number is added to every message that uses the IETF-syslog
> protocol (${.SDATA.meta.sequenceId}), and can be added to BSD-syslog
> messages using the ${SEQNUM}macro.
> ……….
> I think this behavior mentioned in the documents seems appropriate, SEQNUM
> should be per destination and unique-incremental for this destination.
> However if team is deciding to remove the scope of SEQNUM here, then these
> global documentation needs to be updated accordingly
>
for behavioral references.
>
Our idea currently is to make SEQNUM destination specific, _always_
regardless of the message coming from a local source or relayed. And if
that change is done, this should be reflected in the documentation as well.


> $UNIQID seems to be based on source machine running syslog-ng.
> It is fine to use this if there is only 1 destination configured. if there
> are two destinations, and if each is configured to send different
> severities.
> Then both destination would be having some random incremental UNIQIDs.
>

The UNIQID is truely unique, as it is a combination of two properties: a
sequence number $(RCPTID) and a host number ($HOSTID), RCPTID is increasing
monotonically. $HOSTID is a persisted, random ID for the host syslog-ng
running on. This is generated at first startup and remains the same at
least until syslog-ng.persist gets removed. $RCPTID is also saved in the
persist file, so neither reload or restart will affect its value. $RCPTID
is also shared between sources, e.g. you might see skips between messages,
as syslog-ng might be receiving on other channels as well.

The combination of the two should be unique enough globally at least for a
timespan until $RCPTID overflows (64bit counter...), or if there's a HOSTID
collision. We make an effort to do cryptographically strong enough random
for HOSTID generation, so 32 bits should be unique enough even for global
deployments, where the chances of collision are pretty low.

With that said, if you want unique identifiers, I think $UNIQID is the way
to go.

**Comment by alltilla** [comment]
Closing, as it seems, it does not need any more action. Adding this thread to the big SEQNUM related argument, though. :)
