### ISSUE TITLE
make error with 3.20.1 on solaris 11.3

### ISSUE THREAD

**Issue by yanryb** [syslog-ng/syslog-ng#2631]
# syslog-ng

Hi
I am getting an error when running gmake.

error: conflicting types for (compat_generic__getprotobynumber_r)
error: conflicting types for (compat_generic__getprotobyname_r)
error: conflicting types for (compat_generic__getservbyport_r)
error: conflicting types for (compat_generic__getservbynamer_r)

modules/getent/module_getent_libtfgetent_la-tfgetent.lo error 1

/Y

**Comment by yanryb** [comment]
Found the error.

Moved the include up before define in lib/combat/getent.h.

#include "getent-generic.h"
#define getprotobynumber_r _combat_generic__gertprotobynumber_r
.....

**Comment by Kokan** [comment]
Thanks for the report, is this the only build error you found ? Would you mind to create a PR so in the next release you won't face the same issue ?

**Comment by alltilla** [comment]
I will check this on 11.3 myself :)

**Comment by alltilla** [comment]
I created a build environment in a Solaris 11.4 VM, and observed a similar error but referencing to `_compat_sun__getprotoby_name_r`, etc... I will check this problem, because the `compat` layer here is clearly not serving its purpose 100%.

**Comment by alltilla** [comment]
Managed to build and run `syslog-ng` with #3070. I had to disable `snmp-dest`, because `net-snmp-config --cflags` returned the `-mt` flag, which `gcc` did not like, but otherwise, everything went successfully.
