### ISSUE TITLE
create-dirs() option fails in source pipe()

### ISSUE THREAD

**Issue by jtkristoff** [syslog-ng/syslog-ng#2635]
# syslog-ng

## Version of syslog-ng

```
syslog-ng 3.8.1
Installer-Version: 3.8.1
Revision: 3.8.1-10
Module-Directory: /usr/lib/syslog-ng/3.8
Module-Path: /usr/lib/syslog-ng/3.8
Available-Modules: mod-python,pseudofile,cryptofuncs,afsql,affile,afsocket,syslogformat,geoip-plugin,linux-kmsg-format,date,json-plugin,system-source,sdjournal,confgen,cef,redis,afprog,afsmtp,kvformat,graphite,basicfuncs,csvparser,add-contextual-data,afstomp,disk-buffer,dbparser,afuser,riemann,afamqp,afmongodb
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: on
Enable-TCP-Wrapper: on
Enable-Linux-Caps: off
```

## Platform

Debian 9.7

# Issue

Specifying create-dirs(yes) in source pipe() is not recognized / causes a parsing failure.  Note, this is specified in a separate conf.d/local.conf file that gets loaded later.

## Failure

```
syslog-ng[46941]: Error parsing affile, syntax error, unexpected KW_CREATE_DIRS, expecting KW_NORMALIZE_HOSTNAMES or KW_USE_DNS or KW_USE_FQDN or KW_DNS_CACHE in /etc/syslog-ng/conf.d/local.conf at line 6, column 9:
syslog-ng[46941]: included from /etc/syslog-ng/syslog-ng.conf line 162, column 1
syslog-ng[46941]:         create-dirs(yes)
syslog-ng[46941]:         ^^^^^^^^^^^
```

## Steps to reproduce

Create a conf.d/local.conf that includes the following:

```
source s_pipe {
    pipe(
        "/var/local/pipe"
        flags("no-parse")
        time-zone("UTC")
        create-dirs(yes)
        dir-owner(root)
        dir-group(daemon)
        dir-perm(0755)
        owner(root)
        group(daemon)
        perm(0664)
   );
};
```
1. start syslog-ng

If you comment out the create-dirs option, it works fine.

**Comment by bazsi** [comment]
This is a destination specific option, the source side never supported it.
I am not saying it wouldnt make sense to add this, but then we should do
that similarly in unix-dgram/unix-stream drivers, and possibly files as
well.

I currently dont have time for this feature but patches as always are
appreciated :)

**Comment by jtkristoff** [comment]
Thanks bazsi, thanks for your rapid response.  I would just note that the I thought this was an appropriate issue to raise, because a source pipe() will "create" the pipe, so it seemed at least reasonable to expect the create-dirs() option to work as it would in a destination.

This is not big deal of course and I'm happy to have it marked as wish list or very low priority enhancement indefinitely.

Certainly might not hurt to have it noted here for posterity in case anyone else runs into this.

Cheers!

**Comment by parthw1** [comment]
@bazsi I would like to work on the patch. Can you please help me, from where to start. 
Thank you

**Comment by bazsi** [comment]
Well, there's a function that creates directories, you can find it the file
destination that already supports create-dirs().

The code for both the pipe source and the file destination are in the
modules/affile/ directory.

**Comment by parthw1** [comment]
@bazsi Thank you.

**Comment by vic-ma** [comment]
I think I am misunderstanding something here, but when I was messing around the `pipe()` source driver, it would create nonexistent directories on its own. For example, the following would create directories `newdir1`, `newdir2`, and `newdir3`, if they did not already exist:

```
source s_local {
    pipe("/home/victor/syslog-ng/newdir1/newdir2/newdir3/in");
};
```

However, the same did not work with the destination `pipe()`; it gave an error during runtime if the path passed in had nonexistent directories.

**Comment by gaborznagy** [comment]
@jtkristoff @vic-ma 

We had some discussions on this: it is true that currently `pipe()` source is creating any directory that is not existing automatically, while `pipe()` destination does not, and there is no `create-dirs()` option for pipe destination.

This should be fixed: `create-dirs()` option need to be added to `pipe()` dest. 
Although I would like if pipe() destination could open a pipe under not existing directories:
- pipe dest does not have to follow file destinations behaviour (it already differs by not having the above option),
- I don't see the value of having create-dirs() for pipe(), it could add some protection in case you mistype the directory names.

I have a working branch, it's mainly a 1 line commit, though I would like to do some refactor.

**Comment by gaborznagy** [comment]
About the source side: we don't think that `create-dirs()` option should be used on source side (although unix-* socket source drivers have that option, but that's a different thread).

Personally, I don't see the added value with create-dirs() for sources, pipe() source currently does create directories, so a feature is there, with this option we can disable it, but I don't know if there is a need for that.

About unix-dgram/unix-stream sockets:
It's an interesting one, there was an issue that [unix socket drivers were not creating directories](https://github.com/balabit/syslog-ng/issues/583).
There was a short debate, that whether sources should create directories, but the argument "if a source creates a socket, the it can create the subdirectories as well" won.
There were no reasons stated about the configurability, I guess it's just for flexibility, but the default were set to "no".
