### ISSUE TITLE
Validation of TLS close_notify per RFC spec

### ISSUE THREAD

**Issue by gimmic** [syslog-ng/syslog-ng#2703]
# syslog-ng
I have a report that syslog-ng is not sending a response to a tls session's close_notify alert per RFC5425 4.4 spec: https://tools.ietf.org/html/rfc5425#section-4.4

A mutually authenticated TLS session can be closed by the sender with either TCP closure or close_notify. The transport shipper is rsyslog to our receiver, syslog-ng. rsyslog is reporting a connection error when syslog-ng does not properly respond with the close_notify alert response per RFC.

I'm wondering how to validate this as well as potentially log it, and correct it?

## Version of syslog-ng

```
syslog-ng 3 (3.20.1)
Config version: 3.20
Installer-Version: 3.20.1
Revision: 3.20.1-1
Compile-Date: Mar  1 2019 09:36:45
Module-Directory: /usr/lib/syslog-ng/3.20
Module-Path: /usr/lib/syslog-ng/3.20
Include-Path: /usr/share/syslog-ng/include
Error opening plugin module; module='mod-java', error='libjvm.so: cannot open shared object file: No such file or directory'
Available-Modules: hook-commands,stardate,csvparser,dbparser,afuser,add-contextual-data,graphite,riemann,tfgetent,geoip-plugin,afsocket,syslogformat,afsql,redis,disk-buffer,mod-python,pseudofile,afmongodb,pacctformat,affile,http,geoip2-plugin,confgen,basicfuncs,cryptofuncs,afstomp,xml,map-value-pairs,afamqp,kvformat,appmodel,sdjournal,examples,afprog,cef,afsmtp,date,system-source,json-plugin,snmptrapd-parser,tags-parser,linux-kmsg-format
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: on
Enable-TCP-Wrapper: on
Enable-Linux-Caps: on
Enable-Systemd: on

```

## Platform

Ubuntu 16.04.6 LTS
Linux 4.4.0-87-generic #110-Ubuntu SMP Tue Jul 18 12:55:35 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by bazsi** [comment]
Syslog-ng should call SSL_shutdown() and IIRC it does that, but I don't
have the source handy. By a light reading that should respond to the
close_notify.

How does this problem manifest itself? Is it a warning on the rsyslog side?

Bazsi

**Comment by gimmic** [comment]
rsyslog hangs when it fails to receive the close_notify alert response, eventually timing out and closing the connection(generating an error). 
rsyslog to rsyslog appears to behave as expected.

**Comment by MrAnno** [comment]
Hi @gimmic,

Thanks for opening this issue.
You are correct, there are missing `SSL_shutdown()` calls, so the client's `close_notify` alert won't be answered.

From the OpenSSL docs:

>It is acceptable for an application to only send its shutdown alert and then close the underlying connection without waiting for the peer's response. This way resources can be saved, as the process can already terminate or serve another connection. This should only be done when it is known that the other side will not send more data, otherwise there is a risk of a truncation attack.

It seems rsyslog decided to wait for the shutdown response. `network(), syslog()` and almost all of our supported syslog-related protocols are one-way protocols, so it is known by both sides that the server _never_ "sends more data", this is why it would be safe to just close the connection without waiting (RFC5425: `MAY choose to not wait`).

Nevertheless, we should close TLS connections properly (RFC5425: `MUST reply with a close_notify unless it becomes aware that the connection has already been closed`), so I'll open a PR shortly to fix the `close_notify` "response" issue.

Initiating `close_notify` in our destinations (RFC5425: `MUST send a TLS close_notify alert before closing the connection`) requires a bit more work, so I'll fix that in a separate pull request.
