### ISSUE TITLE
syslog-ng Debian packages are not compiled with riemann microseconds support

### ISSUE THREAD

**Issue by smortex** [syslog-ng/syslog-ng#2726]
I guess this report will mainly concern @lbudai who own the mentioned packages on the OpenSuse build service.

# syslog-ng

## Version of syslog-ng

```
syslog-ng 3 (3.21.1)
Config version: 3.21
Installer-Version: 3.21.1
Revision: 3.21.1-1
Compile-Date: May  3 2019 09:11:19
Module-Directory: /usr/lib/syslog-ng/3.21
Module-Path: /usr/lib/syslog-ng/3.21
Include-Path: /usr/share/syslog-ng/include
Available-Modules: kvformat,affile,riemann,cryptofuncs,afuser,afsocket,confgen,system-source,cef,sdjournal,linux-kmsg-format,csvparser,pseudofile,dbparser,disk-buffer,hook-commands,xml,json-plugin,syslogformat,afprog,tags-parser,date,basicfuncs,appmodel
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: on
Enable-TCP-Wrapper: on
Enable-Linux-Caps: on
Enable-Systemd: on
```

## Platform

```
{
  architecture => "amd64",
  distro => {
    codename => "bionic",
    description => "Ubuntu 18.04.2 LTS",
    id => "Ubuntu",
    release => {
      full => "18.04",
      major => "18.04"
    }
  },
  family => "Debian",
  hardware => "x86_64",
  name => "Ubuntu",
  release => {
    full => "18.04",
    major => "18.04"
  },
  selinux => {
    enabled => false
  }
}
```

# Issue

## Failure

When running syslog-ng with the Debian packages from the OpenSUSE build service [as documented on the syslog-ng blog](https://www.syslog-ng.com/community/b/blog/posts/installing-the-latest-syslog-ng-on-ubuntu-and-other-deb-distributions), it is not possible to use microseconds events resolution in the riemann plugin: "Riemann destination was not compiled with microseconds support":

```
Error parsing riemann, Riemann destination was not compiled with microseconds support in /etc/syslog-ng/syslog-ng.conf20190513-28182-1s4sd5v:187:38-187:50:
182             ),
183             description(
184                 "$MESSAGE"
185             ),
186             event_time(
187--->             "$(* $UNIXTIME 1000000)" microseconds
187--->                                      ^^^^^^^^^^^^
188             ),
189             attributes(
190                 scope(
191                     nv-pairs
192                 ),
```

## Steps to reproduce

1. install syslog-ng following [this page instructions](https://www.syslog-ng.com/community/b/blog/posts/installing-the-latest-syslog-ng-on-ubuntu-and-other-deb-distributions)
2. Configure syslog-ng to send messages to riemann [with microsecond resolution](https://github.com/balabit/syslog-ng/pull/17100)

## Input and output logs (if possible)

See failure message above.  The problem is similar to #2702 : building the package against [riemann-c-client >= 1.10.0](https://github.com/algernon/riemann-c-client/releases/tag/riemann-c-client-1.10.0) should fix the issue.

Would it be possible to have an update?  May I help in some way?

**Comment by smortex** [comment]
i unintentionally hit enter while creating the issue after coping the information from the similar issue #2702 but before finishing updating it :confused: .  I have edited the initial message to fix it. Sorry for the noise.

**Comment by Kokan** [comment]
I'm sorry just missclicked while scrolling on the phone.

**Comment by Kokan** [comment]
@lbudai do you plan to include the microseconds support ? if not please close this issue.

**Comment by lbudai** [comment]
@Kokan : yes, I'll check it

**Comment by lbudai** [comment]
@smortex : I've just built riemann-c-client 1.10 on bionic. 
Some time is still needed by OBS to publish the repository, you can check it here: https://build.opensuse.org/package/show/home:laszlo_budai:syslog-ng/riemann-c-client-1.10

and sorry for this huge delay, but I did not track this issue

**Comment by lbudai** [comment]
@smortex : I'm closing the issue, it should work now.
If you would have any issues, just open a new ticket (or, reopen this one).

**Comment by smortex** [comment]
Sorry @lbudai, I forgot to follow-up.  Thanks to your changes, I could update a bunch of nodes and adjust their configuration, thanks a lot!

I am still managing some old Ubuntu 16.04 nodes for which the package does not build and which I would love to see updated.  I feel like I can try to diagnose and fix the issue on the build service and submit a "pull request", but can't find how to proceed to increase verbosity and hopefully understand what is going wrong (I do not have much experience with deb packaging).  If you have some documentation pointers on the topic, I would be interested in it!  Thanks!

**Comment by bazsi** [comment]
You can possibly compile a package on your own (without obs) using dbld
built into the source tree of syslog-ng and relies on docker.

E.g. just download the tarball/do a git clone and then:

```
$ ./dbld/rules pull-ubuntu-xenial
$ ./dbld/rules deb-ubuntu-xenial
```

The first command will download the ubuntu-xenial build image for syslog-ng
that uses the packages from OBS. Then the 2nd one builds the deb (packaging
files are in /packaging/debian subdirectory).

The build image is automatically built in dockerhub, but in case the
riemann stuff is not recent enough in it, you can manipulate that locally
or even rebuild using the `./dbld/rules image-ubuntu-xenial` command. The
dockerfiles are also in the source tree at the /dbld/images/ directory.
