### ISSUE TITLE
'make install' with internal json fails

### ISSUE THREAD

**Issue by czanik** [syslog-ng/syslog-ng#2732]
# syslog-ng

## Version of syslog-ng

3.21.1 release

## Platform

RHEL 8

# Issue

## Failure

I could not find a json-c-devel package on RHEL8, so fall back to the bundled JSON source. Here is the output of configure:
```
syslog-ng Open Source Edition 3.21.1 configured
 Edition settings:
  Release type                : stable
  Pretty version              : 3
  Combined vers.              : 3 (3.21.1)
  Package name                : syslog-ng
 Compiler options:
  compiler                    : gcc
  compiler options            :  -O2 -g -pthread   -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -pthread  -I$(top_srcdir)/lib/eventlog/src -I$(top_builddir)/lib/eventlog/src     -isystem $(top_srcdir)/lib/ivykis/src/include -isystem $(top_builddir)/lib/ivykis/src/include  -D_GNU_SOURCE -D_DEFAULT_SOURCE -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64
  linker flags                :  
  prefix                      : /usr/local
  linking mode                : dynamic
  embedded crypto             : no
  __thread keyword            : yes
 Test dependencies:
  Criterion                   : no
  Unit tests                  : no
 Submodules:
  ivykis                      : internal
  jsonc                       : internal
 Features:
  Forced server mode          : yes
  Debug symbols               : no
  GCC profiling               : no
  Memtrace                    : no
  IPV6 support                : yes
  spoof-source support        : no
  tcp-wrapper support         : no
  Linux capability support    : no
  Env wrapper support         : no
  systemd support             : yes (unit dir: none)
  systemd-journal support     : system
  libmongo-client options     : yes
 Modules:
  Module search path          : ${exec_prefix}/lib/syslog-ng
  Sun STREAMS support (module): no
  OpenBSD syslog (module)     : no
  SQL support (module)        : auto
  PACCT module (EXPERIMENTAL) : no
  MongoDB destination (module): no
  JSON support (module)       : yes
  SMTP support (module)       : no
  HTTP support (module)       : no
  AMQP destination (module)   : no
  Kafka source (module)       : no
  STOMP destination (module)  : yes
  GEOIP support (module)      : no
  GEOIP2 support (module)     : no
  Redis support (module)      : no
  Kafka support (module)      : no
  Riemann destination (module): no, microseconds: no
  python                      : yes (pkg-config package: python3)
  java                        : no
  java modules                : no
  native bindings             : auto
[root@rhel8 syslog-ng-3.21.1]# 
```

```make``` runs just fine, but when I run ```make install```, it fails:

```
libtool: warning: relinking 'modules/json/libjson-plugin.la'
libtool: install: (cd /root/syslog-ng-3.21.1; /bin/sh "/root/syslog-ng-3.21.1/libtool"  --silent --tag CC --mode=relink gcc -Wshadow -fcommon -Wno-stack-protector -Wno-unused-parameter -Wno-variadic-macros -I./lib/jsonc -I./lib/jsonc -O2 -g -pthread -avoid-version -module -no-undefined -o modules/json/libjson-plugin.la -rpath /usr/local/lib/syslog-ng modules/json/modules_json_libjson_plugin_la-format-json.lo modules/json/modules_json_libjson_plugin_la-json-parser.lo modules/json/modules_json_libjson_plugin_la-json-parser-grammar.lo modules/json/modules_json_libjson_plugin_la-json-parser-parser.lo modules/json/modules_json_libjson_plugin_la-dot-notation.lo modules/json/modules_json_libjson_plugin_la-json-plugin.lo ./lib/libsyslog-ng.la ./lib/jsonc/libjson-c.la )
/usr/bin/ld: cannot find -ljson-c
collect2: error: ld returned 1 exit status
libtool:   error: error: relink 'modules/json/libjson-plugin.la' with the above command before installing it
make[3]: *** [Makefile:8752: install-moduleLTLIBRARIES] Error 1
make[2]: *** [Makefile:22174: install-am] Error 2
make[1]: *** [Makefile:20638: install-recursive] Error 1
make: *** [Makefile:22168: install] Error 2
```

**Comment by Kokan** [comment]
Please try to build json-c without syslog-ng, and try to build latest json-c (maybe upstream it is solved). To get a better idea what happens.

**Comment by czanik** [comment]
Installed json-c from source to /usr/local and then using the following commands syslog-ng could also be compiled and installed (copy & paste from history):
```
  109  JSON_CFLAGS="-I/usr/local/include/json-c" JSON_LIBS="-L/usr/local/lib" ./configure --with-jsonc=system
  110  make
  111  make install
```
One more note: ```json-c``` is instaled on the system, but no ```json-c-devel``` which also might confuse ```./configure``` and/or ```make install```

**Comment by czanik** [comment]
While the original problem is still there, my problem is resolved by finding the repo containing the json-c-devel package with the help of a CentOS developer. The problem is most likely that configure/make gets confused from having json-c installed in the OS but using internal json-c for compilation.

**Comment by lbudai** [comment]
@Kokan , @czanik : next step? (or can we close this?)

**Comment by Kokan** [comment]
As far as I am aware the `JSON_LIBS` meant to hold a *libraray* and not to a path where it might find a library, so it should have been `/usr/local/lib/libjson-c.so` (gestimating only about the so name).

@czanik could you please check via that way ?

**Comment by levaidaniel** [comment]
For what it's worth, this is a bit more inconvenient on e.g. RHEL7, where you don't actually have a -devel package for json-c.
So you have to do some magic there **before** running ./configure:
`export LD_RUN_PATH=$SOURCEDIR/lib/jsonc/.libs
export LDFLAGS=-L$SOURCEDIR/lib/jsonc/.libs`

I think(tm) autotools should take care of this in the build process somehow.

**Comment by czanik** [comment]
Right now I don't even have a test environment. I'll try it again next week. As far as I can see from http://smoogespace.blogspot.com/2019/07/epel-8-production-layout.html finally there are some initial steps to build EPEL 8.

**Comment by DerDakon** [comment]
I have tried to update an embedded environment from 3.20.1 to 3.22.1 and encountered the same error. So it looks like basically all you need to do is have a system without json-c installed to see the error. I can test patches easily in case you have some.

**Comment by MrAnno** [comment]
It seems this is an install-time dependency issue, similar to the one we had between `module_LTLIBRARIES` and `lib_LTLIBRARIES`:

https://github.com/balabit/syslog-ng/commit/0c89da24e42058915d9f57f292635c21ed9e21ec

`make install` (CentOS 7, in-source build) tries to install `libjson-plugin.la` before `libjson-c.la`. This results in the mentioned linking error `cannot find -ljson-c`. Installing `json-c-devel` is a dirty workaround, you can imitate the correct dependency order manually instead by executing the following commands:

```
cd source/lib/jsonc/
make install
cd ../../
make install
```

Of course, this is just another (cleaner) workaround; we have to fix this.

**Comment by nitishsaboo** [comment]
@MrAnno @czanik 
Getting the same error during make install step in syslog-ng version 3.25.1 as well

/usr/bin/ld: cannot find -ljson-c
collect2: error: ld returned 1 exit status
libtool:   error: error: relink 'modules/json/libjson-plugin.la' with the above command before installing it
make[3]: *** [install-moduleLTLIBRARIES] 

When can we expect the fix for this issue?

**Comment by MrAnno** [comment]
You can find a workaround in the previous comment.

**Comment by nitishsaboo** [comment]
@MrAnno Sure Thankyou.

**Comment by MrAnno** [comment]
#4078 removed the "internal" json-c submodule.
