### ISSUE TITLE
remove support for legacy maxmind

### ISSUE THREAD

**Issue by rfaircloth-splunk** [syslog-ng/syslog-ng#2776]
# Issue

syslog-ng support legacy maxmind and current geoip versions. Because Maxmind has ended maint for legacy formats only geoip should be retained

**Comment by Kokan** [comment]
I agree, in fact it has been deprecated since `3.11`. I even have a branch for this: https://github.com/Kokan/syslog-ng/commit/22e2d68a6dbd7bc5a3e6964aa277e3343dc3ecdb
After the current release (it is going to happen soon), this could be done imho.
