### ISSUE TITLE
creates logs when run manually but not from systemd

### ISSUE THREAD

**Issue by thankstipscom** [syslog-ng/syslog-ng#2891]
Redhat 7.6 with syslog-ng (3.22)
syslog-ng 3 (3.22.1)
Config version: 3.22
Installer-Version: 3.22.1
Revision:
Compile-Date: Jun 25 2019 13:51:13
Module-Directory: /usr/lib64/syslog-ng
Module-Path: /usr/lib64/syslog-ng
Include-Path: /usr/share/syslog-ng/include
Available-Modules: tags-parser,date,disk-buffer,map-value-pairs,hook-commands,snmptrapd-parser,tfgetent,kvformat,system-source,linux-kmsg-format,sdjournal,confgen,pseudofile,xml,cef,graphite,cryptofuncs,json-plugin,afstomp,stardate,afprog,add-contextual-data,appmodel,basicfuncs,examples,affile,dbparser,afuser,csvparser,afsocket,syslogformat
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: on
Enable-TCP-Wrapper: on
Enable-Linux-Caps: on
Enable-Systemd: on

ive searched and tried all the old remedies. Nothing has worked to resolve this.

My syslog-ng.conf file has a bunch of ports and a bunch of destinations. When something comes in on the port, it creates logs and folders of the destination. Simple.

If I do this from CLI as root:

    /usr/sbin/syslog-ng -F --cfgfile /etc/syslog-ng/syslog-ng.conf --control /var/lib/syslog-ng/syslog-ng.ctl --persist-file /var/lib/syslog-ng/syslog-ng.persist --pidfile /var/run/syslog-ng.pid

Everything works. I can watch my log folder and see logs being made. No problem.

ps -ef |grep syslog 

shows

    root      7179  7166  0 17:15 pts/1    00:00:00 /usr/sbin/syslog-ng -F --cfgfile /etc/syslog-ng/syslog-ng.conf --control /var/lib/syslog-ng/syslog-ng.ctl --persist-file /var/lib/syslog-ng/syslog-ng.persist --pidfile /var/run/syslog-ng.pid

**HOWEVER**

If I run it like this (and when system starts): 

    systemctl start syslog-ng

Everything appears to work.
ps -ef|grep syslog

shows

    root      7434     1  0 17:22 ?        00:00:00 /usr/sbin/syslog-ng -F --cfgfile /etc/syslog-ng/syslog-ng.conf --control /var/lib/syslog-ng/syslog-ng.ctl --persist-file /var/lib/syslog-ng/syslog-ng.persist --pidfile /var/run/syslog-ng.pid

The only difference that when run from systemd, no logs get created. I have no idea what could be causing this. Netstats shows its still listening on all of the ports. 

journalctl -eu syslog-ng shows:

    Aug 27 17:22:32 system-new systemd[1]: Starting System Logger Daemon...
    Aug 27 17:22:32 system-new systemd[1]: Started System Logger Daemon.

Service file looks like this:

	[Unit]
	Description=System Logger Daemon
	Documentation=man:syslog-ng(8)
	Wants=network.target network-online.target
	After=network.target network-online.target

	[Service]
	Type=simple
	Environment=SYSLOGNG_PID_FILE="/var/run/syslog-ng.pid"
	Environment=SYSLOGNG_CONF_FILE="/etc/syslog-ng/syslog-ng.conf"
	Environment=SYSLOGNG_PERSIST_FILE="/var/lib/syslog-ng/syslog-ng.persist"
	Environment=SYSLOGNG_CONTROL_FILE="/var/lib/syslog-ng/syslog-ng.ctl"
	Environment=SYSLOGNG_OPTIONS=""
	EnvironmentFile=-/etc/default/syslog-ng
	EnvironmentFile=-/etc/sysconfig/syslog-ng
	ExecStart=/usr/sbin/syslog-ng -F $SYSLOGNG_OPTIONS --cfgfile $SYSLOGNG_CONF_FILE --control $SYSLOGNG_CONTROL_FILE --persist-file $SYSLOGNG_PERSIST_FILE --pidfile $SYSLOGNG_PID_FILE
	ExecReload=/bin/kill -HUP $MAINPID
	StandardOutput=journal
	StandardError=journal
	Restart=on-failure

	[Install]
	WantedBy=multi-user.target
	Alias=syslog.service

I wanted to run this as a standard user, but I can't even get it to run properly as root.

**Comment by Kokan** [comment]
I am glad you got the solution. Would you mind closing the issue if you thing it is handled ?

I think it is kinda hard to cover SELinux related functionality in documentation, as the what and how highly dependent on your configuration (just like your solution is unique to your setup).

Note: that the syslog-ng repository contains selinux related files: https://github.com/balabit/syslog-ng/tree/master/contrib/selinux

While mentioning the SELinux and capabilities might cause this kind of issue would be nice (have not checked if it is mentioned).
What I'v learned while used system with SELinux if something not working in Enforcing mode, try it out in Permissive and check the logs. SELinux even has tooling to automatically create rules from those diagnostic messages (well but all automatic thing it should be handled with care).

Also the documentation is available here: https://github.com/balabit/syslog-ng-ose-guides  [PRs are welcomed ;)]
