### ISSUE TITLE
Flush logs after x seconds

### ISSUE THREAD

**Issue by DorfilIkatu** [syslog-ng/syslog-ng#2913]
Hi,

I would like to persist my logs on disk. My system generates logs every second and I would like to wait at least 10 seconds before flushing the logs. Is some way to accomplish this?

I've tried with the flush_timeout and flush_lines options they didn't work (logs are flushed continuously).

I'm following this doc: https://www.syslog-ng.com/technical-documents/doc/syslog-ng-open-source-edition/3.18/administration-guide/flush-timeout, which is the corresponding to my syslog-ng version.

Also, is flush_timeout deprecated? I've seen in some places that flush_timeout is deprecated (for example in the 3.16 doc, but then in 3.18 seems not to be deprecated anymore).

I appreciate any help.

Regards,
Héctor

**Comment by bazsi** [comment]
Flush-timeout() is deprecated and does nothing. Is it a problem that
syslog-ng writes messages in real time? Can you elaborate on your use case?

**Comment by alltilla** [comment]
Hi Héctor,

Can you try this config? The interesting parts are the `flush-lines(1000)` and `throttle(100)`, it is enough to use those 2 options in your existing config, to test the theory.
```
@version: 3.23
@include "scl.conf"

options {
    flush_lines(1000);
};

source s_src {
    udp(port(6666));
};

destination d_file {
    file(
        "/tmp/throttle.log"
        throttle(100)
    );
};

log {
    source(s_src);
    destination(d_file);
};
```

It will guarantee, that logs will not be written more frequently than 10 seconds. However it has some drawbacks:
 * It only sends out 1000 message batches, if you have 999, it will be only sent out when a new message arrives, or if you reload/stop syslog-ng.
 * It limits the throughput to 100 message/sec (== 1000 message/10 sec). If you have more messages, they will queue up.

**Comment by alltilla** [comment]
Thanks for reporting! This seems like a bug. We will need a little time to investigate this.

**Comment by DorfilIkatu** [comment]
Since I was having some other requirements I ended using the `pipe` destination driver and then I have a little script that processes this pipe and manages the flush and other stuff in the way we need.

Thanks @alltilla and @bazsi for the help!

Regards

**Comment by MrAnno** [comment]
@DorfilIkatu We're happy to hear that.

Just for the record, the `flush-lines()` option is not really for precise batching, it is more of a performance-related option. I'm quoting the syslog-ng Admin Guide:

> `flush-lines()`: Specifies how many lines are flushed to a destination at a time.
> The syslog-ng OSE application flushes the messages if it has sent flush-lines() number of messages, **or the queue became empty**.

So `flush-lines()` is actually an upper limit, not an exact amount when to flush.

**Comment by alltilla** [comment]
Yes, @MrAnno is right. `flush-lines()` saves us from starving other destinations. Additionally, in general we do not call `fsync()` unless `fsync(yes)` is set to the `file` destination.
