### ISSUE TITLE
Feature Request Build for RHEL 8

### ISSUE THREAD

**Issue by rfaircloth-splunk** [syslog-ng/syslog-ng#2938]
# syslog-ng

RHEL 8 has greatly change the packaging compared to RHEL 7, update DBLD for RHEL 8 support

**Comment by czanik** [comment]
It's on my radar, following RHEL/CentOS/EPEL developments closely. Right now CentOS 8 is not yet available and while an initial EPEL 8 is published, essential syslog-ng dependencies are not yet available. CentOS 8 is expected to be released this week, so I hope I can create my unofficial packages for RHEL 8 in the coming weeks.
Also, RHEL 8 does not include docker, but fully switched to podman/buildah. There should be an easy command line switch to podman in DBLD. Editing the source is easy, but in that case sources are marked as dirty...

**Comment by czanik** [comment]
I have some good news: I have a very limited RHEL 8 build already available locally on my laptop. Much of the dependencies are missing, but the tools are now available and gradually I can make those available.

**Comment by czanik** [comment]
You can test it from: https://copr.fedorainfracloud.org/coprs/czanik/syslog-ng324el8/

```
[root@localhost ~]# uname -a
Linux localhost.localdomain 4.18.0-80.7.1.el8_0.x86_64 #1 SMP Sat Aug 3 15:14:00 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
[root@localhost ~]# syslog-ng -V
syslog-ng 3 (3.24.1)
Config version: 3.24
Installer-Version: 3.24.1
Revision: 
Compile-Date: Oct 10 2019 22:44:18
Module-Directory: /usr/lib64/syslog-ng
Module-Path: /usr/lib64/syslog-ng
Include-Path: /usr/share/syslog-ng/include
Available-Modules: add-contextual-data,affile,afprog,afsocket,afstomp,afuser,appmodel,basicfuncs,cef,confgen,cryptofuncs,csvparser,dbparser,disk-buffer,examples,graphite,hook-commands,json-plugin,kvformat,linux-kmsg-format,map-value-pairs,pseudofile,sdjournal,snmptrapd-parser,stardate,syslogformat,system-source,tags-parser,tfgetent,timestamp,xml
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: on
Enable-TCP-Wrapper: off
Enable-Linux-Caps: on
Enable-Systemd: on
```

**Comment by bigHosting** [comment]
Awesooome, thank you for making this happen!
I've tested 3.24 on CentOS 8 and it looks good !

**Comment by rfaircloth-splunk** [comment]
great progress

**Comment by czanik** [comment]
Closing for now. If you need any of the missing features, let me know in a separate ticket. As there are not yet many people on RHEL/CentOS 8, I want to work on the missing features which have a real demand for them, otherwise still focus on RHEL/CentOS 7.
