### ISSUE TITLE
IETF format is not getting decoded properly.

### ISSUE THREAD

**Issue by JanakiRamiReddy** [syslog-ng/syslog-ng#2958]
I am sending IETF format. 

>>>> 71 <187>1 2019-10-03T18:02:08.075Z - - - - - %this is my first message

But at the receiver side, the msg is received in old format.

the error msg is seen as Invalid frame header; header=''
>>>>> Oct  3 18:01:12 10.64.68.209 %this is my first message.

If the hostname is added to the format, then the receiver is able to detect the msg, but still error msg is seen.
75 <187>1 2019-10-03T18:01:01.966Z 0.0.0.0 - - - - %this is my first message

Invalid frame header; header=''

Oct  3 23:28:14 10.64.68.209 syslog-ng[6780]: Error processing log message: <187>1 2019-10-03T18:00:39.931Z 0.0.0.0 - - - - %this is my first message

config 

source s_net { 
syslog(ip(0.0.0.0) port(6514)
transport("tls")
tls( ca_dir("/etc/syslog-ng/ca.d")
     key_file("/etc/syslog-ng/key.d/privkey.pem")
     cert_file("/etc/syslog-ng/cert.d/cacert.pem")
     peer_verify(optional-untrusted)) ); };

**Comment by MrAnno** [comment]
In your first example, the message seems to be parsed correctly, I think you just used the wrong output format in your destination. Just add `flags(syslog-protocol)` to you **destination**, for example:

```
destination {
  file("/dev/stdout" flags(syslog-protocol));
};
```

The error message `Invalid frame header` is another issue, it's because you're sending framed data (every message should start with the message length in decimal format), and one of your message does not conform to this format.
The actual problem might be that `<187>1 2019-10-03T18:02:08.075Z - - - - - %this is my first message` is not 71 bytes long, it's 68 (if you send the newline character as well).

**Comment by JanakiRamiReddy** [comment]
Sorry for the formatting issue, let me put this way.

**sent from the client.**
68 <187>1 2019-10-03T18:01:01.966Z - - - - - %this is my first message.

Getting the invalid header msg as well in the destination I am seeing the received logs not in the IETF format.

**received**
Oct 3 18:01:12 10.64.68.209 %this is my first message.


**changed the destination as you mentioned.**

@version: 3.5
@include "scl.conf"
@include "`scl-root`/system/tty10.conf"

# Syslog-ng configuration file, compatible with default Debian syslogd
# installation.

# First, set some global options.
options { long_hostnames(off); flush_lines(0); use_dns(no); use_fqdn(no);
    owner("root"); group("adm"); perm(0640); stats_freq(0);
    create_dirs(1); bad_hostname("^gconfd$"); #ts-format(iso);
};

########################
# Sources
########################
# This is the default behavior of sysklogd package
# Logs may come from unix stream, but not from another machine.
#
source s_src {
       system();
       internal();
};

# If you wish to get logs from remote machine you should uncomment
# this and comment the above source line.
#
#source s_net { tcp(ip(0.0.0.0) port(1000)); };

source s_net { 
#tcp(ip(0.0.0.0) port(6514)
syslog(ip(0.0.0.0) port(6514)
transport("tls")
#flags(no-parse)
tls( ca_dir("/etc/syslog-ng/ca.d")
    key_file("/etc/syslog-ng/key.d/privkey.pem")
     cert_file("/etc/syslog-ng/cert.d/cacert.pem")
    peer_verify(optional-untrusted)) ); };

#source s_net {
#tcp(ip(0.0.0.0) port(601));
#};

########################
# Remote Destinations
########################

destination d_net_auth { file("/var/log/HOSTS/$HOST/auth.log" flags(syslog-protocol)); };
destination d_net_cron { file("/var/log/HOSTS/$HOST/cron.log"); };
destination d_net_daemon { file("/var/log/HOSTS/$HOST/daemon.log"); };
destination d_net_kern { file("/var/log/HOSTS/$HOST/kern.log"); };
destination d_net_lpr { file("/var/log/HOSTS/$HOST/lpr.log"); };
destination d_net_mail { file("/var/log/HOSTS/$HOST/mail.log"); };
destination d_net_syslog { file("/var/log/HOSTS/$HOST/syslog.log" flags(syslog-protocol)); };
destination d_net_user { file("/var/log/HOSTS/$HOST/user.log"); };
destination d_net_uucp { file("/var/log/HOSTS/$HOST/uucp.log"); };

destination d_net_mailinfo { file("/var/log/HOSTS/$HOST/mail/mail.info"); };
destination d_net_mailwarn { file("/var/log/HOSTS/$HOST/mail/mail.warn"); };
destination d_net_mailerr { file("/var/log/HOSTS/$HOST/mail/mail.err"); };

destination d_net_debug { file("/var/log/HOSTS/$HOST/debug"); };
destination d_net_error { file("/var/log/HOSTS/$HOST/error"); };
destination d_net_messages { file("/var/log/HOSTS/$HOST/messages"); }; 




#Remote Log paths
########################
log { source(s_net); filter(f_auth); destination(d_net_auth); };
log { source(s_net); filter(f_cron); destination(d_net_cron); };
log { source(s_net); filter(f_daemon); destination(d_net_daemon); };
log { source(s_net); filter(f_kern); destination(d_net_kern); };
log { source(s_net); filter(f_lpr); destination(d_net_lpr); };
log { source(s_net); filter(f_syslog3); destination(d_net_syslog); };
log { source(s_net); filter(f_user); destination(d_net_user); };
log { source(s_net); filter(f_uucp); destination(d_net_uucp); };

log { source(s_net); filter(f_mail); destination(d_net_mail); };
log { source(s_net); filter(f_mail); filter(f_info); destination(d_net_mailinfo); };
log { source(s_net); filter(f_mail); filter(f_warn); destination(d_net_mailwarn); };
log { source(s_net); filter(f_mail); filter(f_err); destination(d_net_mailerr); };

log { source(s_net); filter(f_debug); destination(d_net_debug); };
log { source(s_net); filter(f_error); destination(d_net_error); };
log { source(s_net); filter(f_messages); destination(d_net_messages); };
# Destinations
########################
# First some standard logfile
#
destination d_auth { file("/var/log/auth.log"); };
destination d_cron { file("/var/log/cron.log"); };
destination d_daemon { file("/var/log/daemon.log"); };
destination d_kern { file("/var/log/kern.log"); };
destination d_lpr { file("/var/log/lpr.log"); };
destination d_mail { file("/var/log/mail.log"); };
destination d_syslog { file("/var/log/syslog"); };
destination d_user { file("/var/log/user.log"); };
destination d_uucp { file("/var/log/uucp.log"); };

# This files are the log come from the mail subsystem.
#
destination d_mailinfo { file("/var/log/mail.info"); };
destination d_mailwarn { file("/var/log/mail.warn"); };
destination d_mailerr { file("/var/log/mail.err"); };

# Logging for INN news system
#
destination d_newscrit { file("/var/log/news/news.crit"); };
destination d_newserr { file("/var/log/news/news.err"); };
destination d_newsnotice { file("/var/log/news/news.notice"); };

# Some `catch-all' logfiles.
#
destination d_debug { file("/var/log/debug"); };
destination d_error { file("/var/log/error"); };
destination d_messages { file("/var/log/messages"); };

# The root's console.
#
destination d_console { usertty("root"); };

# Virtual console.
#
destination d_console_all { file(`tty10`); };

# The named pipe /dev/xconsole is for the nsole' utility.  To use it,
# you must invoke nsole' with the -file' option:
#
#    $ xconsole -file /dev/xconsole [...]
#
destination d_xconsole { pipe("/dev/xconsole"); };

# Send the messages to an other host
#
#destination d_net { tcp("127.0.0.1" port(1000) log_fifo_size(1000)); };

# Debian only
destination d_ppp { file("/var/log/ppp.log"); };

########################
# Filters
########################
# Here's come the filter options. With this rules, we can set which 
# message go where.

filter f_dbg { level(debug); };
filter f_info { level(info); };
filter f_notice { level(notice); };
filter f_warn { level(warn); };
filter f_err { level(err); };
filter f_crit { level(crit .. emerg); };

filter f_debug { level(debug) and not facility(auth, authpriv, news, mail); };
filter f_error { level(err .. emerg) ; };
filter f_messages { level(info,notice,warn) and 
                    not facility(auth,authpriv,cron,daemon,mail,news); };

filter f_auth { facility(auth, authpriv) and not filter(f_debug); };
filter f_cron { facility(cron) and not filter(f_debug); };
filter f_daemon { facility(daemon) and not filter(f_debug); };
filter f_kern { facility(kern) and not filter(f_debug); };
filter f_lpr { facility(lpr) and not filter(f_debug); };
filter f_local { facility(local0, local1, local3, local4, local5,
                        local6, local7) and not filter(f_debug); };
filter f_mail { facility(mail) and not filter(f_debug); };
filter f_news { facility(news) and not filter(f_debug); };
filter f_syslog3 { not facility(auth, authpriv, mail) and not filter(f_debug); };
filter f_user { facility(user) and not filter(f_debug); };
filter f_uucp { facility(uucp) and not filter(f_debug); };

filter f_cnews { level(notice, err, crit) and facility(news); };
filter f_cother { level(debug, info, notice, warn) or facility(daemon, mail); };

filter f_ppp { facility(local2) and not filter(f_debug); };
filter f_console { level(warn .. emerg); };

########################
# Log paths
########################
log { source(s_src); filter(f_auth); destination(d_auth); };
log { source(s_src); filter(f_cron); destination(d_cron); };
log { source(s_src); filter(f_daemon); destination(d_daemon); };
log { source(s_src); filter(f_kern); destination(d_kern); };
log { source(s_src); filter(f_lpr); destination(d_lpr); };
log { source(s_src); filter(f_syslog3); destination(d_syslog); };
log { source(s_src); filter(f_user); destination(d_user); };
log { source(s_src); filter(f_uucp); destination(d_uucp); };

log { source(s_src); filter(f_mail); destination(d_mail); };
#log { source(s_src); filter(f_mail); filter(f_info); destination(d_mailinfo); };
#log { source(s_src); filter(f_mail); filter(f_warn); destination(d_mailwarn); };
#log { source(s_src); filter(f_mail); filter(f_err); destination(d_mailerr); };

log { source(s_src); filter(f_news); filter(f_crit); destination(d_newscrit); };
log { source(s_src); filter(f_news); filter(f_err); destination(d_newserr); };
log { source(s_src); filter(f_news); filter(f_notice); destination(d_newsnotice); };
#log { source(s_src); filter(f_cnews); destination(d_console_all); };
#log { source(s_src); filter(f_cother); destination(d_console_all); };

#log { source(s_src); filter(f_ppp); destination(d_ppp); };

log { source(s_src); filter(f_debug); destination(d_debug); };
log { source(s_src); filter(f_error); destination(d_error); };
log { source(s_src); filter(f_messages); destination(d_messages); };

log { source(s_src); filter(f_console); destination(d_console_all);
				    destination(d_xconsole); };
log { source(s_src); filter(f_crit); destination(d_console); };

# All messages send to a remote site
#
#log { source(s_src); destination(d_net); };

###
# Include all config files in /etc/syslog-ng/conf.d/
###
@include "/etc/syslog-ng/conf.d/*.conf"

**Comment by JanakiRamiReddy** [comment]
Thanks MrAnno, it is working.

But I am seeing socket connection closed issue. 

<43>1 2019-10-04T00:59:26+05:30 embd-lnx syslog-ng 7339 - [meta sequenceId="170"] Invalid frame header; header=''
<45>1 2019-10-04T00:59:26+05:30 embd-lnx syslog-ng 7339 - [meta sequenceId="171"] Syslog connection closed;

**Comment by MrAnno** [comment]
Yeah, this is the result of the protocol violation that I've mentioned.
Make sure every message starts with the message length, and the message length should be correct as well:

`68 <187>1 2019-10-03T18:01:01.966Z - - - - - %this is my first message.`
68 is only correct if you don't send a newline character. If you are unsure, just remove the last dot and give it a try.

Examples:
`68 <187>1 2019-10-03T18:01:01.966Z - - - - - %this is my first message` if you are sending `\n`
`67 <187>1 2019-10-03T18:01:01.966Z - - - - - %this is my first message` without newline

**Comment by JanakiRamiReddy** [comment]
Thanks Mr Anno, messages are getting decoding as per IETF format.

**Comment by MrAnno** [comment]
My pleasure.
