### ISSUE TITLE
Debian packaging shouldn't require mod-elastic for elasticsearch-http module

### ISSUE THREAD

**Issue by kjc75** [syslog-ng/syslog-ng#2978]
## Description of the problem
Use of elasticsearch-http is only contingent upon the http module, and not the presence of the elasticsearch2 or java modules.  Requiring mod-elastic to use the elasticsearch-http module ends up pulling in the Java framework unnecessarily.

## Proposed solution
As there are two distinct files in scl/ for the two ES connection modules, retain elasticsearch2 (scl/elasticsearch/plugin.conf) for mod-elastic, and include elasticsearch-http (scl/elasticsearch/elasticsearch-http.conf) for mod-http.

**Comment by lbudai** [comment]
@kjc75 : thanks for reporting the issue.
Where the packages are installed from? OBS repository or are you building from source?
