### ISSUE TITLE
client logs receiving with facility name

### ISSUE THREAD

**Issue by sritath21** [syslog-ng/syslog-ng#3004]
Hi,
We have setup syslog-ng server on RHEL7.4. We need our AIX 7.2 database servers to send logs to syslog-ng server. We have configured rsyslog on AIX 7.2. connectivity is working file as i'm able to send the logs. But, the problem is, files on syslog-ng server are getting stored with facility name.
remote.conf file on syslog-ng has below configuration set.
file ("/rsyslog/HOSTS/$HOST/$YEAR-$MONTH/$DAY/$FACILITY"
rsyslog configuration is as below.
$InputFileName /test/sqllib/db2dump/DIAG0000/db2diag.log
$InputFileTag DIAG0000-db2diag-log:
$InputFileStateFile statefile001
$InputFileSeverity debug
$InputFileFacility local7
$InputRunFileMonitor

Can somebody help me in getting this file saved with InputFileTag instead of InputFileFacility.
Thanks in advance.
Srinivas

**Comment by sritath21** [comment]
Files on syslog-ng are getting stored with name local7(InputFileFacility) and not DIAG0000-db2diag-log(InputFileTag). I know that the remote.conf is asking the files to be stored with $FACILITY. Is there a way, we can change this setting to actually create files with inputfiletag name?

**Comment by szemere** [comment]
Dear @sritath21,
 unfortunately I am not very familiar with the configuration syntax of rsyslog, so maybe I do not understand your problem entirely.
 What you are essentially using in the syslog-ng configuration, is the capability to use `MACROS` in the (string type) filename parameter of the `file` destination driver. The macros will be expanded on per message base, like environment variables in a shell script.

 Documentation about the available [MACROS](https://www.syslog-ng.com/technical-documents/doc/syslog-ng-open-source-edition/3.24/administration-guide/63#TOPIC-1298112) in syslog-ng.

Br,
Laci

**Comment by sritath21** [comment]
Thank you.
