### ISSUE TITLE
Not able to see java modules in /usr/lib64/syslog-ng

### ISSUE THREAD

**Issue by onenessboy** [syslog-ng/syslog-ng#3005]
Hi 
I have installed syslog.ng from yum on fresh rhel machine. and also installed java jdk requried for it. I am able to start ng-service  but

while configuring kafka destination, i could not find /usr/lib64/syslog-ng/java-modules/ directory it self...   

`[root@ip-xx-xx-xx-xx yum.repos.d]# yum install syslog-ng`
`Loaded plugins: amazon-id, search-disabled-repos`
`https://copr-be.cloud.fedoraproject.org/results/czanik/syslog-ng324/epel-7-`aarch64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found`
`Trying other mirror.
To address this issue please refer to the below knowledge base article`

`https://access.redhat.com/articles/1320623`

`If above article doesn't help to resolve this issue please open a ticket with Red Hat Support.`

`epel/aarch64/metalink `                                                                                                                                                `|  18 kB  00:00:00`
`http://csc.mcs.sdsmt.edu/epel/7/aarch64/repodata/repomd.xml: [Errno 12] Timeout on `http://csc.mcs.sdsmt.edu/epel/7/aarch64/repodata/repomd.xml: (28, 'Operation too slow. Less than 1000 bytes/sec transferred the last 30 seconds')`
Trying other mirror.
epel                                                                                                                                                                  | 5.4 kB  00:00:00
http://rpms.adiscon.com/v8-stable/epel-7Server/aarch64/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
(1/3): epel/aarch64/group_gz                                                                                                                                          |  88 kB  00:00:00
(2/3): epel/aarch64/updateinfo                                                                                                                                        | 1.0 MB  00:00:01
(3/3): epel/aarch64/primary_db                                                                                                                                        | 6.6 MB  00:00:01
Resolving Dependencies
--> Running transaction check
---> Package syslog-ng.aarch64 0:3.5.6-3.el7 will be installed
--> Processing Dependency: ivykis >= 0.36.1 for package: syslog-ng-3.5.6-3.el7.aarch64
--> Processing Dependency: libivykis.so.0(IVYKIS_0.29)(64bit) for package: syslog-ng-3.5.6-3.el7.aarch64
--> Processing Dependency: libivykis.so.0(IVYKIS_0.30)(64bit) for package: syslog-ng-3.5.6-3.el7.aarch64`

by above way i have installed syslog-ng...

can some one help me why i missing java-modules please...

**Comment by czanik** [comment]
My syslog-ng 3.24 repo for RHEL 7 had only x86 packages enabled, so you ended up installing syslog-ng 3.5.6 from EPEL. Let me check, if I can add Aarch64 support to that repo.

**Comment by czanik** [comment]
OK. Just finished building syslog-ng for Aarch64. You will also need the ```syslog-ng-java``` package, as that sub-package includes java support and java modules.

Or, you can install ```syslog-ng-kafka```, which has the advantage, that it does not need Java, but is based on ```librdkafka```
