### ISSUE TITLE
Referring to #3005 , How can i write kafka destination in syslog-ng.conf file

### ISSUE THREAD

**Issue by onenessboy** [syslog-ng/syslog-ng#3008]
Hi
1. As per your suggestion I have installed syslog-ng-kafka one
Installed:
  syslog-ng-kafka.aarch64 0:3.24.1-1.el7

Dependency Installed:
  syslog-ng.aarch64 0:3.24.1-1.el7

2. Now I need to configure syslog-ng conf as kafaka destination with below template, but I could not find directories 

destination d_kafka {
  kafka(
    client-lib-dir("/opt/syslog-ng/lib/syslog-ng/java-modules/KafkaDestination.jar:/usr/share/kafka/lib/")
    kafka-bootstrap-servers("1.2.3.4:9092,192.168.0.2:9092")
    topic("${HOST}")
  );
};`

The above is template i got from documentation, but after yum install i am not able to find this location 

/opt/syslog-ng/lib/syslog-ng/java-modules.

any help please

**Comment by onenessboy** [comment]
Ok so, now i get to know what are directories it got insalled with below :
[root@ip-xx.xx..xx..xx syslog-ng]#  syslog-ng --version
syslog-ng 3 (3.24.1)
Config version: 3.24
Installer-Version: 3.24.1
Revision:
Compile-Date: Nov 11 2019 09:10:49
Module-Directory: /usr/lib64/syslog-ng
Module-Path: /usr/lib64/syslog-ng
Include-Path: /usr/share/syslog-ng/include
Available-Modules: add-contextual-data,affile,afprog,afsocket,afstomp,afuser,appmodel,basicfuncs,cef,confgen,cryptofuncs,csvparser,dbparser,disk-buffer,examples,graphite,hook-commands,json-plugin,kvformat,linux-kmsg-format,map-value-pairs,pseudofile,sdjournal,snmptrapd-parser,stardate,syslogformat,system-source,tags-parser,tfgetent,timestamp,xml,kafka
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: on
Enable-TCP-Wrapper: on
Enable-Linux-Caps: on
Enable-Systemd: on

Now I need to help how to write config in syslog-ng.conf to send logs to kafka broker

How should i rewrite below since I got it installed via yum.
destination d_kafka {
kafka(
client-lib-dir("/opt/syslog-ng/lib/syslog-ng/java-modules/KafkaDestination.jar:/usr/share/kafka/lib/")
kafka-bootstrap-servers("1.2.3.4:9092,192.168.0.2:9092")
topic("${HOST}")
);
};`
How to find this path /opt/syslog-ng/lib/syslog-ng/java-modules.

**Comment by onenessboy** [comment]
so what i tried now is to include following line in  /etc/syslong-ng.conf file and tried to restart but i am getting eror, it cant be started..what mistake i am doing here'
`destination d_kafka {
  kafka(
    client-lib-dir("/usr/lib64/syslog-ng/:/usr/lib64/syslog-ng/")
    kafka-bootstrap-servers("xx.xx.x.xx:9092") # target IP that receives logs 
    topic("abcdefgh")
  );
};
`

**Comment by onenessboy** [comment]
than when i probed further, it shows below error

Nov 12 07:44:31 xx-x-xx-xxxinternal systemd[1]: Starting System Logger Daemon...
Nov 12 07:44:31 xx-x-xx-xxxinternal syslog-ng[18694]: [2019-11-12T07:44:31.765392] Plugin module not found in 'module-path'; module-path='/usr/lib64/syslog-ng', module
Nov 12 07:44:31 xx-x-xx-xxxinternal syslog-ng[18694]: [2019-11-12T07:44:31.770759] Plugin module not found in 'module-path'; module-path='/usr/lib64/syslog-ng', module
Nov 12 07:44:31 xx-x-xx-xxxinternal syslog-ng[18694]: [2019-11-12T07:44:31.771772] Plugin module not found in 'module-path'; module-path='/usr/lib64/syslog-ng', module
Nov 12 07:44:31 xx-x-xx-xxxinternal syslog-ng[18694]: [2019-11-12T07:44:31.778269] WARNING: With use-dns(no), dns-cache() will be forced to 'no' too!;
Nov 12 07:44:31 xx-x-xx-xxxinternal systemd[1]: Started System Logger Daemon.
Nov 12 08:09:53 xx-x-xx-xxxinternal systemd[1]: Stopping System Logger Daemon...
Nov 12 08:09:53 xx-x-xx-xxxinternal systemd[1]: Stopped System Logger Daemon.
Nov 12 08:34:02 xx-x-xx-xxxinternal systemd[1]: Starting System Logger Daemon...
Nov 12 08:34:02 xx-x-xx-xxxinternal syslog-ng[18875]: [2019-11-12T08:34:02.543276] Plugin module not found in 'module-path'; module-path='/usr/lib64/syslog-ng', module
Nov 12 08:34:02 xx-x-xx-xxxinternal syslog-ng[18875]: [2019-11-12T08:34:02.550170] Plugin module not found in 'module-path'; module-path='/usr/lib64/syslog-ng', module
Nov 12 08:34:02 xx-x-xx-xxxinternal syslog-ng[18875]: [2019-11-12T08:34:02.551215] Plugin module not found in 'module-path'; module-path='/usr/lib64/syslog-ng', module
Nov 12 08:34:02 xx-x-xx-xxxinternal syslog-ng[18875]: [2019-11-12T08:34:02.556085] WARNING: With use-dns(no), dns-cache() will be forced to 'no' too!;
Nov 12 08:34:02 xx-x-xx-xxxinternal systemd[1]: Started System Logger Daemon.
Nov 12 09:02:44 xx-x-xx-xxxinternal systemd[1]: Stopping System Logger Daemon...
Nov 12 09:02:45 xx-x-xx-xxxinternal systemd[1]: Stopped System Logger Daemon.
Nov 12 09:02:45 xx-x-xx-xxxinternal systemd[1]: Starting System Logger Daemon...
Nov 12 09:02:45 xx-x-xx-xxxinternal syslog-ng[18958]: [2019-11-12T09:02:45.088534] Plugin module not found in 'module-path'; module-path='/usr/lib64/syslog-ng', module
Nov 12 09:02:45 xx-x-xx-xxxinternal syslog-ng[18958]: [2019-11-12T09:02:45.093469] Plugin module not found in 'module-path'; module-path='/usr/lib64/syslog-ng', module
Nov 12 09:02:45 xx-x-xx-xxxinternal syslog-ng[18958]: [2019-11-12T09:02:45.094405] Plugin module not found in 'module-path'; module-path='/usr/lib64/syslog-ng', module
Nov 12 09:02:45 xx-x-xx-xxxinternal syslog-ng[18958]: Error parsing destination statement, destination plugin java not found in block destination kafka-java() at /usr/
Nov 12 09:02:45 xx-x-xx-xxxinternal syslog-ng[18958]: 1
Nov 12 09:02:45 xx-x-xx-xxxinternal syslog-ng[18958]: 2       #Start Block block destination kafka-java() at /usr/share/syslog-ng/include/scl/kafka/plugin.conf:23
Nov 12 09:02:45 xx-x-xx-xxxinternal syslog-ng[18958]: 3
Nov 12 09:02:45 xx-x-xx-xxxinternal syslog-ng[18958]: 4----->   java(
Nov 12 09:02:45 xx-x-xx-xxxinternal syslog-ng[18958]: 4----->   ^^^^
Nov 12 09:02:45 xx-x-xx-xxxinternal syslog-ng[18958]: 5           class_path("/usr/lib64/syslog-ng/java-modules/*.jar:/usr/lib64/syslog-ng/:/usr/lib64/syslog-ng//*.jar
Nov 12 09:02:45 xx-x-xx-xxxinternal syslog-ng[18958]: 6           class_name("org.syslog_ng.kafka.KafkaDestination")
Nov 12 09:02:45 xx-x-xx-xxxinternal syslog-ng[18958]: 7           option("topic", "${HOST}")
Nov 12 09:02:45 xx-x-xx-xxxinternal syslog-ng[18958]: 8           option("key", "")
Nov 12 09:02:45 xx-x-xx-xxxinternal syslog-ng[18958]: 9           option("template", "")
Nov 12 09:02:45 xx-x-xx-xxxinternal syslog-ng[18958]: Included from block destination kafka() at /usr/share/syslog-ng/include/scl/kafka/plugin.conf:48:4:5-4:140:

**Comment by onenessboy** [comment]
Ok now, I tried with python module...
`destination syslog_to_kafka {
    python(
        class("syslogng_kafka.kafkadriver.KafkaDestination")
            on-error("fallback-to-string")
            options(
                hosts("xx.xx.xx.xx:9092")
                topic("syslog")
                partition("10")
                msg_key("src_ip")
                verbose("True")
                display_stats("True")
                producer_config("{'client.id': 'sylog-ng-01', 'retry.backoff.ms': 100, 'message.send.max.retries': 5, 'queue.buffering.max.kbytes': 50240, 'default.topic.config': {'request.required.acks': 1, 'request.timeout.ms': 5000, 'message.timeout.ms': 300000}, 'queue.buffering.max.messages': 100000, 'queue.buffering.max.ms': 1000, 'statistics.interval.ms': 15000, 'socket.timeout.ms': 60000, 'retry.backoff.ms':100,}")
                )
    );
};
`
But it said it cant recognize python, then I tried to install 

it said

Resolving Dependencies
--> Running transaction check
---> Package syslog-ng-python.aarch64 0:3.24.1-1.el7 will be installed
--> Processing Dependency: libpython3.6m.so.1.0()(64bit) for package: syslog-ng-python-3.24.1-1.el7.aarch64
--> Finished Dependency Resolution
Error: Package: syslog-ng-python-3.24.1-1.el7.aarch64 (copr:copr.fedorainfracloud.org:czanik:syslog-ng324)
           Requires: libpython3.6m.so.1.0()(64bit)
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

So I could not find libpython3.6m.so file in /usr/lib64/syslog-ng/ folder which I installed with Yum install syslog-ng..
Can you please help

**Comment by czanik** [comment]
Your very first entry here shows, that you installed the C implementation of the Kafka destination (installed syslog-ng-kafka). It means that you don't need Java or Python, so remove the syslog-ng-java and syslog-ng-python packages. Check the related section of the documentation before editing your syslog-ng configuration any further:

https://www.syslog-ng.com/technical-documents/doc/syslog-ng-open-source-edition/3.24/administration-guide/38#TOPIC-1298013
