### ISSUE TITLE
TLS issue and 100% CPU

### ISSUE THREAD

**Issue by pabloli** [syslog-ng/syslog-ng#3009]
Hi there,
I trying to use tls connection to send logs to syslog server. Using simple tcp destination all thing is work, but when I change it to tls (changing respective ports and configuration) the connection works for 10 ~ 30 minutes and then I can see log entry to my syslog-ng  process but I cannot see them going out.
After it's occurs the CPU is 100%, only restart the syslog-ng helps

Thanks

**Comment by szemere** [comment]
Hello @pabloli ,
 please fill all the information in the issue template properly. If you are able to provide the certs (at least the command you used to generate them), it might help too.

Best regards,
Laci

**Comment by pabloli** [comment]
my configuration is:

I have 2 sources

source s_tcp_syslog {
    network(
		transport("tcp")
		port(601) 
		persist-name("s_tcp_syslog")
    );
};

source s_udp_syslog {
    network(
		transport("udp")
		port(514) 
		persist-name("s_udp_syslog")
    );
};

One common destination
destination d_datadogBase {
	# https://docs.datadoghq.com/integrations/syslog_ng/?tab=datadogussite
	network("`DATADOG_URL`" 
		port("10516")
		persist-name("d_datadogBase")
		# transport("tcp")
		transport("tls")
		tls(
			# https://www.syslog-ng.com/technical-documents/doc/syslog-ng-open-source-edition/3.16/release-notes/tls-options
			# peer-verify(optional-untrusted)
			peer-verify(required-untrusted)
			# peer-verify(optional-trusted)
		)
		keep-alive(no)
		so_keepalive(no)
		# tcp-keepalive-intvl(15)
		# tcp-keepalive-time(15)
	);
};

And this is the log section:
log { 	
	source(s_tcp_syslog);	
	source(s_udp_syslog);
	destination(d_datadogBase);
};

For now i get only tcp logs (UDP is for a future use)
I think that is like a sending wasn't complete or wasn't closed.  
I run multiple instances in different timestamps (with the same input traffic) and both stuck in the same time .

**Comment by szemere** [comment]
Hello @pabloli ,
 thank you for the config.
> I run multiple instances in different timestamps (with the same input traffic) and both stuck in the same time . 

If I understand your statement correctly, than it means that syslog-ng hangs on a specific input message. If you can narrow down the issue to that specific message  (and send it to us) it would be really helpful.

Note: The platform, syslog-ng version, (installation source), the whole config, is still missing.

Br,
Laci

**Comment by MrAnno** [comment]
@pabloli I think I reproduced this (or a very similar) issue. It requires at least 2 TLS connection breakdowns in certain states. Do you have messages like `Syslog connection broken` or `POLLERR occurred while idle` in your internal syslog-ng logs?

Could you share the syslog-ng and OpenSSL version you are using?

I'll share my reproduction soon (and maybe a proposed fix as well).

**Comment by pabloli** [comment]
GreatI get connection broken. It's occurs slso when I don't use internal logs.I'll provide them ASAPPabloSent from my Samsung Galaxy smartphone.
-------- Original message --------From: László Várady <notifications@github.com> Date: 11/22/19  16:54  (GMT+02:00) To: syslog-ng/syslog-ng <syslog-ng@noreply.github.com> Cc: pabloli <pablo.a.liberman@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [syslog-ng/syslog-ng] TLS issue and 100% CPU (#3009) @pabloli I think I reproduced this (or a very similar) issue. It requires at least 2 TLS connection breakdowns in certain states. Do you have messages like Syslog connection broken or POLLERR occurred while idle in your internal syslog-ng logs?
Could you share the syslog-ng and OpenSSL version you are using?
I'll share my reproduction soon (and maybe a proposed fix as well).

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/syslog-ng/syslog-ng/issues/3009?email_source=notifications\u0026email_token=AEGICQXHXCSS26B7JWZRWLDQU7XDZA5CNFSM4JMB6EY2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEE53PLA#issuecomment-557561772",
"url": "https://github.com/syslog-ng/syslog-ng/issues/3009?email_source=notifications\u0026email_token=AEGICQXHXCSS26B7JWZRWLDQU7XDZA5CNFSM4JMB6EY2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEE53PLA#issuecomment-557561772",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by MrAnno** [comment]
@pabloli Thanks. 

Here is my proposed fix for the issue I've reproduced: #3026.

I'm not 100% sure this fixes your problem, so please check your logs, as discussed earlier.
Could you also try the patch above, please?

**Comment by MrAnno** [comment]
#3026 has been merged.

I'm reopening the auto-closed issue. @pabloli Please try the fix if you can, it should fix the intensive CPU usage in case a connection breaks in an idle TLS destination.

**Comment by MrAnno** [comment]
@pabloli Will you be able to try the patch? Can we help you with deb/rpm packages or anything else?

**Comment by MrAnno** [comment]
Please reopen if #3026 hasn't fixed your issue. syslog-ng v3.25.1 contains the fix.
