### ISSUE TITLE
Regex Parser alternative to filter with store-matches

### ISSUE THREAD

**Issue by ryanfaircloth** [syslog-ng/syslog-ng#3010]
## Proposed solution
Presently I need to use a filter with flags("store-matches") to access values that are neither csv nor kv. It would be easier to read if a regex parser was available this parser should support a prefix() argument to allow  .prefix. notation

**Comment by alltilla** [comment]
Hi Ryan,

Please fill all the fields of the "Feature request" template if possible. Please describe the limitation of syslog-ng in the "Description" field. Please provide the imagined config snippet of the requested feature in the "Proposed solution" field, or describe the necessary functional change of syslog-ng. Please fill the "Alternatives" field, if syslog-ng already has a solution for this, but it does not suit all of your needs, or if you happen to have alternative ways of fixing the problem. Please fill the "Additional Context" field with the actual use-case of the feature request, possibly with configuration snippets.

Attila

**Comment by bazsi** [comment]
please note this is listed as a gsoc project: https://github.com/syslog-ng/syslog-ng/wiki/GSoC2020-Idea-&-Project-list#add-regexp-parser

**Comment by Kokan** [comment]
This was implemented in https://github.com/syslog-ng/syslog-ng/pull/3702
