### ISSUE TITLE
DNS re-write rule

### ISSUE THREAD

**Issue by rfaircloth-splunk** [syslog-ng/syslog-ng#3011]
## Description of the problem
The performance of reverse DNS lookup significantly impacts the overall performance of a syslog-ng instance when enabled on a network source.

## Proposed solution
Provide a new re-write function based on the approach of the one added to "fix time stamp" "fix host" would allow the administrator/developer to limit which events may cause a DNS query based on other conditions.

## Alternatives
globally enable or disable reverse dns on any source

## Additional context
Main use case, enrich a message with the actual host name using reverse DNS for a subset of events based on parser or log path conditions

**Comment by alltilla** [comment]
Hi Ryan,

Please fill all the fields of the "Feature request" template if possible. Please describe the limitation of syslog-ng in the "Description" field. Please provide the imagined config snippet of the requested feature in the "Proposed solution" field, or describe the necessary functional change of syslog-ng. Please fill the "Alternatives" field, if syslog-ng already has a solution for this, but it does not suit all of your needs, or if you happen to have alternative ways of fixing the problem. Please fill the "Additional Context" field with the actual use-case of the feature request, possibly with configuration snippets.

Attila

**Comment by alltilla** [comment]
Thanks for the update! :)

What do you think about the following idea?
```
rewrite r_rev_dns_lookup {
  set(
    "$(reverse-dns-lookup ${HOST})",
    value("HOST")
    condition(program("myapplication"))
);
```

Attila

**Comment by gaborznagy** [comment]
Hi, just for info: there were some discussion previously: https://github.com/syslog-ng/syslog-ng/issues/275

**Comment by bazsi** [comment]
It'd be great to use the naming from #275 eg, to start ask dns related functions with the DNS prefix so they order neatly after one another in documentation.

**Comment by rfaircloth-splunk** [comment]
Would it be like this use the fromhost that would have IP to update host?

> rewrite r_rev_dns_lookup {

  set(
    "$(reverse-dns-lookup ${FROMHOST})",
    value("HOST")
    condition(program("myapplication"))
  );
};

**Comment by alltilla** [comment]
@rfaircloth-splunk :
Yes. Also, we have an PR now. #3046
