### ISSUE TITLE
dbld/rules rpm-centos-7 fails due loggen library path changes

### ISSUE THREAD

**Issue by czanik** [syslog-ng/syslog-ng#3023]
# syslog-ng
## Version of syslog-ng
Fresh git snapshot: syslog-ng-3.24.1.176.g39ed128

## Platform
CentOS 7 platform within DBLD

# Issue
## Failure
```dbld/rules rpm-centos-7```
fails with the following error:
```
RPM build errors:
    Directory not found: /root/rpmbuild/BUILDROOT/syslog-ng-3.24.1.176.g39ed128-1+20191120T122658.el7.x86_64/usr/lib64/syslog-ng/loggen
    File not found by glob: /root/rpmbuild/BUILDROOT/syslog-ng-3.24.1.176.g39ed128-1+20191120T122658.el7.x86_64/usr/lib64/syslog-ng/loggen/libloggen*
make: *** [dbld/rules:118: rpm-centos-7] Error 1
```
When removed the related two lines from the spec file, I get:
```
    Installed (but unpackaged) file(s) found:
   /usr/lib/syslog-ng/loggen/libloggen_socket_plugin.so
   /usr/lib/syslog-ng/loggen/libloggen_ssl_plugin.so
```

Before modifying any spec files: is this an expected change?

**Comment by MrAnno** [comment]
I think this is an accidental change, we should follow `--with-module-dir` in case of loggen plugins too.
I'll open a PR with the fix.

**Comment by MrAnno** [comment]
#3024 should fix this, now it follows `--with-module-dir` as before.
