### ISSUE TITLE
Checkpoint parser not working?

### ISSUE THREAD

**Issue by jstorgaard** [syslog-ng/syslog-ng#3055]
I'm trying to get the checkpoint parser to work on my syslog-ng 3.21 server running on Centos 7.

My checkpoint log exporter is configured as format: syslog, read-mode: raw.

I have copied the plugin.conf from this repo to /etc/syslog-ng/scl/checkpoint/plugin.conf on my server.

This is the relevant block from syslog-ng.conf
```
@version:3.21
@include "scl.conf"

options {
    flush_lines (100);
    time_reopen (10);
    log_fifo_size (1000);
    chain_hostnames (off);
    use_dns (no);
    dns_cache (no);
    use_fqdn (no);
    create_dirs (yes);
    keep_hostname (yes);
    threaded (yes);
};

#############################
## FILTER DEFINITIONS
#############################

filter f_kernel     { facility(kern); };
filter f_default    { level(info..emerg) and
                        not (facility(mail)
                        or facility(authpriv)
                        or facility(cron)); };
filter f_auth       { facility(authpriv); };
filter f_mail       { facility(mail); };
filter f_emergency  { level(emerg); };
filter f_news       { facility(uucp) or
                        (facility(news)
                        and level(crit..emerg)); };
filter f_boot   { facility(local7); };
filter f_cron   { facility(cron); };

#############################
## LOG OUTPUT DEFINITIONS
#############################

log {
    source { network(ip(172.16.0.1) transport(tcp) port(1514) flags(no-parse)); };
    parser { checkpoint-parser(); };
    destination { syslog("172.16.0.2" transport("udp") port(514)); };
};


@include "/etc/syslog-ng/conf.d/*.conf"
```

scl.conf contains this:
```
@include 'scl/*/*.conf'

@define java-module-dir "`module-install-dir`/java-modules"
```

Nothing arrives at the destination. If I comment out the line parser { checkpoint-parser(); }; I get logs at destination.

**Comment by Kokan** [comment]
Could you please share the exact version of `checkpoint-parser` ?
The current on master should not work with syslog-ng 3.21 (multiple format string were not supported in that version).
Could you try this version ? (https://github.com/syslog-ng/syslog-ng/blob/8d92233f66e459a4cba22582ae4a8ff7d779b5eb/scl/checkpoint/plugin.conf )

**Comment by jstorgaard** [comment]
I was using the current one from the repo here. a28ff8a.
Tried the version you suggested, but still nothing seems to be sent/received. 
Can I check a log somewhere of what is happening? /var/log/messages seems to not tell me anything. Unless syslog-ng[25462]: [2020-01-02T14:20:19.763096] Plugin module not found in 'module-path'; module-path='//usr/lib64/syslog-ng', module='http' is related?

**Comment by jstorgaard** [comment]
I updated to syslog-ng 3.24.1 now. 
Logs are forwarded now with the parser enabled, but it just looks like normal unparsed logs?

**Comment by Kokan** [comment]
How does a parsed log look like ? (The below example is just using `checkpoint-parser` and using file destination saving it)
```
Parsed, and written into a file destination format:
Mar 21 17:25:25 MDS-72 CheckPoint[13752]: [action:"Update"; flags:"150784"; ifdir:"inbound"; logid:"160571424"; loguid:"{0x5ab27965,0x0,0x5b20a8c0,0x7d5707b6}"; origin:"192 .16 8.32.91"; originsicname:"CN=GW91,O=Domain2_Server..cuggd3"; sequencenum:"1"; time:"1521645925"; version:"5"; auth_method:"Machine Authentication (Active Directory)"; auth_status:"Succe ss ful Login"; authentication_trial:"this is a reauthentication for session 9a026bba"; client_name:"Active Directory Query"; client_version:"R80.10"; domain_name:"spec.mgmt"; endpoint_ip:" 1 92.168.32.69"; identity_src:"AD Query"; identity_type:"machine"; product:"Identity Awareness"; snid:"9a026bba"; src:"192.168.32.69"; src_machine_group:"All Machines"; src_machine_name:"y onatanad";]
Input example log:
<134>1 2018-03-21 17:25:25 MDS-72 CheckPoint 13752 - [action:"Update"; flags:"150784"; ifdir:"inbound"; logid:"160571424"; loguid:"{0x5ab27965,0x0,0x5b20a8c0,0x7d5707b6}"; origin:"192 .16 8.32.91"; originsicname:"CN=GW91,O=Domain2_Server..cuggd3"; sequencenum:"1"; time:"1521645925"; version:"5"; auth_method:"Machine Authentication (Active Directory)"; auth_status:"Succe ss ful Login"; authentication_trial:"this is a reauthentication for session 9a026bba"; client_name:"Active Directory Query"; client_version:"R80.10"; domain_name:"spec.mgmt"; endpoint_ip:" 1 92.168.32.69"; identity_src:"AD Query"; identity_type:"machine"; product:"Identity Awareness"; snid:"9a026bba"; src:"192.168.32.69"; src_machine_group:"All Machines"; src_machine_name:"y onatanad";]
```

Do you mean it did not parse the log ? (Can you share the log it missed to parse as `checkpoint` logs)
It is easier with example to find out what went wrong during the parsing.

Thanks.

**Comment by jstorgaard** [comment]
This is what the message looks like with the parser enabled:
`1 2020-01-02T15:04:52+01:00 172.16.0.10 - - - - <134>1 2020-01-02T14:04:50Z fwmgmt CheckPoint 16559 - [action:"Accept"; flags:"411908"; ifdir:"inbound"; ifname:"bond0.401"; logid:"0"; loguid:"{0x5e0df882,0x0,0x20010ac,0xc0000002}"; origin:"172.16.0.2"; originsicname:"CN=fw01,O=fwmgmt.ny-net.local.nahkt6"; sequencenum:"6"; time:"1577973890"; version:"5"; __policy_id_tag:"product=VPN-1 & FireWall-1[db_tag={E97DE696-700C-7F42-BD71-537C8A0883CB};mgmt=fwmgmt;date=1556607233;policy_name=Standard\]"; dst:"192.203.230.10"; inzone:"Internal"; layer_name:"Network"; layer_uuid:"0eeae4c4-aa05-40a9-a319-623823330c95"; match_id:"7"; parent_rule:"0"; rule_action:"Accept"; rule_name:"ALLOW"; rule_uid:"52ff639d-c772-4797-8b45-e151e295702e"; nat_addtnl_rulenum:"1"; nat_rulenum:"8"; outzone:"External"; product:"VPN-1 & FireWall-1"; proto:"17"; s_port:"55263"; service:"53"; service_id:"domain-udp"; src:"10.126.0.154"; xlatedport:"0"; xlatedst:"0.0.0.0"; xlatesport:"52993"; xlatesrc:"172.16.16.10"; ]`

**Comment by Kokan** [comment]
I tried with the following configuration:

```
@version: 3.24
@include "scl.conf"

log {

  source { stdin(flags(no-parse)); };
  parser { checkpoint-parser(); };
  destination { file("/dev/stdout" ); };

};
```

Saving your message from `<134>1 2020-0...` into ` file `/tmp/example`, then running syslog-ng as:
```
$> cat /tmp/example | /tmp/install/sbin/syslog-ng -F
Jan  2 14:04:50 CheckPoint 16559: flags:"411908"; ifdir:"inbound"; ifname:"bond0.401"; logid:"0"; loguid:"{0x5e0df882,0x0,0x20010ac,0xc0000002}"; origin:"172.16.0.2"; originsicname:"CN=fw01,O=fwmgmt.ny-net.local.nahkt6"; sequencenum:"6"; time:"1577973890"; version:"5"; __policy_id_tag:"product=VPN-1 & FireWall-1[db_tag={E97DE696-700C-7F42-BD71-537C8A0883CB};mgmt=fwmgmt;date=1556607233;policy_name=Standard\]"; dst:"192.203.230.10"; inzone:"Internal"; layer_name:"Network"; layer_uuid:"0eeae4c4-aa05-40a9-a319-623823330c95"; match_id:"7"; parent_rule:"0"; rule_action:"Accept"; rule_name:"ALLOW"; rule_uid:"52ff639d-c772-4797-8b45-e151e295702e"; nat_addtnl_rulenum:"1"; nat_rulenum:"8"; outzone:"External"; product:"VPN-1 & FireWall-1"; proto:"17"; s_port:"55263"; service:"53"; service_id:"domain-udp"; src:"10.126.0.154"; xlatedport:"0"; xlatedst:"0.0.0.0"; xlatesport:"52993"; xlatesrc:"172.16.16.10"; ]
```

Is it possible that your logpathes are mixed up ? Could you try with the minimal configuration or similar (one source, parser and destination) ?

**Comment by jstorgaard** [comment]
I did like your example and got this:
`2]# cat /tmp/example | /sbin/syslog-ng -F
[2020-01-02T15:24:34.954282] Plugin module not found in 'module-path'; module-path='/usr/lib64/syslog-ng', module='http'
[2020-01-02T15:24:34.957647] Plugin module not found in 'module-path'; module-path='/usr/lib64/syslog-ng', module='http'
[2020-01-02T15:24:34.958288] Plugin module not found in 'module-path'; module-path='/usr/lib64/syslog-ng', module='http'
Jan  2 15:24:34 syslog02 <134>1 2020-01-02T14:04:50Z fwmgmt CheckPoint 16559 - [action:"Accept"; flags:"411908"; ifdir:"inbound"; ifname:"bond0.401"; logid:"0"; loguid:"{0x5e0df882,0x0,0x20010ac,0xc0000002}"; origin:"172.16.0.2"; originsicname:"CN=fw01,O=fwmgmt.ny-net.local.nahkt6"; sequencenum:"6"; time:"1577973890"; version:"5"; __policy_id_tag:"product=VPN-1 & FireWall-1[db_tag={E97DE696-700C-7F42-BD71-537C8A0883CB};mgmt=fwmgmt;date=1556607233;policy_name=Standard\]"; dst:"192.203.230.10"; inzone:"Internal"; layer_name:"Network"; layer_uuid:"0eeae4c4-aa05-40a9-a319-623823330c95"; match_id:"7"; parent_rule:"0"; rule_action:"Accept"; rule_name:"ALLOW"; rule_uid:"52ff639d-c772-4797-8b45-e151e295702e"; nat_addtnl_rulenum:"1"; nat_rulenum:"8"; outzone:"External"; product:"VPN-1 & FireWall-1"; proto:"17"; s_port:"55263"; service:"53"; service_id:"domain-udp"; src:"10.126.0.154"; xlatedport:"0"; xlatedst:"0.0.0.0"; xlatesport:"52993"; xlatesrc:"172.16.16.10"; ]`

**Comment by Kokan** [comment]
Yeah, my output was from master.
This was introduced/fixed in `3.25`, with your `2.24` you still need to use the `checkpoint/plugin.conf` from current master.

Now compiling `3.24` + using the `checkpoint` scl from master works for me.

could you try that out ? or as an alternative is it possible to update to 3.25 ?

**Comment by jstorgaard** [comment]
I tried with the checkpoint/plugin.conf from the current master, but the logs are still unparsed and looks like the post above. 
I'm using the czanik/syslog-ng-stable repo for Centos 7. Newest version from this is 3.24.
Could it be that the plugin.conf are somehow not loaded correctly? Or would I get a warning/error about that?

**Comment by Kokan** [comment]
Normally some error about loading `plugin.conf` could slide without detecting as long as you are not using that in your configuration. As you use this one in your configuration it should work or fail to start (well there is also a possibility of bug there ...).

You could verify if the proper `checkpoint` plugin is loaded in this case, asking syslog-ng to print out the configuration file it uses.

```
> syslog-ng -F --preprocess-into=/dev/stdout | less -S # The /dev/stdout could be any file it creates and stores the config
...
block parser checkpoint-parser(prefix('.checkpoint.')) {
...
            if {
                parser { date-parser(format("%Y-%m-%dT%H:%M:%S%z",
                                            "%Y-%m-%dT%H:%M:%S") template("$2")); };
            } else {
...
...

You should see this one with the `%z` there

**Comment by jstorgaard** [comment]
Looks like I got two different parser configurations for Checkpoint. One with the %z and one without. 
Also I got the other parsers. Apache etc. even though I did not copy them to the scl folder. They must be located somewhere else on the server, but I can't see any reference to the dir. 
Do you have a clue where I should look for them?

**Comment by bazsi** [comment]
The scl files are installed under /usr/share/syslog-ng so that syslog-ng
can include them with a simple "include scl.conf"

If you also have an include file in /etc/syslog-ng you might be including
two separate versions of the checkpoint-parser.

The behavior is that we'll use the last one.

So make sure you only have one copy or that the last included is the right
one.

Syslog-ng does emit trace level messages on log path evaluation but those
are pretty verbose and not necessarily the most intuitive/easy to
understand. You can enable them with the -t command line option.

**Comment by jstorgaard** [comment]
I deleted the checkpoint plugin.conf from /usr/share/syslog-ng and it seems like the parser is doing something now. 
However, it's still not as well formated as your example?
`2020-01-03T11:32:17+00:00 CheckPoint 16559 - [action:"Accept"; - conn_direction:"Incoming"; flags:"8800516"; ifdir:"inbound"; ifname:"bond0.450"; logid:"0"; loguid:"{0x5e0f2641,0x2,0x20010ac,0xc0000002}"; origin:"172.16.0.2"; originsicname:"CN=fw01,O=fwmgmt.ny-net.local.nahkt6"; sequencenum:"8"; time:"1578051137"; version:"5"; __policy_id_tag:"product=VPN-1 & FireWall-1[db_tag={E97DE696-700C-7F42-BD71-537C8A0883CB};mgmt=fwmgmt;date=1556607233;policy_name=Standard\]"; dst:"10.103.222.237"; layer_name:"Network"; layer_uuid:"0eeae4c4-aa05-40a9-a319-623823330c95"; match_id:"6"; parent_rule:"0"; rule_action:"Accept"; rule_uid:"f37232c4-01fc-4621-beea-46675458dbbc"; product:"VPN-1 & FireWall-1"; proto:"6"; s_port:"57075"; service:"443"; src:"10.125.0.7"; ]`
Am I using incorrect source log format?

**Comment by Kokan** [comment]
The log source as it was configured with `flags(no-parse)` does not matter, and I guess this logs were generated by checkpoint so they should be valid.

But I am not sure syslog-ng handles these form of checkpoint well. It is kinda better to check out value of each macro instead of comparing parse+destination outputs.

```
log {
  source { stdin(flags(no-parse)); };
  parser { checkpoint-parser(); };
  destination { file("/dev/stdout" template("$(format-json --scope nv-pairs)\n") ); };
};
```

This results in: (latest master)
```json
{
  "SOURCE": "#anon-source0",
  "PROGRAM": "16559",
  "PID": "",
  "MSGID": "[action:\"Accept\";",
  "MESSAGE": "flags:\"411908\"; ifdir:\"inbound\"; ... xlatesrc:\"172.16.16.10\"; ]",
  "HOST_FROM": "peterkokai-work",
  "HOST": "CheckPoint",
  "FILE_NAME": "-",
  "3": "fwmgmt",
  "2": "2020-01-02T14:04:50Z",
  "1": "<134>1"
}
```

The `PROGRAM`, `HOST` and `MSGID`, `MESSAGE` values are seems odd.

If you check the `checkpoint` parser, it first parses the values as CSV with space separator
https://github.com/syslog-ng/syslog-ng/blob/a28ff8a358472e27e569f0f649da1241503a5456/scl/checkpoint/plugin.conf#L50-L59

There is case with space between date and time, and the one with T between. In case of space in the date, the timestamp became `$2` and `$3`, but in case of the lack of space the fields are shifted.

I did a patch that tries to resolve that issue, would you try that out ?
https://github.com/Kokan/syslog-ng/blob/checkpoint-parser/scl/checkpoint/plugin.conf

**Comment by jstorgaard** [comment]
The patch you created looks better. When routing to Graylog I get the correct fields for application_name, timestamp, source etc. Message is everything inside [], including the brackets ([action:".......]). 
Are these key-values supposed to be parsed also or is it correct that the rest of the line is inside "message"?

**Comment by jstorgaard** [comment]
Looking back at your parsed line I see that you haven't got the brackets. So there is probably something still not parsed correctly in my logs?

**Comment by Kokan** [comment]
I think the `MESSAGE` macro is correct having those values, but they are also parsed and the parsed fields are stored under the default `prefix` domain. (in this case `.checkpoint.`).

See: `destination { file("/dev/stdout" template("$(format-json --scope nv-pairs --key .checkpoint.*)\n") ); };`

```json
{
  "_checkpoint": {
    "xlatesrc": "172.16.16.10",
    "xlatesport": "52993",
    "xlatedst": "0.0.0.0",
    "xlatedport": "0",
    "version": "5",
    "time": "1577973890",
    "src": "10.126.0.154",
    "service_id": "domain-udp",
    "service": "53",
    "sequencenum": "6",
    "s_port": "55263",
    "rule_uid": "52ff639d-c772-4797-8b45-e151e295702e",
    "rule_name": "ALLOW",
    "rule_action": "Accept",
    "proto": "17",
    "product": "VPN-1 & FireWall-1",
    "parent_rule": "0",
    "outzone": "External",
    "originsicname": "CN=fw01,O=fwmgmt.ny-net.local.nahkt6",
    "origin": "172.16.0.2",
    "nat_rulenum": "8",
    "nat_addtnl_rulenum": "1",
    "match_id": "7",
    "loguid": "{0x5e0df882,0x0,0x20010ac,0xc0000002}",
    "logid": "0",
    "layer_uuid": "0eeae4c4-aa05-40a9-a319-623823330c95",
    "layer_name": "Network",
    "inzone": "Internal",
    "ifname": "bond0.401",
    "ifdir": "inbound",
    "flags": "411908",
    "dst": "192.203.230.10",
    "action": "Accept",
    "__policy_id_tag": "product=VPN-1 & FireWall-1[db_tag={E97DE696-700C-7F42-BD71-537C8A0883CB};mgmt=fwmgmt;date=1556607233;policy_name=Standard\\]"
  },
  "SOURCE": "#anon-source0",
  "PROGRAM": "CheckPoint",
  "PID": "16559",
  "MSGID": "",
  "MESSAGE": "[action:\"Accept\"; flags:\"411908\"; ifdir:\"inbound\"; ifname:\"bond0.401\"; logid:\"0\"; loguid:\"{0x5e0df882,0x0,0x20010ac,0xc0000002}\"; origin:\"172.16.0.2\"; originsicname:\"CN=fw01,O=fwmgmt.ny-net.local.nahkt6\"; sequencenum:\"6\"; time:\"1577973890\"; version:\"5\"; __policy_id_tag:\"product=VPN-1 & FireWall-1[db_tag={E97DE696-700C-7F42-BD71-537C8A0883CB};mgmt=fwmgmt;date=1556607233;policy_name=Standard\\]\"; dst:\"192.203.230.10\"; inzone:\"Internal\"; layer_name:\"Network\"; layer_uuid:\"0eeae4c4-aa05-40a9-a319-623823330c95\"; match_id:\"7\"; parent_rule:\"0\"; rule_action:\"Accept\"; rule_name:\"ALLOW\"; rule_uid:\"52ff639d-c772-4797-8b45-e151e295702e\"; nat_addtnl_rulenum:\"1\"; nat_rulenum:\"8\"; outzone:\"External\"; product:\"VPN-1 & FireWall-1\"; proto:\"17\"; s_port:\"55263\"; service:\"53\"; service_id:\"domain-udp\"; src:\"10.126.0.154\"; xlatedport:\"0\"; xlatedst:\"0.0.0.0\"; xlatesport:\"52993\"; xlatesrc:\"172.16.16.10\"; ]",
  "HOST_FROM": "peterkokai-work",
  "HOST": "fwmgmt",
  "FILE_NAME": "-",
  "4": "fwmgmt CheckPoint 16559 - [action:\"Accept\"; flags:\"411908\"; ifdir:\"inbound\"; ifname:\"bond0.401\"; logid:\"0\"; loguid:\"{0x5e0df882,0x0,0x20010ac,0xc0000002}\"; origin:\"172.16.0.2\"; originsicname:\"CN=fw01,O=fwmgmt.ny-net.local.nahkt6\"; sequencenum:\"6\"; time:\"1577973890\"; version:\"5\"; __policy_id_tag:\"product=VPN-1 & FireWall-1[db_tag={E97DE696-700C-7F42-BD71-537C8A0883CB};mgmt=fwmgmt;date=1556607233;policy_name=Standard\\]\"; dst:\"192.203.230.10\"; inzone:\"Internal\"; layer_name:\"Network\"; layer_uuid:\"0eeae4c4-aa05-40a9-a319-623823330c95\"; match_id:\"7\"; parent_rule:\"0\"; rule_action:\"Accept\"; rule_name:\"ALLOW\"; rule_uid:\"52ff639d-c772-4797-8b45-e151e295702e\"; nat_addtnl_rulenum:\"1\"; nat_rulenum:\"8\"; outzone:\"External\"; product:\"VPN-1 & FireWall-1\"; proto:\"17\"; s_port:\"55263\"; service:\"53\"; service_id:\"domain-udp\"; src:\"10.126.0.154\"; xlatedport:\"0\"; xlatedst:\"0.0.0.0\"; xlatesport:\"52993\"; xlatesrc:\"172.16.16.10\"; ]",
  "3": "fwmgmt",
  "2": "2020-01-02T14:04:50Z",
  "1": "<134>1"
}
```

The message just works fine with this modified version (see it has the end bracket).

**Comment by jstorgaard** [comment]
Looks good, I have never worked with a parsed result from json in syslog-ng. 
How would I correctly send this json to a graylog (GELF) or syslog destination?

**Comment by bazsi** [comment]
Once you have a suitable set of name-value pairs you can use those to format a JSON payload using $(format-json) that can use sets of name-value pairs to include in the payload.

For example:
```
template("$(format-json .checkpoint.*)");
```

would include all name-value pairs that are prefixed with `.checkpoint.` You can also bulk rename name-value pairs using the value-pairs options. You can find more information about value-pairs here: https://www.syslog-ng.com/technical-documents/doc/syslog-ng-open-source-edition/3.22/administration-guide/9#TOPIC-1209097

value-pairs are available in two contexts: 1) template functions such as $(format-json) where the value-pairs options are like command-line options, 2) destination drivers such as mongodb() where they are represented as driver configuration options.

Here's the $(format-gelf) template function that we supply along syslog-ng (in the SCLs) that is the default for the graylog2() destination:


```
template-function "format-gelf" "$(format-json version='1.1' host='${HOST}' short_message='${MSG}' level=int(${LEVEL_NUM}) timestamp=int64(${R_UNIXTIME}) _program='${PROGRAM}' _pid=int(${PID}) _facility='${FACILITY}' _class='${.classifier.class}' --key .* --key _*)$(binary 0x00)";
```

More complex scenarios can be found in the SCL (loggly and slack destinations for example), which you can find in the github repository. https://github.com/syslog-ng/syslog-ng/tree/master/scl
