### ISSUE TITLE
i want to know the diff between syslog-ng and flume-ng 

### ISSUE THREAD

**Issue by xx-zhang** [syslog-ng/syslog-ng#3081]
## Description of the problem

> I have always using syslog-ng with the old config of common using syslog-ng like this file1. and now i want to using java-distnation to receive the none-json style txt parsed to json . and i have know syslog-ng and using python-distination in a long time ago. and also i can write some java code because of my team that they are all java-coder. they want to using flume that would make more and confuence , what do you think so , our data store is ElasticSearch. 

best wish to you.  i think your advice will decrease my studing round.

**Comment by alltilla** [comment]
I am not sure, I follow.
Can you please describe what kind of sources and destination do you need to have? Are you sending logs to ElasticSearch?

**Comment by xx-zhang** [comment]
@alltilla yes, but i should parse the txt for the json that what i want and then push it to es. the log-source like the `modsec.log`(modsecurity) which if a waf log ABCDFUI split that cann't parse to json with regex easily.

```
--H---
[client 200.249.12.31] ModSecurity: Access denied with code 400 (phase -1). Matched "Operator `Rx' with parameter `bar' against variable `ARGS:foo' (Value: `bar' ) [file ""] [line "0"] [id "0"] [rev ""] [msg "Test message"] [data "Test logdata"] [severity "2"] [ver ""] [maturity "0"] [accuracy "0"] [hostname "200.249.12.31"] [uri "/"] [unique_id "1578403341"] [ref "o0,3v10,3"]
---I---
GET /  ....
```

**Comment by alltilla** [comment]
I think when you referred to java destination, you thought, that you can receive logs with it. We only have java destination, and not source.

The correct way of handling ModSecurity logs should be to have a general (file/network/...) source, and a modsec parser, which would populate the name-value pairs. Then, we could forward that message to ES easily. 

So you would like to parse ModSecurity logs? Can you provide a documentation with the log format of ModSecurity? :)

**Comment by xx-zhang** [comment]
@a
