### ISSUE TITLE
syslog-ng 3.19 systemd-journal module does not respect read-old-logs option in docker container

### ISSUE THREAD

**Issue by brettmcintosh** [syslog-ng/syslog-ng#3096]
# syslog-ng
## Version of syslog-ng
3.19

## Platform
Docker on Amazon Linux 2

# Issue
## Failure
When restarting (or stop/starting) the docker container, all logs in the systemd journal are forwarded to the destination, even when using the `read-old-records(no)` option. 

The `read-old-records` documentation mentions:
> If the source has a state in the persist file, this option will have no effect.

I can see that the persist file at `/var/lib/syslog-ng/syslog-ng.persist` contains what looks like journal state:
```
SLP4run_ihost_idsystemd-journٔ@s=d47b51c72ab7453dbf3f2f2caaef128d;i=cefc68;b=6ab829477b784bf5a4dfba0dc6aff054;m=102fd503b378;t=59d2581067f86;x=7f25ff8463c6c833
```

I attempted to bind mount an empty persist file to the docker container hoping that syslog-ng would use it when the container is restarted, but instead it just creates a new persist file at `/var/lib/syslog-ng/syslog-ng.persist-` (note the `-` appended to the file).

What is the proper way to use persist files and not forward old journal logs when using Docker? 

## Configuration
```
@version: 3.19

options {
  ts_format(iso);
  frac-digits(6);
};

source s_journald {
  systemd-journal(
    prefix(".SDATA.journald.")
    read-old-records(no)
  );
};

filter f_filter {
  "${.SDATA.journald.CONTAINER_TAG}" eq "nginx"
  or "${.SDATA.journald.CONTAINER_TAG}" eq "gunicorn"
  or "${.SDATA.journald.CONTAINER_TAG}" eq "celery"
  or "${.SDATA.journald.CONTAINER_TAG}" eq "celery-heavy"
  or "${.SDATA.journald.CONTAINER_TAG}" eq "celery-beat"
};

destination d_pgsql {
  sql(
    type(pgsql)
    host("`LOGS_PRIVATE_IP`") username("logwriter") password ("`LOGS_DB_PASSWORD`")
    database("syslog")
    table("logs")
    columns("datetime timestamp with time zone", "program", "message")
    values("$R_ISODATE", "$PROGRAM", "$MSG")
    indexes("datetime", "program", "message")
  );
};

log {
  source(s_journald);
  filter(f_filter);
  destination(d_pgsql);
};
```

## Docker volume mounts
```
       "Mounts": [
            {
                "Type": "bind",
                "Source": "/etc/machine-id",
                "Destination": "/etc/machine-id",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/home/ops/syslog-ng.conf",
                "Destination": "/etc/syslog-ng/syslog-ng.conf",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/home/ops/log",
                "Destination": "/var/log",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/var/log/journal",
                "Destination": "/var/log/journal",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/home/ops/syslog-ng.persist",
                "Destination": "/var/lib/syslog-ng/syslog-ng.persist",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            }
        ]
```

**Comment by alltilla** [comment]
As the documentation states, the `read-old-records` option only has effect, when `syslog-ng` does not have any persist entry from the source.

At `systemd-journal`:
 * if we set `read-old-records(yes)`, then we call `sd_journal_seek_head()`, when we do not have a persist entry. 
 * if we set it to `no`, we call `sd_journal_seek_tail()`, when we do not have a persist entry.
 * if we have a persist entry, it does not matter, if we set `read-old-records` to `yes` or `no`, we call `sd_journal_seek_cursor()` and jump to the last sent position, and send the next log.

According to the [manpage](https://www.systutorials.com/docs/linux/man/3-sd_journal_seek_cursor/):
> sd_journal_seek_cursor() seeks to the entry located at the specified cursor string. For details on cursors, see sd_journal_get_cursor(3). If no entry matching the specified cursor is found the call will seek to the next closest entry (in terms of time) instead.

It is possible that after a docker restart, the old cursor is lost, as systemd deletes it, and we start from the next available entry (which is the first entry after the reload). **Is this the case for you, OR you observe, that after the reload, `syslog-ng` sends an older log, than the last sent log from the `systemd-journal`?**

---

Regarding the persist name. the file with `syslog-ng.persist-` name is a temporary file which we use when operating on the actual persist file. The data is saved to `syslog-ng.persist` in the end.

**Comment by brettmcintosh** [comment]
Thanks for the reply. I upgraded to 3.24.1 and now the `read-old-records(no)` option now works as expected. I don't have to mount the persist file to the container. When the container is restarted, the old persist data is removed and syslog-ng just starts at the current journal cursor.
