### ISSUE TITLE
syslog-ng-3.25.1 fails to build with -fno-common

### ISSUE THREAD

**Issue by hydrapolic** [syslog-ng/syslog-ng#3101]
# syslog-ng
## Version of syslog-ng
3.25.1

## Platform
Linux Gentoo

## Steps to reproduce
Build syslog-ng with CFLAGS="... -fno-common"

## Issue
https://gcc.gnu.org/gcc-10/changes.html:
````
GCC now defaults to -fno-common. As a result, global variable accesses are more efficient on various targets. In C, global variables with multiple tentative definitions now result in linker errors. With -fcommon such definitions are silently merged during linking. 
````

This can be simulated on gcc 9.2.0 with CFLAGS="... -fno-common" too.

Gentoo bug: https://bugs.gentoo.org/707124

**Comment by alltilla** [comment]
We explicitly set the `-fcommon` flag, which `gcc` should prefer instead of its default. I tried to build `syslog-ng` with `gcc10` (from ArchLinux AUR `gcc-git`), and the `-fno-common` flag was not added to the `CFLAGS`.

> gcc -DHAVE_CONFIG_H -I.  -I./lib -D_FORTIFY_SOURCE=2 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -pthread  -I./lib/eventlog/src -I./lib/eventlog/src     -isystem ./lib/ivykis/src/include -isystem ./lib/ivykis/src/include  -D_GNU_SOURCE -D_DEFAULT_SOURCE -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -Wshadow -fcommon -Wno-stack-protector -Wno-unused-parameter -Wno-variadic-macros  -g -pthread -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -g -fvar-tracking-assignments -fdebug-prefix-map=/build/syslog-ng/src=/usr/src/debug -MT persist-tool/persist_tool-persist-tool.o -MD -MP -MF persist-tool/.deps/persist_tool-persist-tool.Tpo -c -o persist-tool/persist_tool-persist-tool.o `test -f 'persist-tool/persist-tool.c' || echo './'`persist-tool/persist-tool.c

I will try out some other combinations as well.

**Comment by hydrapolic** [comment]
We can workaround this by forcing -fcommon, but it should be fixed properly and make it build even with -fno-common.

**Comment by MrAnno** [comment]
@hydrapolic Thanks for the issue.

#3114 fixes the multi-defined variables in persist-tool and in a unit test. 
I've also removed `-fcommon` from our build.

`-fcommon` was first added to the autotools build in bf53d6dd0 with this note:
```
-fcommon is important to emit because we have all kind of breakage due
 to this on non-linux platforms.
```

I hope this isn't true anymore.

**Comment by hydrapolic** [comment]
Thanks @MrAnno, tested with 3.25.1, builds just fine.

**Comment by MrAnno** [comment]
@hydrapolic Thanks for testing.

The patch is not final yet, I broke the macOS build, and I also would like to add a better fix for the persist-tool options.

**Comment by hydrapolic** [comment]
Thanks
