### ISSUE TITLE
add support for the "arrow" syntax for java/python

### ISSUE THREAD

**Issue by bazsi** [syslog-ng/syslog-ng#3105]
When adding support for the librdkafka based kafka-c() destination, we introduced a new format for specifying name=>value entries that describe the librdkafka configuration. This is the arrow syntax, e.g:

```
                      config( "queue.buffering.max.ms" => "1000",
                             "message.timeout.ms" => "5000",
                             "debug" => "all")
```

This is now specific to kafka, but we have _very_ similar use-cases in java/python where we are passing options to the interpreted code, e.g.

scl/elasticsearch:
```
    option("index", `index`)
    option("type", `type`)
    option("server", `server`)
    option("port", "`port`")
    option("message-template", `template`)
    option("cluster", "`cluster`")
    option("flush_limit", `flush_limit`)
    option("flush_timeout", `flush_timeout`)
    option("client_mode", `client_mode`)
    option("resource", "`resource`")
    option("custom_id", "`custom_id`")
    option("concurrent_requests", `concurrent_requests`)
    option("skip_cluster_health_check", "`skip_cluster_health_check`")
    option("cluster_url", "`cluster_url`")
    option("java_keystore_filepath", "`java_keystore_filepath`")
    option("java_keystore_password", "`java_keystore_password`")
    option("java_truststore_filepath", "`java_truststore_filepath`")
    option("java_truststore_password", "`java_truststore_password`")
    option("java_ssl_insecure", `java_ssl_insecure`)
    option("http_auth_type", `http_auth_type`)
    option("http_auth_type_basic_username", "`http_auth_type_basic_username`")
    option("http_auth_type_basic_password", "`http_auth_type_basic_password`")
```

The goal would be to unify the syntax for these options in python/java, that is:

```
java/python(
     options("key" => "value",
                  "key2" => "value2"))
```

Couple of notes:
  * the keyword that introduces the config block should be plural (e.g. options instead of option)
  * there should be support for _multiple_ options blocks to make the life of wrapper SCLs easier (e.g. the java/python source/destination driver should be able to merge options specified via multiple options blocks).
  * we should be backward compatible in syntax (e.g. accept the old way of doing things)
  * we should be using common code for the implementation (see modules/kafka/kafka-grammar.ym as a starting point).

**Comment by furiel** [comment]
I was late in noticing that #3161 only deals with python destination. We have python source, python fetcher, and python http auth header as well.

@mehul-m-prajapati, could you add arrow syntax to these too?

It would be nice if we could avoid duplicating the setter grammar. It is easy to forget propagating the bugfixes/features from one to the others. I do not know the "how", though.

**Comment by MrAnno** [comment]
@furiel Maybe we could add a general nonterminal symbol to cfg-grammar that returns a name-value or tuple type and allows all 3 syntaxes, for example:

```
custom_option
  : string string_or_number { $$ = custom_option_new($1, $2); }
  | string '(' string_or_number ')' { $$ = custom_option_new($1, $3); }
  | string LL_ARROW string_or_number { $$ = custom_option_new($1, $3); }
```

```
java_dest_custom_option
  : custom_option { java_dd_set_option(last_driver, $1->name, $1->value); custom_option_free($1); }
```

**Comment by MrAnno** [comment]
@bazsi What do you think, do we need such a general option in cfg-grammar? We could remove some setter duplications, we'd be able to deprecate the old syntax uniformly everywhere too.

**Comment by bazsi** [comment]
It would be great and it also crossed my mind. The question is if its easy
to find a data structure that matches all plugin's expectations.

So agreed but I would probably do that in a separate PR.
