### ISSUE TITLE
FR: An option to use the OS's cert bundle for validating certificates

### ISSUE THREAD

**Issue by CRCinAU** [syslog-ng/syslog-ng#3111]
## Description of the problem
Using TLS for transporting logs around is good practice, but the configuration for TLS leaves lots of room for improvement. If the server side has a well known, good certificate that can be validated via the OS's installed trusted certificate bundle, the option should be present to allow this.

## Proposed solution
Right now, not only do you have to manually populate certificates into the `ca-dir` - but you also have to have non-obvious naming, or use the c_rehash utility - which is not part of the standard openssl install on most distros.

An option should be added to use the system trusted bundle to validate a presented certificate.

**Comment by alltilla** [comment]
The TLS implementation is different in the `http` and `network, tcp, ...` drivers. You are using `network, ...`, right?

Does it work, if you use the OS's provided certs with changing the `cert-file()` or `ca-dir()` options? The value varies by OS.

**Comment by CRCinAU** [comment]
I tried passing the ca-dir as `/etc/pki/tls/certs/` - which in CentOS stores the trusted bundles (or links to the trusted bundles).

This didn't seem to work as the certs could still not be verified.

**Comment by alltilla** [comment]
Does it work with `cert-file("/etc/pki/tls/certs/ca-bundle.crt")`?

**Comment by CRCinAU** [comment]
This gives me:
```
syslog-ng[1354462]: [2020-02-17T20:03:59.809415] Error setting up TLS session context; tls_error='(null):(null):(null)', location='/etc/syslog-ng/conf.d/log-forwarding.conf:2:83'
syslog-ng[1354462]: [2020-02-17T20:03:59.809444] Error initializing message pipeline; plugin_name='syslog', location='/etc/syslog-ng/conf.d/log-forwarding.conf:2:28'
```

The config file contains:
```
destination d_syslog_tcp { syslog("<servername>" port(6514) transport("tls") tls(cert-file("/etc/pki/tls/certs/ca-bundle.crt") peer-verify(required-trusted)) ); };
log { source(s_sys); destination(d_syslog_tcp); };
```

**Comment by alltilla** [comment]
I think I got my head around the problem now, please correct me if I misunderstood something.

In the `network()` `tls()` block we have 3 options regarding keys and certs:
 1. `key-file()`: the key file necessary for the encryption
 2. `cert-file()`: the cert file necessary for authorizing ourselves at the peer
 3. `ca-dir()`: the directory, where we store the trusted certificates, and we will authorize the peer from this list

However, we can store the trusted certs in one bundled file ("/etc/pki/tls/certs/ca-bundle.crt" in our case), and we have no option to use it instead of `ca-dir()`. We have this option (`ca-file()`) at the `http()` driver, and it does not seem very complicated to implement into the `network()` driver as well.

**Comment by CRCinAU** [comment]
That's my understanding.... `ca-dir()` only seems to understand files that are named in that weird way by c_rehash. `cert-file()` only takes a certificate (not a possible chain of certificates, or a bundle).

Loading the trusted bundle shipped with the OS allows the client to validate a host exactly how a browser would for https - which compares the CN to the hostname provided, then validates the chain from the server + trusted bundle. In a lot of cases, this is usefule when encrypted is used in transit - but not required for authentication.

**Comment by faxm0dem** [comment]
I agree that if `ca-dir` is omitted, we should let the underlying library decide on which trust bundle to use (`/etc/pki/tls/certs/ca-bundle.crt` in many gnu/linux dists)

**Comment by alltilla** [comment]
@CRCinAU 

Can you build from source? I prepared a branch https://github.com/alltilla/syslog-ng/commits/network_tls_ca_file

Example config:
```
destination d_syslog_tcp { syslog("<servername>" port(6514) transport("tls") tls(ca-file("/etc/pki/tls/certs/ca-bundle.crt") peer-verify(required-trusted)) ); };
```

I managed to try it out in my environment and it works for me.

**Comment by CRCinAU** [comment]
Thanks for this - I haven't had a chance to build a package or test as yet - so it was still sitting in my inbox to action & test.

Thanks to those who beat me to it...
