### ISSUE TITLE
Forward integrity and confidentiality of logs

### ISSUE THREAD

**Issue by nbsd** [syslog-ng/syslog-ng#3118]
## Description of the problem

Logs processed by _syslog-ng_ are neither confidential nor integrity protected. The use of these logs for the purpose of security monitoring and forensic analysis in case of an incident is rather limited, as they may have been tampered with by an attacker trying to hide his trace.

## Proposed solution

An implementation providing forward integrity and confidentiality of logs using _syslog-ng_ was recently presented at the [FOSDEM 2020](https://fosdem.org/2020/schedule/event/security_secure_logging_with_syslog_ng/). This implementation should be merged into the _syslog-ng_ source tree so that all users of syslog-ng may add forward integrity and confidentiality to their logs in case this is needed or required.

## Alternatives

N/A

## Additional context

The implementation of the secure logging functionality providing forward integrity and confidentiality was branched off _syslog-ng_ at version 3.23.1. The development repository continued to track the master branch of _syslog-ng_. Tests have shown only one possible merge conflict in the RPM spec file. This is not relevant to the core functionality of _syslog-ng_ and might be resolved manually.

**Comment by furiel** [comment]
Fixed in #3121
