### ISSUE TITLE
hangs on boot due to a lack of entropy, system never boots, remote servers offline forever during update

### ISSUE THREAD

**Issue by nathanshearer** [syslog-ng/syslog-ng#3124]
# syslog-ng
## Version of syslog-ng
3.22.1 and 3.25.1 are both affected

## Platform
Gentoo, fully updated, with LTS Vanilla Sources kernel 4.4.213

## Debug bundle
Created

# Issue
## Failure
hangs system during boot due to a lack of entropy, system never boots
remote servers go permanently offline during reboot
why does a system logger even need high quality random data for logging??
For more inforamtion: https://forums.gentoo.org/viewtopic-t-1053732-start-0.html
I shouldn't have to modify my kernel to prevent syslog-ng from freezing forever

## Steps to reproduce
Install Gentoo
Install syslog-ng
reboot
press the keyboard a few times to generate entropy because syslog-ng is hanging the system bootup

## Configuration
Syslog-ng default configuration file for Gentoo Linux. No changes whatsoever from the default.

**Comment by bazsi** [comment]
By a cursory check it is openssl that tries to initialize its PRNG. Then I started up syslog-ng and I found getrandom() to be called from these locations:

- riemann initialization (through gnutls), 1 byte
- http initialization (through libcurl -> gnutls), 1 byte

I've also found one using strace, where syslog-ng tries to get 32 bytes, but that's not caught by a gdb breakpoint, it probably happens during openssl initialization.... Yup, with creative debugging I've now confirmed that OpenSSL's RAND_status() will try to open /dev/random, srandom and urandom as well as getrandom(). This is a pretty recent change in openssl.

syslog-ng has been doing this for a long time now:

```
  if (RAND_status() < 0 || getenv("RANDFILE"))
    {
      char rnd_file[256];

      RAND_file_name(rnd_file, sizeof(rnd_file));
      if (rnd_file[0])
        {
          RAND_load_file(rnd_file, -1);
          randfile_loaded = TRUE;
        }

      if (RAND_status() < 0)
        fprintf(stderr,
                "WARNING: a trusted random number source is not available, crypto operations will probably fail. Please set the RANDFILE environment variable.");
    }

```

The RAND_status() call is what causes blocking on /dev/random. We are calling that as there are quite a few call-sites which use random data and we want to ensure that random source is available in case it is needed.

**Comment by bazsi** [comment]
This code was added by this patch back in 2011:

```
commit 01b8e0994521454d2ff5f208038f4380fc1421c6
Author: Balazs Scheidler <bazsi@balabit.hu>
Date:   Wed Sep 21 11:58:34 2011 +0200

    crypto: autodetect the need to seed the PRNG
    
    This patch changes the crypto.c module to perform an autodetection whether
    the random number generator needs to be seeded.
    
    RAND_loadfile() is triggered if the environment variable RANDFILE is set, or
    when openssl itself is unable to detect how to seed the random
    number generator.
    
    This gets rid of the --seed command line option too (which is
    kept for compatibility for now).
    
    A warning is printed on stderr if everything fails.
    
    Signed-off-by: Balazs Scheidler <bazsi@balabit.hu>
```

**Comment by nathanshearer** [comment]
This bug is also related: https://bugs.gentoo.org/698590

**Comment by bazsi** [comment]
Hmm... I am not sure what's the best course of action here, syslog-ng calls RAND_status() to confirm we have sufficient randomness for SSL, but that might not be needed if a user is not using SSL(and other crypto) at all.

If we, however, delay this to the first actual user of SSL, we might allow the boot to continue but then syslog-ng will stuck, somewhat later, causing roughly the same effect (ok, it might only be a subset of the users, those that actually use SSL in their config).

hmm.. after a bit of reading my conclusion is this:

- we should always attempt to load the random file, regardless of the return value of RAND_status(), that saves us one RAND_status() call.
- if RAND_file_name() returns something, we'll trigger RAND_load_file() and RAND_write_file() for that filename.
- if we attempted to load the random file, we can call RAND_status() and that call should remain there. If this happens, we should even be more strict and instead of a warning, we should abort syslog-ng with an error message. 

- This can only happen if:
    1) someone already specified RANDFILE
    2) the specified seed file didn't have enough entropy
    3) and the system sources don't supply enough entropy.

- the happy path: 
  1) no RANDFILE (we don't even try), 
  2) RANDFILE is present and contains sufficient entropy, 
  3) there's a local random source.

What we will catch is that the user specified RANDFILE (e.g. he has shown interest in crypto related functionality) and we can't use it for some reason.

With this description this becomes a "good first issue".

**Comment by nathanshearer** [comment]
Another thing to consider, is using /dev/urandom instead of /dev/random can be good enough if cryptographically secure pseudorandom is good enough for the system logger. An advantage is there is much more data available at /dev/urandom and it won't block IO due to low entropy, but will still produce high quality random data.

**Comment by vatsal-encs** [comment]
Hi @bazsi,

I have looked into `crypto_init` function. I can understand that I need to remove first `RAND_status()` call.
But,  when 2nd `RAND_status()` call fails, how can I abort syslog-ng with an error message ?

**Comment by bazsi** [comment]
It's not syslog-ng that tries to read /dev/random, rather it is openssl, so
we can't do too much about it.

**Comment by bazsi** [comment]
On Thu, Mar 26, 2020, 06:13 Vatsal <notifications@github.com> wrote:

> Hi @bazsi <https://github.com/bazsi>,
>
> I have looked into crypto_init function. I can understand that I need to
> remove first RAND_status() call.
> But, when 2nd RAND_status() call fails, how can I abort syslog-ng with an
> error message ?
>
This is pretty early in the startup process, so we still have stderr to
print messages to.

If I remember correctly we dont have error handling in app_startup() so the
only way to exit the process is to actually call exit() or even abort()

This is pretty ugly, so I would look at how difficult it would be to
propagate an error back. But I am a bit afraid that it would be somewhat of
a chain reaction without too much gain.

Check if there are other cases during startup that cause syslog-ng to bail
out early and follow that example.

>

**Comment by Evanok** [comment]
Hello,

I am working on an embedded system (imx7 ARM) built with buildroot. I tried to use syslog-ng instead of old syslog package. It seems that I have the same problem than here.
I tried to have rngd or haveged to fix the issue but without success.

I also tried to disable all fancy features without more success. I only use basic feature : 
```
SYSLOG_NG_CONF_OPTS += --disable-geoip
SYSLOG_NG_CONF_OPTS += --disable-linux-caps
SYSLOG_NG_CONF_OPTS += --disable-python
SYSLOG_NG_CONF_OPTS += --disable-smtp
SYSLOG_NG_CONF_OPTS += --disable-json
SYSLOG_NG_CONF_OPTS += --disable-spoof-source
SYSLOG_NG_CONF_OPTS += --disable-http
SYSLOG_NG_CONF_OPTS += --disable-amqp
SYSLOG_NG_CONF_OPTS += --disable-systemd
SYSLOG_NG_CONF_OPTS += --disable-snmp-dest
```

I currently need between 45 and 120 seconds to init syslog...
My syslog-ng version : SYSLOG_NG_VERSION = **3.26.1**

My strace log :

```
020-04-07 11:54:10] 09:53:15 ioctl(0, TCGETS, {B115200 opost isig icanon echo ...}) = 0 <0.000138>
[2020-04-07 11:54:10] 09:53:15 ioctl(0, TIOCNOTTY)            = -1 ENOTTY (Inappropriate ioctl for device) <0.000106>
[2020-04-07 11:54:10] 09:53:15 setsid()                       = 140 <0.000093>
[2020-04-07 11:54:10] 09:53:15 ugetrlimit(RLIMIT_NOFILE, {rlim_cur=1024, rlim_max=4*1024}) = 0 <0.000086>
[2020-04-07 11:54:10] 09:53:15 setrlimit(RLIMIT_NOFILE, {rlim_cur=4*1024, rlim_max=4*1024}) = 0 <0.000095>
[2020-04-07 11:54:10] 09:53:15 pipe([3, 4])                   = 0 <0.000142>
[2020-04-07 11:54:10] 09:53:15 rt_sigprocmask(SIG_BLOCK, ~[RTMIN RT_1], [], 8) = 0 <0.000099>
[2020-04-07 11:54:10] 09:53:15 clone(child_stack=NULL, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x76f30068) = 141 <0.001405>
[2020-04-07 11:54:10] 09:53:15 rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0 <0.000124>
[2020-04-07 11:54:10] 09:53:15 close(4)                       = 0 <0.000096>
[2020-04-07 11:54:10] 09:53:15 read(3, 
[2020-04-07 11:54:49] 
[2020-04-07 11:54:49] 
[2020-04-07 11:54:49] 
[2020-04-07 11:54:50] 
[2020-04-07 11:54:50] 
[2020-04-07 11:55:00] random: nonblocking pool is initialized
[2020-04-07 11:55:01] "0\n", 6)              = 2 <50.634274>
[2020-04-07 11:55:01] 09:54:06 close(3)                       = 0 <0.000061>
[2020-04-07 11:55:01] 09:54:06 exit_group(0)                  = ?
[2020-04-07 11:55:01] 09:54:06 +++ exited with 0 +++
[2020-04-07 11:55:01] OK
[2020-04-07 11:55:01] OK
```

my very basic configuration : 

```
# cat /etc/syslog-ng.conf 
@version: 3.26

filter f_middleware {
    facility("local1");
};
template t_json_filetemplate {
    template("{\"date\":\"${ISODATE}\",${MESSAGE}\n");
};
source s_kernel {
        file("/proc/kmsg" program_override("kernel"));
};
source s_middleware {
        unix-stream("/dev/log");
};
destination d_kernel {
        file("/data/logs/kern.log");
};
destination d_middleware {
        file("/data/logs/dreem.log", template(t_json_filetemplate));
};
log {
        source(s_kernel);
        destination(d_kernel);
};
log {
        source(s_middleware);
        filter(f_middleware);
        destination(d_middleware);
};
```

Is there a workaround or a way to fix this ? Thank you !

**Comment by nathanshearer** [comment]
Is there some way the requirement for openssl can be removed or disabled by default for the basic local logging that is used on most systems? As it stands I can't have syslog-ng in my default runlevel because it blocks forever during bootup and results in offline systems during restarts. The actual log file at /var/log/messeges has no encrypted data or random numbers that even requires a strong random number generator.

**Comment by bazsi** [comment]
If you can recompile the source code, just remove the random initialization
from crypto_init(), e.g. the part that starts with RAND_status().

Or, create a file with 128 bytes of random data and specify its name using
the RANDFILE environment variable.

The latter should work workout having to recompile.
