### ISSUE TITLE
syslog-ng OSE 3.19 rpm check

### ISSUE THREAD

**Issue by phbfr** [syslog-ng/syslog-ng#3131]
## Description of the problem

Before to upgrade syslog-ng OSE from 3.7 to 3.19, i would like to check the RPM. But, 

rpm -K syslog-ng-3.19.1-3.el6.x86_64.rpm 
 gives output: 
RSA sha1 ((MD5) PGP) md5 PAS OK (MISSING KEYS: (MD5) PGP#5fbb93f1) 

And 
rpm -qi gpg-pubkey-0d137fce-55e842f0
 gives output of czanik gpg-pubkey but 3.7: 
Summary     : gpg(czanik_syslog-ng37epel6 (None) <czanik#syslog-ng37epel6@copr.fedorahosted.org>)

Is there other public keys to import, to check the 3.19 rpm before to upgrade from 3.7 ?

I'm trying to check :

libdbi-0.9.0-6.el6.x86_64.rpm
libmaxminddb-1.1.1-5.el6.x86_64.rpm
syslog-ng-3.19.1-3.el6.x86_64.rpm
syslog-ng-libdbi-3.19.1-3.el6.x86_64.rpm

which seems come from 
czanik-syslog-ng319epel6-epel-6.repo

Thanks in advance for your welcome help !

Philippe

**Comment by alltilla** [comment]
@czanik Hi Peter, can you give a little help here? Thank you very much!

**Comment by czanik** [comment]
I don't have an RHEL/CentOS 6 environment any more to test it, but looking at https://copr-be.cloud.fedoraproject.org/results/czanik/syslog-ng319epel6/ I see a file there called ```pubkey.gpg```

Let us know, if it resolved your problem!

**Comment by phbfr** [comment]
Above all thanks for your help. 

" rpm -K * " now gives output: 

libdbi-0.9.0-6.el6.x86_64.rpm: rsa sha1 (md5) pgp md5 OK
syslog-ng-3.19.1-3.el6.x86_64.rpm: rsa sha1 (md5) pgp md5 OK
syslog-ng-libdbi-3.19.1-3.el6.x86_64.rpm: rsa sha1 (md5) pgp md5 OK

Everything look good!

libmaxminddb-1.1.1-5.el6.x86_64.rpm: RSA sha1 ((MD5) PGP) md5 PAS OK (CLES MANQUANTES: (MD5) PGP#0608b895) 

libmaxminddb - a library for working with MaxMind DB files - appears to come from Fedora project distribution... I will see if i can bother someone else so ;-) 

THANKS for your mutual help!
PhBfr

**Comment by alltilla** [comment]
No problem :) May I close this issue, then?

**Comment by phbfr** [comment]
Yes, thanks a lot!
