### ISSUE TITLE
Failure on startup when using Loggly TLS configuration

### ISSUE THREAD

**Issue by nullus** [syslog-ng/syslog-ng#3148]
# syslog-ng
## Version of syslog-ng

syslog-ng 3 (3.25.1)
Config version: 3.25
Installer-Version: 3.25.1
Revision:
Compile-Date: Feb 22 2020 08:22:53
Module-Directory: /usr/local/lib/syslog-ng
Module-Path: /usr/local/lib/syslog-ng
Include-Path: /usr/local/share/syslog-ng/include
Available-Modules: json-plugin,appmodel,cef,syslogformat,add-contextual-data,timestamp,disk-buffer,afsocket,affile,afprog,afuser,csvparser,confgen,examples,system-source,linux-kmsg-format,basicfuncs,dbparser,cryptofuncs,afstomp,pseudofile,graphite,kvformat,map-value-pairs,snmptrapd-parser,stardate,tfgetent,tags-parser,xml,hook-commands,http
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: off
Enable-TCP-Wrapper: off
Enable-Linux-Caps: off
Enable-Systemd: off

## Platform

FreeBSD 12.1-RELEASE r354233 GENERIC

## Debug bundle
N/A

# Issue
## Failure
On startup:
```
Starting syslog_ng.
[2020-02-25T12:03:29.131954] tls() options specified for a transport that doesn't allow TLS encryption; transport='tcp'
[2020-02-25T12:03:29.132345] Error initializing message pipeline; plugin_name='network', location='#buffer:4:3'
/usr/local/etc/rc.d/syslog-ng: WARNING: failed to start syslog_ng
```

## Steps to reproduce
Use the example supplied in Loggly SCL for TLS configuration, restart syslog-ng (see below)

## Configuration
```
@version:3.25
@include "scl.conf"

options { chain_hostnames(off); flush_lines(0); threaded(yes); };

source src { system();
             udp(); internal(); };

log {
       source(src);
       destination {
                loggly(token("USER-TOKEN-AS-PROVIDED-BY-LOGGLY") port(6514)
                       tls(peer-verify(required-trusted) ca-dir('/etc/ssl/certs'))
                );
       };
};
```

**Comment by MrAnno** [comment]
Fixed in #3149 

Usage:
```
destination {
  loggly(token("USER-TOKEN-AS-PROVIDED-BY-LOGGLY") port(6514) transport(tls)
    tls(peer-verify(required-trusted) ca-dir('/etc/ssl/certs'))
  );
};
```

Thanks for the fix! :+1:
