### ISSUE TITLE
some logs are not seen by syslog-ng

### ISSUE THREAD

**Issue by shinji7800** [syslog-ng/syslog-ng#3168]
Hello, 

I came here because I desperate …

I have trouble to debug a situation.

I tried to log two new servers on my syslog server but I don’t see syslog from this two new equipments logged into file.

So I try a tcpdump to verify my networks and check if packet arrived to my server. I see it on destination udp port 514.

I activated debug/verbose/trace mode on syslog-ng to see incoming logs and if there are a filtering issue ... but I don’t see my logs trying to be processed by syslog-ng (no line Incoming log entry; for my new equipement)

I restarted my server my configuration is pretty simple : 

source s_log { 
udp (ip("192.168.1.1"), port(514));
};

destination d_local{ 
file("/log/SRV/$YEAR-$MONTH-$DAY/$HOST");
};

log{ 
source(s_log);
destination(d_local);
};

and for my old hosts on same subnet there no issues … 

It is like my packet/logging messages are lost between layer 3/4 and 7.

Sorry if it is not clear enough. Forgive my approximate English I am French.

Let me know and try to explain better if needed 
Best regards

**Comment by czanik** [comment]
There are at least two possible causes:

 * firewall (packet filter)
 * SELinux

Try to disable them, and if it works, create the necessary rules before enabling them again.

**Comment by shinji7800** [comment]
Thanks your reply!

Okay I will check this two leads

I am pretty sure I don’t have firewall but I am not familiar with SELinux so maybe :/

I let you know 

Best regards

**Comment by shinji7800** [comment]
Hello ! 

SELinux is disable and iptables was enable but with no specific rules (everything is a Policy ACCEPT). 

I disable iptable for testing anyway … but logs still missing on Syslog-ng 

it is confusing ...

**Comment by furiel** [comment]
Does the connectivity work within the server? If you try to send a message from the same host to 192.168.1.1, do the messages arrive?

If you replace syslog-ng with another application (socat, netcat, etc), do the messages arrive?

Do you use some kind of cloud/virtualization environment? They usually add their own extra layer of firewall configuration that can be changed from a webui, that is independent from the host's iptables rules.

**Comment by shinji7800** [comment]
I believe  finding a lead : rp_filter …

I change value 1 to 2 (strict to loose)

it seems better ...

**Comment by bazsi** [comment]
rp_filter should only matter if the host has multiple IP interfaces and the
packet is coming from the "wrong" interface considering its source IP.

E.g. if 10.0.0.0/8 is routed to eth1 and a packet with the source IP
10.0.0.1 is coming through eth0, then rp_filter will drop it.

**Comment by furiel** [comment]
If I understand correctly, you managed to figure it out the problem. I am closing this. In case you still have problem, and think it is a bug in syslog-ng, feel free to reopen.
