### ISSUE TITLE
disable multi-line-timeout for logpipe source (temporarily)

### ISSUE THREAD

**Issue by furiel** [syslog-ng/syslog-ng#3178]
As it turns out: https://github.com/syslog-ng/syslog-ng/issues/3170
multi line timeout do not work with logpipe source, however grammar accepts it.

It is silently not working. Lets remove the option temporarily, until multi line timeout is implemented for logpipe sources.

```
source s_text {
    pipe("/tmp/pipe" owner('user') multi-line-mode(indented) multi-line-timeout(2) flags(no-parse));
};
```

Should result in a parse error.

**Comment by vivinperis** [comment]
How do I get started with this?

**Comment by alltilla** [comment]
The `syslog-ng` configuration language is described in `...-grammar.ym` files in YACC syntax.

The `pipe()` related rules can be found at `modules/affile/affile-grammar.ym`, and every `...-grammar.ym` file can use definitions from the `lib/cfg-grammar.y` file, as well.

Hint: Look for `KW_PIPE`.
