### ISSUE TITLE
mongodb: cmake find_package() runs regardless -DENABLE_MONGODB=no

### ISSUE THREAD

**Issue by alltilla** [syslog-ng/syslog-ng#3184]
# syslog-ng
## Version of syslog-ng
Compiling from source (master: 531d70bfbcf19a97a5278f324d141386d568ce7f)

## Platform
 * `docker` image: `balabit/syslog-ng-devshell:latest`
 * `docker` runs on `ubuntu-xenial` or `ubuntu-bionic`

# Issue
## Failure
Even though I set `-DENABLE_MONGODB=no` to cmake, `find_package(libmongoc-1.0)` still runs, which is a problem on `ubuntu-bionic`, as the `libbson` (or `libmongoc`) package is bugged there.

I am getting the following error:
```
CMake Error at /usr/lib/x86_64-linux-gnu/cmake/libbson-1.0/libbson-1.0-config.cmake:28 (message):
  File or directory /usr/lib/include/libbson-1.0 referenced by variable
  BSON_INCLUDE_DIRS does not exist !
Call Stack (most recent call first):
  /usr/lib/x86_64-linux-gnu/cmake/libbson-1.0/libbson-1.0-config.cmake:32 (set_and_check)
  /usr/lib/x86_64-linux-gnu/cmake/libmongoc-1.0/libmongoc-1.0-config.cmake:20 (find_package)
  modules/afmongodb/CMakeLists.txt:1 (find_package)


-- Configuring incomplete, errors occurred!
See also "/syslog-ng/build/CMakeFiles/CMakeOutput.log".
See also "/syslog-ng/build/CMakeFiles/CMakeError.log".
```
## Steps to reproduce
```
$ docker pull balabit/syslog-ng-devshell:latest
$ docker run -it balabit/syslog-ng-devshell:latest bash

# git clone https://github.com/syslog-ng/syslog-ng.git
# cd syslog-ng/
# mkdir build
# cd build
# cmake -DCMAKE_INSTALL_PREFIX=$HOME/install/syslog-ng -DENABLE_MONGODB=no ..
```

## Input and output logs
[cmake.log](https://github.com/syslog-ng/syslog-ng/files/4359377/cmake.log)
[CMakeOutput.log](https://github.com/syslog-ng/syslog-ng/files/4359379/CMakeOutput.log)
[CMakeError.log](https://github.com/syslog-ng/syslog-ng/files/4359380/CMakeError.log)

**Comment by lbudai** [comment]
@alltilla : yes, it is a known issue :

https://github.com/syslog-ng/syslog-ng/pull/3109

**Comment by alltilla** [comment]
Now it can be disabled with `-DENABLE_MONGODB=OFF`.
