### ISSUE TITLE
SDATA key > 32 characters is malformed

### ISSUE THREAD

**Issue by nswalters** [syslog-ng/syslog-ng#3197]
# syslog-ng
## Version of syslog-ng
root@system-test:/tmp # syslog-ng --version
syslog-ng 3 (3.25.1)
Config version: 3.25
Installer-Version: 3.25.1
Revision: 
Compile-Date: Mar 11 2020 05:16:25
Module-Directory: /usr/local/lib/syslog-ng
Module-Path: /usr/local/lib/syslog-ng
Include-Path: /usr/local/share/syslog-ng/include
Available-Modules: json-plugin,appmodel,cef,syslogformat,add-contextual-data,timestamp,disk-buffer,afsocket,affile,afprog,afuser,csv
parser,confgen,examples,system-source,linux-kmsg-format,basicfuncs,dbparser,cryptofuncs,afstomp,pseudofile,graphite,kvformat,map-val
ue-pairs,snmptrapd-parser,stardate,tfgetent,tags-parser,xml,hook-commands,http
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: off
Enable-TCP-Wrapper: off
Enable-Linux-Caps: off
Enable-Systemd: off

## Platform
root@system-test:/tmp # uname -a
FreeBSD system-test 11.2-RELEASE-p14 FreeBSD 11.2-RELEASE-p14 #0: Mon Aug 19 22:38:50 UTC 2019     root@amd64-builder.daemonology.net:
/usr/obj/usr/src/sys/GENERIC  amd64

## Debug bundle
Not Available

# Issue
## Failure
Syslog-ng mangles SDATA PARAM-NAME when the PARAM-NAME is longer than 32 characters.  If I only change the PARAM-NAME to be shorter than 32 chars (leaving the JSON key the same at longer than 32 chars) parsing is completed successfully.

## Steps to reproduce
Send SDATA PARAM with PARAM-NAME longer than 32 characters.

## Configuration
**syslog-ng.conf**
```
@version: 3.25

source s_json_file {
    file("/tmp/full_log.txt" flags(syslog-protocol));
};

destination d_file {
    file("/tmp/in-out.log" flags(syslog-protocol));
};

parser p_json {
    json-parser(prefix(".event"));
};

log {
    source(s_json_file);
    parser(p_json);
    # Write messages in syslog protocol
    destination(d_file); 
};
```

## Input and output logs (if possible)

**Input File with Long PARAM-NAME**
```
<13>1 2020-03-02T05:30:11.293419-06:00 HOSTNAME program - - [NXLOG@14506 EventReceivedTime="2020-03-02 05:30:11" Really_Long_Field_N
ame_Right_here="longKey"] {"EventReceivedTime"="2020-03-02 -5:30:11", "Really_Long_Field_Name_Right_here"="longKey"}
```

**Command Ran and Error Received**
```
root@system-test:/tmp # syslog-ng -Fdev -c /usr/local/etc/syslog-ng.conf -R /tmp/syslog-ng.persist

[...]

[2020-03-25T14:12:18.818010] syslog-ng starting up; version='3.25.1'
[2020-03-25T14:12:18.818218] Running application hooks; hook='2'
[2020-03-25T14:12:18.818659] Incoming log entry; line='<13>1 2020-03-02T05:30:11.293419-06:00 HOSTNAME program - - [NXLOG@14506 EventReceivedTime="2020-03-02 05:30:11" Really_Long_Field_Name_Right_here="longKey"] {"EventReceivedTime"="2020-03-02 -5:30:11", "Really_Long_Field_Name_Right_here"="longKey"}'
[2020-03-25T14:12:18.818981] json-parser(): failed to parse JSON payload; input='Error processing log message: <13>1 2020-03-02T05:30:11.293419-06:00 HOSTNAME program - - [NXLOG@14506 EventReceivedTime="2020-03-02 05:30:11" Really_Long_Field_Name_Right_he>@<re="longKey"] {"EventReceivedTime"="2020-03-02 -5:30:11", "Really_Long_Field_Name_Right_here"="longKey"}', json_error='unexpected character'
```

---

**Input File with PARM-NAME Less Than 32 Chars**
```
<13>1 2020-03-02T05:30:11.293419-06:00 HOSTNAME program - - [NXLOG@14506 EventReceivedTime="2020-03-02 05:30:11" Really_Long="longKe
y"] {"EventReceivedTime":"2020-03-02 -5:30:11", "Really_Long_Field_Name_Right_here":"longKey"}
```

**Command Ran and Debug Output Showing No Errors**
```
root@system-test:/tmp # syslog-ng -Fdev -c /usr/local/etc/syslog-ng.conf -R /tmp/syslog-ng.persist

[...]

[2020-03-25T14:34:06.292977] syslog-ng starting up; version='3.25.1'
[2020-03-25T14:34:06.293079] Running application hooks; hook='2'
[2020-03-25T14:34:06.293425] Incoming log entry; line='<13>1 2020-03-02T05:30:11.293419-06:00 HOSTNAME program - - [NXLOG@14506 EventReceivedTime="2020-03-02 05:30:11" Really_Long="longKey"] {"EventReceivedTime":"2020-03-02 -5:30:11", "Really_Long_Field_Name_Right_here":"longKey"}'
[2020-03-25T14:34:06.293981] Initializing destination file writer; template='/tmp/in-out.log', filename='/tmp/in-out.log'
[2020-03-25T14:34:06.294262] Outgoing message; message='<13>1 2020-03-02T05:30:11-06:00 system-test program - - [NXLOG@14506 EventReceivedTime="2020-03-02 05:30:11" Really_Long="longKey"][meta sequenceId="1"] {"EventReceivedTime":"2020-03-02 -5:30:11", "Really_Long_Field_Name_Right_here":"longKey"}\x0a'
```

**Output File with PARAM-NAME less than 32 Chars**
```
root@system-test:/tmp # cat in-out.log 
<13>1 2020-03-02T05:30:11-06:00 system-test program - - [NXLOG@14506 EventReceivedTime="2020-03-02 05:30:11" Really_Long="longKey"][me
ta sequenceId="1"] {"EventReceivedTime":"2020-03-02 -5:30:11", "Really_Long_Field_Name_Right_here":"longKey"}
```

**Comment by bazsi** [comment]
Iirc there's a hardcoded limit on sdata field sizes, but I think they can
easily be increased.

**Comment by furiel** [comment]
I think the reason for the 32 limit is because of the rfc: https://tools.ietf.org/html/rfc5424#page-8

```
      STRUCTURED-DATA = NILVALUE / 1*SD-ELEMENT
      SD-ELEMENT      = "[" SD-ID *(SP SD-PARAM) "]"
      [...]
      SD-ID           = SD-NAME
      [...]
      SD-NAME         = 1*32PRINTUSASCII
                        ; except '=', SP, ']', %d34 (")
```

**Comment by nswalters** [comment]
Thanks folks.  Looks like syslog-ng is actually following the RFC then... not sure how I missed that when looking over the RFC, but thanks for pointing that out @furiel!

In my case, this long field is being parsed from a JSON output log source using an agent that then sends it over RFC5424 syslog.  Seems that agent is not properly handling those fields in the SDATA.  I can address it at that level then.

However, for my knowledge and understanding, is it possible at all to adjust on the syslog-ng side of things though, through a rewrite or something?  Given that it's a standard conflict, I'm assuming it's not possible to parse that and rewrite it on syslog-ng's side (or just truncate), but figured I'd ask the subject matter experts. :)

**Comment by bazsi** [comment]
I think it would make sense to increase those limits, this is not the first
time I see this issue.

And sometimes we ourselves can generate longer IDs.

Bazsi

**Comment by jszigetvari** [comment]
This issue has also sparked interests from the PE side, as a customer has also complained about this.

IMHO it's a difficult question whether we should break the RFC or not. Both has its ups and downs.
Another idea was whether we should make this new behavior configurable, so that longer keys would be allowed in SDATA key-value pairs if a config option is enabled.
That possibility would also be worth exploring.

**Comment by furiel** [comment]
There is a little subtley in the RFC: https://tools.ietf.org/html/rfc5424#section-6.3

```
A collector MAY ignore malformed STRUCTURED-DATA elements.  A relay
   MUST forward malformed STRUCTURED-DATA without any alteration.
```

What is a collector and what is a relay? Syslog-ng is a collector or a relay? 

I am just guessing: from usecase perspective, most of the syslog-ng destinations send the message elsewhere. Maybe except for the file destination, I have kind of relay-ish feeling for typical syslog-ng way of life.

What the rfc is probably meant by relay is some kind of proxy/unaltered forwarding/maybe loadbalancing functinality. So with mathematical precision, a `flags(no-parse)` and unaltered forward would be only a `MUST` from syslog-ng perspective.

Still, me feels this is a gray area. With a little liberty in interpreting the RFC, a size increase behind optionality sound fine for me.

**Comment by bazsi** [comment]
I don't think we need the optionality of this or maybe create a "strict"
flag that would encapsulate all such deviations. But given everyone would
rather get the data in the first place. You can't do too much about an
unconforming implementation.

**Comment by jszigetvari** [comment]
@bazsi The overall strict flag seems like a good idea.
The downside of it is that over time many more similar things will depend on it. But there are cases when syslog-ng has to send to other logging software that implements the RFC in a more strict manner, and in that case sticking to the standard may be the only viable way.

On the other hand it should be thoroughly documented (maybe the description of the strict flag would be the best place for it) where we relax the constraints put in place by the RFC.
Also, it would be worth another discussion whether it should be a global-only flag, or whether it should be overridable on a per destination level.
Imagine a use-case where a server sends logs over syslog() to a SIEM that requires stict compliance with the RFC, and also to other syslog-ng servers which already implement the "relaxations" of the standard.

**Comment by bazsi** [comment]
This is a source side flag, e.g. weather we accept such data. I dont think
we can do much on the destination side.

Truncating the field name in case it's longer does not seem to be a very
good idea to me.

**Comment by jszigetvari** [comment]
Ok, it seems that I have misunderstood some things.
Upon re-checking the defails, it turned out that solving this problem on the source side will solve the PE customer's use-case as well.

It seems that on the destination side we have no safeguards in place to prevent sending out SDATA keys longer than the allowed length. (But I don't want that to change.)
