### ISSUE TITLE
secure logging should be a deb package of its own

### ISSUE THREAD

**Issue by bazsi** [syslog-ng/syslog-ng#3202]
Right now libsecure-logging.so is installed into the core package and I would rather see it as a separate package.

**Comment by furiel** [comment]
Why is it better to move it into it's own module? 

Until now, the thumb rule was every module that has no external dependency, was put into the core module. Except the scl's (but that exception has it's own reason).

I have no particular argument for keeping it in core, though. I am just interested in the reasons.

**Comment by bazsi** [comment]
Two reasons:

1) I think this is complex enough with command line tools et al

2) I dont consider it a core use-case for syslog-ng that would be needed by
most installations or that we want to deploy with new installations.

**Comment by furiel** [comment]
Sounds good to me.
