### ISSUE TITLE
Add values(key1 => value1, ...) support for example-msg-generator

### ISSUE THREAD

**Issue by furiel** [syslog-ng/syslog-ng#3215]
`example-msg-generator` generates a message from template, which is very useful, when someone wants to build their config iteratively, with trial and error.

For now, only the message part can be specified by the `example-msg-generator`. If I want to specify the `program` field for example, I need to add an extra rewrite rule after `example-msg-generator` to set it.

It would be nice if these assignments could be specified inside the `example-msg-generator`. The list of name-value pairs could be specified with a new `values` option, using the arrow syntax. The value part of the name-value pairs need to be evaluated as templates.

For example
```
@version: 3.26
log {
  source { example-msg-generator(template("message part")
                                 num(1)
                                 values("PROGRAM" => "program-name"
                                        "current-second" => "$C_SEC"
                                        "quick-maths" => "2+2-1=$(- $(+ 2 2) 1)"
                                );
         };
  destination { file(/dev/stdout template("$(format-json --scope all-nv-pairs)\n")); };
};
```

**Comment by vivinperis** [comment]
I would like to try this out. Can you please help me get started

**Comment by furiel** [comment]
You can look for `LL_ARROW` in the code for examples that already use arrow syntax.
For setting things in message, you can check `log_msg_set_value_by_name` invocations. The template evaluation can be done in similar fashion as it is done for the message part in the `example-msg-generator`:
 https://github.com/syslog-ng/syslog-ng/blob/627e585d1e3c3afcc000b218612ea24d0131da51/modules/examples/sources/msg-generator/msg-generator-source.c#L108
