### ISSUE TITLE
Develop own JDBC destination

### ISSUE THREAD

**Issue by Wernfried** [syslog-ng/syslog-ng#3217]
I consider to write my own custom destination in Java/JDBC. However my Java skills are very limited, so mainly I would copy/paste from https://github.com/hackyourlife/syslog-ng-jdbc

I have one major question: Does syslog-ng starts a new Java process for every message (i.e. opens a new JDBC connection to database) or is there only one Java process/class initialized when syslog-ng starts and messages are sent to this single process?

Kind Regards

**Comment by lbudai** [comment]
* syslog-ng starts only one JVM instance
 * from the message processing pipeline point of view: the lifecycle of the Java object (`TextLogDestination`) is bound to standard syslog-ng `LogPipe` instances 
(`LogPipe` nodes and the connection between them forms the log message processing pipeline/graph; when a message is read by a source pipe, it forwards the message to the next hop; until configuration is not changed and reloaded, the graph remain the same, so the messages are received by the same object, but don't forget: you can setup several destination in a single config - in that case you still have a single JVM instance that runs multiple instances of the JDBCDestinationDriver)

(_nb.:_ The referred destination is not developed by the syslog-ng team, and as I see, the author did not provide license - so if I were you, I'd contact to the developer before copy-pasting the code.)
