### ISSUE TITLE
Issue with escaped value sperators

### ISSUE THREAD

**Issue by rfaircloth-splunk** [syslog-ng/syslog-ng#3218]
# syslog-ng
## Version of syslog-ng
3.26.1

## Platform
RHEL 8

## Steps to reproduce

Given the following message:

<189> Apr  1 15:35:02 chpt-foo time=1585690683|hostname=xxxx-fwlog1|severity=Medium|product=Firewall|action=Drop|ifdir=inbound|ifname=eth1|loguid={0x0,0x0,0x0,0x0}|origin=1.2.2.3|originsicname=CN\=brtdcpl-xxx.xxx.net,O\=xxx-PCN.xxx.net.burmak|sequencenum=64|time=1585690683|version=5|dst=1.2.3.4|inspection_category=anomaly|foo=bar bat mark|subproduct=bat|thing=value

originsicname and fields following are not correctly parsed into kv pairs when the value separator appears inside the value but before the field separator

## Configuration
        parser {
            kv-parser(prefix(".kv.") pair-separator("|") template("${MSGHDR} ${MSG}"));
            date-parser-nofilter(format("%s") template("${.kv.time}"));
        };

**Comment by furiel** [comment]
Printing the parsed values I receive:

```
{
  "version": "5",
  "time": "1585690683",
  "thing": "value",
  "subproduct": "bat",
  "severity": "Medium",
  "sequencenum": "64",
  "product": "Firewall",
  "originsicname": "CN=brtdcpl-xxx.xxx.net,O=xxx-PCN.xxx.net.burmak",
  "origin": "1.2.2.3",
  "loguid": "{0x0,0x0,0x0,0x0}",
  "inspection_category": "anomaly",
  "ifname": "eth1",
  "ifdir": "inbound",
  "hostname": "xxxx-fwlog1",
  "foo": "bar bat mark",
  "dst": "1.2.3.4",
  "action": "Drop"
}
```

These values look good to me. What is that you receive, and what is that you expect?

**Comment by rfaircloth-splunk** [comment]
Found the error on my side it was subtle closing
