### ISSUE TITLE
Add support for http/https proxy

### ISSUE THREAD

**Issue by rfaircloth-splunk** [syslog-ng/syslog-ng#3232]
## Description of the problem
In newer deployments, there is resistance to the use of HTTP destination using a firewall rule. Adoption would be easier if an explicit proxy was supported

## Proposed solution
Enhance the configuration of syslog-ng to pass proxy option to the libcurl component

**Comment by furiel** [comment]
As a workaround:

syslog-ng honors the proxy settings from environment variables, as it is explained in libcurl:
https://curl.haxx.se/libcurl/c/CURLOPT_PROXY.html

Just make sure you use lowercase `http_proxy` and `https_proxy`, and use `http_proxy` for http, and `https_proxy` for https. It does not make smart detection as many linux cli commands.

**Comment by vatsal-encs** [comment]
@furiel : I want to work on this issue. Can you give me a brief idea about it?

**Comment by furiel** [comment]
Unless I am overlooking something, we just need a new grammar option `proxy` in the http destination, that will store the proxy address, and apply the proxy settings in
https://github.com/syslog-ng/syslog-ng/blob/bbee1016bbd488259b71fa0b269e721c532bc2ec/modules/http/http-worker.c#L104
where the other static options are applied.

To set a proxy:
https://curl.haxx.se/libcurl/c/CURLOPT_PROXY.html

According to the documentation, users can set a http proxy for https connections and vice versa. I suppose in that case no proxying happens, and it can be considered a configuration problem. In that case, let's emit a warning.
