### ISSUE TITLE
SysLog-NG helm chart

### ISSUE THREAD

**Issue by marcoboffi** [syslog-ng/syslog-ng#3267]
Question: is available an helm chart to deploy syslog-ng docker version inside k8s?
If not can you open a PR?

**Comment by Kokan** [comment]
Probably not, not in syslog repo nor in helm/charts. Maybe somebody does have their own somewhere...

> If not can you open a PR?

Could you please specific? Do you want the syslog-ng maintainers to open a PR introducing a helm chart for syslog-ng in https://github.com/helm/charts ?

As far as I am aware that is not on the near future plan. But anybody can open such a PR.
I have had some experience with helm, so if somebody picks up this task feel free to reach out.

**Comment by MrAnno** [comment]
A Helm chart is now available in the syslog-ng-docker repository:
https://github.com/balabit/syslog-ng-docker/tree/master/syslog-ng-helm-chart

**Comment by eumel8** [comment]
For Google: The Helm Chart is now here: https://github.com/syslog-ng/syslog-ng/tree/master/contrib/syslog-ng-helm-chart

**Comment by bazsi** [comment]
@eumel8 can you create a post in the GitHub discussion board about this? Hopefully that's even easier to find. Thanks

**Comment by MrAnno** [comment]
#3979 might be also a good candidate.

**Comment by eumel8** [comment]
Hi @bazsi, @MrAnno ,

would love to see this Helm chart in an extra repo in your organization, so it's faster to download as this whole repo here. 
Github Actions provides also the possibility to package and store the chart as OCI in Github registry, like here: https://github.com/marketplace/actions/package-helm-ghcr
