### ISSUE TITLE
FreeBSD 11 - tcp/ip-protocol(6) denies host connecting via ipv4

### ISSUE THREAD

**Issue by cwollett-niksun** [syslog-ng/syslog-ng#3276]
# syslog-ng
## Version of syslog-ng

/usr/local/sbin/syslog-ng -V
syslog-ng 3 (3.26.1)
Config version: 3.22
Installer-Version: 3.26.1
Revision:
Compile-Date: May  3 2020 05:52:40
Module-Directory: /usr/local/lib/syslog-ng
Module-Path: /usr/local/lib/syslog-ng
Include-Path: /usr/local/share/syslog-ng/include
Available-Modules: appmodel,azure-auth-header,basicfuncs,cryptofuncs,dbparser,afstomp,pseudofile,graphite,afuser,csvparser,linux-kmsg-format,http,syslogformat,add-contextual-data,cef,timestamp,confgen,examples,system-source,json-plugin,kvformat,map-value-pairs,snmptrapd-parser,stardate,tfgetent,tags-parser,xml,hook-commands,disk-buffer,afsocket,affile,afprog
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: off
Enable-TCP-Wrapper: off
Enable-Linux-Caps: off
Enable-Systemd: off

## Platform
FreeBSD 11.3 amd64

## Debug bundle

# Issue
## Steps to reproduce

Documentation for ip-protocol (https://www.syslog-ng.com/technical-documents/doc/syslog-ng-open-source-edition/3.25/administration-guide/ip-protocol) states "if you want to have receive messages on an IP-address/port pair using both IPv4 and IPv6, create a source that uses the ip-protocol(6)."

Syslog-ng accepts the below config and listens on tcp6/514:

sockstat -l | grep 514
root     syslog-ng  8464  17 tcp6   *:514                 *:*

Connecting host's connection, however, is refused:

syslog-ng[549]: Syslog connection failed; fd='17', server='AF_INET(10.70.143.42:514)', error='Connection refused (61)', time_reopen='60'

Changing ip-protocol(6) to ip-protocol(4):

sockstat -l | grep 514
root     syslog-ng  8636  17 tcp4   *:514                 *:*

Connecting host's connection now succeeds:

syslog-ng[549]: Syslog connection established; fd='17', server='AF_INET(10.70.143.42:514)', local='AF_INET(0.0.0.0:0)'

I've confirmed this to be the case from versions 3.22 through 3.26 on FreeBSD.  This is not the case on similar syslog-ng versions on RHEL 7.2 (ip-protocol(6) behavior is consistent with documentation for ipv4).

## Configuration

@version:3.25

options { chain_hostnames(off); flush_lines(100); log_fifo_size(5000); };

destination dst { unix-stream("/tmp/.socket"); };
source src { network(transport("tcp") port(514) ip-protocol(6) flags(no-parse)); };
log { source(src); destination(dst); flags(flow-control);};

**Comment by Kokan** [comment]
Is it possible that on RHEL 7.2 (or any linux) it just works due to `sysctl net.ipv6.bindv6only -> 0` let you use IPV4 mapped IPV6 ?

**Comment by cwollett-niksun** [comment]
Ahh, I was not aware.  Thank you, that appears to resolve my issue:

sockstat -l | grep 514
root     syslog-ng  2056  19 tcp46  *:514                 *:*

syslog-ng[549]: Syslog connection established; fd='25', server='AF_INET(10.70.143.42:514)', local='AF_INET(0.0.0.0:0)'
