### ISSUE TITLE
secure-logging module errors on 32-bit architectures

### ISSUE THREAD

**Issue by qboosh** [syslog-ng/syslog-ng#3289]
# syslog-ng
## Version of syslog-ng
syslog-ng 3.27.1 and some earlier versions

## Platform
Linux i686 (and many other 32-bit)

# Issue
## Failure
Test suite fails in secure-logging module:
FAIL: modules/secure-logging/tests/test_secure_logging
(when comparing first encoded-decoded message, even timestamps differ - the decoded one is 0)

It's caused by mixing guint64 and gsize/size_t types (and pointers to them), which differ on ILP32 architectures (gsize/size_t is 32-bit).

Fixing all compiler warnings in secure-logging module also fixes this test.
Proposed patch is attached.
[syslog-ng-types.patch.gz](https://github.com/syslog-ng/syslog-ng/files/4607496/syslog-ng-types.patch.gz)

**Comment by Kokan** [comment]
@qboosh thanks for the report and patch.
@nbsd could you please check this out ?

**Comment by nbsd** [comment]
Thanks for providing the patch. The changes are included in PR #3284 and will become available after the merge.
