### ISSUE TITLE
Implement journal namespaces

### ISSUE THREAD

**Issue by bjoe2k4** [syslog-ng/syslog-ng#3296]
## Description of the problem
In systemd v245 the concept of namespaces for the system journal was introduced. Journal namespaces are a convenient way of grouping unrelated services. (Merged pull: https://github.com/systemd/systemd/pull/14178)

According to @MrAnno on the #syslog-ng channel freenode IRC, there is currently no convenient way to get these namespaced journal messages into syslog-ng in the same sane and safe way it currently works for the default namespace via `systemd-journal()`, which calls `sd_journal_open()` with the flag `SD_JOURNAL_LOCAL_ONLY` from systemd. For namespaces a new function `sd_journal_open_namespace()` was introduced, which has all the functionality of `sd_journal_open()`, but accepts a `namespace` parameter and two additional valid flags `SD_JOURNAL_ALL_NAMESPACES` and `SD_JOURNAL_INCLUDE_DEFAULT_NAMESPACE`. 

```c
_public_ int sd_journal_open_namespace(sd_journal **ret, const char *namespace, int flags)
```

The original `sd_journal_open()` function is actually just a wrapper:

```c
_public_ int sd_journal_open(sd_journal **ret, int flags) {
        return sd_journal_open_namespace(ret, NULL, flags);
}
```

To query the journal from the console, there are now four ways.
1. just `journalctl` uses `sd_journal_open()` (actually `sd_journal_open_namespace()` with namespace NULL) and flags `SD_JOURNAL_LOCAL_ONLY`, so this is what syslog-ng currently does as well, but via the journal API.
2. `journalctl --namespace=*` uses `sd_journal_open_namespace()` with flags `SD_JOURNAL_ALL_NAMESPACES` and  `SD_JOURNAL_LOCAL_ONLY`
3. `journalctl --namespace=foo` uses `sd_journal_open_namespace()` with namespace `foo` and flags  `SD_JOURNAL_LOCAL_ONLY`
4. `journalctl --namespace=+foo` uses `sd_journal_open_namespace()` with namespace `foo` `SD_JOURNAL_INCLUDE_DEFAULT_NAMESPACE` and `SD_JOURNAL_LOCAL_ONLY`

While way 4 is probably good for debugging, it seems less useful in the syslog-ng context to me.

## Proposed solution

Introduce an additional option `all_namespaces()` to `systemd-journal()`, which sets the additional flag `SD_JOURNAL_ALL_NAMESPACES`. The separation of namespaces would be up to the user based on filters on journal fields. This seems to be the most minimal implementation to make syslog-ng fully namespace aware, but syslog-ng will have to parse _all_ incoming journal messages, which would generate some overhead, if only one namespace is of interest.

Given that systemd v245 is already widely deployed, at least for more up-to-date distros, this would be the preferred solution to make syslog-ng namespace aware ASAP (maybe already in syslog-ng 3.28.1).

## Alternatives
Currently `systemd-journal()` may only be specified once in the config. With this limitation an additional option `namespace("foo")` is less useful.
Therefore a new source `systemd-journal-namespace()` needs to be introduced which has all the options of `systemd-journal()` but accepts a `namespace("foo")` option. Also allow this source to be specified multiple times in the config. Seems more efficient, but needs more work for the implementation.

**Comment by MrAnno** [comment]
@bjoe2k4 Thank you for the very detailed and professional feature request! :+1:

**Comment by bjoe2k4** [comment]
Sad to see 3.28.1 happen without this rather simple feature suggestion. While I realize that 3.28.1 was probably too ambitious, I am starting to get my hopes up for 3.29.1  👍
