### ISSUE TITLE
Does "syslog-ng-ctl reopen" also reopen sql destination?

### ISSUE THREAD

**Issue by Wernfried** [syslog-ng/syslog-ng#3317]
When you execute `syslog-ng-ctl reopen` then syslog-ng runs Re-open of log destination files

Does it only apply for destination "file()" or also for "sql() - type(sqlite3)"?
I ask this question because sqlite3 is also file based (and other destination might be also file based).

Kind Regards
Wernfried

**Comment by MrAnno** [comment]
Hi @Wernfried,

Currently, only `file()` destinations support the reopen hook.

In case of SQL destinations, the connection (or the file when using SQLite) can be reopened by reloading syslog-ng (`syslog-ng-ctl reload`).

**Comment by Wernfried** [comment]
Thank you for clarification.
Wernfried
