### ISSUE TITLE
Question: how to put NILVALUE into transmitted timestamp

### ISSUE THREAD

**Issue by shyrodgau** [syslog-ng/syslog-ng#3318]
My system does not have a buffered clock. So until some synchronization the local time runs up from Jan 1 1970. The RFC 5424 specifies in Section 6

`TIMESTAMP       = NILVALUE / FULL-DATE "T" FULL-TIME`

How can I specify that the `syslog` (IETF/RFC5424) destination should send no timestamp but a NILVALUE `-` instead? I would like to do this in addition to adding the structured data `[timeQuality isSynced="0" tzKnown="0"]` (which I manage to do). 

I am already thinking about patching the source so that all timestamps with a year < 1980 are replaced by `-` but this is a dirty hack and there must be a more official way to do it?

Thanks in advance.

**Comment by MrAnno** [comment]
Hi @shyrodgau,

Log messages in syslog-ng always have a timestamp assigned to them, even if they're out of sync, so NILVALUEs are not used.

`year < 1980` can be expressed in the syslog-ng config using `$YEAR`, `$R_YEAR`, etc.
It is not convenient, but you may create your own RFC 5424 template that replaces the invalid date field with `-` based on that condition.

**Comment by shyrodgau** [comment]
Thanks for the explanation @MrAnno !
