### ISSUE TITLE
Performance regression for file destinations with syslog-ng 3.25.1

### ISSUE THREAD

**Issue by mkauf** [syslog-ng/syslog-ng#3319]
# syslog-ng
## Version of syslog-ng
syslog-ng 3.27.1

## Platform
CentOS 7 (64 bit)

# Issue
## Failure

The performance of the "file" destination got worse with syslog-ng 3.25.1, compared to syslog-ng 3.24.1.

I have a web server that writes a log message for every request to a log file and to Elasticsearch. syslog-ng 3.25.1 is limiting the request rate that the web server can handle. The "file" destination is now slower than the "http" destination with Elasticsearch.

The release notes mention this change: https://github.com/syslog-ng/syslog-ng/pull/2985. I have reverted commit https://github.com/syslog-ng/syslog-ng/pull/2985/commits/dd64d960670c55f3fafd5808d3b14d1cf402840d, built new RPMs and verified that this commit causes the performance regression.

There seems to be a workaround, this setting on the file destination improves the performance again:
```
disk-buffer(
    disk-buf-size(1048576)
    dir("/tmp/disk-buffer")
)
```

I don't understand why, because the size of the buffer file /tmp/disk-buffer/syslog-ng-00000.qf is just 4096 bytes.

What do you recommend to get the performance of syslog-ng 3.24.1 back? Is this a bug or is there some setting that I have missed?

## Steps to reproduce

Measure with the "loggen" tool:

```
loggen --rate 1000000 --dgram --unix /var/run/syslog-input.sock --dont-parse --loop-reading --read-file log.txt
```

log.txt:
```
<34>Oct 11 22:14:15 mymachine {"key1":"value1","key2":"value2","key3":"value3","key4":"value4","key5":"value5","key6":"value6","key7":"value7","key8":"value8","key9":"value9","key10":"value10"}
```

My measurements:
* syslog-ng 3.24.1, without "disk-buffer": ~26000 msg/sec, with "disk-buffer": ~26000 msg/sec
* syslog-ng 3.27.1, without "disk-buffer": ~18000 msg/sec, with "disk-buffer": ~25000 msg/sec

## Configuration
```
@version:3.24

options {
	keep-hostname(yes);
	chain-hostnames(off);
	keep-timestamp(yes);
	check-hostname(yes);
	use-dns(no);
	dns-cache(no);
	use-fqdn(no);
	create-dirs(yes);
	stats-freq(0);
	mark-freq(0);
};

source s_global_raw {
	unix-dgram(
		"/var/run/syslog-input.sock"
		log-fetch-limit(20000)
	);
};

parser p_test {
	json-parser();
};

destination d_file {
	file("/var/log/test"
		disk-buffer(
			disk-buf-size(1048576)
			dir("/tmp/disk-buffer")
		)
		template("${S_ISODATE} ${LOGHOST} $(format-json --scope nv-pairs)\n")
	);
};

log {
	source(s_global_raw);
	parser(p_test);
	destination(d_file);
};
```

**Comment by mkauf** [comment]
> Can you bump log-iw-size () on the source?

Yes, I got good results with log-iw-size(10000): about 29000 msg/sec. Thank you very much for this hint!

> The value you specify will be distributed evenly for every possible connection (which is specified by the max-connections () parameter)

Does this also apply to the unix-dgram() source in the example? Or does the unix-dgram() source count as 1 connection?

**Comment by bazsi** [comment]
Good question wrt unix-dgram() and max-connections(). Honestly I don't
know. I checked the source and the distribution of iw-size across
connections are only done for unix-stream (and tcp), but I dont know what
it defaults to otherwise. I dont have a computer at hand to try.

**Comment by MrAnno** [comment]
Hi @mkauf,

`unix-dgram()` is considered as a "connectionless" proto, it counts as a single connection, so the default IW is 100, and the `max-connections()` option is ignored for this source.

**Comment by mkauf** [comment]
Thanks! This makes sense.

A question about the default value: On [log-iw-size (syslog-ng 3.26)](https://www.syslog-ng.com/technical-documents/doc/syslog-ng-open-source-edition/3.26/administration-guide/log-iw-size), the default is 10000, in the [previous version of the documentation (syslog-ng 3.25)](https://www.syslog-ng.com/technical-documents/doc/syslog-ng-open-source-edition/3.25/administration-guide/log-iw-size) it is 100 and I think in the current source code it's also 100:
```
./lib/logsource.c:    options->init_window_size = 100;
```

Has the default value really changed?

Last question: The documentation for [flush-lines()](https://www.syslog-ng.com/technical-documents/doc/syslog-ng-open-source-edition/3.26/administration-guide/flush-lines) mentions that flush-lines() should be smaller than log-iw-size(). The documentation for [log-iw-size()](https://www.syslog-ng.com/technical-documents/doc/syslog-ng-open-source-edition/3.26/administration-guide/log-iw-size) mentions that it should be bigger than log-fetch-limit().

So, the conclusion is that log-iw-size() should be bigger than both flush-lines() and log-fetch-limit(), right?

**Comment by MrAnno** [comment]
The default IW is still 100 in syslog-ng, the value `10000` must be a documentation bug.

In case of network sources, `max-connections()` defaults to `10`, so the IW size is set to `1000` in order to get 100 window slots for each connection.

The same is true for unix streams: `max-connections()` defaults to 256, therefore `log-iw-size()` defaults to `256 * 100` there.

----

> So, the conclusion is that log-iw-size() should be bigger than both flush-lines() and log-fetch-limit(), right?

Yeah, `log-fetch-limit()` and `flush-lines()` are performance-related options, they exert their effect when `log-iw-size() >  log-fetch-limit()`.

`log-iw-size() > flush-lines()` is also a good choice, where IW is a source, flush-lines is a destination option and they are in the same log path.

**Comment by MrAnno** [comment]
(I'm marking this issue as a question, because dd64d960670c55f3fafd5808d3b14d1cf402840d contains a necessary fix that avoids message loss. The fix had some negative performance effects, but the original speed can be achieved by increasing `log-iw-size()` on the source side.)

**Comment by mkauf** [comment]
Thank you for your help! I have solved the performance problem by setting "log-iw-size". I compared the values of "log-fetch-limit" and "flush-lines" and used the bigger value for "log-iw-size".
