### ISSUE TITLE
Syslog-ng kafka module does not inform that a file does not exist

### ISSUE THREAD

**Issue by samthegolden** [syslog-ng/syslog-ng#3331]
# syslog-ng
## Version of syslog-ng
syslog-ng 3 (3.17.2)
## Platform
CentOS Linux release 7.7.1908 (Core)

# Issue
## Failure

A file defined in `properties-file` does not exist. It was the reason syslog-ng was not delivering events to kafka. 
```
destination d_CDC_kafka_dev {
    kafka(
        client-lib-dir("/usr/lib64/syslog-ng/java-modules/kafka.jar:/opt/kafka/libs/")
        kafka-bootstrap-servers("**suppressed**")
        properties-file("**/opt/kafka/config/producer.properties**")
        topic("event-input")
        template("${MSGHDR}${MESSAGE}")
    );
}
```
Expected to have some information on logs about the missing file.
Note: the destination entry was being used by the service.
## Steps to reproduce
Add a properties file entry on `kafka` with a file that does not exist.
Invoke the destination statement and no errors will appear in `/var/log/syslog-ng/`.

## Configuration
```
destination d_CDC_kafka_dev {
    kafka(
        client-lib-dir("/usr/lib64/syslog-ng/java-modules/kafka.jar:/opt/kafka/libs/")
        kafka-bootstrap-servers("**suppressed**")
        properties-file("**/opt/kafka/config/producer.properties**")
        topic("event-input")
        template("${MSGHDR}${MESSAGE}")
    );
}
...
**suppressed**
...
log { source(my_source); destination(d_CDC_kafka_dev); };
```

## Input and output logs (if possible)
(no logs related appear)

**Comment by Kokan** [comment]
About that as far as I remember the java modules also requires log4j if you want to get debug/error messages emitted by java based destinations. This is kinda unfortunate.

You could do two things:
* Follow the administrator guide regarding java based kafka and install log4j: https://www.syslog-ng.com/technical-documents/doc/syslog-ng-open-source-edition/3.19/administration-guide/37#TOPIC-1094603 (please report back if still there is no error regarding missing properties file)
* Try out the other kafka destination based on `librdkafka` writtine in C, you only have to replace the `kafka` with `kafka-c` (and of course have a new enough syslog-ng that has `kafka-c`).

**Comment by MrAnno** [comment]
I believe this is not an issue anymore with the native `kafka-c()` destination.
