### ISSUE TITLE
make persist_state_alloc_string() reuse the same entry if possible

### ISSUE THREAD

**Issue by furiel** [syslog-ng/syslog-ng#3337]
If a module needs to store a string inside the persist file, there are two nice helper functions:

```
gchar *persist_state_lookup_string(PersistState *self, const gchar *key, gsize *length, guint8 *version);
void persist_state_alloc_string(PersistState *self, const gchar *persist_name, const gchar *value, gssize len);
```

These work well in general with a small inconvenience: `persist_state_alloc_string()` always allocates a new persist entry and invalidates the old entry. Invalidation is not removal, just setting the `in_use` flag to false. This means the persist file grows after each call on the disk.

It would be a nice optimalizaton that if the string to store would fit into the original place, then `persist_state_alloc_string()` should reuse it.

The change would require a few lines of addition around:
https://github.com/syslog-ng/syslog-ng/blob/a66a82dd6fe04113bd48d1b05c6737550de57869/lib/persist-state.c#L899
And of course a new unit test. We can test if the same place reused by comparing the original and new `PersistEntryHandle`-s

Marking as good first issue.

**Comment by AniruddhaGawali** [comment]
hi is this issue is still open
i will like to contribute in it can you plz help me how would i start,

**Comment by alltilla** [comment]
Hi @AniruddhaGawali,

Yes, this is still open.

You can read some useful tips about building syslog-ng from scratch here: https://gitter.im/syslog-ng/syslog-ng?at=61ed4d5146529077f59be90c

After you have build syslog-ng, you can look into the mentioned code parts and unit tests. Maybe write a unit test, which tests the desired feature and then you can implement it.

**Comment by purviporwal0** [comment]
Is this issue solved yet? Otherwise I'd like to work on it. Can you assign this issue to me?
