### ISSUE TITLE
optionality for examples module

### ISSUE THREAD

**Issue by furiel** [syslog-ng/syslog-ng#3366]
Currently, the libexamples module is built in syslog-ng unconditionally.

This causes some inconvenience for those who want to experiment with the tutorials in gitbook: their drivers will conflict with the shipped version. They either need to choose another name and adapt significant amount of code for the followup, or need to disconnect the examples module from the build system, prior their work.

The latter alternative sounds better. Still it would be best if they would not need to modify the source beforehand, and work on the top of unmodified source.

Please introduce optionality for both autotools and cmake, that disables the libexamples module.
- autotools
The ususal `--[enable/disable]-examples`

- cmake
The usual `-DENABLE_EXAMPLES=[yes/no]`

Marking as good first issue.

**Comment by AryanSharma9917** [comment]
@furiel  If this issue is still unsolved I would love to work on this one.

**Comment by furiel** [comment]
@AryanSharma9917 sounds good to me. The issue is still unresolved.

**Comment by AryanSharma9917** [comment]
if ENABLE_libexamples
  lib_LTLIBRARIES = libexamples.la
  libexamples_la_SOURCES = mymodule.c mymodule.h
endif
AM_CPPFLAGS = -DENABLE_MYMODULE

@furiel  To enable the module, you can define the macro ENABLE_MYMODULE in your build system. For example, you could add the following line to a Makefile.
To disable the module, you can either undefine the ENABLE_MYMODULE macro or comment out the AM_CPPFLAGS line in your Makefile.

**Comment by furiel** [comment]
@AryanSharma9917 It looks like the changes try to solve a different problem: how to optionally add a custom plugin to libexamples. The goal here is to either build and package `libexamples` itself or not. 

Being a bit more elaborate: 

For the configuration part:

Optionality should be changed by parameterizing the configure script with a new `--enable-examples` or `--disable-examples` flag. You can copy how [--enable-redis](https://github.com/syslog-ng/syslog-ng/blob/3611f13a82842ac84668a4a049bbd16f457b5fe2/configure.ac#L305) works.

You also need to edit [--enable-all-modules](https://github.com/syslog-ng/syslog-ng/blob/4b6b8ae879da5d8e76c049ca1015b51ac2e87746/configure.ac#L381) to work for the examples module too.

In terms of implementation: You can copy how [redis](https://github.com/AryanSharma9917/syslog-ng/blob/5ddf743437a93622385d1a026a502efbfb4bb76e/modules/redis/Makefile.am#L1) works for example.

You can test your changes by deleting the install directory. Prepare the source for testing with a `make clean`,`./configure [...] --disable-examples`,and after a `make` call, `libexamples.so` is not built. After a `make install`, `libexamples.so` is not copied.

**Comment by MrAnno** [comment]
Fixed in #4668
