### ISSUE TITLE
json parsing of int64 integers is wrong

### ISSUE THREAD

**Issue by jszigetvari** [syslog-ng/syslog-ng#3367]
# syslog-ng
## Version of syslog-ng
Latest OSE and PE releases

## Platform
Irrelevant

# Issue
## Failure
If we try to parse an int64 integer with a value larger than INT32_MAX with json-parser, then the result will be a 32-bit integer value set to INT32_MAX.

## Steps to reproduce
See the configuration

## Configuration
```
source s_local {
	example-msg-generator(template('{ "date": 1595441285858 }'));
};destination d_local {
	file("/dev/stdout" template("$(format-json date=int64(${.json.date}))\n"));
};parser p_json {
	json-parser(prefix('.json.'));
};log {
	source(s_local);
	parser(p_json);
	destination(d_local);
};
```

## Input and output logs (if possible)
```
[2020-07-30T08:59:20.499218] json-parser message processing started; input='{ "date": 1595441285858 }', prefix='.json.', marker='(null)', msg='0x55d8d3acc7a0'
[2020-07-30T08:59:20.499352] Setting value; name='.json.date', value='2147483647', msg='0x55d8d3acc7a0'
```

**Comment by MrAnno** [comment]
It seems we use the 32-bit json-c integer function to query 64-bit values too:

`json_object_get_int()`:
> Note that integers are stored internally as 64-bit values.
> **If the value of too big or too small to fit into 32-bit, INT32_MAX or INT32_MIN are returned, respectively.**

`json_object_get_int64()` should be used instead.

**Comment by jszigetvari** [comment]
Yes, but then the problem is that we don't know in advance whether the integer being parsed will fit into a 32-bit integer, or whether we'll need a 64-bit integer.

**Comment by MrAnno** [comment]
I think we could always use int64 for integers. 

(Key-value pairs are strings in syslog-ng, so after querying the value from json-c, we immediately serialize it back to a string name-value pair.)
