### ISSUE TITLE
millisecond format element for date-parser()

### ISSUE THREAD

**Issue by jszigetvari** [syslog-ng/syslog-ng#3371]
## Description of the problem
If one has a millisecond timestamp (Unix timestamp plus milliseconds), and needs to process it using the date-parser(), one has to go through a lot of trouble to achieve his/her goal. Currently the only solution is to separate the millisecond part of the date to a macro, and also separate the second part (seconds since Epoch) to a different macro, and then multiply the millisecond part by 1000 so that it can be parsed by the %f format specifier. And finally one has to parse the standard Unix timestamp part with %s. So the final format string becomes "%s.%f".

## Proposed solution
Either or both of the following format specifier should be added:

- millisecond since Epoch
- milliseconds

This would eliminate the need for the trickery described above.

**Comment by alltilla** [comment]
Plain millisecond parsing should be handled by `%f`.:
https://github.com/syslog-ng/syslog-ng/blob/master/lib/timeutils/tests/test_wallclocktime.c#L57

Not sure yet about milliseconds since Epoch.

**Comment by bazsi** [comment]
I don't really understand what you mean here. %f should be able to parse up
to nanoseconds. It assumes the digits are following a dot, and if it finds
3 digits it assumes milliseconds, if it's 6 then microseconds and so on.

Can you give an example where it does something that you didn't expect?

**Comment by rfaircloth-splunk** [comment]
Sorry lots of github messages I didn't see the ask for respose 
Right now real epoch is 1610996436 %s works fine
epoch with ms 1610996436.3456 works fine with %s.%f
some devices send epoch as miliseconds sense epoch  not seconds sense epoch
16109964363456 note the lack of period and implied precision

**Comment by bazsi** [comment]
You can use the division template function with floating point numbers:

Both of these worked for me:

```
# set value
	rewrite { set("${S_UNIXTIME}123" value("timestamp")); }; 

# using floating point division
        parser { date-parser(format("%s.%f") template('$(/ ${timestamp} 1000.0)')); };

# using fixed point arithmetic
        parser { date-parser(format("%s.%f") template('$(/ ${timestamp} 1000).$(% ${timestamp} 1000)')); };

```

I just made up "123" as the millisecond part after a normal UNIX timestamp without the ".". 

In the floating point case, the "1000.0" is a floating point number to tell the "$(/)" function to do floating point maths.

Does this solve your use-case?

**Comment by bazsi** [comment]
btw, one thing is that I am a bit reluctant to add extra format specifiers to our strptime() implementation, except if there's at least one wide-spread platform that already defines the format. I am concerned that something else would add an incompatible meaning to the same specifier.

The '%f' was used by Python, that's where it was borrowed from.
