### ISSUE TITLE
Kafka java performance

### ISSUE THREAD

**Issue by ronaldfenner** [syslog-ng/syslog-ng#3377]
# syslog-ng
## Version of syslog-ng
3.28.1

## Platform
Amazon Linux 2
Linux 4.14.186-146.268.amzn2.x86_64 #1 SMP Tue Jul 14 18:16:52 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

## Debug bundle
attached 
[syslog.debun.ip-172-30-12-202.ec2.internal.2020-08-06_05-09.6593.zip](https://github.com/syslog-ng/syslog-ng/files/5032728/syslog.debun.ip-172-30-12-202.ec2.internal.2020-08-06_05-09.6593.zip)

# Issue
## Failure
For some reason performance of the Kafka java plugin has tanked when sending the messages. Was working fine with disk buffering then for some response possible a automatic yum update cause the performance sending messages to the Kafka cluster to tank. It's seems to be able to only send a couple messages a second now.

## Steps to reproduce
You'd have to have out infrastructure setup to be able to reproduce.

```
## Configuration
#############################################################################
# Default syslog-ng.conf.partial file which collects all local logs into a
# single file called /var/log/messages.
#

@version: 3.28
@module "mod-java"
@include "scl.conf"
@include "conf.d/gc-parsers.conf"

source s_internal {internal();};

source s_rtl_stream {
    unix-stream("/var/gamecircus/log/rtl-stream.sock" flags(no-parse) log_msg_size(1000000));
};

# messages sent here use the specified topic with no modification
source s_rtl_raw_stream {
    unix-stream("/var/gamecircus/log/rtl-raw-stream.sock" flags(no-parse) log_msg_size(1000000));
};

# Backup for when syslog-ng crashes and doesn't restart queues the messages
source s_rtl_backup {
    file("/var/gamecircus/log/rtl-backup.log" flags(no-parse) log_msg_size(1000000));
};

# Backup for when syslog-ng crashes and doesn't restart queues the messages
source s_rtl_raw_backup {
    file("/var/gamecircus/log/rtl-raw-backup.log" flags(no-parse) log_msg_size(1000000));
};

destination d_kafka_unstructured {
    kafka (
        client-lib-dir("/opt/syslog-ng/lib/syslog-ng/java-modules/kafka.jar:/opt/kafka/libs/")
        kafka-bootstrap-servers("kafka.service.consul:9092")
        topic("syslog-ng-`DeployedEnvironment`")
    );
};

# environmnet is added to the topic
destination d_kafka_environment {
    kafka (
        client-lib-dir("/opt/syslog-ng/lib/syslog-ng/java-modules/kafka.jar:/opt/kafka/libs/")
        kafka-bootstrap-servers("kafka.service.consul:9092")
        topic("${topic}.${environment}")
        template("$(format-json --scope nv_pairs --exclude MESSAGE)\n")
#    disk-buffer(
#        mem-buf-size(10485760) # 10MB
#        disk-buf-size(10737412742) # 10GB
#        reliable(yes)
#        dir("/opt/syslog-ng/disk-buffers/")
#    )
    );
};

# raw topic no modification
destination d_kafka_raw {
    kafka (
        client-lib-dir("/opt/syslog-ng/lib/syslog-ng/java-modules/kafka.jar:/opt/kafka/libs/")
        kafka-bootstrap-servers("kafka.service.consul:9092")
        topic("${topic}")
        template("$(format-json --scope nv_pairs --exclude MESSAGE)\n")
    );
};

destination d_syslog_ng {
    file("/var/log/syslog-ng.log");
};

parser p_json { json-parser(); };

log {
    source(s_internal);
    destination(d_syslog_ng);
};

log {
    source(s_rtl_stream);
    parser(p_json);
    destination(d_kafka_environment);
};

log {
    source(s_rtl_raw_stream);
    parser(p_json);
    destination(d_kafka_raw);
};

log {
    source(s_rtl_backup);
    parser(p_json);
    destination(d_kafka_environment);
};

log {
    source(s_rtl_raw_backup);
    parser(p_json);
    destination(d_kafka_raw);
};

# Build script will add stuff below for the specific build.
###############################################################################
# This Files is merged into the main syslog-ng.conf file to form the full conf file for the server.
# Source BaseNginxPhpFpm
source s_default_access_log {
    file("/var/gamecircus/log/default-www-access.log", flags(no-parse));
};

source s_php_fpm {
    file("/var/gamecircus/log/php-fpm.www.log", flags(no-parse));
};

parser p_apache { apache-accesslog-parser(); };

parser p_php_fpm { python(class("PhpFpmParser")); };

rewrite r_add_access_topic {
    set("access.log", value("topic"));
};

rewrite r_add_error_topic {
    set("errors", value("topic"));
};

rewrite r_add_backend_name {
    set("`SERVER_GROUP`", value("backend_name"));
};

log {
  source(s_default_access_log);
  parser(p_apache);
  rewrite(r_add_access_topic);
  rewrite(r_add_backend_name);
  destination(d_kafka_environment);
};

log {
    source(s_php_fpm);
    parser(p_php_fpm);
    rewrite(r_add_error_topic);
    rewrite(r_add_backend_name);
    destination(d_kafka_environment);
};

###############################################################################
################################################################
# Additions for relaying from another VPC or source not in the Kafka VPC
#Source for data to be fed to the no env destination
source s_rtl_stream_relay {
    unix-stream("/var/gamecircus/log/rtl-stream-relay.sock" flags(no-parse) log_msg_size(1000000));
};

# Backup for when syslog-ng crashes and doesn't restart queues the messages
#Source for data to be fed to the no env destination
source s_rtl_backup_relay {
    file("/var/gamecircus/log/rtl-backup-relay.log" flags(no-parse) log_msg_size(1000000));
};

log {
    source(s_rtl_stream_relay);
    parser(p_json);
    destination(d_kafka_environment);
};

log {
    source(s_rtl_backup_relay);
    parser(p_json);
    destination(d_kafka_environment);
};

##################################################################
#APi Access Logs
source s_prod_access_logs {
    file("/var/gamecircus/log/api-access.log" flags(no-parse));
};

rewrite r_add_prod_environment {
    set("production", value("environment"));
};

log {
  source(s_prod_access_logs);
  parser(p_apache);
  rewrite(r_add_prod_environment);
  rewrite(r_add_access_topic);
  rewrite(r_add_backend_name);
  destination(d_kafka_environment);
};

```

**Comment by ronaldfenner** [comment]
After some more investigation i determined that one of the topics didn't exist and i have auto topic creation turned off for the cluster. Apparently it seems syslog-ng was getting stuck somehow and not wanting to send messages to any of the other topics that did exist. I see this behavior in 3.23.1 as well.

Once i created the topic then it started sending message again with no problem. This seems like a bug as it should continue to send message to the topics that exists. Not sure what option should be taken on a topic that doesn't exist.

**Comment by gaborznagy** [comment]
Hello!

Sorry for the late answer. 
You mentioned that syslog-ng should continue to send messages to existing topics and not stuck on errors. This is true, but please note that syslog-ng destinations process their message-queues sequentially, and they attempt to redeliver a message in case of error. The number of attempts (before the message is finally dropped) can be configured with the `retries()` option (default: 3). Also, there is a `time-reopen()` waiting time between 2 retries, which have a default of 60 seconds.
This could take a huge penalty on the outgoing message rate, but message sending shouldn't stuck.
You said that performance reduced to couple of messages per second, right? 

I would like to understand what's happening in your setup in case of non-existing topic.
Do you have any `internal()` logs from syslog-ng or from kafka side maybe?

**Comment by Kokan** [comment]
I think it is quite okay to slow down the destination if it cannot properly forward a message. It is hard to know that a next message would be successful if tried, as from syslog-ng point of view there is an error as the other side cannot process the logs. Maybe none of the topic could receives logs, what threshold should syslog-ng stop if any.
The good news, that this can be done if you separate your logs via important/less important logs/topic and separate the traffic into different destination and even could configure the behavior differently. (drop/max_retries/...). But I think this should be done in configuration, as the user has extra information to help syslog-ng.
