### ISSUE TITLE
Spelling issues found by lintian

### ISSUE THREAD

**Issue by mochrul** [syslog-ng/syslog-ng#3394]
# syslog-ng
## Version of syslog-ng
3.28.1

## Platform
any

## Debug bundle
It's not needed

# Issue
## Failure
The lintian found some spelling problems in the binary files:
I: syslog-ng-core: spelling-error-in-binary usr/bin/dqtool initalizing initializing
I: syslog-ng-core: spelling-error-in-binary usr/bin/loggen successfuly successfully
I: syslog-ng-core: spelling-error-in-binary usr/bin/pdbtool debuging debugging
I: syslog-ng-core: spelling-error-in-binary usr/bin/pdbtool correllation correlation
I: syslog-ng-core: spelling-error-in-binary usr/bin/slogencrypt Addtional Additional
I: syslog-ng-core: spelling-error-in-binary usr/bin/slogkey Addtional Additional
I: syslog-ng-core: spelling-error-in-binary usr/bin/slogverify descryption description
I: syslog-ng-core: spelling-error-in-binary usr/bin/slogverify Addtional Additional
I: syslog-ng-core: spelling-error-in-binary usr/lib/syslog-ng/3.28/libdbparser.so correllation correlation
I: syslog-ng-core: spelling-error-in-binary usr/lib/syslog-ng/3.28/libdisk-buffer.so initalizing initializing
I: syslog-ng-core: spelling-error-in-binary usr/lib/syslog-ng/3.28/libsecure-logging.so Addtional Additional
I: syslog-ng-core: spelling-error-in-binary usr/lib/syslog-ng/3.28/loggen/libloggen_socket_plugin.so occured occurred
I: syslog-ng-core: spelling-error-in-binary usr/lib/syslog-ng/3.28/loggen/libloggen_socket_plugin.so refernce reference
I: syslog-ng-core: spelling-error-in-binary usr/lib/syslog-ng/3.28/loggen/libloggen_ssl_plugin.so occured occurred
I: syslog-ng-core: spelling-error-in-binary usr/lib/syslog-ng/3.28/loggen/libloggen_ssl_plugin.so refernce reference
I: syslog-ng-core: spelling-error-in-binary usr/lib/syslog-ng/libsyslog-ng-3.28.so.0.0.0 occured occurred
I: syslog-ng-core: spelling-error-in-binary usr/lib/syslog-ng/libsyslog-ng-3.28.so.0.0.0 succeded succeeded
I: syslog-ng-core: spelling-error-in-binary usr/lib/syslog-ng/libsyslog-ng-3.28.so.0.0.0 emptry empty
I: syslog-ng-core: spelling-error-in-manpage usr/share/man/man1/pdbtool.1.gz allows to allows one to
I: syslog-ng-core: spelling-error-in-manpage usr/share/man/man1/syslog-ng-debun.1.gz debuging debugging
I: syslog-ng-mod-python: spelling-error-in-binary usr/lib/syslog-ng/3.28/libmod-python.so explicitely explicitly
I: syslog-ng-mod-examples: spelling-error-in-binary usr/lib/syslog-ng/3.28/libexamples.so initalizing initializing
I: syslog-ng-mod-stardate: spelling-error-in-binary usr/lib/syslog-ng/3.28/libstardate.so fuction function

## Steps to reproduce
These spelling mistakes are in the source code, so it can be found with a grep command, like

sasa@sasalaptop:~/Work/debian/syslog-ng/src$ git grep fuction
lib/stats/stats-registry.c: * This **fuction** registers a general purpose counter. Whenever multiple
modules/stardate/stardate-plugin.c:  .description = "This **fuction** provides stardate template function: "

## Configuration
N/A

## Input and output logs (if possible)
N/A

**Comment by gaborznagy** [comment]
Hi @mochrul !

I've ran `spellintian` on the source itself as well, and I've found some more typos, see #3421.

Also, I've found a reports page on lintian's web page, which shows less issues than spellintian:
https://lintian.debian.org/sources/syslog-ng/3.27.1-3.html.

Can you check our fixes, please?
