### ISSUE TITLE
include/syslog-ng/signal-handler.h

### ISSUE THREAD

**Issue by czanik** [syslog-ng/syslog-ng#3410]
While packaging the latest syslog-ng git master snapshot (syslog-ng-3.28.1.293.g64964a5.tar.gz) on FreeBSD I ran into an interesting issue. When I disable all features the include file ```include/syslog-ng/signal-handler.h``` is installed. When I enable all features in configure, the file is missing:

```
====> Checking for pkg-plist issues (check-plist)
===> Parsing plist
===> Checking for items in STAGEDIR missing from pkg-plist
===> Checking for items in pkg-plist which are not in STAGEDIR
Error: Missing: include/syslog-ng/signal-handler.h
===> Error: Plist issues found.
```

- is it the expected behavior?

- If yes, what disables installing it (so I don't have to test all the options)?

**Comment by Kokan** [comment]
I mean it is hard to say. Can you share the steps to reproduce ? (I mean also this `pkg-plist` stuff...)

**Comment by czanik** [comment]
OK, just found it. If http(curl) support is enabled the include file is missing. Otherwise it is installed.

You can find the current state of the upcoming 3.29 port below.

[syslog-ng329.zip](https://github.com/syslog-ng/syslog-ng/files/5141576/syslog-ng329.zip)

**Comment by czanik** [comment]
Problem seems to be resolved.
