### ISSUE TITLE
Syslog-ng filter issue

### ISSUE THREAD

**Issue by vishnu2281** [syslog-ng/syslog-ng#3460]
I have applied the syslog-ng filter for 3 applications. And it worked for one day.From next day it stopped working. So I have a doubt that if i use the same programlist.list  filter list for more applications would it cause issue? can someone clarify this issue please?
syslog filter sample config:

->Created a text file in /etc/syslog-ng/programlist.list and add the keywords in the file.
->And Added a whitelist in the syslog config
filter f_whitelist { in-list("/etc/syslog-ng/programlist.list", value("PROGRAM")); };
->At last,  Added a blacklist in the config.
filter f_blacklist { not in-list("/etc/syslog-ng/programlist.list", value("PROGRAM")); };

**Comment by gaborznagy** [comment]
Hi!

Can you describe the problem in more detail, please? What do you mean it stopped working?
What PROGRAM fields do you see when the issue occurs? What are the keywords in the file for in-list() filter?
What do you see in the `internal()` logs when the issue occurs?
Can you help us with reproduction steps, please?
What version of syslog-ng do you use?

**Comment by gaborznagy** [comment]
You can use the same in-list() filter in multiple log paths or in the same log path multiple times.
The file used for the in-list() filter is processed on startup.

**Comment by vishnu2281** [comment]
Hi ,

I found the below error logs from internal().I guess its a permission issue. So do i need add any config extra in syslog config?
Oct 20 10:40:35 SLHROGLE
[programlist.txt](https://github.com/syslog-ng/syslog-ng/files/5414651/programlist.txt)

 syslog-ng[3166]: Error opening file for writing; filename='/var/log/remote/all_maya_logs/6516/NUAGE_VSC_OS/fb01xssl1NUAGE_VSC-20-10-2020.log', error='No such file or directory (2)'



Syslog config:
source source_splunk_net_NUAGE_VSC_syslog {
        network( transport(tcp) port(6516));
        network( transport(udp) port(6516));
};

destination remote_splunk_net_NUAGE_VSC_syslog {
        file("/var/log/remote/all_maya_logs/6516/NUAGE_VSC/${FULLHOST}/NUAGE_VSC-${DAY}-${MONTH}-${YEAR}.log");
};

destination remote_splunk_net_NUAGE_VSC_OS_syslog {
        file("/var/log/remote/all_maya_logs/6516/NUAGE_VSC_OS/${FULLHOST}/NUAGE_VSC-${DAY}-${MONTH}-${YEAR}.log");
};
filter nuagevscos{ in-list("/etc/syslog-ng/programlist.list", value("PROGRAM")); };

filter nuagevscapp{ not in-list("/etc/syslog-ng/programlist.list", value("PROGRAM")); };

log {
        source(source_splunk_net_NUAGE_VSC_syslog);
        filter(nuagevscapp);
        destination(remote_splunk_net_NUAGE_VSC_syslog);
};

log {
        source(source_splunk_net_NUAGE_VSC_syslog);
        filter(nuagevscos);
        destination(remote_splunk_net_NUAGE_VSC_OS_syslog);
};

I have attached the filter list as well.

Thanks!

**Comment by gaborznagy** [comment]
I think your need to enable directory creation on your file destinations. File destinations doesn't create underlying directories by default when a new file is created.

```
destination remote_splunk_net_NUAGE_VSC_syslog {
file("/var/log/remote/all_maya_logs/6516/NUAGE_VSC/${FULLHOST}/NUAGE_VSC-${DAY}-${MONTH}-${YEAR}.log" create-dirs(yes));
};

destination remote_splunk_net_NUAGE_VSC_OS_syslog {
file("/var/log/remote/all_maya_logs/6516/NUAGE_VSC_OS/${FULLHOST}/NUAGE_VSC-${DAY}-${MONTH}-${YEAR}.log" create-dirs(yes));
};

**Comment by vishnu2281** [comment]
Thanks for your help.it worked well
