### ISSUE TITLE
loggen should attempt reconnect when destination connections are lost

### ISSUE THREAD

**Issue by haidangwa** [syslog-ng/syslog-ng#3469]
## Description of the problem

We tested with an AnyCast configuration between two geographically distant locations, and when we shutdown all the network interfaces at one location, we expected all the loggen messages to be sent automatically to the second site. We confirmed that Anycast was detecting the downed interfaces and resolving all traffic to the second site; however, loggen failed to send data as soon as all services in site 1 was down. If we re-run loggen while the interfaces in site1 were still down, the traffic connected to interfaces in site2 successfully, as we originally expected.

Target destination was over UDP 514 (standard UDP syslog) and TCP 514. The result was the same whether we tested with UDP or TCP.

## Additional context

This was the loggen output. The lines showing `error` occurred as soon as we downed one of 2 interfaces in site1. When we downed the final of 2 interfaces of site1, loggen just stopped sending and never reconnected -- this is demonstrated by the rate of messages sent dropping off at the end of the output.

```
loggen -i -r 1000 -I 60 -P --read-file /tmp/vanhalen -l --active-connections 20 -F oursyslog.com 514 -d
count=36983, rate = 19177.47 msg/sec
count=46583, rate = 19195.74 msg/sec
count=56173, rate = 19176.09 msg/sec
count=65774, rate = 19197.47 msg/sec
count=75384, rate = 19216.93 msg/sec
count=84976, rate = 19180.05 msg/sec
count=94591, rate = 19225.73 msg/sec
count=104188, rate = 19190.24 msg/sec
count=113790, rate = 19200.39 msg/sec
count=123390, rate = 19196.08 msg/sec
count=132990, rate = 19195.97 msg/sec
count=142591, rate = 19198.24 msg/sec
count=152197, rate = 19207.97 msg/sec
count=161803, rate = 19207.35 msg/sec
count=171401, rate = 19192.12 msg/sec
count=181008, rate = 19209.20 msg/sec
count=190606, rate = 19191.82 msg/sec
count=200206, rate = 19196.08 msg/sec
count=209806, rate = 19196.24 msg/sec
count=219414, rate = 19212.20 msg/sec
count=229022, rate = 19212.20 msg/sec
error [socket_plugin.c:active_thread_func:393] error sending buffer on 35 (rc=-1)
error [socket_plugin.c:active_thread_func:393] error sending buffer on 30 (rc=-1)
error [socket_plugin.c:active_thread_func:393] error sending buffer on 29 (rc=-1)
error [socket_plugin.c:active_thread_func:393] error sending buffer on 40 (rc=-1)
error [socket_plugin.c:active_thread_func:393] error sending buffer on 41 (rc=-1)
error [socket_plugin.c:active_thread_func:393] error sending buffer on 33 (rc=-1)
error [socket_plugin.c:active_thread_func:393] error sending buffer on 26 (rc=-1)
error [socket_plugin.c:active_thread_func:393] error sending buffer on 28 (rc=-1)
error [socket_plugin.c:active_thread_func:393] error sending buffer on 42 (rc=-1)
error [socket_plugin.c:active_thread_func:393] error sending buffer on 39 (rc=-1)
count=236298, rate = 14549.06 msg/sec
count=241108, rate = 9618.13 msg/sec
count=245908, rate = 9598.10 msg/sec
count=250704, rate = 9590.10 msg/sec
count=255503, rate = 9596.41 msg/sec
count=260300, rate = 9592.14 msg/sec
count=265105, rate = 9608.10 msg/sec
count=269905, rate = 9598.04 msg/sec
count=274705, rate = 9598.10 msg/sec
count=279503, rate = 9594.20 msg/sec
count=284303, rate = 9597.97 msg/sec
count=289103, rate = 9598.08 msg/sec
count=293904, rate = 9600.21 msg/sec
count=298701, rate = 9592.08 msg/sec
count=303502, rate = 9600.20 msg/sec
count=308294, rate = 9582.56 msg/sec
count=313074, rate = 9558.11 msg/sec
count=317852, rate = 9554.05 msg/sec
count=322644, rate = 9582.01 msg/sec
count=327444, rate = 9598.21 msg/sec
count=332241, rate = 9592.08 msg/sec
count=337046, rate = 9608.19 msg/sec
count=341872, rate = 9650.26 msg/sec
count=345252, rate = 6758.61 msg/sec
count=345734, rate = 963.81 msg/sec
count=345845, rate = 221.94 msg/sec
```

**Comment by Kokan** [comment]
The loggen is primary a testing tool, and as such not to re-connect by default I think is a good option. Otherwise you may not detect an issue when a source connection is broken for some reason (issue in source side code) but re-connects silently and tests observed as successful.

Making this as an opt-in behaviour with an argument should be fine. This should be a straight forward implementation; that being said I am not sure when somebody from the core team could work on this. If you have the capacity to work on this, we can give you pointers if needed.

**Comment by LittleFish33** [comment]
Hi, I would like to work on this issue, I've reviewed codes related to `loggen`. According to the problem statement, `loggen` should add an argument to allow it to reconnect when the destination is down. However, as it can be seen from the code, message sending will not be turned on until all threads have tried connected to the destination (take `socket_plugin.c` for example):

```c++
// lines 196-209 of socket_plugin.c
g_mutex_lock(thread_lock);
while (connect_finished != option->active_connections + option->idle_connections)
{
    if (! g_cond_wait_until(thread_connected, thread_lock, end_time))
    {
        ERROR("timeout occurred while waiting for connections\n");
        break;
    }
}

/* start all threads */
g_cond_broadcast(thread_start);
thread_run = TRUE;
g_mutex_unlock(thread_lock);
```

`connect_finished` will equals to `option->active_connections + option->idle_connections` when all threads have executed the following codes:

```c++
// lines 328-343 of socket_plugin.c
int fd;
if (unix_socket_x)
    fd = connect_unix_domain_socket(sock_type, option->target);
else
    fd = connect_ip_socket(sock_type, option->target, option->port, option->use_ipv6);

if (fd<0)
{
    ERROR("can not connect to %s:%s (%p)\n", option->target, option->port, g_thread_self());
}
else
{
    DEBUG("(%d) connected to server on socket %d (%p)\n", thread_index, fd, g_thread_self());
}

g_mutex_lock(thread_lock);
connect_finished++;
```

Therefore, if we want to reconnect to the destination, we need to copy the above code that initializing the connection. A pseudo code might be:

```c++
connect to destination;
while(not done)
{
    try to send message;
    if(send failure)
    {
        sleep(interval)
    	reconnect to destination;        
    }
}
```

The disadvantage of this solution is a little code duplication. I am uncertain if this is the best solution. It would be great if you can provide some guide.


> The loggen is primary a testing tool, and as such not to re-connect by default I think is a good option. Otherwise you may not detect an issue when a source connection is broken for some reason (issue in source side code) but re-connects silently and tests observed as successful.
> 
> Making this as an opt-in behaviour with an argument should be fine. This should be a straight forward implementation; that being said I am not sure when somebody from the core team could work on this. If you have the capacity to work on this, we can give you pointers if needed.

**Comment by Kokan** [comment]
You could extract the socket connection part into a local function, and re-use that later in the loop thus eliminating code duplication.
