### ISSUE TITLE
External Python Script Example

### ISSUE THREAD

**Issue by mike-albano** [syslog-ng/syslog-ng#3491]
# syslog-ng
## Version of syslog-ng

syslog-ng -V
syslog-ng 3 (3.29.1)
Config version: 3.29
Installer-Version: 3.29.1
Revision: 3.29.1-1
Compile-Date: Aug 28 2020 12:13:25
Module-Directory: /usr/lib/syslog-ng/3.29
Module-Path: /usr/lib/syslog-ng/3.29
Include-Path: /usr/share/syslog-ng/include

## Platform

cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04 LTS"

## Debug bundle

[Link to debug bundle](https://drive.google.com/file/d/1xI6IPE8Twy2sLvuKSXLELoGelewIpEZ8/view?usp=sharing)
# Issue
## Failure

Trying to use external Python script but getting ModuleNotFound. Following [this example](https://www.syslog-ng.com/technical-documents/doc/syslog-ng-open-source-edition/3.19/administration-guide/16#TOPIC-1094518). I suspect it's a PYTHONPATH issue, but have tried setting that path according to [this](https://www.syslog-ng.com/technical-documents/doc/syslog-ng-open-source-edition/3.19/administration-guide/destination-forward-send-and-store-log-messages/python-writing-custom-python-destinations/), [this](https://www.syslog-ng.com/technical-documents/doc/syslog-ng-open-source-edition/3.19/administration-guide/source-read-receive-and-collect-log-messages/python-writing-server-style-python-sources/) and [this](https://www.syslog-ng.com/technical-documents/doc/syslog-ng-open-source-edition/3.19/administration-guide/16#TOPIC-1094518).

Is there a dependency on using external Python script? Note, I've also tried including my desired code within syslog-ng.conf, but it relies on imported libraries, which syslog-ng could not find (emitting similar output, eg ModuleNotFound)
## Steps to reproduce

sudo syslog-ng -Fvde
```
Error loading Python module; module='pythonexample', exception='ModuleNotFoundError: No module named \'pythonexample\''
ModuleNotFoundError: No module named 'pythonexample'
```
## Configuration

Relevant config from syslog-ng.conf:
```
# Using external python script
source s_local {
    system();
    internal();
};

destination d_python_to_file {
    python(
        class("pythonexample.TextDestination")
        on-error("fallback-to-string")
        value-pairs(scope(everything))
        #options(my_sample_option option_value)
    );
};

log {
    source(s_src);
    destination(d_python_to_file);
};
```
Full syslog-ng.conf available in debug attached above.
## Input and output logs (if possible)

The python script (taken from [example link](https://www.syslog-ng.com/technical-documents/doc/syslog-ng-open-source-edition/3.19/administration-guide/16#TOPIC-1094518)):
cat /etc/syslog-ng/pythonexample.py
```
class LogDestination(object):

    def open(self):
        """Open a connection to the target service

        Should return False if opening fails"""
        return True

    def close(self):
        """Close the connection to the target service"""
        pass

    def is_opened(self):
        """Check if the connection to the target is able to receive messages"""
        return True

    def init(self, options):
        """This method is called at initialization time

        Should return false if initialization fails"""
        return True

    def deinit(self):
        """This method is called at deinitialization time"""
        pass

    def send(self, msg):
        """Send a message to the target service

        It can return boolean. Since 3.20, it can return integer
        alternatively.
        Boolean: True to indicate success, False will suspend the
        destination for a period specified by the time-reopen() option.
        After that the same message is retried until retries() times.

        Integer:
        self.SUCCESS: message sending was successful (same as boolean True)
        self.ERROR: message sending was unsuccessful. Same message is retried.
            (same as boolean False)
        self.DROP: message cannot be sent, it should be dropped immediately.
        self.QUEUED: message is not sent immediately, it will be sent with the flush method.
        self.NOT_CONNECTED: message is put back to the queue, open method will be called until success.
        self.RETRY: message is put back to the queue, try to send again until 3 times, then fallback to self.NOT_CONNECTED."""

        return True

    def flush(self):
        """Flush the queued messages

        Since 3.20. It can return either a boolean or integer.
        Send needs to return with self.QUEUED in order to work.
        Boolean: True to indicate that the batch is successfully sent.
        False indicates error while sending the batch. The destination is suspended
        for time-reopen period. The messages in the batch are passed again to send, one by one.

        Integer:
        self.SUCCESS: batch sending was successful (same as boolean True)
        self.ERROR: batch sending was unsuccessful. (same as boolean False)
        self.DROP: batch cannot be sent, the messages should be dropped immediately.
        self.NOT_CONNECTED: the messages in the batch is put back to the queue,
            open method will be called until success.
        self.RETRY: message is put back to the queue, try to send again until 3 times, then fallback to self.NOT_CONNECTED."""

        return True

class TextDestination(LogDestination):
    def __init__(self):
        self.outfile = None
        self._is_opened = False

    def init(self, options):
        self.outfile = open("/tmp/example.txt", "a")
        self.outfile.write("initialized with {}\n".format(options))
        self.outfile.flush()
        return True

    def is_opened(self):
        return self._is_opened

    def open(self):
        self.outfile.write("opened\n")
        self.outfile.flush()
        self._is_opened = True
        return True

    def close(self):
        self.outfile.write("closed\n")
        self.outfile.flush()
        self._is_opened = False

    def deinit(self):
        self.outfile.write("deinit\n")
        self.outfile.flush()
        self.outfile.close();

    def send(self, msg):
        self.outfile.write("Name Value Pairs are:\n")

        for key,v in msg.items():
            self.outfile.write(str(key) + " = " + str(v) + "\n");
        self.outfile.write("________________________\n\n")
        self.outfile.flush()
        return True
```

**Comment by MrAnno** [comment]
AFAIK `sudo` drops environment variables by default.
`PYTHONPATH` has to be set to `/etc/syslog-ng/` in your example, and this should somehow be preserved by sudo.

`sudo --preserve-env` may help here.

**Comment by mike-albano** [comment]
Closing this, as I was able to achieve this via rsyslogd.

FWIW, it does seem like an env issue (so probably just a docs update needed). Will resurrect if I resume troubleshooting this in syslog-ng.
