### ISSUE TITLE
TLS macros have wrong name

### ISSUE THREAD

**Issue by hvt** [syslog-ng/syslog-ng#3494]
## Documentation version

3.26

## Incorrect section

https://www.syslog-ng.com/technical-documents/doc/syslog-ng-open-source-edition/3.26/administration-guide/64#macro-tls-x509

## Description of the problem

First of all, I really like syslog-ng's documentation. It is clear and contains good examples. Keep up the good work!

Nevertheless, I want to report an issue in the macro docs I stumbled upon, and cost me quite a headache ;].

The TLS macros mentioned are here in uppercase. That however does not
work, they must be in lowercase.

## Proposed solution

* .tls.x509_cn: The Common Name of the certificate.
* .tls.x509_o: The value of the Organization field.
* .tls.x509_ou: The value of the Organization Unit field.

And the proof of this in the source:
https://github.com/syslog-ng/syslog-ng/blob/master/lib/transport/transport-tls.c#L109-L111

**Comment by szemere** [comment]
Thank You for reporting it! I forwarded the issue towards the documentation team.

**Comment by MrAnno** [comment]
(Internal documentation ticket: DOC-5396)

**Comment by MrAnno** [comment]
Merged (balabit/syslog-ng-ose-guides#42).
