### ISSUE TITLE
syslog-ng spams system.log in OPNsense when enabling remote target (v329)

### ISSUE THREAD

**Issue by mimugmail** [syslog-ng/syslog-ng#3506]
# syslog-ng
## Version of syslog-ng
syslog-ng 3 (3.29.1)
Config version: 3.29
Installer-Version: 3.29.1
Revision:
Compile-Date: Nov 17 2020 05:22:14
Module-Directory: /usr/local/lib/syslog-ng
Module-Path: /usr/local/lib/syslog-ng
Include-Path: /usr/local/share/syslog-ng/include
Available-Modules: affile,afprog,afsocket,afstomp,afuser,appmodel,azure-auth-header,basicfuncs,cef,confgen,cryptofuncs,csvparser,dbparser,disk-buffer,examples,graphite,hook-commands,http,kvformat,json-plugin,linux-kmsg-format,map-value-pairs,pseudofile,secure-logging,stardate,syslogformat,system-source,tags-parser,tfgetent,timestamp,xml,add-contextual-data
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: off
Enable-TCP-Wrapper: off
Enable-Linux-Caps: off
Enable-Systemd: off

## Platform
root@OPNsense:/var/unbound/etc # uname -a
FreeBSD OPNsense.localdomain 12.1-RELEASE-p10-HBSD FreeBSD 12.1-RELEASE-p10-HBSD #0  6e16e28f1bf(stable/20.7)-dirty: Tue Oct 20 13:30:19 CEST 2020     root@sensey64:/usr/obj/usr/src/amd64.amd64/sys/SMP  amd64

## Debug bundle

# Issue
## Failure
When enabling remote syslog in OPNsense the system.log is constantly spamming with this message:
Dec  3 11:53:06 OPNsense.localdomain syslog-ng[74190]: Destination timeout has elapsed, closing connection; fd='24'
Dec  3 11:53:07 OPNsense.localdomain syslog-ng[74190]: Destination timeout has elapsed, closing connection; fd='27'
Dec  3 11:53:34 OPNsense.localdomain syslog-ng[39013]: Destination timeout has elapsed, closing connection; fd='5'
Dec  3 11:53:36 OPNsense.localdomain syslog-ng[42398]: Destination timeout has elapsed, closing connection; fd='5'
Dec  3 11:54:07 OPNsense.localdomain syslog-ng[74190]: Destination timeout has elapsed, closing connection; fd='24'
Dec  3 11:54:09 OPNsense.localdomain syslog-ng[74190]: Destination timeout has elapsed, closing connection; fd='27'
Dec  3 11:54:34 OPNsense.localdomain syslog-ng[39013]: Destination timeout has elapsed, closing connection; fd='5'
Dec  3 11:54:36 OPNsense.localdomain syslog-ng[42398]: Destination timeout has elapsed, closing connection; fd='5'
Dec  3 11:55:09 OPNsense.localdomain syslog-ng[74190]: Destination timeout has elapsed, closing connection; fd='24'
Dec  3 11:55:11 OPNsense.localdomain syslog-ng[74190]: Destination timeout has elapsed, closing connection; fd='27'
Dec  3 11:55:34 OPNsense.localdomain syslog-ng[39013]: Destination timeout has elapsed, closing connection; fd='5'
Dec  3 11:55:36 OPNsense.localdomain syslog-ng[42398]: Destination timeout has elapsed, closing connection; fd='5'

## Steps to reproduce
Just enable a remote target in OPNsense

## Configuration
Configuration is templated to several files, for more information here is a thread in the forums with most details:
https://forum.opnsense.org/index.php?topic=18363.0

The current workaround is to silence this message but I have no idea where it comes from and it only appears when adding remote syslog.

**Comment by furiel** [comment]
Sorry for that! We accidentally enabled that log on notice level, hence it is written unconditionally, even though it is only a diagnostical log. This problem is fixed in https://github.com/syslog-ng/syslog-ng/pull/3444. The correction is available in 3.30.

**Comment by mimugmail** [comment]
Awesome, thanks for this one! 👍
