### ISSUE TITLE
Invalid checksum of 0 in UDP6 packet when using spoof_source(yes)

### ISSUE THREAD

**Issue by mjducharme** [syslog-ng/syslog-ng#3525]
Hello,

spoof_source(yes) works fine in IPv4. In IPv6, it does correctly spoof the source, but creates an invalid checksum 0 for the packet, and so it ends up being dropped by the receiver as invalid. If spoof_source(no) is used instead, then the IPv6 checksum is calculated correctly, and so the packet is correctly processed by the receiver.

I suspect the issue might be that this "temporary workaround" is no longer working:

https://github.com/syslog-ng/syslog-ng/blob/1a7cc761b6c61c4abd2bcfaea4c6af3be6d862cc/modules/afsocket/afinet-dest.c#L552

Very likely that workaround is not needed anymore because it was added 8 years ago.

**Comment by alltilla** [comment]
Hi,

Thanks for your report! :)

Unfortunately, I couldn't find what bug is there in libnet 1.1.2, and why it was worked around this way.
I will locally remove this line, test it with libnet 1.1.2, and find out why it was added. If it is safe to remove with newer versions, I will do so.

I will keep you posted.
Cheers!
