### ISSUE TITLE
Unable to compile 3.30.1.  No "configure" file, autogen.sh fails.

### ISSUE THREAD

**Issue by bsilva-bentlabs** [syslog-ng/syslog-ng#3534]
# syslog-ng
## Version of syslog-ng
3.30.1

## Platform
Ubuntu 20.04

## Steps to reproduce
No "configure" file was present, so tried "autogen.sh".
Note that I did not do a "make clean" or anything else.  The first command run after unpacking the code is below.
./autogen.sh
Running autogen in 'lib/ivykis'...
Don't know how to bootstrap submodule 'lib/ivykis'

Tried several sources for the source code.
Github clone, 
Both tarballs on the Releases page (why are there two?)

Same result.

Thanks,
Brad

**Comment by MrAnno** [comment]
Hello @bsilva-bentlabs,

The release tarball for v3.30.1 can be found here:
https://github.com/syslog-ng/syslog-ng/releases/download/syslog-ng-3.30.1/syslog-ng-3.30.1.tar.gz

This archive contains the generated `configure` script, no need to run `autogen.sh`.

> (why are there two?)

`Source code (tar.gz)` and `Source code (zip)` are generated automatically by GitHub, they are exact copies of the latest git version tag. They are not for "end users".

**Comment by MrAnno** [comment]
Please reopen if you have any further questions/problems on how to compile syslog-ng from source.
