### ISSUE TITLE
Pattern DB optional space

### ISSUE THREAD

**Issue by rfaircloth-splunk** [syslog-ng/syslog-ng#3539]
## Description of the problem
The use of @SET:: @ In Some cases a position may be optional for example 

*July
Jul

## Proposed solution
The asterisk may be optional have an OPTIONALSET version of SET that can be omitted

## Alternatives
@PCRE@ however this is slower

**Comment by alltilla** [comment]
Hi Ryan,

I have prepared a [PR](https://github.com/syslog-ng/syslog-ng/pull/3540) for this feature request. Can you build from source? It would be nice if you could verify the new behavior.

**Comment by faxm0dem** [comment]
I could think of many places in my patterndb this could be useful :+1:

**Comment by rfaircloth-splunk** [comment]
I just spent two weeks getting personal with patterndb its allowed me to double throughput in lab tests compared to my prior use of filters. Let me see if I can get a source build working I recently discontinued building from source in favor of using the rpms provided

**Comment by bazsi** [comment]
Every pull request builds an rpm as a part of the ci run.

https://github.com/syslog-ng/syslog-ng/pull/3540/checks?check_run_id=1726459607

Look for the artifacts drop down.
