### ISSUE TITLE
Syslog-ng TLS 3.30.1 not listening on port 6515

### ISSUE THREAD

**Issue by junier16** [syslog-ng/syslog-ng#3545]
I configure the conf file on syslog-ng server to listen on port 6514 and for reason is not listening on the port. No error messages on syslog. Im not very famaliar with Syslog. Any help is appreciated 

source source_6514_tls {
tcp(port(6514)
tls(
key-file("/etc/syslog-ng/cert.d/server.key")
cert-file("/etc/syslog-ng/cert.d/server.crt")
peer-verify(optional-untrusted)
)
flags(no-multi-line)
);
};

destination dest_6514_local { file("/var/log/syslog/logs"); };

log {source(source_6514_tls); destination(dest_6514_local); };

**Comment by bazsi** [comment]
Syslog-ng's own internal logs are logged into the internal () source which
is not present in your config.

Alternatively you can tell syslog-ng to logs its messages to stderr using
the -e option.

I think you should try running syslog-ng in the foreground and see if
there's a problem.

Here's how:

# /sbin/syslog-ng -Fedv

Make sure the syslog-ng service is not running when you start syslog-ng in
the foreground.

**Comment by Kokan** [comment]
Please if the issue persist, share the debug logs and re-open this issue.
