### ISSUE TITLE
tarball build fails for deb-ubuntu-bionic doxygen missing in container image

### ISSUE THREAD

**Issue by jspurestore** [syslog-ng/syslog-ng#3552]
# syslog-ng
## Version of syslog-ng
3.25.1

## Platform
ubuntu 18.04

I am trying to use dbld/rules to build debians for 3.25.1 on ubuntu 18.04
At the top it pulls the latest bionic docker image:
Unable to find image 'balabit/syslog-ng-ubuntu-bionic:latest' locally
latest: Pulling from balabit/syslog-ng-ubuntu-bionic
d519e2592276: Pulling fs layer
d22d2dfcfa9c: Pulling fs layer
b3afe92c540b: Pulling fs layer
10a9b5a31b22: Pulling fs layer
f229b9f05a0d: Pulling fs layer
8c2f749c3b93: Pulling fs layer
00cdbe59f347: Pulling fs layer
904101d74918: Pulling fs layer
ffe281947d32: Pulling fs layer
2bb9ce4aec19: Pulling fs layer
ca3ffacb9482: Pulling fs layer
8c73940b960b: Pulling fs layer
00cdbe59f347: Waiting
2bb9ce4aec19: Waiting
ca3ffacb9482: Waiting
ffe281947d32: Waiting
904101d74918: Waiting
8c73940b960b: Waiting
10a9b5a31b22: Waiting
f229b9f05a0d: Waiting
d22d2dfcfa9c: Verifying Checksum
d22d2dfcfa9c: Download complete
b3afe92c540b: Verifying Checksum
b3afe92c540b: Download complete
d519e2592276: Verifying Checksum
d519e2592276: Download complete
f229b9f05a0d: Verifying Checksum
f229b9f05a0d: Download complete
10a9b5a31b22: Verifying Checksum
10a9b5a31b22: Download complete
8c2f749c3b93: Verifying Checksum
8c2f749c3b93: Download complete
904101d74918: Verifying Checksum
904101d74918: Download complete
d519e2592276: Pull complete
00cdbe59f347: Verifying Checksum
00cdbe59f347: Download complete
d22d2dfcfa9c: Pull complete
b3afe92c540b: Pull complete
ca3ffacb9482: Verifying Checksum
ca3ffacb9482: Download complete
10a9b5a31b22: Pull complete
f229b9f05a0d: Pull complete
8c2f749c3b93: Pull complete
8c73940b960b: Verifying Checksum
8c73940b960b: Download complete
ffe281947d32: Verifying Checksum
ffe281947d32: Download complete
00cdbe59f347: Pull complete
904101d74918: Pull complete
2bb9ce4aec19: Verifying Checksum
2bb9ce4aec19: Download complete
ffe281947d32: Pull complete
2bb9ce4aec19: Pull complete
ca3ffacb9482: Pull complete
8c73940b960b: Pull complete
Digest: sha256:a31a3e04b98c2bc57477976b1d4b77adcd1da7b7457722a6add6d62300a26d37
Status: Downloaded newer image for balabit/syslog-ng-ubuntu-bionic:latest
Failed to add group ir/100 in docker entrypoint-debian.sh
Submodule 'lib/ivykis' (https://github.com/buytenh/ivykis.git) registered for path 'lib/ivykis'
Submodule 'lib/jsonc' (https://github.com/json-c/json-c.git) registered for path 'lib/jsonc'
Cloning into '/source/lib/ivykis'...
Cloning into '/source/lib/jsonc'...

about 1000 lines later:
 (cd lib/jsonc && make --no-print-directory top_distdir=../../syslog-ng-3.25.1 distdir=../../syslog-ng-3.25.1/lib/jsonc \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
(CDPATH="${ZSH_VERSION+.}:" && cd /source/lib/jsonc && /bin/bash /source/lib/jsonc/missing autoheader)
rm -f stamp-h1
touch /source/lib/jsonc/config.h.in
:
test -d "../../syslog-ng-3.25.1/lib/jsonc" || mkdir "../../syslog-ng-3.25.1/lib/jsonc"
 (cd tests && make  top_distdir=../../../syslog-ng-3.25.1 distdir=../../../syslog-ng-3.25.1/lib/jsonc/tests \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
make  \
  top_distdir="../../syslog-ng-3.25.1" distdir="../../syslog-ng-3.25.1/lib/jsonc" \
  dist-hook
test -d "../../syslog-ng-3.25.1/lib/jsonc/doc" || mkdir "../../syslog-ng-3.25.1/lib/jsonc/doc"
chmod -R u+w "../../syslog-ng-3.25.1/lib/jsonc/doc"
cd "../../syslog-ng-3.25.1/lib/jsonc" && doxygen
/bin/bash: doxygen: command not found
make[3]: *** [dist-hook] Error 127
Makefile:1100: recipe for target 'dist-hook' failed
Makefile:766: recipe for target 'distdir' failed
make[2]: *** [distdir] Error 2
Makefile:22812: recipe for target 'distdir' failed
make[1]: *** [distdir] Error 1
Makefile:22911: recipe for target 'dist' failed
make: *** [dist] Error 2
dbld/rules:91: recipe for target 'tarball-ubuntu-bionic' failed
make: *** [tarball-ubuntu-bionic] Error 2

Sure looks like oxygen is missing from the container image

$ docker images
REPOSITORY                                                      TAG                                        IMAGE ID            CREATED             SIZE
balabit/syslog-ng-ubuntu-bionic                                 latest                                     ed258593ffc8        9 hours ago         1.19GB

**Comment by jspurestore** [comment]
I should add that this is following a clone of the tree and a got checkout syslog-ng-3.25.1

**Comment by bazsi** [comment]
We have created a dedicated image to build our tarballs, which has recently
been converted to debian-testing.

At the same time, the bionic image has been degraded to be able to "build"
a production package from a tarball.

This would work as long as you are using the latest version of syslog-ng,
but you are not.

To fix the issue, just build the image locally, instead of fetching via
docker pull.

./dbld/rules image-ubuntu-bionic

This should create the right image for 3.25 from files right within the
source code.

Honestly, up to now I didn't consider image compatibility with old
syslog-ng versions and I am not sure we can always remain compatible, but
usually we can.

With all this said, thanks for letting us know, I will consider this use
case, the next time we do such reorganizations.

**Comment by jspurestore** [comment]
The workaround is exactly what I needed. I appreciate the quick response. Building the image will also help me with some other things I am having to address.
One possibility is to keep the release versions around as targets other than latest and pull those when working from a release tag like I am. Not sure it's worth the work. I hope this helps the next person who might run into the problem.
If yo udon't want to solve the tag issue, feel free to close the ticket.
