### ISSUE TITLE
how to use unset() with coditions

### ISSUE THREAD

**Issue by AlexProfi** [syslog-ng/syslog-ng#3571]
## Documentation version
3.30
## Incorrect section
unset() description need more examples

## Description of the problem
I try to use this unset(value("source.nat.ip") condition(match("")));
Expected behaviour: delete ip from json object source.nat if ip is blank
but it removes ip always

How to resolve it?

**Comment by bazsi** [comment]
condition () specifies an expression that is independent from the value
specified for unset(), so match() would be applied to MSG by default, which
always matches as the empty text matches everything.

Something like

unset(value("source.nat.ip") condition ("${source.nat.ip" eq ""));


Should work and is a bit faster than using regards via match()

**Comment by AlexProfi** [comment]
Thanks a lot for answer))
