### ISSUE TITLE
[rm: invalid option -- '3'] make syslog-ng 3.29.1 failed

### ISSUE THREAD

**Issue by WigginsLiu2016** [syslog-ng/syslog-ng#3578]
#### Steps
- autoreconf --force --install
- ./configure
- make

#### Result

 ... ...
  CC       syslog-ng/main.o
  CC       syslog-ng-ctl/syslog_ng_ctl_syslog_ng_ctl-syslog-ng-ctl.o
  CC       syslog-ng-ctl/commands/syslog_ng_ctl_syslog_ng_ctl-commands.o
  CC       syslog-ng-ctl/commands/syslog_ng_ctl_syslog_ng_ctl-config.o
  CC       syslog-ng-ctl/commands/syslog_ng_ctl_syslog_ng_ctl-credentials.o
  CC       syslog-ng-ctl/commands/syslog_ng_ctl_syslog_ng_ctl-verbose.o
  CC       syslog-ng-ctl/commands/syslog_ng_ctl_syslog_ng_ctl-ctl-stats.o
  CC       syslog-ng-ctl/commands/syslog_ng_ctl_syslog_ng_ctl-query.o
  CC       syslog-ng-ctl/commands/syslog_ng_ctl_syslog_ng_ctl-license.o
  CCLD     lib/eventlog/src/libevtlog.la
  CCLD     lib/secret-storage/libsecret-storage.la
  CCLD     tests/loggen/libloggen_helper.la
rm: invalid option -- '3'
Try 'rm --help' for more information.
Makefile:9560: recipe for target 'lib/eventlog/src/libevtlog.la' failed
make[2]: *** [lib/eventlog/src/libevtlog.la] Error 1
make[2]: *** Waiting for unfinished jobs....
rm: invalid option -- '3'
Try 'rm --help' for more information.
Makefile:11712: recipe for target 'tests/loggen/libloggen_helper.la' failed
make[2]: *** [tests/loggen/libloggen_helper.la] Error 1
Makefile:22721: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
Makefile:9230: recipe for target 'all' failed
make: *** [all] Error 2
--ERROR: build syslog-ng make failed

It's so strange, does anyone know why this is?

Signed-off-by: wiggin <1228270079@qq.com>

**Comment by Kokan** [comment]
Strange indeed, could you please paste here the whole output. Please use `autogen.sh` instead of `autoreconf`. Additionally use make with verbose (it is either `make V=1` or `make VERBOSE=1` one of it anyway).

**Comment by Kokan** [comment]
I couldn't reproduce the above error even without `autogen.sh`. If this persist please share more details and re-open the issue.
