### ISSUE TITLE
context-* or grep template functions not return all name-value pairs from the current context (grouping-by)

### ISSUE THREAD

**Issue by lucasfersil** [syslog-ng/syslog-ng#3590]
# syslog-ng
## Version of syslog-ng
syslog-ng 3 (3.27.1)

## Platform
Ubuntu 20.10 (Groovy Gorilla)

# Issue
When using _context-values_, _context-lookup_ or _grep_ template functions outside aggregate() (using _grouping-by_ with _context_ as _inherited-mode_), only the last/current required name-value pair is provided, making hard to use other message values from a context, what would be a useful feature. I've also been tested on v3.30 without success. I don't need generate an aggregated message at the timeout of a correlation, but I need refer to nv pairs from context.

**Comment by lucasfersil** [comment]
I will assume that the context-* and grep template functions were projected to work only inside the aggregate() option (I didn't found this information or examples on the documentation) because syslog-ng should have to map the grouping-by' key option value with the equivalent external name-value pairs, otherwise it doesn't would know which context to lookup for values. Also, the grouping-by was made with correlation in mind. I will suggest the implementation of that feature (lookup for context values from outside of aggregate option). My point is to use these values as complement data for output, eg: adding a mail sender to each delivered log message from the same context.

**Comment by bazsi** [comment]
Those template functions work on "message contexts", which exist either within grouping-by() or withing db-parser ()'s correlations.

Message contexts affect the behavior of templates (where you might use $(grep)) and filter expressions (which also allows the use of template strings in comparisons).

grouping-by() has multiple options that accept either a filter expression or a template, whether the context is available for a specific option was decided based on whether the intent behind that option needed it.

For instance: where() is a simple filter expression that drops individual messages, without context being available, while the having() option evaluates the whole context, based on the context. 

aggregate() specifies a template that forms an "output" message based on all the messages in the context, so there the context is available.

trigger() can be used to finish an aggregation (and emit the resulting message) without having to wait for its timeout to expire.

The naming matches how the SQL language uses these terms in a SELECT statement with GROUPING BY. 

Hope this helps.

**Comment by lucasfersil** [comment]
Context values would be useful if also available as data beyond of groping-by(). The needed of refer to past MESSAGE values to complement an output is not uncommon and correlation in many cases isn't the viable solution when is necessary to preserve the MESSAGE and additional parsed data withing output.

**Comment by bazsi** [comment]
The state is maintained by grouping-by(), so it is available only inside
grouping-by. If you want to peek into past messages, you can generate a
new, translated message that includes all data points you will need in a
potential output.

**Comment by lucasfersil** [comment]
The problem is that the use case output is JSON and each message has its own detailed information, but it could be more clear to read if additional values were present. Put all together on the same message not fits well as with audit logs or ssh session logs. My use case is email and the destination is elasticsearch/open distro, but could be any other use case where a same 'session key' is common on certain messages and detailed information needs be searchable. I tried correlate messages and ended up with flat arrays with more than 50 recipients, but related detailed data was lost, like those that require nested objects. From a data modeling point of view, keeping the parsed nv pairs as it are and adding the missing pairs is more efficient and readable.

> The state is maintained by grouping-by(), so it is available only inside grouping-by. If you want to peek into past messages, you can generate a new, translated message that includes all data points you will need in a potential output.
