### ISSUE TITLE
Will only write to mysql database with the username "mysql" and not any other username

### ISSUE THREAD

**Issue by moscal65** [syslog-ng/syslog-ng#3596]
Was pulling my hair out on this for a few days. Like the title says, no other username except for "mysql" will allow syslog-ng to write to a mysql database. 

- syslog-ng-core 3.25.1-3 amd64
- syslog-ng-mod-sql 3.25.1-3 amd64
- libdbd-mysql 0.9.0-8ubuntu1 amd64
- mysql-server 8.0.23-0ubuntu0.20.04 amd64
- mysql-server-core-8.0 8.0.23-0ubuntu0.20.04.1 amd64
- Ubuntu 20.04.2 LTS

Table created:
```
CREATE TABLE `syslogs` (
  `seq` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `datetime` datetime DEFAULT NULL,
  `host` text DEFAULT NULL,
  `priority` text DEFAULT NULL,
  `program` text DEFAULT NULL,
  `msg` text,
  PRIMARY KEY (`seq`)
);
```

Mysql user was created and granted privs:
```
CREATE USER 'syslog'@'%' IDENTIFIED BY 'password';
GRANT ALL on *.* to 'syslog'@'%';
FLUSH PRIVILEGES;
```

syslog-ng.conf modified:
```
source s_network {
    syslog(transport("udp"));
    syslog(transport("tcp") port(514)); 
};

destination d_mysql {
  sql(
    type(mysql)
    host("127.0.0.1")
    username("syslog")
    password("password")
    database("home")
    table("syslogs")
    columns("datetime", "host", "priority", "program", "msg")
    values("${R_ISODATE}", "${HOST}", "${PRIORITY}", "${PROGRAM}", "${MSGONLY}")
    indexes("datetime", "host")
  );
};

filter f_3925 { host(192.168.0.1); };

log {
        source(s_network);
        filter(f_3925);                                 
        destination(d_mysql);             
        flags(final);
};
```

No rows were being inserted into the syslog mysql table at this point. Only after changing the username to "mysql" did it work.

```
CREATE USER 'mysql'@'%' IDENTIFIED BY 'password';
GRANT ALL on *.* to 'mysql'@'%';
FLUSH PRIVILEGES;
```

After which I updated syslog-ng.conf with the new username/password, restarted service, and all is well. I did not see any documentation indicating that "mysql" had to be the username used by syslog-ng. Is this actually the case?

**Comment by Kokan** [comment]
There is no such restriction on username. syslog-ng simply passes the username/password to libdbi (the layer handles database communication). Could you please check and share the internal logs of syslog-ng ?
You can obtain them for example running syslog-ng in foreground with `-Fe` (where `-F` is to run in foreground, and `-e` is to print internal logs to the `stderr`).

There should be an error message at least, why it cannot insert an entry to the database.

**Comment by moscal65** [comment]
Sorry, it ended up being a permissions issue with the mysql user. Didn't realize I had also created the user under localhost as well. Thanks!

**Comment by Kokan** [comment]
I'm happy it worked out in the end. Closing the issue.
