### ISSUE TITLE
 Syslog-ng Disk Space Expansion 

### ISSUE THREAD

**Issue by raguvaranarumuagm** [syslog-ng/syslog-ng#3605]
Hi Team,

We are using below syslog-ng as application logging server in our production environment. 

Currently, we are unable to login to web console due to disk space issue (out of free disk space). 

However, we are able to login to syslog-ng server using ssh and found /(root) filesystem usage is 100%.

/mnt/drbd/private folders occupies 100% and unable remove any files under that, as files are very important.

We have available storage under ESXi for storage expansion.

Kindly advise us with the steps to increase the disk size without any impact and alternate options to fix this issue.
[syslog-ng_disk_space_issue.docx](https://github.com/syslog-ng/syslog-ng/files/6132864/syslog-ng_disk_space_issue.docx)

**Comment by bazsi** [comment]
This mailing list is about the syslog-ng open source edition, even if we
wanted to help you we couldn't as syslog-ng store box is an appliance,
containing the premium edition, which is not something that I have access
to.

Also, disk space issues are definitely closer to the appliance in terms of
support than the syslog-ng instance within it.

**Comment by jszigetvari** [comment]
Hi @raguvaranarumuagm,

As @bazsi mentioned this is the project that develops, maintains and manages the syslog-ng OSE (Open-Source Edition) software.
The product that you seem to be using is the syslog-ng Store Box, which is a commercial product, that is sold and supported by One Identity.
If you have an active support contract with One Identity, then you can open a support ticket at: https://support.oneidentity.com/create-service-request/
