### ISSUE TITLE
loggen -  incorrect debug message

### ISSUE THREAD

**Issue by LittleFish33** [syslog-ng/syslog-ng#3623]
# syslog-ng
## Version of syslog-ng
the source code in master branch

## Platform
Ubuntu 16.04

# Issue
## Failure
Hi, I am a programmer who wants to contributes to syslog-ng. While I try to fix issue #3469, I get another issue. First, I compile the source code and test the `loggen` module in my Ubuntu. The command I use is:

```
loggen -i -r 1000 -I 60 -P --read-file /home/qiuxy/tmp/input -l --active-connections 1 -F 192.168.133.1 50468 --debug
```

And then I get the following debug messages:

```
debug [socket_plugin.c:active_thread_func:350] thread (ssl-plugin,0x822c00) created. wait for start ...
debug [socket_plugin.c:active_thread_func:359] thread (ssl-plugin,0x822c00) started. (r=1000,c=0)
```

this debug message is printed by the  `active_thread_func` function of  `socket_plugin.c`, while the message on the back says ` thread (ssl-plugin,0x822c00)`. This is conflict with the `[socket_plugin.c:active_thread_func:350]`.

## Steps to reproduce
install the syslog-ng and use the following command:

```
loggen -i -r 1000 -I 60 -P --read-file /home/qiuxy/tmp/input -l --active-connections 1 -F 192.168.133.1 50468 --debug
```

`/home/qiuxy/tmp/input` , `192.168.133.1` and `50468` should be changed according to your configuration.

## Additional context

I have reviewed the source code related to the `loggen` modules. I see `loggen` has two plugins: `socket-plugin`  and `ssl-plugin`. Each plugin has a `loggen_plugin_info` object as:

```c++
// in socket-plugin.c
PluginInfo loggen_plugin_info =
{
  .name = "socket-plugin",
  // ...
};

// in ssl-plugin.c
PluginInfo loggen_plugin_info =
{
  .name = "ssl-plugin",
  // ...
};
```

And one of the debug message I show above is printed by the following code:

```c++
DEBUG("thread (%s,%p) created. wait for start ...\n", loggen_plugin_info.name, g_thread_self());
```

I think the original intention of the this code is to called the `loggen_plugin_info` object defined in their respective files. Therefore, for socket-plugin.c, it is expected to print:

```
debug [socket_plugin.c:active_thread_func:350] thread (socket-plugin,0x822c00) created. wait for start ...
```

However, the test result shows otherwise. I think this is because `socket-plugin` and `ssl-plugin` is implemented as shared libraries, i.e., `libloggen_socket_plugin.so` and `libloggen_ssl_plugin.so`. If these two file have global variables with the same identifier, one of them will become invisible.

An related example can be found in [Linking two shared libraries with some of the same symbols](https://stackoverflow.com/questions/6538501/linking-two-shared-libraries-with-some-of-the-same-symbols).

To verify this, I add an line in the `is_plugin_activated` function of these two plugins:

```c++
DEBUG("the address of loggen_plugin_info in ssl_plugin: %p\n", &loggen_plugin_info);
```

And then I get the following debug messages:

```
debug [ssl_plugin.c:is_plugin_activated:87] the address of loggen_plugin_info in ssl_plugin: 0x7f1b35be12a0
debug [socket_plugin.c:is_plugin_activated:94] the address of loggen_plugin_info in socket_plugin: 0x7f1b35be12a0
```

It can be observed that despite `loggen_plugin_info` is called from different `.c` files, the address of it is the same. This verifies the above guess, the use of shared libraries makes one of the `loggen_plugin_info` invisible.

## Proposed solution

I found the `loggen_plugin_info` is used in two places:

* get plugin info from lib file with g_module_symbol (see loggen.c, line 196)
* output DEBUG message with `loggen_plugin_info.name`

Therefore, we can directly declare a `gchar*` variable with different identifiers:

```c++
// in socket-plugin.c
PluginInfo loggen_plugin_info =
{
  .name = "socket-plugin",
  // ...
};
const gchar* loggen_socket_plugin_name = "socket-plugin";

// in ssl-plugin.c
PluginInfo loggen_plugin_info =
{
  .name = "ssl-plugin",
  // ...
};
const gchar* loggen_ssl_plugin_name = "ssl-plugin";
```

And then we can use it to replace the original one. An example is:

```c++
DEBUG("thread (%s,%p) created. wait for start ...\n", loggen_socket_plugin_name, g_thread_self());
```

**Is there a problem with my idea? And if it is okay, I would like to work on this issue by submitting a pull request. It would be my pleasure!**

**Comment by bazsi** [comment]
What if you specified the static qualifier? Would that help?

**Comment by LittleFish33** [comment]
> What if you specified the static qualifier? Would that help?

I have tried to specify a static qualifier before `loggen_plugin_info`, but unfortunately, it didn't work. In fact, it leads to another new problem.

I get the following output (I change the line 197 of loggen.c file from `DEBUG` to `ERROR`):

```
error [loggen.c:enumerate_plugins:197] libloggen_ssl_plugin.so isn't a plugin for loggen. skip it. ('loggen_plugin_info': /home/qiuxy/install/syslog-ng/lib/syslog-ng/loggen/libloggen_ssl_plugin.so: undefined symbol: loggen_plugin_info)
error [loggen.c:enumerate_plugins:197] libloggen_socket_plugin.so isn't a plugin for loggen. skip it. ('loggen_plugin_info': /home/qiuxy/install/syslog-ng/lib/syslog-ng/loggen/libloggen_socket_plugin.so: undefined symbol: loggen_plugin_info)
```

I think this is because the scope of a static variable is local to the block in which the variable is defined. As a result, we can't use `g_module_symbol(module, LOGGEN_PLUGIN_INFO, (gpointer *) &plugin)` to load the plugin.

**Comment by Kokan** [comment]
I do not think that hiding the real issue with extracting and renaming plugin name solve the issue. As the `PluginInfo` does have different fields (I guess those are not accessed currently the same way, thus not causing an issue.)

You could mark them `const` and that should resolve the issue.

**Comment by LittleFish33** [comment]
> I do not think that hiding the real issue with extracting and renaming plugin name solve the issue. As the `PluginInfo` does have different fields (I guess those are not accessed currently the same way, thus not causing an issue.)
> 
> You could mark them `const` and that should resolve the issue.

Yes, this works. If you accept, it would be my pleasure to commit a pull request.

**Comment by Kokan** [comment]
I do not like the fact that the same global name is reused(the global name collision happens in syslog-ng modules as well).

If you create a PR with marking these loggen plugins, I'd approve it.

**Comment by LittleFish33** [comment]
> I do not like the fact that the same global name is reused(the global name collision happens in syslog-ng modules as well).

@Kokan I agree with you, I think there may be another approach. Because the dynamic linked libraries of plugins are `libloggen_ssl_plugin.so` and `libloggen_socket_plugin.so`, we can infer the name of target plugins from the library name. Specifically, 

first, we rename the `loggen_plugin_info` in socket_plugin.c (take it for example, same for ssl_plugin.c):

```c++
PluginInfo socket_loggen_plugin_info =
{
  .name = "socket-plugin",
  // ...
};
```

Second, we define two Macro in `loggen_plugin.h` , which will be used later:

```c++
#define LOGGEN_PLUGIN_INFO_DELIMITERS "_"
#define LOGGEN_PLUGIN_INFO_NAME_MAXSIZE 100
```

Thrid, we change the code in `loggen.c`, which infers the name of `PluginInfo` variable from the `fname` (for `socket_plugin`, the fname will be ``libloggen_socket_plugin.so``):

```c++
gchar *full_lib_path = g_build_filename(plugin_path, fname, NULL);
module = g_module_open(full_lib_path, G_MODULE_BIND_LAZY);
g_free(full_lib_path);
gchar **fname_split = g_strsplit (fname, LOGGEN_PLUGIN_INFO_DELIMITERS, -1);

if (!module || g_strv_length(fname_split) < 3)
{
    ERROR("error opening plugin module %s (%s)\n", fname, g_module_error());
    continue;
}

// infers the name of `PluginInfo` 
g_snprintf(plugin_name, LOGGEN_PLUGIN_INFO_NAME_MAXSIZE, "%s_%s", fname_split[1], LOGGEN_PLUGIN_INFO); 
/* get plugin info from lib file */
PluginInfo *plugin;
if (!g_module_symbol(module, plugin_name, (gpointer *) &plugin))
{
    DEBUG("%s isn't a plugin for loggen. skip it. (%s)\n", fname, g_module_error());
    g_module_close(module);
    continue;
}

g_strfreev(fname_split);
```

I've tested this approach which work well. Which solution would you prefer?

**Comment by Kokan** [comment]
Yes, the approach to use different name based on filename can work. The only downside that you create a connection between naming that variable and naming the `.so` files, which could yield confusion if one is changed. But I think it is manageable in case of loggen plugin. So I would prefer the option you presented just now.

But instead splitting up the name via `_`, I would remove the prefix `libloggen_` and suffix `_plugin*` and use the name between. As somebody might create name with double underline in it.
