### ISSUE TITLE
Syslog-ng logging LogLevels

### ISSUE THREAD

**Issue by willcey** [syslog-ng/syslog-ng#3625]
Hello

I am running syslog-ng as a "Proxy" to receive messages from the internet over TLS and forward them to an internal tcp syslog server. The syslog-ng is also used to terminate the TLS connection.

If i am running syslog-ng in debug mode, i see the message which i receive including the TLS Handshakes which are made with the remote party.

For future investigation purposes (if there are customer complaints) i would like to extend the logging a bit.

The configuration for the syslog-ng logging looks as follows:
```
source s_sys {
    system();
    internal();
};
...
destination d_sysl { file("/var/log/syslog-ng"); };
...
filter f_syslog-ng  { program("syslog-ng"); };
...
log { source(s_sys); filter(f_syslog-ng); destination(d_sysl); };
```

My source where the customer is sending to looks as follows:
```
source customer_int_tls_source {
        syslog(ip(x.x.x.x)
                port(7000)
                transport("tls")
                tls(
                        key-file("/etc/syslog-ng/cert.d/server_ext.key")
                        cert-file("/etc/syslog-ng/cert.d/server_ext.pem")
                        ca-dir("/etc/syslog-ng/ca.d/customer_int")
                        peer-verify(required-trusted)
                        ssl-options(no-sslv2, no-sslv3, no-tlsv1, no-tlsv11)
                        trusted-keys(
                                "SHA1:XX"
                        )

                )
        );
};
```
Is there a possibility to log received messages and TLS handshakes without running syslog-ng in debug mode forever? Is there something like "LogLevels" which i can configure for the syslog-ng itself?

At the moment the only solution i have is to create a second destination where i can log the message received, but that does not give me the handshake information.

Thank you in advance.
willcey

**Comment by Kokan** [comment]
> Is there a possibility to log received messages and TLS handshakes without running syslog-ng in debug mode forever?

I do not think so, unless you are willing to change the code.

> Is there something like "LogLevels" which i can configure for the syslog-ng itself?

Not in the configuration. But you can use `syslog-ng-ctl` to change log level on the fly (without restart or reload).
Example: `syslog-ng-ctl debug --set=<on|off|0|1>`.
