### ISSUE TITLE
Failure to detect log rotations of PuppetServer / PuppetDB

### ISSUE THREAD

**Issue by smortex** [syslog-ng/syslog-ng#3633]
# syslog-ng
## Version of syslog-ng
Latest: 3.31.2-1 (deb); 3.31.2-1.el7 (rpm); Previous versions where affected too, this is _not_ a regression recently introduced.

## Platform
Debian 10 / CentOS 7; With all updates; Bare metal

## Debug bundle
N/A, no crash

# Issue
## Failure
When using syslog-ng to process the logs from the _[PuppetServer](https://github.com/puppetlabs/puppetserver/)_ or the _[PuppetDB](https://github.com/puppetlabs/puppetdb/)_ services, sometimes syslog-ng fails to detect that log have been rotated.  Logs are not collected/processed/stored by syslog-ng setup (in our case the log is send to ElasticSearch):

![image](https://user-images.githubusercontent.com/148721/113189558-06163380-91f7-11eb-89c9-de46b3272ec5.png)

Restarting syslog-ng allows it to catch-up with the missed entries in the log:

![image](https://user-images.githubusercontent.com/148721/113192234-3a3f2380-91fa-11eb-9b96-6a97ba761d01.png)

As you can see on the above graph, sometimes syslog-ng detects something happen the second or third rotation, sometimes event later, but it seems not to be something predictible / reproducible.

The same issue appears with _PuppetDB_, developed by the same company with the same tooling.  Since PuppetDB is way more painful to deploy, I will focus on PuppetServer for now.

## Steps to reproduce
Install Open Source PuppetServer.  On Debian:

```
wget http://apt.puppet.com/puppet7-release-bionic.deb # adjust bionic if needed to the Debian release used
dpkg -i puppet7-release-bionic.deb
apt-get update
apg-get install puppetserver
vi /etc/hosts # edit the 127.0.0.1 line and add `puppet` so that `ping puppet` works
systemctl start puppetserver
systemctl start puppet
```

This is a rather minimal setup, with this the _Puppet (Agent)_ service will query the _Puppet Server_ every 30 minutes and each time, some logging will happens in `/var/log/puppetlabs/puppetserver/puppetserver.log`

This log file is rotated everyday with the default configuration

## Configuration

Stripped-down `syslog-ng.conf`:

```
@version: 3.30
@include "scl.conf"
options {
    create-dirs(yes);
    frac-digits(6);
    use-fqdn(yes);
};

rewrite r_riemann_tag {
    set-tag(
        "syslog-ng"
    );
};

rewrite r_puppetserver {
  set-severity("${.puppetserver.severity}");
};

parser p_puppetserver {
  date-parser(format('%Y-%m-%dT%H:%M:%S.%f%z') template("${.puppetserver.timestamp}"));
};

parser p_patterndb {
    db_parser(
        file(
            "/var/lib/syslog-ng/patterndb/default.xml"
        )
    );
};

source s_puppetserver {
    file(
        "/var/log/puppetlabs/puppetserver/puppetserver.log",
        flags(
            no-parse
        ),
        program_override(
            "puppetserver"
        ),
        multi_line_mode(
            regexp
        ),
        multi_line_prefix(
            '\d{4}-\d{2}-\d{2}T'
        ),
        multi_line_timeout(
            4
        )
    );
};

log {
    source(s_puppetserver);
    parser(p_patterndb);
    parser(p_puppetserver);
    rewrite(r_puppetserver);
    rewrite(r_riemann_tag);
    destination(d_riemann);
};
```

Stripped-down PatternDB configuration:
```xml
<?xml version='1.0' encoding='UTF-8'?>
<patterndb version='4' pub_date='2021-03-03'>
    <!-- ... -->
        <ruleset name='puppetserver' id='7fc67fd9-ef16-4fce-808a-632cf7cc95bd'>
                <description>generated by puppet</description>
                <patterns>
                        <pattern>puppetserver</pattern>
                </patterns>
                <rules>
                        <rule provider='puppet' id='491b346f-4f02-475e-95e8-cb691f305286' class='system'>
                                <patterns>
                                        <pattern>@ESTRING:.puppetserver.timestamp: @@STRING:.puppetserver.severity@ @QSTRING:.puppetserver.thread_name:[]@ @QSTRING:puppetserver.category:[]@ @ANYSTRING:puppetserver.message@</pattern>
                                        <pattern>@ESTRING:.puppetserver.timestamp: @@STRING:.puppetserver.severity@  @QSTRING:.puppetserver.thread_name:[]@ @QSTRING:puppetserver.category:[]@ @ANYSTRING:puppetserver.message@</pattern>
                                </patterns>
                                <examples>
                                        <example>
                                                <test_message program='puppetserver'>2021-02-04T13:23:36.354-05:00 ERROR [qtp1102047314-254822] [puppetserver] Puppet Evaluation Error: Error while evaluating a Function Call, Could not find class ::mcollective_agent_bolt_tasks for vps238244.vittoria.pro (file: /etc/puppetlabs/code/environments/production/modules/mcollective/manifests/init.pp, line: 77, column: 3) on node vps238244.vittoria.pro</test_message>
                                                <test_values>
                                                        <test_value name='.puppetserver.severity'>ERROR</test_value>
                                                        <test_value name='.puppetserver.thread_name'>qtp1102047314-254822</test_value>
                                                        <test_value name='.puppetserver.timestamp'>2021-02-04T13:23:36.354-05:00</test_value>
                                                        <test_value name='puppetserver.category'>puppetserver</test_value>
                                                        <test_value name='puppetserver.message'>Puppet Evaluation Error: Error while evaluating a Function Call, Could not find class ::mcollective_agent_bolt_tasks for vps238244.vittoria.pro (file: /etc/puppetlabs/code/environments/production/modules/mcollective/manifests/init.pp, line: 77, column: 3) on node vps238244.vittoria.pro</test_value>
                                                </test_values>
                                        </example>
                                        <example>
                                                <test_message program='puppetserver'>2021-02-04T13:22:47.081-05:00 INFO  [qtp1102047314-255208] [puppetserver] Puppet Caching facts for desktop-8snl8la.lan</test_message>
                                                <test_values>
                                                        <test_value name='.puppetserver.severity'>INFO</test_value>
                                                        <test_value name='.puppetserver.thread_name'>qtp1102047314-255208</test_value>
                                                        <test_value name='.puppetserver.timestamp'>2021-02-04T13:22:47.081-05:00</test_value>
                                                        <test_value name='puppetserver.category'>puppetserver</test_value>
                                                        <test_value name='puppetserver.message'>Puppet Caching facts for desktop-8snl8la.lan</test_value>
                                                </test_values>
                                        </example>
                                        <example>
                                                <test_message program='puppetserver'>2021-02-04T13:55:42.518-05:00 WARN  [qtp1102047314-255768] [puppetserver] Scope(Class[Nginx::Package::Debian]) You must set $package_name to &quot;nginx-extras&quot; to enable Passenger</test_message>
                                                <test_values>
                                                        <test_value name='.puppetserver.severity'>WARN</test_value>
                                                        <test_value name='.puppetserver.thread_name'>qtp1102047314-255768</test_value>
                                                        <test_value name='.puppetserver.timestamp'>2021-02-04T13:55:42.518-05:00</test_value>
                                                        <test_value name='puppetserver.category'>puppetserver</test_value>
                                                        <test_value name='puppetserver.message'>Scope(Class[Nginx::Package::Debian]) You must set $package_name to &quot;nginx-extras&quot; to enable Passenger</test_value>
                                                </test_values>
                                        </example>
                                </examples>
                                <actions>
                                </actions>
                        </rule>
                </rules>
        </ruleset>
    <!-- ... -->
</patterndb>
```

## Input and output logs (if possible)
N/A

**Comment by smortex** [comment]
Using the TZ of the server in the browser helps seeings the issue:

![image](https://user-images.githubusercontent.com/148721/113197747-be94a500-9200-11eb-90df-c952a669fc76.png)

Cc @faxm0dem since he is using the same tooling :grin: have you tried this?

**Comment by Kokan** [comment]
I tried to reproduces your issue based on your configuration, but rather using puppet a simple hand made log source[1]. With that I could conjure a case where messages are not read from the file. (messages just written into the file before move).
I think this behavior is not what you just described, it is still strange to see not to pick up messages from a file for days.
Do you have any logs from syslog-ng when it starts to detect changes in the file (I am looking for any error logs, as we have a few of those when it picks up file content changed.)

What I would suggest as of now is to replace the simple file source with a wildcard-file source, where the pattern matches the original file and the rotated ones as well. That picked up logs for me. In the meantime I'll try to reproduce exactly your issue and see what can be the root cause.


[1]
 ```bash
bash -c 'seq 11 | xargs -I{} echo "9999-99-99Tmessage{}
                                                   message_part" >> /tmp/puppet/puppetserver.log' && mv /tmp/puppet/puppetserver.log /tmp/puppet/puppetserver.log.1 && touch /tmp/puppet/puppetserver.log
```

**Comment by smortex** [comment]
Hum, I guess it's not what I see since the last messages seems to be present, but I only have a dozen lines per minute in this file.

While looking to do what you say, I realized that the rotated files are immediately compressed, and maybe some kind of race condition is happening.  I guess the file is renamed, compressed and then deleted, while a new file is being created with the original name. I have a puppet server that is supposed to do this in a few hours, I'll check the files inodes:

```sh-session
root@xxxxxxx /var/log/puppetlabs/puppetserver # ls -lirt | tail
102112644 -rw-r-----. 1 puppet puppet  369567  4 avril 00:00 puppetserver-2021-04-03.0.log.gz
102113725 -rw-r-----. 1 puppet puppet  296444  4 avril 00:00 puppetserver-access-2021-04-03.0.log.gz
102111681 -rw-r-----. 1 puppet puppet  294410  5 avril 00:00 puppetserver-access-2021-04-04.0.log.gz
102113472 -rw-r-----. 1 puppet puppet  369200  5 avril 00:00 puppetserver-2021-04-04.0.log.gz
102109048 -rw-r-----. 1 puppet puppet  293842  6 avril 00:00 puppetserver-access-2021-04-05.0.log.gz
102113305 -rw-r-----. 1 puppet puppet  365023  6 avril 00:00 puppetserver-2021-04-05.0.log.gz
102106288 -rw-r-----. 1 puppet puppet  303747  7 avril 00:00 puppetserver-access-2021-04-06.0.log.gz
102106362 -rw-r-----. 1 puppet puppet  375647  7 avril 00:00 puppetserver-2021-04-06.0.log.gz
102105337 -rw-r-----. 1 puppet puppet 2368420  7 avril 18:42 puppetserver.log
102105235 -rw-r-----. 1 puppet puppet 2893699  7 avril 18:42 puppetserver-access.log
root@xxxxxxx /var/log/puppetlabs/puppetserver #
```

Logs are managed by [Logback](http://logback.qos.ch/), I'll try to see if I can build a minimalist "thing" that reproduce the issue.  Maybe with some luck, when using the same config, logging "a lot" of data (dozens of MB), I will be able to reproduce the issue in a timely fashion…

**Comment by smortex** [comment]
After rotation:

```sh-session
root@xxxxxxx /var/log/puppetlabs/puppetserver # ls -lirt | tail
102111681 -rw-r-----. 1 puppet puppet 294410  5 avril 00:00 puppetserver-access-2021-04-04.0.log.gz
102113472 -rw-r-----. 1 puppet puppet 369200  5 avril 00:00 puppetserver-2021-04-04.0.log.gz
102109048 -rw-r-----. 1 puppet puppet 293842  6 avril 00:00 puppetserver-access-2021-04-05.0.log.gz
102113305 -rw-r-----. 1 puppet puppet 365023  6 avril 00:00 puppetserver-2021-04-05.0.log.gz
102106288 -rw-r-----. 1 puppet puppet 303747  7 avril 00:00 puppetserver-access-2021-04-06.0.log.gz
102106362 -rw-r-----. 1 puppet puppet 375647  7 avril 00:00 puppetserver-2021-04-06.0.log.gz
102109307 -rw-r-----. 1 puppet puppet 369763  8 avril 00:00 puppetserver-2021-04-07.0.log.gz
102114567 -rw-r-----. 1 puppet puppet 297317  8 avril 00:00 puppetserver-access-2021-04-07.0.log.gz
102105226 -rw-r-----. 1 puppet puppet 131482  8 avril 01:00 puppetserver.log
102105362 -rw-r-----. 1 puppet puppet 161111  8 avril 01:00 puppetserver-access.log
root@xxxxxxx /var/log/puppetlabs/puppetserver #
```

inodes have changed so files are not truncated.

**Comment by bazsi** [comment]
Do you think syslog-ng has enough time to notice/start following the file
before or gets compressed?

**Comment by HofiOne** [comment]
@smortex as Bazsi mentioned it could easily be a timing issue. Anyway, we add some enhancements to the directory and file change detection in the latest syslog-ng release (4.8.1), but to the `wildcard-file()` source, could you please give it a try using that instead of the old `file()` source?

**Comment by HofiOne** [comment]
the behavior of the `file()` source has not changed, so it is normal you did not see any changes, only the `wildcard-file()` was enhanced, I hope it will help you

yepp, your feedback would be appreciated, thanks!

**Comment by smortex** [comment]
> your feedback would be appreciated, thanks!

I changed the config one week ago and saw no issue since then, so the new logic used by `wildcard-file()` seems to be immune to the issue triggered by the `file()` one.

**Comment by smortex** [comment]
Hum, I am not sure to follow, is this issue is being closed because:

1. `file()` is expected to be removed and we only should rely on `wildcard-file()` even to match a single file with a known name; or
2. the logic that seems to works with `wildcard-file()` is being integrated to `file()` to fix it.

I could not find information nor code that indicates one or the other of these scenarios, and while we have a workaround, if the root issue is still present people will continue to face it from time to time.  Maybe the issue should rather stay open until it is fixed so that people can more easily find it the proposed workaround?

**Comment by HofiOne** [comment]
> Hum, I am not sure to follow, is this issue is being closed because:
> 
>     1. `file()` is expected to be removed and we only should rely on `wildcard-file()` even to match a single file with a known name; or
> 
>     2. the logic that seems to works with `wildcard-file()` is being integrated to `file()` to fix it.
> 
> 
> I could not find information nor code that indicates one or the other of these scenarios, and while we have a workaround, if the root issue is still present people will continue to face it from time to time. Maybe the issue should rather stay open until it is fixed so that people can more easily find it the proposed workaround?

- the `file()` source has not changed, it behaves the same
- `wildcard-file()` always had a much better file and directory monitoring capability, now it is even better in some cases (after the latest fixes)

so, you should use `wildcard-file()` source to get a better result

(alternatively, if you want to stay with the `file()` source, as the quoted help page suggested, you must restart syslog-ng by yourself after the log file is rotated)


there will be no fix for this, this is an inherited behavior of the earlier (somehow deprecated `file()` source), `wildcard-file()` source is a proper replacement for the other, please use it

**Comment by faxm0dem** [comment]
I can confirm the problem disappears for opensearch logs when migrating from `file` to `wildcard-file` :+1:
