### ISSUE TITLE
Config option keep-hostname(yes) still tries to resolve hostname using /etc/hosts file

### ISSUE THREAD

**Issue by deepasoni27** [syslog-ng/syslog-ng#3635]
# syslog-ng
## Version of syslog-ng
syslog-ng --version
syslog-ng 3 (3.26.1)
Config version: 3.22
Installer-Version: 3.26.1
Revision: 
Compile-Date: Mar 15 2021 17:12:17
Module-Directory: /usr/lib/syslog-ng
Module-Path: /usr/lib/syslog-ng
Include-Path: /usr/share/syslog-ng/include
Available-Modules: xml,syslogformat,snmptrapd-parser,tfgetent,mod-python,examples,json-plugin,hook-commands,kvformat,http,afuser,add-contextual-data,afprog,afstomp,dbparser,azure-auth-header,pseudofile,disk-buffer,timestamp,afsocket,basicfuncs,system-source,cryptofuncs,tags-parser,stardate,confgen,appmodel,graphite,cef,map-value-pairs,affile,linux-kmsg-format,csvparser
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: on
Enable-TCP-Wrapper: off
Enable-Linux-Caps: on
Enable-Systemd: off

## Platform
ubuntu 4.19.94-rt39
## Debug bundle

# Issue
## Configuration
options {
  keep-hostname(yes);
};

## Input and output logs (if possible)

Do I need to add any other config to disabled DNS resolution

**Comment by deepasoni27** [comment]
We want message to have hostname but no DNS resolution

**Comment by deepasoni27** [comment]
one way I found is to have entry for hosts in /etc/hosts file and that works but according to  documentation can we expect that keep-hostname(yes) should just pick up hostname from message and without  any DNS resolution.

Basically DNS resolution is adding delay in syslog-ng start/reload

**Comment by deepasoni27** [comment]
It would be helpful if I can get a quick response to know if we can avoid /etc/hosts lookup or not during syslog-ng start/reload, 

Thank you

**Comment by bazsi** [comment]
keep-hostname() only affects the incoming log messages. It doesn't affect
the resolution of the name of a target server, as configured in a tcp
destination (or similar).

If you don't want that, use an IP address in your config, so no dns
resolution would happen.

**Comment by deepasoni27** [comment]
Thank a lot,  means I need to add entry for hostname and IP address in /etc/hosts file

**Comment by bazsi** [comment]
Yup, that's a solution.

**Comment by deepasoni27** [comment]
So is It must to add local resolution to avoid DNS or can we make use of "use-dns" options ?. 

I really don't want to resolve DNS for hostname where syslog-ng is started, as my client and server are running on same host. How can I avoid resolution in such case.

Thanks.

**Comment by Kokan** [comment]
If you want to make sure, the suggestion from Bazsi is the best. The `use-dns` works in some cases, but not with all the destination. (like http based destinations uses libcurl to resolve addresses), while network based destination should respect `use-dns` option.

**Comment by bazsi** [comment]
If your destination uses an IP address instead of a hostname in all cases,
dns would not be used. If you do, syslog-ng will try to resolve it
regardless of what you have in use-dns().

Use-dns affects the message flow, e.g. the incoming message will have its
hostname updated, based on the reversal of the sender's IP address, iff
keep-hostname () is set to "no" and use-dns() is yes. In this case if
use-dns() is no, you'd get an IP address instead of a hostname reversed via
DNS.

**Comment by deepasoni27** [comment]
Thanks a lot!.  I got it, use-dns  only effect message flows but we have issue while starting or reload syslog-ng and not with message flow.

We are using only file and http based destination and all destination uses below template

template("${FACILITY}.${LEVEL} ${R_YEAR}-${R_MONTH}-${R_DAY}T${R_HOUR}:${R_MIN}:${R_SEC}.${R_USEC} ${SYS_SN} ${PROGRAM} ${PID} ${MSG}\n");

where we rewrite  SYS_SN as follows
# replace SYS_SN with the proper system serial number
rewrite r_rewrite_sys_sn {
  set(sys_sn()
      value("SYS_SN")
  );
};
I am seeing DNS resolution being attempted for value at SYS_SN(which is system hostname on which syslog-ng server is running). When I saw delay in syslog-ng start or reload, then with strace I observed it is trying to resolve SYS_SN IP address as on some system DNS server is not reachable, it tried to resolve for approx 30s and then gets timeout but when DNS server is reachable it is start/reloads pretty fast. 

I am not clear why syslog-ng start/reload is trying to resolve self hostname.


Thanks

**Comment by Kokan** [comment]
@deepasoni27 could you please paste here a minimal syslog-ng configuration that starts, and does the dns lookup ?

**Comment by deepasoni27** [comment]
$ syslog-ng-ctl config                                                             
@version: 3.26                                                                                                                                
                                                                                                             
@module confgen context(rewrite) name(sys_sn) exec("echo HOST123")
                                                   
# Disable hostname resolution for client messages                 
options {                                                                
  keep-hostname(yes);
};                                                             
                                         
# s_kernel contains kernel log messages.                               
source s_kernel {                                                          
  file("/proc/kmsg" program_override("kernel"));
};
  
# s_dev_log is all log messages logged over the syslog socket at /dev/log,
# which includes everything logged via the `syslog()` C syscall.
source s_dev_log { 
  unix-stream ("/dev/log");
};
  
# s_syslog-ng_internal are messages coming from syslog-ng itself.
source s_syslog-ng_internal {
  internal();
};
  
# messages logged should contain the following in $MSG to support RFC5424 format
# $MSG = MSGID SP STRUCTURED-DATA SP MSG_CONTENT
template descpri {
  template("${FACILITY}.${LEVEL} ${R_YEAR}-${R_MONTH}-${R_DAY}T${R_HOUR}:${R_MIN}:${R_SEC}.${R_USEC} ${SYS_SN} ${PROGRAM} ${PID} ${MSG}\n");
  template_escape(no);
};
  
# d_var_log_messages is the /var/log/messages file, and is designed to contain
# "everything".
destination d_var_log_messages {
  file("/var/log/messages"
        template(descpri)
        perm(0644)
        throttle(400)
  );
};

Above config tries to resolve DNS for hostname on which we start syslog-ng

Thanks!

**Comment by bazsi** [comment]
Ok, so it does it for its own hostname. That makes sense, as syslog-ng
tries to detect its own hostname at startup.

For which it does a dns lookup.

It's considered best practice that the hosts own hostname is listed in
/etc/hosts

You can also override this in /etc/nsswitch.conf

IIRC this resolution is not configurable  in syslog-ng at this point.

**Comment by deepasoni27** [comment]
okay I understood. Thanks a lot !
