### ISSUE TITLE
Tag is not showing in logs

### ISSUE THREAD

**Issue by aniketpant1** [syslog-ng/syslog-ng#3641]
I am taking the logs of client system through syslog-ng version 3.31 and i am using syslog-ng kafka module as destination
```
options {
    flush_lines (0);
    time_reopen (10);
    log_fifo_size (1000);
    chain_hostnames (off);
    use_dns (no);
    use_fqdn (no);
    create_dirs (no);
    keep_hostname (yes);
};

source s_sys {
#    system();
#    internal();
     udp(port(514),tags("tag","TEST"));
};
destination d_kafka {
  kafka-c(config(metadata.broker.list("127.0.0.1:9092")
                   queue.buffering.max.ms("1000"))
        topic("syslog")
        #message("$(format-json --scope rfc5424 --scope nv-pairs)"));
);};
#destination test_logs {
#file(
#            "/var/log/syslog-ng/${YEAR}.${MONTH}.${DAY}logs.log"
#            owner("root")
#            group("root")
#            perm(0777)
#            ); };

log { source(s_sys);  destination(d_kafka); };
# Source additional configuration files (.conf extension only)
@include "/etc/syslog-ng/conf.d/*.conf"
# vim:ft=syslog-ng:ai:si:ts=4:sw=4:et:
```

logs which is consuming by kafka 
```
2021-04-13T13:22:17+05:30 ew1 root[7062]: Hi
2021-04-13T13:24:11+05:30 ew1 systemd[1]: Starting dnf makecache...
2021-04-13T13:24:14+05:30 ew1 dnf[7064]: Copr repo for syslog-ng331 owned by czanik       12 kB/s |  27 kB     00:02
2021-04-13T13:24:18+05:30 ew1 dnf[7064]: Extra Packages for Enterprise Linux Modular 8 - 146 kB/s | 557 kB     00:03
2021-04-13T13:24:30+05:30 ew1 dnf[7064]: Extra Packages for Enterprise Linux 8 - x86_64  790 kB/s | 9.2 MB     00:11
2021-04-13T13:24:33+05:30 ew1 dnf[7064]: Oracle Linux 8 BaseOS Latest (x86_64)            70 MB/s |  32 MB     00:00
2021-04-13T13:24:40+05:30 ew1 dnf[7064]: Oracle Linux 8 Application Stream (x86_64)       77 MB/s |  24 MB     00:00
2021-04-13T13:24:46+05:30 ew1 dnf[7064]: Latest Unbreakable Enterprise Kernel Release 6   66 MB/s |  18 MB     00:00
2021-04-13T13:24:54+05:30 ew1 systemd[1]: dnf-makecache.service: Succeeded.
2021-04-13T13:24:54+05:30 ew1 systemd[1]: Started dnf makecache.
2021-04-13T13:24:54+05:30 ew1 dnf[7064]: Metadata cache created.
```
as you can see tag value is not showing

**Comment by Kokan** [comment]
The default format for kafka-c is `$ISODATE $HOST $MSGHDR$MSG`, you should try to change it and include the `${TAGS}`.

```
destination d_kafka {
  kafka-c(config(metadata.broker.list("127.0.0.1:9092")
                   queue.buffering.max.ms("1000"))
        topic("syslog")
        message("$ISODATE $TAGS $HOST $MSGHDR$MSG"));
);};
```

**Comment by aniketpant1** [comment]
hey @Kokan is there any way to show a tag like `tag: tag_name' and if i use filter then how can i add this filter to message sorry i am new to this syslog-ng

**Comment by Kokan** [comment]
Well you can do: `tag: ${TAGS}` I guess, but likely it is not the thing you want to achieve. I would encourage you to check out the admin guide[1]. It has section describing tags, how you can do filtering based on them, etc.

If you could describe the exact problem you want to solve, we may also help you.

[1] https://www.syslog-ng.com/technical-documents/doc/syslog-ng-open-source-edition/3.30/administration-guide

**Comment by aniketpant1** [comment]
okay , we want to capture pfsense log earlier for this we use syslog-ng to gather the log and store them as a file in system and we also used filebeat which is a tool of elasticsearch the filebeat take the logs from particular directory and send it logstash and logstash  filter the logs and send it to elasticsearch.With the help of filebeat we have the fields and now we are not using filebeat so we   want to some add fields like earlier we had.

**Comment by Kokan** [comment]
You can actually (if you want to) can send directly to elasticsearch[1] the logs from syslog-ng.
Please provide specific example, as it is too general for me to help. (I have no clue what fields means in the context of filebeat, as I've never used that).

For example, I have that metadata based on this, and I would like to send it out like this.

**Comment by Kokan** [comment]
The basic issue have been resolved, so I am closing this ticket now. Feel free to open a new issue, or write to the mail list if you have further questions.

**Comment by aniketpant1** [comment]
Hey @Kokan can i open this same issue or do i have to mail you

**Comment by Kokan** [comment]
You can either open a new issue or send an e-mail to the syslog-ng mail list[1] (please do not send e-mail directly to me, as other might help on public).
I closed this issues, as your original concern about tag set in source, actually works but you have too use `${TAGS}`.
If you studied syslog-ng, and elasticsearch destination/kafka destiantion and have question regarding them feel free to ask them on channels written above.
But mixing issues with different sets of question might be hard to untangle in the future so this one is better to be closed.

[1] https://lists.balabit.hu/mailman/listinfo/syslog-ng
