### ISSUE TITLE
RFC5424 feature indicator for `/dev/log`

### ISSUE THREAD

**Issue by eqvinox** [syslog-ng/syslog-ng#3642]
## Description of the problem

Since #2430 was merged, syslog-ng supports RFC5424 syslog on `/dev/log` on all systems that use a socket there, including Linux.  However, there is no way to detect this support (other than through a `FreeBSD >= 12 || NetBSD >= 5` check)

## Proposed solution

Some way to autodetect 5424 support on `/dev/log` would be great.  Discussion is ongoing in https://github.com/systemd/systemd/issues/19251 on how to do that.  Suggestions welcome ;)

Personally, I think making `/dev/log` a symlink and looking for some string in the symlink destination might be a good option.

## Alternatives

(not applicable, though "do nothing" and stick with old-style pseudo-3164 on `/dev/log` is an option.)

## Additional context

libc might want to detect 5424 support on `/dev/log` in order to provide sub-second timestamps in `syslog()`.

Applications might want to detect 5424 support for timestamps as well as structured data support (if the application is using its own code to send data to `/dev/log` rather than `syslog()`).

**Comment by bazsi** [comment]
I added a detailed comment why I don't necessarily agree with adding RFC5424 to /dev/log (but I can live with it and are willing to support it in default configs of syslog-ng).

https://github.com/systemd/systemd/issues/19251#issuecomment-819538363

**Comment by eqvinox** [comment]
@bazsi so - this issue and the systemd issue are different in a very important way:  systemd-journald gives me (as the application writer) an autodetectable interface that I can send key/value data on, namely `/run/systemd/journal/socket` - if that exists, I can send journald-formatted log messages with nice extra k/v data.

For syslog-ng I have no way to automatically enable k/v data without the user telling me that I can send RFC5424 on `/dev/log`, which already works - there is just no way to detect it.

I'm currently doing this: https://github.com/FRRouting/frr/pull/8458/files#diff-85323d202bf2d01c25ea7316767a24f925946005c22d0c2d519f6605d4c50e01R434-R452  ... which leaves Linux users without k/v data in their logs.

Any suggestions?

**Comment by bazsi** [comment]
How does a normal message look for you? I can see the fields you added, and these fall nicely into the "extra meta information" for the message in the $MSG field, so that actually makes sense. I am just wondering how the rest of the message looks like.

Thanks

**Comment by eqvinox** [comment]
```
<31>1 2021-04-11T22:33:05.257088Z areia bgpd 590103 BGP
[location@50145 tid="590103" id="ZWCSR-M7FG9"]
[keywords@50145 BGP_INST_ASN="65000" VRF="default" NEIGHBOR="192.168.0.123"]
[args@50145 arg1="192.168.0.123" arg2="BGP_Start" arg3="Idle" arg4="Connect" arg5="-1"]
 192.168.0.123 [FSM] BGP_Start (Idle->Connect), fd -1
```

Linebreaks added for readability.

(The "keywords@50145" stuff is not in the PR I linked, that's work in progress.)

**Comment by eqvinox** [comment]
```
<31>1 2021-04-14T18:18:19.719694Z areia-zebra zebra 503987 ZEBRA 
[location@50145 tid="503987" id="ZWE6K-GRWAN" file="zebra/zapi_msg.c" line="763" func="route_notify_internal"]
[args@50145 arg1="connected" arg2="172.22.2.0/26" arg3="254" arg4="2" arg5="0"]
 Not Notifying Owner: connected about prefix 172.22.2.0/26(254) 2 vrf: 0

<31>1 2021-04-14T18:18:19.719719Z areia-zebra zebra 503987 ZEBRA 
[location@50145 tid="503987" id="ZWE6K-GRWAN" file="zebra/zapi_msg.c" line="763" func="route_notify_internal"]
[args@50145 arg1="connected" arg2="fe80::/64" arg3="254" arg4="2" arg5="0"]
 Not Notifying Owner: connected about prefix fe80::/64(254) 2 vrf: 0

<31>1 2021-04-14T18:18:19.719735Z areia-zebra zebra 503987 ZEBRA 
[location@50145 tid="503987" id="ZWE6K-GRWAN" file="zebra/zapi_msg.c" line="763" func="route_notify_internal"]
[args@50145 arg1="kernel" arg2="0.0.0.0/0" arg3="254" arg4="2" arg5="0"]
 Not Notifying Owner: kernel about prefix 0.0.0.0/0(254) 2 vrf: 0

<27>1 2021-04-14T18:18:19.719635Z areia-zebra zebra 503987 ZEBRA 
[location@50145 tid="503989" id="HSYZM-HV7HF" ec="0" file="zebra/kernel_netlink.c" line="689" func="netlink_parse_extended_ack"]
[args@50145 arg1="Carrier for nexthop device is down"]
 Extended Error: Carrier for nexthop device is down

<27>1 2021-04-14T18:18:19.719865Z areia-zebra zebra 503987 ZEBRA 
[location@50145 tid="503989" id="WVJCK-PPMGD" ec="4043309093" file="zebra/kernel_netlink.c" line="872" func="netlink_parse_error"]
[args@50145 arg1="netlink-dp (NS 0)" arg2="Network is down" arg3="RTM_NEWNEXTHOP" arg4="104" arg5="10" arg6="2172075428"]
 netlink-dp (NS 0) error: Network is down, type=RTM_NEWNEXTHOP(104), seq=10, pid=2172075428

<27>1 2021-04-14T18:18:19.719989Z areia-zebra zebra 503987 ZEBRA 
[location@50145 tid="503987" id="P2XBZ-RAFQ5" ec="4043309074" file="zebra/zebra_nhg.c" line="2875" func="zebra_nhg_dplane_result"]
[args@50145 arg1="13"]
 Failed to install Nexthop ID (13) into the kernel

<31>1 2021-04-14T18:18:19.720018Z areia-zebra zebra 503987 ZEBRA 
[location@50145 tid="503987" id="ZWE6K-GRWAN" file="zebra/zapi_msg.c" line="763" func="route_notify_internal"]
[args@50145 arg1="kernel" arg2="169.254.0.0/16" arg3="254" arg4="2" arg5="0"]
 Not Notifying Owner: kernel about prefix 169.254.0.0/16(254) 2 vrf: 0

<31>1 2021-04-14T18:18:19.720026Z areia-zebra zebra 503987 ZEBRA
 [location@50145 tid="503987" id="ZWE6K-GRWAN" file="zebra/zapi_msg.c" line="763" func="route_notify_internal"]
[args@50145 arg1="kernel" arg2="::/0" arg3="254" arg4="2" arg5="0"]
 Not Notifying Owner: kernel about prefix ::/0(254) 2 vrf: 0
```

Some more for context (the message I pasted is a bit untypical with almost the entire message replicated in the args@50145 part)

**Comment by bazsi** [comment]
Thanks for the samples. These are great examples of how RFC5424 should have been used :)

I can see that you basically retain the original message piece, a human readable message while extending the same with meta-information that you wouldn't want to add to the message itself. 

The model that most SIEMs, logging tools use today however is that each message is a set of fields, so at the very end, this message would logically become something like this list of name-value pairs:

location@50145.tid="503987" 
location@50145.id="ZWE6K-GRWAN" 
location@50145.file="zebra/zapi_msg.c" 
location@50145.line="763" 
location@50145.func="route_notify_internal"
args@50145.arg1="kernel"
args@50145.arg2="::/0" 
args@50145.arg3="254" 
args@50145.arg4="2" 
args@50145.arg5="0"
message="Not Notifying Owner: kernel about prefix ::/0(254) 2 vrf: 0"

The naming of the fields may vary, but that's roughly it.

I think you have two major use-cases that are somewhat incompatible:

1) people who use /var/log/messages style files where they are grepping stuff from
2) people who would send these logs to a Splunk/Elastic/whatever SIEM and build dashboards

For the first group of people, I understand that you are trying to retain the original log format and that you don't want to add clutter about line numbers and such. For the second group of people however, the whole thing could just become JSON or even XML (not really recommending that though). Their primary objective is to get your messages into their SIEM of choice and make it easy to extract values from.

Sometimes these use-cases are used at the same time, the network guy configuring BGP would use the local logs, while the SOC/NOC people look at dashboards that are generated on data delivered to their SIEM.

The problem I see is that it is difficult to make both groups of people happy, especially as they already got used to some existing behaviour. The network guy could just use a name=value style logs, if it had been the original Zebra logging format. Unfortunately we can't change the past :) If your application would be a new one, I'd just recommend to use key=value and satisfy both set of people with the same format. 

See for instance postfix logs:

```
2021-04-14T07:52:32.741+02:00 bimp postfix/cleanup[3621624]: B4FAD2E5812: message-id=<20210414055232.B4FAD2E5812@bimp.lan>
2021-04-14T07:52:32.742+02:00 bimp postfix/bounce[3621628]: A0CE22E0A56: sender non-delivery notification: B4FAD2E5812
2021-04-14T07:52:32.742+02:00 bimp postfix/qmgr[2459]: B4FAD2E5812: from=<>, size=3395, nrcpt=1 (queue active)
2021-04-14T07:52:32.742+02:00 bimp postfix/cleanup[3621624]: B541C2E0A54: message-id=<20210414055232.B4FAD2E5812@bimp.lan>
2021-04-14T07:52:32.742+02:00 bimp postfix/local[3621626]: B4FAD2E5812: to=<root@bimp.lan>, relay=local, delay=0, delays=0/0/0/0, dsn=2.0.0, status=sent (forwarded as B541C2E0A54)
2021-04-14T07:52:32.743+02:00 bimp postfix/qmgr[2459]: B4FAD2E5812: removed
```

or sudo:
```
2021-04-15T07:45:00.861+02:00 bimp sudo[3650869]:    bazsi : TTY=pts/1 ; PWD=/home/bazsi ; USER=root ; COMMAND=/bin/grep B4FAD2E5812 /var/log/messages
```

These are different formats, but still easy enough to extract fields from, while this mesage:

```
Not Notifying Owner: kernel about prefix ::/0(254) 2 vrf: 0
```

Is _really_ difficult to get details from and needs a couple of regexps and an intricate knowledge of zebra (which SOC/NOC people have a limited supply of).

With all this said, I think I would offer the following options for the user to choose from:
1) use the RFC5424 format as you implemented it and offer it to submit to /dev/log or via UDP/TCP on 127.0.0.1/::1 (unless you also want to implement TLS that is, in which case you could allow to submit to an IP address directly. buffering/queueing might also be needed in case the server goes down)
2) introduce a logging format that merges your RFC5424 key-value pairs and the message itself into a name=value format and simply submit it to /dev/log as today.
3) use journald submission, those name-value pairs are automatically picked up by syslog-ng if you are using the systemd-journal() source (which you do with recent versions of syslog-ng).

Implementing the journald socket is actually a good idea, which I like very much. :)

Now, if syslog-ng already has the name-value pairs (either via rfc5424 or via journald) it would not change the format of /var/log/messages by default nor would it use them when sending to the central log server. Both of these needs user configuration changes.

For the first, one needs to change the format of /var/log/messages (which is just as difficult for me as it is for you to change the default logs of Zebra). For the second, one needs to use the syslog-ng specific "syslog-ng()" destination and its pair on the server side, which automatically transmits all name-value pairs to the central infrastructure. Adoption here is pretty slow.

And these last two paragraphs is the reason that explicit name-value pairs in RFC5424 you worked so tirelessly to create, don't give much value at the end: they don't make it to the usual syslog storage destinations by default.

**Comment by eqvinox** [comment]
> These are great examples of how RFC5424 should have been used :)

Ouch — I'm starting to see where my head went wrong.  I honestly assumed that everyone would keep human readable log messages and have separate metadata channels.

(I need to spend some time thinking about this; thanks a lot for the extensive information!)

On the plus side it's a pretty small change to add another output format to our backend, it's already doing journald & RFC5424 (and 3164 without K/V), and only a very small amount of time went into 5424 specifics.

**Comment by Kokan** [comment]
Based on the systemd ticket, and conversation here. This change is not going to happen, therefore I am closing the issue. (Feel free to continue the conversion, or open new ticket with question.)
