### ISSUE TITLE
syslog-ng fails to find newer esmtp

### ISSUE THREAD

**Issue by hydrapolic** [syslog-ng/syslog-ng#3646]
# syslog-ng
## Version of syslog-ng
3.30.1

## Platform
Linux Gentoo

# Issue
## Failure
Syslog-ng fails to find libesmtp during compilation:
````
checking for libESMTP... no
configure: error: libESMTP not found
````

## Steps to reproduce
Install newer libesmtp (we used commit c80e46678e1025f3116bdcc75563364744adbe18) and build syslog-ng with smtp support.

# Additional notes
Downstream bug report: https://bugs.gentoo.org/782643
Fix: https://github.com/gentoo/gentoo/blob/master/app-admin/syslog-ng/files/syslog-ng-3.30.1-esmtp-pkgconfig.patch

The newer version of libesmtp (snapshot) drops autotools and dropped its homebrew libesmtp-config utility too. We now have to use pkgconfig to find it.

**Comment by bazsi** [comment]
The problem with the patch above is that most distros still have 1.0.6, which does NOT have pkgconfig files, so this patch fixes the behaviour for 1.0.7 onwards but breaks anything prior to that.

Could you submit a patch that prefers pkg-config but falls back to libesmtp-config in case pkg-config fails?

thanks
