### ISSUE TITLE
DATE Macro appends miliseconds

### ISSUE THREAD

**Issue by rfaircloth-splunk** [syslog-ng/syslog-ng#3664]
# syslog-ng
## Version of syslog-ng
3.31.2

## Platform
linux

# Issue
## Failure
template t_standard {
        template("${DATE} ${HOST} ${MSGHDR}${MESSAGE}");
        };

produces note "ms" is included however the BSD format typically does not produce BSD. While I can see desirable use we do have a need to produce "BSD" format headers without MS for legacy systems.

May  6 11:56:44.000 gustav-freddie AlsidForAD[4]: "0" "1" "EXAMPLE_AD_FOREST" "EXAMPLE_AD_DOMAIN" "C-DANG-PRIMGROUPID" "critical" "CN=CN=EXAMPLE_AD_ACCOUNT,OU=EXAMPLE_OU,OU=EXAMPLE_OU,DC=EXAMPLE_AD_FOREST,DC=EXAMPLE_AD_DOMAIN,DC=EXAMPLE_AD_FOREST_FQDN,DC=com,DC=au" "427573" "2" "R-DANG-PRIMGROUPID" "1727453" "AccountCn"="EXAMPLE_AD_ACCOUNT" "PrimaryGroupId"="16611" "GroupCn"="EXAMPLE_AD_GROUP_NAME" "DomainName"="EXAMPLE_AD_DOMAIN" "ObjectType"="User" "ObjectTypePrimaryGroupId"="513"

**Comment by bazsi** [comment]
Use frac-digits(0) on the destination.
