### ISSUE TITLE
How to create multiple input files destination files

### ISSUE THREAD

**Issue by aniketpant1** [syslog-ng/syslog-ng#3673]
I want to multiple input one for tcp,one for udp
I want to use tags so that i can differentiate which one is tcp logs and which one is udp
Destination is same kafka but topic is different 
How to do this?

**Comment by alltilla** [comment]
Hi @aniketpant1 

There are a lot of useful info in the Admin Guide regarding tags: https://www.syslog-ng.com/technical-documents/doc/syslog-ng-open-source-edition/3.30/administration-guide/61#TOPIC-1595085

Cheers,
Attila
