### ISSUE TITLE
Where to check syslog_facility_code and syslog_severity_code

### ISSUE THREAD

**Issue by aniketpant1** [syslog-ng/syslog-ng#3678]
I am sending logs to syslog-ng and then kafka but it is showing me only that log which has facility code 1 and severity code 5, i am seeing on kafka side when consumer pulls the messages.
In client side(source side) i provided only `ip:514` is there any option so that i can check that i am consuming all the messages of client.Because it showing me only user-level (facility code 1) and severity code 5

my syslog-ng conf file
```

@version: 3.30
@include "scl.conf"
#@module mod-java
@define kafka-implementation kafka-c
# syslog-ng configuration file.
#
# This should behave pretty much like the original syslog on RedHat. But
# it could be configured a lot smarter.
#
# See syslog-ng(8) and syslog-ng.conf(5) for more information.
#
# Note: it also sources additional configuration files (*.conf)
#       located in /etc/syslog-ng/conf.d/

options {
    flush_lines (0);
    time_reopen (10);
    log_fifo_size (1000);
    chain_hostnames (off);
    use_dns (no);
    use_fqdn (no);
    create_dirs (no);
    keep_hostname (yes);
};

source s_network {
     network(
     transport("udp")
     port(514)
);
};

rewrite r_rewrite_set {
set(
"pfsense",
        value("tags")
);
};

destination d_kafka
{
kafka (
bootstrap-servers("kafka_ip:9092")
topic("pfsense")
 message("$(format-json time=$ISODATE tags host=$HOST message='${MSGHDR}${MSG}')")
);
};

log{ source(s_network); rewrite(r_rewrite_set); destination(d_kafka); };
# Source additional configuration files (.conf extension only)
@include "/etc/syslog-ng/conf.d/*.conf"
# vim:ft=syslog-ng:ai:si:ts=4:sw=4:et:
```

**Comment by alltilla** [comment]
Hi @aniketpant1,

You can start `syslog-ng` in foreground with high verbosity: `syslog-ng -Fedtv`.
You should see a lot of useful information there.
Keep an eye for `Incoming log entry` and `Outgoing message` logs.

Cheers,
Attila

**Comment by aniketpant1** [comment]
hey @alltilla  with this 'syslog-ng -Fedtv' i've got useful information, but the question is if the sender sends its device messages to syslog-ng , is there any facility that i can see ,what syslog facilities information its(sender) providing me and its level because i am not defining syslog facilities details.

**Comment by alltilla** [comment]
`syslog-ng` can automatically parse these values, if they are given in the log, like in BSD messages:
https://www.syslog-ng.com/technical-documents/doc/syslog-ng-open-source-edition/3.30/administration-guide/8#TOPIC-1594873

However, if not present, you can define your own with `default-facility()` and `default-priority()`. See `Example: Setting default priority and facility` at https://www.syslog-ng.com/technical-documents/doc/syslog-ng-open-source-edition/3.30/administration-guide/18#TOPIC-1594914

**Comment by aniketpant1** [comment]
Thank you @alltilla
