### ISSUE TITLE
Syslog-ng Filter host function does not accepting multiple host

### ISSUE THREAD

**Issue by aniketpant1** [syslog-ng/syslog-ng#3682]
I have a filter in syslog-ng conf file
`
filter  test{ host("xx.xx.xx.xx") };
`
it is working fine but i want to have one more ip in this filer i tried this
`
filter test{ host("xx.xx.xx.xx","xx.xx.xx.xx") };` and this `filter test{ host("xx.xx.xx.xx"),host("xx.xx.xx.xx") };`
i cant use `filter test{ host("xx.xx.xx.xx",) }; filter test2{ host("xx.xx.xx.xx","xx.xx.xx.xx") };` so is there any option to correct this

**Comment by Kokan** [comment]
What should the `host("xxx", "yyy")` filter do ?
If you want, you can combine filters with logical operator `and`, `or`, `not`. Also maybe the `in_list` filter is something you are looking for.

**Comment by aniketpant1** [comment]
we have 2 server(high availability) for one application if one server can down other can send logs to syslog-ng so thats why we need to host , now i will use this operators as you previously said.

**Comment by MrAnno** [comment]
I think the question has been answered.
Please reopen if you have further questions about filters/boolean operators.
