### ISSUE TITLE
How to differenciate multiple source messages

### ISSUE THREAD

**Issue by aniketpant1** [syslog-ng/syslog-ng#3691]
Things going hilarious because we are getting messages from different source.Earlier we have one source and  one destination  -kafka, so whenever a logs come from source it goes into kafka topic

The architecture we have now is the client send logs to the syslog-ng but before sending logs to syslog-ng we have load-balancer tool called `haproxy' this tool  send logs to the syslog-ng

We have 4 clients first two client send logs(type tcp but different host_ip) directly to syslog-ng and remaining other send logs(type udp port 514 different host) to syslog-ng through 'haproxy'

So we want to differentiate the log message because the client which is sending logs through haproxy(load_balancer) have the same ip.
if client1 is sending message like 'This is for testing purpose' through load-balancer ip to syslog-ng and client2 is also sending message like 'Hey i am client2' both these client is sending their messages to syslog-ng through haproxy on port 514 tcp and in kafka we are seeing that in both messages we have same host ip(showing load-balancer ip)

we have different topics in kafka,one topic has the same messages as in different topic so syslog-ng merging the messages

so is there any way to differentiate log message apart from host filter if we add tag in source we don't how we gonna use for multiple sources
my conf file
```
@define kafka-implementation kafka-c

#############################################
source s_network_udp {
     network(
     transport("udp")
     port(514)
);
};
source s_network_tcp {
     network(
     transport("tcp")
     port(1470)
     log_fetch_limit(1000)
);
};
#############################################

rewrite pfsense_tag {
set(
"pfsense",
        value("tags")
);
};
rewrite vpn1_tag {
set(
"vpn1",
        value("tags")
);
};
rewrite vpn2_tag {
set(
"vpn2",
        value("tags")
);
};
rewrite vpn7_tag {
set(
"vpn7",
        value("tags")
);
};


############################################

filter host99{ host("192.168.0.109") or host("192.168.0.110") };
filter host65{ host("xx.xx.xx.xx") };
filter vpn2{ host("xx.xx.xx.xx") };
filter vpn1{ host("xx.xx.xx.xx") };

#############################################
destination pfsense_kafka
{
kafka (
bootstrap-servers("xx.xx.xx.xx:9092")
topic("pfsense")
message("$(format-json time=$ISODATE tags host=$HOST message='${MSGHDR}${MSG}')")
);
};
destination vpn_kafka
{
kafka (
bootstrap-servers("xx.xx.xx.xx:9092")
topic("vpn")
message("$(format-json time=$ISODATE tags host=$HOST message='${MSGHDR}${MSG}')")
log-fifo-size(20000)
);
};
destination vpn1_tcp
{
kafka (
bootstrap-servers("xx.xx.xx.xx:9092")
topic("vpn1_tcp")
message("$(format-json time=$ISODATE tags host=$HOST message='${MSGHDR}${MSG}')")
);
};
destination vpn1_udp
{
kafka (
bootstrap-servers("xx.xx.xx.xx:9092")
topic("vpn1_udp")
config("enable.idempotence" => "true"
"acks" => "all")
message("$(format-json time=$ISODATE tags host=$HOST message='${MSGHDR}${MSG}')")
);
};

############################################

log{ source(s_network_udp); filter(host99); rewrite(pfsense_tag); destination(pfsense_kafka); };
log{ source(s_network_tcp); filter(vpn1); rewrite(vpn1_tag); destination(vpn_kafka); flags(flow-control);};
log{ source(s_network_tcp); filter(vpn2); rewrite(vpn2_tag); destination(vpn_kafka); flags(flow-control);};
log{ source(s_network_tcp); filter(host99); rewrite(vpn7_tag); destination(vpn_kafka); };
log{ source(s_network_tcp); filter(host65); rewrite(vpn7_tag); destination(vpn_kafka); };
log{ source(s_network_udp); filter(host99); rewrite(vpn1_tag); destination(vpn1_udp); };
log{ source(s_network_tcp); filter(host65); rewrite(vpn1_tag); destination(vpn1_tcp); };
#log{ source(s_network_tcp); filter(ise); rewrite(ise_tag); destination(vpn_kafka); };


###############################################

```

**Comment by alltilla** [comment]
Hi @aniketpant1 

The easiest solution would be to not use the load balancer, but I assume that is not possible.

We have proxy protocol support, but that only works with `tcp` and `tls` transports, it does not work for `udp`.
Implementing proxy-protocol support for `udp` is one solution, but that takes time, because we only have proxy-protocol v1 support, which only works with tcp, so we would need to implement proxy-protocol v2 in order to use it with udp.

If you can change your `udp` source to `transport(proxied-tcp)`, and you turn on the proxy-protocol feature in haproxy, it should be handled correctly in syslog-ng.

Another alternative would be to embed the host information in the message itself, and parse it in syslog-ng, but we can only support you with the syslog-ng side.

Cheers,
Attila

**Comment by aniketpant1** [comment]
```
@define kafka-implementation kafka-c

source s_network_tcp {
     network(
     transport("proxied-tcp")
     port(1060)
     tags("tcp")
);
};


rewrite r_rewrite_src1 {
set("tcp23", value("tags"));
};
;


destination d_kafka
{
kafka (
bootstrap-servers("xx.xx.xx.xx:9092")
topic("proxy-tcp")
message("$(format-json time=$ISODATE tags  host=$PROXIED_SRCIP message='${MSGHDR}${MSG}')")
);
};
log{ source(s_network_tcp);  rewrite(r_rewrite_src1); destination(d_kafka); };
```
when i run `logger --tcp --port 1060 --server haproxy-server --rfc3164 this is a test`  from two clients
Output in Kafka
```
{"time":"2021-06-03T18:03:13+05:30","tags":"tcp23","message":"root: this is client1","host":"xx.xx.xx.23"}
{"time":"2021-06-03T18:03:14+05:30","tags":"tcp23","message":"root: this is a client2","host":"xx.xx.xx.24"}
```
but i want to filter on the basis of source ip
```
@define kafka-implementation kafka-c

source s_network_tcp {
     network(
     transport("proxied-tcp")
     port(1060)
     tags("tcp")
);
};

filter src2{host("xx.xx.xx.24")};
filter src1{host("xx.xx.xx..23")};

rewrite r_rewrite_src1 {
set("tcp23", value("tags"));
};

rewrite r_rewrite_src2 {
set("tcp24", value("tags"));
};

destination d_kafka
{
kafka (
bootstrap-servers("xx.xx.xx.xx:9092")
topic("proxy-tcp")
message("$(format-json time=$ISODATE tags  host=$PROXIED_SRCIP message='${MSGHDR}${MSG}')")
);
};
log{ source(s_network_tcp);filter(src1); rewrite(r_rewrite_src1); destination(d_kafka);};
log{ source(s_network_tcp);filter(src2); rewrite(r_rewrite_src2); destination(d_kafka);};
```
But after reloading the syslog-ng service i can't get any logs
Hey @czanik i follow  [this](https://www.syslog-ng.com/community/b/blog/posts/finding-the-real-source-ip-using-the-proxy-protocol-with-syslog-ng) doc

**Comment by MrAnno** [comment]
The question has been answered.
