### ISSUE TITLE
syslog-ng installation on ubuntu 18.04 fails to install libjson-c4 dependancy from http://download.opensuse.org/repositories/home:/laszlo_budai:/syslog-ng/xUbuntu_18.04

### ISSUE THREAD

**Issue by andrewbierbaum** [syslog-ng/syslog-ng#3694]
# syslog-ng
## Version of syslog-ng
anything newer than the bionic included syslog-ng-core 3.13.2-3 from the repo described https://www.syslog-ng.com/community/b/blog/posts/installing-the-latest-syslog-ng-on-ubuntu-and-other-deb-distributions
this has previously worked for at least the past month. 

## Platform
Ubuntu 18.04

## Debug bundle
unable to do so because syslog-ng won't install 

# Issue
## Failure
vagrant@ubuntu-bionic:/etc/apt/sources.list.d$ sudo apt-get install syslog-ng-core
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 syslog-ng-core : Depends: libjson-c4 (>= 0.13.1) but it is not installable
E: Unable to correct problems, you have held broken packages.

vagrant@ubuntu-bionic:/etc/apt/sources.list.d$ apt-cache policy syslog-ng-core
syslog-ng-core:
  Installed: (none)
  Candidate: 3.31.2-1
  Version table:
     3.31.2-1 500
        500 http://download.opensuse.org/repositories/home:/laszlo_budai:/syslog-ng/xUbuntu_18.04 ./ Packages
     3.31.1-1 500
        500 http://download.opensuse.org/repositories/home:/laszlo_budai:/syslog-ng/xUbuntu_18.04 ./ Packages
     3.30.1-2 500
        500 http://download.opensuse.org/repositories/home:/laszlo_budai:/syslog-ng/xUbuntu_18.04 ./ Packages
     3.29.1-1 500
        500 http://download.opensuse.org/repositories/home:/laszlo_budai:/syslog-ng/xUbuntu_18.04 ./ Packages
     3.28.1-1 500
        500 http://download.opensuse.org/repositories/home:/laszlo_budai:/syslog-ng/xUbuntu_18.04 ./ Packages
     3.27.1-2 500
        500 http://download.opensuse.org/repositories/home:/laszlo_budai:/syslog-ng/xUbuntu_18.04 ./ Packages
     3.26.1-1 500
        500 http://download.opensuse.org/repositories/home:/laszlo_budai:/syslog-ng/xUbuntu_18.04 ./ Packages
     3.25.1-1 500
        500 http://download.opensuse.org/repositories/home:/laszlo_budai:/syslog-ng/xUbuntu_18.04 ./ Packages
     3.24.1-2 500
        500 http://download.opensuse.org/repositories/home:/laszlo_budai:/syslog-ng/xUbuntu_18.04 ./ Packages
     3.23.1-1 500
        500 http://download.opensuse.org/repositories/home:/laszlo_budai:/syslog-ng/xUbuntu_18.04 ./ Packages
     3.22.1-2 500
        500 http://download.opensuse.org/repositories/home:/laszlo_budai:/syslog-ng/xUbuntu_18.04 ./ Packages
     3.21.1-1 500
        500 http://download.opensuse.org/repositories/home:/laszlo_budai:/syslog-ng/xUbuntu_18.04 ./ Packages
     3.20.1-1 500
        500 http://download.opensuse.org/repositories/home:/laszlo_budai:/syslog-ng/xUbuntu_18.04 ./ Packages
     3.19.1-1 500
        500 http://download.opensuse.org/repositories/home:/laszlo_budai:/syslog-ng/xUbuntu_18.04 ./ Packages
     3.18.1-1 500
        500 http://download.opensuse.org/repositories/home:/laszlo_budai:/syslog-ng/xUbuntu_18.04 ./ Packages
     3.17.2-1 500
        500 http://download.opensuse.org/repositories/home:/laszlo_budai:/syslog-ng/xUbuntu_18.04 ./ Packages
     3.16.1-1 500
        500 http://download.opensuse.org/repositories/home:/laszlo_budai:/syslog-ng/xUbuntu_18.04 ./ Packages
     3.15.1-1 500
        500 http://download.opensuse.org/repositories/home:/laszlo_budai:/syslog-ng/xUbuntu_18.04 ./ Packages
     3.13.2-3 500
        500 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages

## Steps to reproduce
following https://www.syslog-ng.com/community/b/blog/posts/installing-the-latest-syslog-ng-on-ubuntu-and-other-deb-distributions

wget -qO - http://download.opensuse.org/repositories/home:/laszlo_budai:/syslog-ng/xUbuntu_18.04/Release.key | sudo apt-key add -

add to /etc/apt/sources.list.d/testing.list
deb http://download.opensuse.org/repositories/home:/laszlo_budai:/syslog-ng/xUbuntu_18.04 ./

apt-get update
sudo apt-get install syslog-ng-core

**Comment by Kokan** [comment]
This repository is discontinued, for details see: https://lists.balabit.hu/pipermail/syslog-ng/2021-June/026292.html

**Comment by lbudai** [comment]
@Kokan : this is a different issue.
@andrewbierbaum : I'm trying to solve it (I've removed some old packages, and OBS removed the previously generated packages, too).

**Comment by lbudai** [comment]
@andrewbierbaum : I've re-added libjson-c.

Currently the following modules are not installable (if someone would like to install, open an issue and I'm trying to help):
 * syslog-ng-mod-mongodb
 * syslog-ng-mod-redis
 * syslog-ng-mod-riemann

Other modules are installable.

**Comment by andrewbierbaum** [comment]
@lbudai I can confirm those packages are the issue. `sudo apt-get -y install syslog-ng-core syslog-ng
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 syslog-ng : Depends: syslog-ng-mod-mongodb but it is not going to be installed
             Recommends: syslog-ng-mod-redis but it is not going to be installed
             Recommends: syslog-ng-mod-riemann but it is not going to be installed
E: Unable to correct problems, you have held broken packages.`

**Comment by lbudai** [comment]
@andrewbierbaum : are you planning to use mod-mongodb, mod-redis, mod-riemann?
If not, then you could give a try to install syslog-ng-core and those modules that are required in your environment.

**Comment by andrewbierbaum** [comment]
@lbudai 
after installing syslog-ng-core cleanly, I was unable to install syslog-ng due to the dependancy on  syslog-ng-mod-mongodb. 

```
17:43 andrewbierbaum@HOST:~$  sudo apt-get install syslog-ng
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 syslog-ng : Depends: syslog-ng-mod-mongodb but it is not going to be installed
             Recommends: syslog-ng-mod-redis but it is not going to be installed
             Recommends: syslog-ng-mod-riemann but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```
Trying to force the installation of syslog-ng-mod-mongodb along with syslog-ng fails to find two required packages. 
```
17:45 andrewbierbaum@HOST:~$  sudo apt-get install syslog-ng syslog-ng-mod-mongodb
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 syslog-ng-mod-mongodb : Depends: libbson-1.0-0 (>= 1.15.0) but it is not going to be installed
                         Depends: libmongoc-1.0-0 (>= 1.15.0) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
````
perhaps moving syslog-ng-mod-mongodb to `Recommends` instead of `Depends` would fix it? 

Thanks again

**Comment by lbudai** [comment]
@andrewbierbaum : oh, so you need mod-mongodb package?
Then I'm trying to re-add libbson and libmongoclient.

**Comment by andrewbierbaum** [comment]
@lbudai I don't need it for my use case, but attempting to install syslog-ng fails on the mod-mongodb package. I'm not sure why `Depends: syslog-ng-mod-mongodb but it is not going to be installed` is not `Recommends:` instead. Either way, I'm just needing a working installation. thanks again!

**Comment by lbudai** [comment]
@andrewbierbaum : `syslog-ng` is a metapackage - it installs everything.

**Comment by andrewbierbaum** [comment]
It took a whille to get back to this, but just installing `syslog-ng-crore` then `syslog-ng-mod-http` was enough for my use case. It's still fairly concerning that the previously working repo now has broken `syslog-ng` packages, and is there a pathway to getting the repo working again or is the suggested path to build packages if required (https://www.syslog-ng.com/community/b/blog/posts/dbld-a-syslog-ng-developer-tool-not-just-for-developers)? This appears relatively straighforward, I'm just wondering what the future holds here. Thanks again for helping me getting this working again!

**Comment by MrAnno** [comment]
Hi @andrewbierbaum,

We have plans to replace the discontinued OBS repository, we are planning to do it as a syslog-ng team effort.
This may take some time, so currently our suggestion would be to use `dbld` to build your packages.

**Comment by Kokan** [comment]
The mentioned repository arrived, instruction to use can be found at https://github.com/syslog-ng/syslog-ng#debianubuntu .
If you still have issue installing those packages please reopen this issue.
