### ISSUE TITLE
Syslog-ng with HAPROXY

### ISSUE THREAD

**Issue by aniketpant1** [syslog-ng/syslog-ng#3714]
Hi,
I have haproxy load-balancer tool b/w my source and destination(syslog-ng).The source sends the message to the haproxy server and then haproxy send  the message to the syslog-ng.
The problem i am facing is that in HOST field i am getting hostname of original source instead i shoud get the hostname or ip of haproxy server
```
@define kafka-implementation kafka-c

source s_network_tcp {
     network(
     transport("proxied-tcp")
     port(1470)
);
};

filter src4{match("xx.xx.17.204" value("$PROXIED_SRCIP"))};
rewrite r_rewrite_src4 {
set("ise",value("tags"));
set("$PROXIED_SRCIP",value("HOST_FROM"));
};
destination ise_kafka
{
kafka (
bootstrap-servers("xx.xx.xx.xx:9092")
topic("ise")
message("$(format-json time=$ISODATE tags proxied_srcip=$PROXIED_SRCIP host=$HOST message='${MSGHDR}${MSG}')")
);
};
log{ source(s_network_tcp);filter(src4);rewrite(r_rewrite_src4); destination(ise_kafka);};
```
A sample of message output using `bin/kafka-console-consumer` command
```
{"time":"2021-06-28T12:44:10+05:30","tags":"ise","proxied_srcip":"xx.xx.17.204","message":"xxxxxxxxxxxxxxxxx ","host":"test"}
```
I have other log messages architecture is same in host field i get the ip/hostname of haproxy server 
```
{"time":"2021-06-28T13:06:11+05:30","tags":"vpn34","proxied_srcip":"xx.xx.xx.6","message":"xxxxxxxxxxxxxxxx","host":"xx.xx.32.249"}
```

**Comment by MrAnno** [comment]
You replaced `HOST_FROM` with `PROXIED_SRCIP` in the `r_rewrite_src4` rewrite rule.

If that's undesirable, remove `set("$PROXIED_SRCIP",value("HOST_FROM"));`.

**Comment by MrAnno** [comment]
Has this resolved your problem?
If so, can we close the issue?

**Comment by aniketpant1** [comment]
Yes
