### ISSUE TITLE
How to check rfc protocal ?

### ISSUE THREAD

**Issue by aniketpant1** [syslog-ng/syslog-ng#3716]
hey team 
I want to check which rfc protocol is using by client when sending logs to syslog-ng because in message i can't see rfc protocol like rfc3164

**Comment by MrAnno** [comment]
The `network(), tcp(), udp()` destinations use the old BSD protocol by default (RFC3164).
You can switch to the IETF syslog (RFC5424) protocol by setting `flags(syslog-protocol)` in these destinations.

The `syslog()` destination uses RFC5424 by default, and its framed transport is defined in RFC6587.

**Comment by MrAnno** [comment]
You can reopen this issue if you have further questions.
