### ISSUE TITLE
Issue when trying to compile 

### ISSUE THREAD

**Issue by depshai** [syslog-ng/syslog-ng#3728]
Fail with the below:

checking dependency style of gcc... gcc3
checking host operating system type... posix
./configure: line 3838: syntax error near unexpected token `('
./configure: line 3838: `case "(($ac_try" in'
configure: error: ./configure failed for test.mt
configure: error: ./configure.gnu failed for lib/ivykis

Syslog ng version syslog-ng-3.32.1
 Ubuntu 20.04.2 LTS
 
 I have been following various links and have installed all the required dependencies I think

**Comment by szemere** [comment]
Hello @depshai ,

Could you please describe your environment, and the command you use? Are you trying to build from the github repository, or using one of the release tarball?


Also, our CI system uses a docker based environment to avoid any "leftover" on the build system. This way the github actions together with the dbld files are a really good documentation of the build process. It might give you a hint.

Br,
Laci

**Comment by depshai** [comment]
Thanks a lot for your answer. I downloaded the released tarball (syslog-ng-3.32.1.tar.gz ), extracted it, installed all the dependancies as per https://www.syslog-ng.com/technical-documents/doc/syslog-ng-open-source-edition/3.19/administration-guide/37#TOPIC-1094603

I have been using the below commands:
sudo ./configure --enable-java \
                   --enable-java-modules \
                   --enable-json 
 sudo make 
 sudo make install
 
 I was thinking of using docker as it would be easy. Just thought I tried the whole process myself to understand it

**Comment by depshai** [comment]
I am still at it. I have been spending too much time on that already :-) I have solved the previous issue and am facing the following now. 
I got this error message:

Makefile:28334: *** multiple target patterns.  Stop.

When checking the MakeFile (vim +28334  Makefile), it seems to be this line below:

java-headers: $(JAVA_HEADER_FILES) : $(JAVA_CLASS_FILES)

The command I ran initially:
./configure --disable-dependency-tracking && make && make install

**Comment by szemere** [comment]
Hello @depshai ,

 "I was thinking of using docker as it would be easy. Just thought I tried the whole process myself to understand it"

I can only encourage you to do it! I was only referring to dbld as a good reference point.


- The syntax error in configure indicate that there might be some problem with your autoconf step.
- May I ask how did you install Java on Ubuntu 20.04.2? Unfortunately we only support Java 8 at this time, so you should use the "openjdk-8-jre-headless" package.

Br,
Laci

**Comment by depshai** [comment]
Thanks for your answer. I am using the below Java version:

openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.20.04)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.20.04, mixed mode, sharing)

I used the apt-get install. I thought there was an issue with this version, something to do with the headers. I will uninstall it and install version 8. I will keep you posted. Thanks

**Comment by depshai** [comment]
I installed the recommended version:

sudo apt-get install -y openjdk-8-jre-headless

I changed Java version with the below:

sudo update-alternatives --config java

I Still got the same error message:

Makefile:28334: *** multiple target patterns.  Stop.

Should I completely uninstall Java 11?

Regards,

Mehdi

**Comment by szemere** [comment]
Hello @depshai ,

I am not sure if you have to remove the other version or not. However I think you should re-run the build process from autogen (also deleting the temporary files), because of some detection code (https://github.com/syslog-ng/syslog-ng/blob/66d8017a1198b15df72a58133756efee3dfb2755/m4/check_java_support.m4)

Br,
Laci

**Comment by depshai** [comment]
Hello @szemere 

Thank you so much for your help.

I have uninstalled the more recent version of Java and run the same command again. It seems to have done the trick. 

I attach the output
[cd.docx](https://github.com/syslog-ng/syslog-ng/files/6799340/cd.docx)

**Comment by depshai** [comment]
@szemere I still don't see my messages in Kafka. Not sure why.

When running the below command:

syslog-ng -Fdev

I can see the below error messages:

[2021-07-14T13:02:48.598349] Starting to read include file; filename='/usr/local/share/syslog-ng/include/scl/kafka/kafka-java.conf', depth='2'
[2021-07-14T13:02:48.598399] Included file was skipped because of a missing module; module='mod-java', location='/usr/local/share/syslog-ng/include/scl/kafka/kafka-java.conf:24:1'

I checked the file and here is what I got:


@requires mod-java

block destination kafka-java(
  topic()
  key("")
  template("")
  kafka_bootstrap_servers()
  properties_file("")
  sync_send("")
  client_lib_dir("")
  ...
)
{
  java(
    class_path("`java-module-dir`/*.jar:`client_lib_dir`/*.jar")
    class_name("org.syslog_ng.kafka.KafkaDestination")
    option("topic", `topic`)
    option("key", "`key`")
    option("template", "`template`")
    option("kafka_bootstrap_servers", `kafka_bootstrap_servers`)
    option("properties_file", "`properties_file`")
    option("sync_send", "`sync_send`")
    `__VARARGS__`
  );
};
                 
Any troubleshooting tip please?

Best Regards,

**Comment by bazsi** [comment]
Included file was skipped because of a missing module; module='mod-java',
location='/usr/local/share/syslog-ng/include/scl/kafka/kafka-java.conf:24:1'


Btw, there's a native kafka destination that is not java based.

**Comment by depshai** [comment]
location='/usr/local/share/syslog-ng/include/scl/kafka/kafka-java.conf:24:1'

This is where I get confused. Where is this module?  Are we talking about the below:

libjvm.so

In that case, I have already specified:

export LD_LIBRARY_PATH=/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server/libjvm.so

However, the documentation below mentions a KafkaDestination.jar file:

https://www.syslog-ng.com/technical-documents/doc/syslog-ng-open-source-edition/3.18/administration-guide/37

I don't have such a file. I do have KafkaDestination.java though.

Btw, there's a native kafka destination that is not java base -- Really? Any tutorial?

Thanks and Best Regards,

**Comment by Kokan** [comment]
For the native kafka, the only dependency you need is `librdkafka` (and `librdkafka-dev` if you compile syslog-ng yourself).
Recompile and check if `kafka-c` module is avaiable:
```bash
$ syslog-ng --module-registry|grep -A 5 kafka
Module: kafka
Status: ok
Version: 3.33.1.7.ga887890
Core-Revision: 3.33.1.7.ga887890
Description:
  The kafka module provides native librdkafka based Kafka support for syslog-ng.
Plugins:
  destination     kafka_c
```
In the configuration you can use as:
```
kafka-c(
  bootstrap-server("...")
  topic("syslog-ng")
);
```
For further option look for admin guide.

**Comment by depshai** [comment]
@Kokan, thanks for your answer. I can see the modules is there.

syslog-ng --module-registry|grep -A 5 kafka
Module: kafka
Status: ok
Version: 3.33.1
Core-Revision: 
Description:
  The kafka module provides native librdkafka based Kafka support for syslog-ng.
Plugins:
  destination     kafka_c

Module: pseudofile
Status: ok
Version: 3.33.1
Core-Revision: 

I amended my Syslog con as per below:
@module mod-java
@version: 3.33
@include "scl.conf"


destination d_kafka {
     kafka-c(
     bootstrap-server("127.0.0.1:9092,localhost:9092")
 topic("test")
  );
};

I still cannot see the messages coming into the Kafka topic, so I will investigate more. Thanks a lot for your help. Much appreciated.

**Comment by Kokan** [comment]
You can enable extra logging from kafka-c destination side with adding `config( debug => all )` inside `kafka-c()`. Btw what `syslog-ng-ctl stats` says ? Does messages supposed to be sent toward kafka?

**Comment by depshai** [comment]
@Kokan , that is indeed what I am trying to achieve. I have Syslog-ng and Kafka on the same machine (Ubuntu) and when messages are generated from Syslog, they should be sent to Kafka. Here is the output of Syslog-ng ctl stats:
syslog-ng-ctl stats
SourceName;SourceId;SourceInstance;State;Type;Number
global;scratch_buffers_count;;a;queued;0
global;scratch_buffers_bytes;;a;queued;0
src.internal;s_local#2;;a;processed;0
src.internal;s_local#2;;a;stamp;0
center;;received;a;processed;3
center;;queued;a;processed;6
global;msg_clones;;a;processed;3
destination;d_local;;a;processed;6
source;s_local;;a;processed;3
global;sdata_updates;;a;processed;0
global;payload_reallocs;;a;processed;4

**Comment by Kokan** [comment]
It is strange as kafka did not show up in your stats, which means it is not connected to a logpath.
What is your configuration ? Could you verify that kafka-c works for you with a simple configuration like:
```
@version: 3.33

log {
  source { network(port(1111)); };
  destination {  kafka-c( bootstrap-servers("...") topic("...")); };
};
```
and sending logs into that with `loggen --inet localhost 1111`

**Comment by depshai** [comment]
That's what I was wondering as well. My config is as below:

@module mod-java
@version: 3.33
@include "scl.conf"


destination d_kafka {  
     kafka-c(
     config( debug => all )
     bootstrap-server("127.0.0.1:9092,localhost:9092")
 topic("test")
  );
};


destination d_kafka {
  kafka(
    client-lib-dir("/root/syslog-ng-3.33.modules/java-modules/:/usr/local/kafka/libs/*.jar")
    kafka-bootstrap-servers("127.0.0.1:9092,x.x.x.x:9092")
    topic("test")
  );
};

my config is located in /etc/syslog-ng/conf.d but my install is in /root/syslog-ng-3.33.1/syslog-ng. 

I created the below config:

@version: 3.33

log {
source s_myfilesource {
    file("/var/log/messages" follow-freq(1));
  destination {  kafka-c( bootstrap-servers("127.0.0.1:9092,localhost:9092") topic("test")); };
};

Still no logs coming up in Kafka.

**Comment by Kokan** [comment]
Your second configuration is not valid, please note that if you change the configuration and reload (not restart) syslog-ng, it will load the new configuration only if it is valid otherwise it rolls back the old one.

Try with:
```
@version: 3.33

log {
source { file("/var/log/messages" follow-freq(1)); };
destination { kafka-c( bootstrap-servers("127.0.0.1:9092,localhost:9092") topic("test")); };
};
```

**Comment by depshai** [comment]
Thanks. I have amended the config and reloaded it via syslog-ng-ctl reload, but the issue is still the same.

When running the stats command, the output is still the same:

syslog-ng-ctl stats
SourceName;SourceId;SourceInstance;State;Type;Number
global;scratch_buffers_count;;a;queued;0
global;scratch_buffers_bytes;;a;queued;0
src.internal;s_local#2;;a;processed;0
src.internal;s_local#2;;a;stamp;0
center;;received;a;processed;9
center;;queued;a;processed;18
global;msg_clones;;a;processed;3
destination;d_local;;a;processed;18
source;s_local;;a;processed;9
global;sdata_updates;;a;processed;0
global;payload_reallocs;;a;processed;8

I can see that Kafka is running:

● kafka.service - Apache Kafka Server
     Loaded: loaded (/etc/systemd/system/kafka.service; disabled; vendor preset: enabled)
     Active: active (running) since Mon 2021-07-26 12:03:29 UTC; 14min ago
       Docs: http://kafka.apache.org/documentation.html
   Main PID: 1497 (java)
      Tasks: 76 (limit: 19198)
     Memory: 376.8M
     CGroup: /system.slice/kafka.service
             └─1497 /usr/lib/jvm/java-8-openjdk-amd64/bin/java -Xmx1G -Xms1G -server -XX:+UseG1GC -XX:MaxGCPauseMillis=20 -XX:InitiatingHeapOccupancyPercent=35 -XX:+ExplicitGCInvokesConcurrent -XX:MaxInlineLevel=15 -Djava.awt.headless=tr>

Jul 26 12:05:10 ip-172-31-10-133 kafka-server-start.sh[1497]: [2021-07-26 12:05:10,744] INFO [GroupCoordinator 0]: Stabilized group console-consumer-27963 generation 1 (__consumer_offsets-8) with 1 members (kafka.coordinator.group.GroupC>
Jul 26 12:05:10 ip-172-31-10-133 kafka-server-start.sh[1497]: [2021-07-26 12:05:10,750] INFO [GroupCoordinator 0]: Assignment received from leader for group console-consumer-27963 for generation 1. The group has 1 members, 0 of which are>
Jul 26 12:06:32 ip-172-31-10-133 kafka-server-start.sh[1497]: [2021-07-26 12:06:32,710] INFO [GroupCoordinator 0]: Member[group.instance.id None, member.id consumer-console-consumer-27963-1-dd53eafd-033d-4ae3-b40c-e2c78bde9f89] in group >
Jul 26 12:06:32 ip-172-31-10-133 kafka-server-start.sh[1497]: [2021-07-26 12:06:32,710] INFO [GroupCoordinator 0]: Preparing to rebalance group console-consumer-27963 in state PreparingRebalance with old generation 1 (__consumer_offsets->
Jul 26 12:06:32 ip-172-31-10-133 kafka-server-start.sh[1497]: [2021-07-26 12:06:32,710] INFO [GroupCoordinator 0]: Group console-consumer-27963 with generation 2 is now empty (__consumer_offsets-8) (kafka.coordinator.group.GroupCoordinat>
Jul 26 12:06:38 ip-172-31-10-133 kafka-server-start.sh[1497]: [2021-07-26 12:06:38,880] INFO [GroupCoordinator 0]: Preparing to rebalance group console-consumer-6967 in state PreparingRebalance with old generation 0 (__consumer_offsets-3>
Jul 26 12:06:38 ip-172-31-10-133 kafka-server-start.sh[1497]: [2021-07-26 12:06:38,881] INFO [GroupCoordinator 0]: Stabilized group console-consumer-6967 generation 1 (__consumer_offsets-37) with 1 members (kafka.coordinator.group.GroupC>
Jul 26 12:06:38 ip-172-31-10-133 kafka-server-start.sh[1497]: [2021-07-26 12:06:38,886] INFO [GroupCoordinator 0]: Assignment received from leader for group console-consumer-6967 for generation 1. The group has 1 members, 0 of which are >
Jul 26 12:13:32 ip-172-31-10-133 kafka-server-start.sh[1497]: [2021-07-26 12:13:32,438] INFO [GroupMetadataManager brokerId=0] Group console-consumer-27963 transitioned to Dead in generation 2 (kafka.coordinator.group.GroupMetadataManage>
Jul 26 12:13:32 ip-172-31-10-133 kafka-server-start.sh[1497]: [2021-07-26 12:13:32,442] INFO [GroupMetadataManager brokerId=0] Group console-consumer-36915 transitioned to Dead in generation 2 (kafka.coordinator.group.GroupMetadataManage>

I even restarted the machine.

**Comment by Kokan** [comment]
Based on the stats my guess still that you have different configuration under the hood. You can also query the actice configuration via ctl using `syslog-ng-ctl config`, that should print out the current configuration.

When I am using the configuration above:
```bash
#  cat /tmp/syslog-ng.conf
@version: 3.33

log {
source { file("/var/log/messages" follow-freq(1)); };
destination { kafka-c( bootstrap-servers("127.0.0.1:9092,localhost:9092") topic("test")); };
};
```

starting syslog-ng by hand (make sure that no other syslog-ng is running) also I am using custom syslog-ng configuration path (with `-f` option). 
```bash
# syslog-ng -f /tmp/syslog-ng.conf
syslog-ng: Error setting capabilities, capability management disabled; error='Operation not permitted'
[2021-07-26T16:20:00.852111] librdkafka: FAIL(3): [thrd:127.0.0.1:9092/bootstrap]: 127.0.0.1:9092/bootstrap: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT);
# as you can see I do not have kafka server configurad, but it is not important for now
# syslog-ng-ctl config
@version: 3.33

log {
source { file("/var/log/messages" follow-freq(1)); };
destination { kafka-c( bootstrap-servers("127.0.0.1:9092,localhost:9092") topic("test")); };
};
```
The same configuration, so everything is as expected. But my stats are different from yours:

```bash
# syslog-ng-ctl stats
SourceName;SourceId;SourceInstance;State;Type;Number
destination;#anon-destination0;;a;processed;0
global;scratch_buffers_count;;a;queued;0
global;scratch_buffers_bytes;;a;queued;0
global;msg_clones;;a;processed;0
center;;received;a;processed;0
center;;queued;a;processed;0
global;sdata_updates;;a;processed;0
source;#anon-source0;;a;processed;0
dst.kafka;#anon-destination0#0;kafka,test;a;dropped;0
dst.kafka;#anon-destination0#0;kafka,test;a;processed;0
dst.kafka;#anon-destination0#0;kafka,test;a;queued;0
dst.kafka;#anon-destination0#0;kafka,test;a;written;0
global;payload_reallocs;;a;processed;0
```

I have `dst.kafka` lines. I would suggest to try the steps I did before.

**Comment by depshai** [comment]
You're a star!  Problem solved. You are right. A different instance was running with another configuration. Killing the processes and forcing syslog to use the right config did the trick. Thanks a lot!

syslog-ng-ctl stats
SourceName;SourceId;SourceInstance;State;Type;Number
destination;#anon-destination0;;a;processed;498
global;scratch_buffers_count;;a;queued;0
global;scratch_buffers_bytes;;a;queued;0
global;msg_clones;;a;processed;0
center;;received;a;processed;498
center;;queued;a;processed;498
global;sdata_updates;;a;processed;0
source;#anon-source0;;a;processed;498
dst.kafka;#anon-destination0#0;kafka,test;a;dropped;0
dst.kafka;#anon-destination0#0;kafka,test;a;processed;498
dst.kafka;#anon-destination0#0;kafka,test;a;queued;0
dst.kafka;#anon-destination0#0;kafka,test;a;written;498
global;payload_reallocs;;a;processed;0
