### ISSUE TITLE
Issue with syslog-ng-mod-sql and PostgreSQL: Error when creating table names containing dots 

### ISSUE THREAD

**Issue by Killom** [syslog-ng/syslog-ng#3734]
# syslog-ng: syslog-ng-mod-sql
## Version of syslog-ng
syslog-ng 3 (3.28.1)

## Platform
Debian 5.10.40-1

## Debug bundle
Syslog-NG DEBUg buNdle generator
Start environment detection
Linux-type FHS detected
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye

Operating System Name: Linux

Debian specific checks
Check package files integrity
Package files are intact
list syslog-related packages

Start general info collection
System's full uname: Linux syslog01 5.10.0-7-amd64 #1 SMP Debian 5.10.40-1 (2021-05-28) x86_64 GNU/Linux
Getting network-interface information: Success
Getting network routes: Success
Getting DNS resolution-related information: Done
List all processes
Mount and disk free info collection

Start Syslog-specific info collection
Copy configuration files from /etc/syslog-ng
28 blocks
Copy SCL configuration files
185 blocks
Gathering PKI information... done.
SVpid: 1 SNGpid: 645 Chpids:
Syslog-ng's exact version: syslog-ng 3 (3.28.1)
/usr/sbin/syslog-ng-ctl stats
/usr/sbin/syslog-ng-ctl query get *
/usr/sbin/syslog-ng-ctl show-license-info
/usr/sbin/syslog-ng-ctl credentials status
33 blocks
dpkg-query: no path found matching pattern /lib/x86_64-linux-gnu/libglib-2.0.so.0
dpkg-query: no path found matching pattern /lib/x86_64-linux-gnu/libgmodule-2.0.so.0
dpkg-query: no path found matching pattern /lib/x86_64-linux-gnu/libgthread-2.0.so.0
dpkg-query: no path found matching pattern /lib/x86_64-linux-gnu/libivykis.so.0
dpkg-query: no path found matching pattern /lib/x86_64-linux-gnu/libsystemd.so.0
dpkg-query: no path found matching pattern /lib/x86_64-linux-gnu/libssl.so.1.1
dpkg-query: no path found matching pattern /lib/x86_64-linux-gnu/libcrypto.so.1.1
dpkg-query: no path found matching pattern /lib/x86_64-linux-gnu/libzstd.so.1
dpkg-query: no path found matching pattern /lib/x86_64-linux-gnu/liblz4.so.1
dpkg-query: no path found matching pattern /lib/x86_64-linux-gnu/libgcrypt.so.20
Detecting init system: systemd detected...
Generating second batch of statistics
/usr/sbin/syslog-ng-ctl stats
/usr/sbin/syslog-ng-ctl query get *

Generating hashes... done.
Debug Bundle generation: Done.
tar: ./var/syslog-ng.ctl: socket ignored
Terminating live message watcher:

# Issue
## Failure
syslog-ng[499]: Error running SQL query; type='pgsql', host='127.0.0.1', port='5432', user='syslog', database='db_syslog', error='6819553: ERROR:  Syntax error at ».168«\x0aLINE 1: CREATE TABLE logs_192.168.75.102 (datetime varchar(16), ho...\x0a                              ^\x0a', query='CREATE TABLE logs_192.168.75.102 (datetime varchar(16), host varchar(32), program varchar(20), pid varchar(10), message varchar(800))'
syslog-ng[499]: Error creating table, giving up; table='logs_192.168.75.102'

## Steps to reproduce
Configuration should be set to create table names containing the hostname. When hostname is not available, IP address is instead returned by $HOST macro.

The SQL statement sent by syslog-ng is not enclosed in quotes, so the dots from IP address are concidered as illegal character in the SQL statement. (i.e.: CREATE TABLE logs_192.168.75.102);

When enclosing single quotes into the config statment, the SQL statement will be malformed with underscores instead of quotes, leading to the same outcome.

i.e.: table("'logs_${HOST}'") will result in -> CREATE TABLE \_logs_192.168.75.102\_ instead of CREATE TABLE 'logs_192.168.75.102'

## Configuration

source s_extern {
	network( ip("0.0.0.0") transport("udp") port(514));
};
destination d_pgsql {
                sql(type(pgsql)
                host("127.0.0.1") username("syslog")
                password("syslog") port("5432")
                database("db_syslog")
                table("logs_${HOST}")
                columns("datetime varchar(16)", "host varchar(32)", "program varchar(20)", "pid varchar(10)", "message varchar(800)")
                values("$R_DATE", "$HOST", "$PROGRAM", "$PID", "$MSG")
                indexes("datetime", "host", "program", "pid", "message"));
};

log { source(s_extern); destination(d_pgsql); };

**Comment by OverOrion** [comment]
The `.` character is mostly used for accessing for schemas / refering to absolute table names.
As such I would suggest you to use the following template option which replaces the `.` character with `_`.

```
table("$(sanitize -i . -r _ logs_${HOST})")
```

There is an inner sanitizer logic which is responsible for replacing quotation marks with underscores. Therefore it was not possible to quote the table name.
