### ISSUE TITLE
With the "default-network-drivers" the options "use-dns(yes)" and "keep-hostname(no)" are ignored.

### ISSUE THREAD

**Issue by Trevelian** [syslog-ng/syslog-ng#3738]
# syslog-ng
## Version of syslog-ng
3.33

## Platform
Centos8 / Archlinux

## Steps to reproduce
Using the source "default-network-drivers" with the global options use-dns(yes) and keep-hostname(no)
The hostname in the destination logs are not replaced with the DNS or the /etc/hosts entry

Using the source "syslog"  with the global options use-dns(yes) and keep-hostname(no)
The hostname in the destination logs are correctly replaced by the DNS or /etc/hosts entry.

## Expected behaviour 
use-dns(yes) and keep-hostname(no) on the global option are not ignored when using the "default-network-drivers" source.

## Configuration
@version: 3.33
@include "scl.conf"

options {
  use-fqdn(no);
  use-dns(yes);
  keep-hostname(no);
};

source s_syslog {
     default-network-drivers();
};

destination d_file {
    file("/var/log/syslog-ng");
};

log {
  source(s_syslog);
  destination(d_file);
};

**Comment by szemere** [comment]
Hello @Trevelian ,

The difference between the two drivers is coming from the different internal use of the syslog-parser.

The information you require is still accessible in the $HOST_FROM macro. You can "fix" the $HOST macro with a rewrite rule. I modified your original configuration example, so it is easier to track the difference:

```
@Version: 3.33
@include "scl.conf"

options {
use-fqdn(no);
use-dns(yes);
keep-hostname(no);
};

source s_syslog {
default-network-drivers();
};

destination d_file {
file("/var/log/syslog-ng");
};

rewrite use_host_from {
  set("$HOST_FROM", value("HOST"));
};

log {
source(s_syslog);
rewrite(use_host_from);
destination(d_file);
};

```

### In more details

- default-network-drivers https://github.com/syslog-ng/syslog-ng/blob/e0104231703d5d68091183f24696e83ba014a722/scl/default-network-drivers/plugin.conf uses a network source with a flags(no-parse) option and (among with many others) a syslog-parser to process incoming messages.
- keep-hostname, use-fqdn, etc... are source driver options, so syslog-parser does not handle them.
- The syslog source changes the order of processing. It first parses the message with the syslog-parser. And after that it uses the https://github.com/syslog-ng/syslog-ng/blob/master/lib/logsource.c#L369 function to fill out HOST related data.

**Comment by Trevelian** [comment]
Thanks for this detailed explanation, it's working good with your solution.
