### ISSUE TITLE
Why host field is showing ip address not hostname

### ISSUE THREAD

**Issue by aniketpant1** [syslog-ng/syslog-ng#3739]
if we use file output it will host:host-name but when we use other output like kafka it will show host:ip
```
destination ise_file {
file(
            "/var/log/ise/${YEAR}.${MONTH}.${DAY}logs.log"
            owner("root")
            group("root")
            perm(0777)
            );
};
```
in /var/log/ise/2021.07.19 file will show hostname `Jul 20 14:29:00 hostname xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx`
but if we use 
```
destination test_ise_kafka
{
kafka (
bootstrap-servers("xx.xx.xx.xx:9092")
topic("test_ise")
message("$(format-json time=$ISODATE tags proxied_srcip=$HOST_FROM  host=$HOST message='${MSGHDR}${MSG}')")
);
};
```
then in host field it will show ip address not hostname

**Comment by MrAnno** [comment]
The `keep-hostname()`, `use-dns()`, `use-fqdn()`, `dns-cache()`, and other options can be used to set what the `$HOST` macro should return.

https://www.syslog-ng.com/technical-documents/doc/syslog-ng-open-source-edition/3.30/administration-guide/62

See also the HOST, HOST_FROM section:
https://www.syslog-ng.com/technical-documents/doc/syslog-ng-open-source-edition/3.30/administration-guide/66#TOPIC-1595107

----

You have 4 pending tickets open, please close/resolve them before opening another one.
