### ISSUE TITLE
proxied-tls behind a TCP loadbalancer with proxy protocol

### ISSUE THREAD

**Issue by tdenof** [syslog-ng/syslog-ng#3758]
## Description of the problem
The `proxied-tls` transport for network source only supports reading the PROXY header inside the encrypted payload.
In practice, when using haproxy for example in front of a syslog-ng server, the PROXY header will be outside the TLS payload as the TLS termination is performed on syslog-ng side.
When using `proxied-tls` with the previous configuration, syslog-ng raises an SSL error as the TCP packet contains the PROXY header first , but syslog-ng is expecting a TLS handshake client hello first

To be honest, except when using `loggen -U -H` for tests, I'm not aware of a way of having the PROXY header inside the encrypted payload as the remote logging clients are not the ones adding the PROXY header

## Proposed solution
A possible solution could be support reading the PROXY header before performing the TLS handshake

## Alternatives
The current workaround I could find when using haproxy and performing TLS termination on the syslog-ng machine, is having locally another haproxy installed on the syslog machine configured to accept proxy protocol and perform the TLS offload, then forward the decrypted data and the initial PROXY header to syslog-ng which will be using `proxied-tcp`

If I'm mistaken about `proxied-tls` option, or the use case is not clear, I can give more context of course
Thanks

**Comment by MrAnno** [comment]
Hi,

Thanks for opening this enhancement idea.

This sounds like opportunistic TLS (usually called STARTTLS), which is currently not supported by `proxied-tls`, but we could implement that in the future with some `multitransport_switch()` trickery.
