### ISSUE TITLE
COPR builds for 333 do not have aarch64

### ISSUE THREAD

**Issue by rfaircloth-splunk** [syslog-ng/syslog-ng#3776]
# syslog-ng
## Version of syslog-ng
3.33.2

## Platform
Arm64 aarch64

While 332 did have arm64 builds the repo for 3.33 does not would it be possible to continue both arm64 and x64 builds?

**Comment by czanik** [comment]
As syslog-ng 3.34 was released today, I'll do it there early next week.

(creating ARM64 packages for 3.33 is as much work as doing the whole release again, while doing it from right at the beginning is just an extra mouse click)

**Comment by czanik** [comment]
3.34 is now compiled with Aarch64 support for RHEL8/CentOS8.

**Comment by rfaircloth-splunk** [comment]
Excellent thank you
