### ISSUE TITLE
Syslog is not sending ca names

### ISSUE THREAD

**Issue by willcey** [syslog-ng/syslog-ng#3785]
Hello

One of our customers recognized that the syslog-ng server is not sending ca names during the TLS handshake on the source connector.

Here is our configuration:
```
source customer_int_tls_source {
        syslog(ip(x.x.x.x)
                port(7003)
                transport("tls")
                tls(
                        key-file("/etc/syslog-ng/cert.d/server_ext.key")
                        cert-file("/etc/syslog-ng/cert.d/server_ext.pem")
                        ca-dir("/etc/syslog-ng/ca.d/customer_int")
                        peer-verify(required-trusted)
                        ssl-options(no-sslv2, no-sslv3, no-tlsv1, no-tlsv11)
                        trusted-keys(
                                "SHA1:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00"
                        )

                )
        );
};

```

And here are the list of our ca-dir:

```
[root@server customer_int]# ls -al /etc/syslog-ng/ca.d/customer_int/
total 8
drwxr-xr-x. 2 root root  168 Sep 14 13:53 .
drwxr-xr-x. 9 root root 4096 Jul 22 09:38 ..
lrwxrwxrwx. 1 root root   46 Feb 10  2021 22b7e9b1.0 -> /etc/syslog-ng/ca.d/RootCA.pem
lrwxrwxrwx. 1 root root   44 Jul  7 13:12 35448bde.0 -> /etc/syslog-ng/ca.d/IntermediateCA.pem
```

Howewer openssl s_client tells the following:
```
---
No client certificate CA names sent
Requested Signature Algorithms: ECDSA+SHA256:ECDSA+SHA384:ECDSA+SHA512:Ed25519:Ed448:RSA-PSS+SHA256:RSA-PSS+SHA256:RSA-PSS+SHA384:RSA-PSS+SHA384:RSA-PSS+SHA512:RSA-PSS+SHA512:RSA+SHA256:RSA+SHA384:RSA+SHA512:ECDSA+SHA224:RSA+SHA224:ECDSA+SHA1:RSA+SHA1
Shared Requested Signature Algorithms: ECDSA+SHA256:ECDSA+SHA384:ECDSA+SHA512:Ed25519:Ed448:RSA-PSS+SHA256:RSA-PSS+SHA256:RSA-PSS+SHA384:RSA-PSS+SHA384:RSA-PSS+SHA512:RSA-PSS+SHA512:RSA+SHA256:RSA+SHA384:RSA+SHA512
Peer signing digest: SHA256
Peer signature type: RSA-PSS
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 6439 bytes and written 429 bytes
Verification: OK
---
```

Is there an option for enabling sending ca names? The problem is that the library of the customer does not send a client certificate if there is no matching CA sent from the server.

Thank you very much
willcey

**Comment by alltilla** [comment]
Hi @willcey

syslog-ng supports mutual authentication, so this is either a bug or a misconfiguration. You can read about the best practices of mutual authentication here: https://www.syslog-ng.com/technical-documents/doc/syslog-ng-open-source-edition/3.33/mutual-authentication-using-tls

When encountering a problem, next time please open an Issue with our bug-report template. There are a lot of useful questions there, which I will ask now, but you can save a bit of time, by answering them when creating the issue.
https://github.com/syslog-ng/syslog-ng/issues/new?assignees=&labels=bug&template=10-bug-report.md&title=

Kindly answer these questions:
 * Which syslog-ng version produced the problem?
 * Which platform does the problem appear on?
 * Please reproduce the problem locally with a minimal config and custom, test-only cert files. Then please send us the config and the cert files with the exact reproduction steps.

Thanks!

Cheers,
Attila

**Comment by MrAnno** [comment]
The message in `openssl s_client` (`No client certificate CA names sent`) might be a bit misleading. As far as I know it refers to a TLS 1.3 extension called "certificate_authorities":

https://datatracker.ietf.org/doc/html/rfc8446#section-4.2.4

https://www.openssl.org/docs/man1.1.1/man3/SSL_set0_CA_list.html

This is just an extension. Mutual authentication, of course, works without it.
@willcey could you please clarify whether the "library of the customer" needs the mentioned TLS 1.3 extension in order to send client certificates?

**Comment by MrAnno** [comment]
In TLS 1.2, there's something similar, which can be used for the same purpose:


https://datatracker.ietf.org/doc/html/rfc5246#section-7.4.4


      A non-anonymous server can optionally request a certificate from
      the client...
      
      A list of the distinguished names [X501] of acceptable
      certificate_authorities, represented in DER-encoded format.  These
      distinguished names may specify a desired distinguished name for a
      root CA or for a subordinate CA; thus, this message can be used to
      describe known roots as well as a desired authorization space.  If
      the certificate_authorities list is empty, then the client MAY
      send any certificate of the appropriate ClientCertificateType,
      unless there is some external arrangement to the contrary.

This can be set with the previously mentioned OpenSSL call as well: https://www.openssl.org/docs/man1.1.1/man3/SSL_set0_CA_list.html

**Comment by MrAnno** [comment]
With the new `openssl-conf-cmds()` option that we are about to introduce in #4209, sending CA names will be possible by setting `RequestCAFile`.

@willcey Can you confirm that this is suitable for you and works as well?
