### ISSUE TITLE
doc bug: if template and == vs eq

### ISSUE THREAD

**Issue by furiel** [syslog-ng/syslog-ng#3787]
I noticed there is a documentation bug in the example section of the `$(if)` template.

https://www.syslog-ng.com/technical-documents/doc/syslog-ng-open-source-edition/3.33/administration-guide/68#TOPIC-1663418

<img width="808" alt="image" src="https://user-images.githubusercontent.com/11007226/133727862-2369c774-b34b-4d94-887d-46f9743993e2.png">

In the first example `$(if ("${username}" == "root") "violation" "system")` does not work as expected. `eq` should have been used instead of `==`, as we are comparing strings, not numbers. I did not test the patterndb samples, but probably same goes for those too.

It would also be nice to add a link to the section that explains how the `condition` part looks like. Or create such page if it does not exist yet.

---

In the source code
https://github.com/syslog-ng/syslog-ng/blob/4b6b8ae879da5d8e76c049ca1015b51ac2e87746/lib/template/tests/test_template.c#L313
is misleading. In the unit test, `eq` should have been used instead of `==` too.

That unit test asserts escaping, so from coverage perspective this does not change anything. But from documentation perspective, it is something that's worth fixing.

---

From design perspective, using `==` is essentially unusable for strings. This is very unfortunate, considering how easy to make this mistake in the configuration.

 `==` internally receives strings. So the first thing it does is it converts the arguments into numbers. Conversion is done by `atoi`, so unless the string starts with a digit, the result will be zero. From user experience, `==` feels a constant true for all strings, as we are comparing two zeroes for every typical strings.

Just an idea, but the conversion might be improved to detect error, and fallback to string comparison if any of the argument conversion fails.
It should be an easy change in the code: just a few lines around: https://github.com/syslog-ng/syslog-ng/blob/4b6b8ae879da5d8e76c049ca1015b51ac2e87746/lib/filter/filter-cmp.c#L50
Though the implications should be enumerated and evaluated.

**Comment by alltilla** [comment]
Hi @furiel 

Thanks! I have opened a DOC ticket, to fix the documentation (sadly ~20 examples were incorrect).
Also, I have opened a PR to fix the unit tests: https://github.com/syslog-ng/syslog-ng/pull/3789

I kind of like the idea of falling back to string comparison, if `atoi()` fails.
Maybe we could add a stats-counter, which counts have many fallback have been done, so users could find the misconfigured filters.

Also, I am thinking about how this feature would be improved with bazsi's `NVEntry` `type` feature: https://github.com/syslog-ng/syslog-ng/pull/3768

Cheers,
Attila
