### ISSUE TITLE
Syslog-ng not writing to disk version 3.23.1

### ISSUE THREAD

**Issue by kiphackman** [syslog-ng/syslog-ng#3818]
Having an issue where syslog-ng is not writing to disk. version 3.23.1
We have multiple servers getting logs. Im running the same version on both servers Version 3.23.1 
I copied the configuration from a production server where the configuration is successfully writing to disk and replaced it with the config on the server where syslog-ng is not writing to disk. However I cant seem to resolve the issue.
Troubleshooting I did:
I verified Syslog is coming in via udp 514 and a TCP dump.
I verified path permissions, service level permissions, error messages.
I modified the configuration to use create_dirs and create-dirs
I tried to use a udp port 514 config and a udp ip0.0.0.0 port 514 had no luck. 
I tried changing the $HOST variable in the destination d_catch line, same thing no luck.
I tried restarting the process in between changes for the configuration by using systemctl restart syslog-ng and                
 syslog-ng.service nothing worked .
Any advice or troubleshooting or remediations you guys would recommend?
This has been going on prior to me joining the company.

syslog-ng.conf ( I attached it since the markdown is changing the font.)

[syslog-ng - Copy.txt](https://github.com/syslog-ng/syslog-ng/files/7391121/syslog-ng.-.Copy.txt)

syslog-ng --version
`syslog-ng 3 (3.23.1)
Config version: 3.23
Installer-Version: 3.23.1
Revision: 
Compile-Date: Jul  2 2020 13:35:47
Module-Directory: /usr/lib64/syslog-ng
Module-Path: /usr/lib64/syslog-ng
Include-Path: /usr/share/syslog-ng/include
Available-Modules: add-contextual-data,affile,afprog,afsocket,afstomp,afuser,appmodel,basicfuncs,cef,confgen,cryptofuncs,csvparser,date,dbparser,disk-buffer,examples,graphite,hook-commands,json-plugin,kvformat,linux-kmsg-format,map-value-pairs,pseudofile,sdjournal,snmptrapd-parser,stardate,syslogformat,system-source,tags-parser,tfgetent,xml
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: on
Enable-TCP-Wrapper: off
Enable-Linux-Caps: on
Enable-Systemd: on`
syslog-ng -v (the HTTP issue is benign I also have this on the my prod working server)
`[2021-10-21T11:39:00.435230] Plugin module not found in 'module-path'; module-path='/usr/lib64/syslog-ng', module='http'
[2021-10-21T11:39:00.437820] Plugin module not found in 'module-path'; module-path='/usr/lib64/syslog-ng', module='http'
[2021-10-21T11:39:00.438438] Plugin module not found in 'module-path'; module-path='/usr/lib64/syslog-ng', module='http'
[2021-10-21T11:39:00.441024] WARNING: With use-dns(no), dns-cache() will be forced to 'no' too!;`

OS
`Red Hat Enterprise Linux release 8.4 (Ootpa)`

**Comment by czanik** [comment]
SELinux and firewall can both block network traffic. Try to disable them *temporarily* and see which causes the problem. In both cases you can see network traffic to port 514, but logs never reach syslog-ng.
