### ISSUE TITLE
documentation marks unix-dgram as unreliable although it is reliable on every Linux system

### ISSUE THREAD

**Issue by nmav** [syslog-ng/syslog-ng#3828]
## Documentation version
3.30

## Incorrect section
https://www.syslog-ng.com/technical-documents/doc/syslog-ng-open-source-edition/3.30/administration-guide/29#TOPIC-1594959

## Description of the problem
The document says that the `/dev/log` DGRAM socket is unreliable and messages can be lost:
```
The unix-stream() and unix-dgram() drivers open an AF_UNIX socket and start listening on it for messages.
The unix-stream() driver is primarily used on Linux and uses SOCK_STREAM semantics (connection oriented,
no messages are lost), while unix-dgram() is used on BSDs and uses SOCK_DGRAM semantics: this may
result in lost local messages if the system is overloaded.
```
that is incorrect. Unix domain sockets are reliable. You can see that explicitly spelled out in `unix(7)`:
http://manpages.ubuntu.com/manpages/bionic/en/man7/unix.7.html
`UNIX domain datagram sockets are always reliable and  don't  reorder datagrams`

## Proposed solution
Replace the text to the following:
```
The unix-stream() and unix-dgram() drivers open an AF_UNIX socket and start listening on it for messages.
On Linux both the unix-stream() and unix-dgram() drivers are used and are always reliable,
while unix-dgram() is used on BSDs and uses SOCK_DGRAM semantics: this may result in lost local
messages if the system is overloaded.
```

**Comment by nmav** [comment]
I do not know if `unix-dgram` is unreliable on BSD systems. I kept the existing documentation as it was for that case on my suggestion.

**Comment by gaborznagy** [comment]
Hi @nmav 

Thank you for opening an issue and sorry for the late reply.
We'll discuss this chapter with the doc team.

If you consider this note in the admin guide, I think the above paragraph about only unix-dgram is used on BSDs is meant about the usage of `/dev/log` socket. The above paragraph can be confusing.
> NOTE:syslogd on Linux originally used SOCK_STREAM sockets, but some distributions switched to SOCK_DGRAM around 1999 to fix a possible DoS problem. On Linux you can choose to use whichever driver you like as syslog clients automatically detect the socket type being used.

See in the admin guide
https://www.syslog-ng.com/technical-documents/doc/syslog-ng-open-source-edition/3.33/administration-guide/29#TOPIC-1663263

We will revise the part about mentioning reliability: I don't know the implementation details of unix sockets on Linux vs BSDs, but I think the BSD implementation should as reliable as the Linux implementation.
See https://www.unix.com/man-page/FreeBSD/4/unix/
https://groups.seas.harvard.edu/courses/cs143/pa-one/bsd-ipctut.html

**Comment by nmav** [comment]
Thank you.

**Comment by HofiOne** [comment]
documentation is moved, a corresponding issue is created for this at

https://github.com/syslog-ng/syslog-ng.github.io/issues/130
