### ISSUE TITLE
syslog-ng on macOS Monterey

### ISSUE THREAD

**Issue by czanik** [syslog-ng/syslog-ng#3829]
# syslog-ng
## Version of syslog-ng

root@Peters-MacBook-Pro syslog-ng-3.34.1 # /usr/local/sbin/syslog-ng -s
iv_tls_user_register: called after iv_init
zsh: abort      /usr/local/sbin/syslog-ng -s
root@Peters-MacBook-Pro syslog-ng-3.34.1 # /usr/local/sbin/syslog-ng -V
syslog-ng 3 (3.34.1)
Config version: 3.33
Installer-Version: 3.34.1
Revision: 
Compile-Date: Nov  5 2021 16:51:12
Module-Directory: /usr/local/lib/syslog-ng
Module-Path: /usr/local/lib/syslog-ng
Include-Path: /usr/local/share/syslog-ng/include
Error opening plugin module; module='json-plugin', error='dlopen(/usr/local/lib/syslog-ng/libjson-plugin.dylib, 0x0009): Library not loaded: /usr/local/lib/libjson-c.3.dylib\x0a  Referenced from: /usr/local/lib/syslog-ng/libjson-plugin.dylib\x0a  Reason: tried: \'/usr/local/lib/libjson-c.3.dylib\' (no such file), \'/usr/lib/libjson-c.3.dylib\' (no such file)'
zsh: bus error  /usr/local/sbin/syslog-ng -V
root@Peters-MacBook-Pro syslog-ng-3.34.1 # 

## Platform

MacOS Monterey

root@Peters-MacBook-Pro syslog-ng-3.34.1 # uname -a
Darwin Peters-MacBook-Pro.local 21.1.0 Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:23 PDT 2021; root:xnu-8019.41.5~1/RELEASE_X86_64 x86_64

# Issue
## Failure

syslog-ng compiles, but aborts with various errors when trying to start, see above.

My compile was from 3.34.1 release. I'll try to compile from git as well, and share the results.

I used instructions from https://yash6866.gitbook.io/syslog-macos-testing/installation but with slight modification:

export PKG_CONFIG_PATH="/usr/local/opt/openssl@1.1/lib/pkgconfig:$PKG_CONFIG_PATH"

(note: the command in the instructions are for Apple ARM-based systems.

**Comment by czanik** [comment]
Update!

With a bit of extra work it looks better now :-)

- added configure option --with-ivykis=system
- installed json-c with brew: brew install json-c
- added configure option to make sure that the freshly installed json package is used: --with-jsonc=system

bash-3.2$ /usr/local/sbin/syslog-ng -s
[2021-11-05T17:42:37.483684] system(): Error detecting platform, unable to define the system() source. Please send your system information to the developers!; sysname='Darwin', release='21.1.0'
Error parsing config, syntax error, unexpected LL_ERROR, expecting '}' in /usr/local/etc/syslog-ng.conf:10:2-10:8:
5       
6       @version: 3.34
7       @include "scl.conf"
8       
9       source s_local {
10----> 	system();
10----> 	^^^^^^
11      	internal();
12      };
13      
14      source s_network {
15      	default-network-drivers(


syslog-ng documentation: https://www.syslog-ng.com/technical-documents/list/syslog-ng-open-source-edition
contact: https://lists.balabit.hu/mailman/listinfo/syslog-ng
bash-3.2$ /usr/local/sbin/syslog-ng -V
syslog-ng 3 (3.34.1)
Config version: 3.33
Installer-Version: 3.34.1
Revision: 
Compile-Date: Nov  5 2021 17:38:34
Module-Directory: /usr/local/lib/syslog-ng
Module-Path: /usr/local/lib/syslog-ng
Include-Path: /usr/local/share/syslog-ng/include
Available-Modules: timestamp,kvformat,appmodel,afprog,examples,cef,map-value-pairs,afsnmp,stardate,system-source,confgen,afuser,xml,disk-buffer,tfgetent,linux-kmsg-format,dbparser,json-plugin,add-contextual-data,pseudofile,affile,csvparser,basicfuncs,syslogformat,hook-commands,graphite,tags-parser,afstomp,http,secure-logging,mod-python,afsocket,cryptofuncs,azure-auth-header,regexp-parser
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: off
Enable-TCP-Wrapper: off
Enable-Linux-Caps: off
Enable-Systemd: off
bash-3.2$ 

More testing later, now off to weekend mode :-) I close it once I also did some functional testing.

**Comment by czanik** [comment]
I did some testing, and syslog-ng itself seems to work fine.

However, loggen has problems:

bash-3.2$ /usr/local/bin/loggen --help-all
error [loggen.c:enumerate_plugins:245] no loggen plugin found in /usr/local/lib/syslog-ng/loggen
error [loggen.c:enumerate_plugins:246] hint: you can use the SYSLOGNG_PREFIX environmental variable to specify plugin path
Usage:
  loggen [OPTION?]  target port

Help Options:
  -h, --help                                 Show help options
  --help-all                                 Show all help options
  --help-file-reader                         Show options

file-reader
  -R, --read-file=<filename>                 Read log messages from file
  -l, --loop-reading                         Read the file specified in read-file option in loop (it will restart the reading if reached the end of the file)
  --skip-tokens=<number>                     Skip the given number of tokens (delimined by a space) at the beginning of each line (default value: 0)
  -d, --dont-parse                           Don't parse the lines coming from the readed files. Loggen will send the whole lines as it is in the readed file

Application Options:
  -r, --rate=<msg/sec/active connection>     Number of messages to generate per second
  -s, --size=<size>                          Specify the size of the syslog message
  -I, --interval=<sec>                       Number of seconds to run the test for
  -T, --permanent                            Send logs without time limit
  -P, --syslog-proto                         Use the new syslog-protocol message format (see also framing)
  -H, --proxied                              Generate PROXY protocol v1 header
  --proxy-src-ip=<ip address>                Source IP for the PROXY protocol v1 header
  --proxy-dst-ip=<ip address>                Destination IP for the PROXY protocol v1 header
  --proxy-src-port=<port>                    Source port for the PROXY protocol v1 header
  --proxy-dst-port=<port>                    Destination port for the PROXY protocol v1 header
  -p, --sdata                                Send the given sdata (e.g. "[test name=\"value\"]") in case of syslog-proto
  -F, --no-framing                           Don't use syslog-protocol style framing, even if syslog-proto is set
  --active-connections=<number>              Number of active connections to the server (default = 1)
  --idle-connections=<number>                Number of inactive connections to the server (default = 0)
  -6, --ipv6                                 Use AF_INET6 sockets instead of AF_INET (can use both IPv4 & IPv6)
  -C, --csv                                  Produce CSV output
  -n, --number=<number>                      Number of messages to generate
  -Q, --quiet                                Don't print the msg/sec data
  --debug                                    Enable loggen debug messages
  --reconnect                                Attempt to reconnect when destination connections are lost

bash-3.2$ ls -l /usr/local/lib/syslog-ng/loggen/
total 240
-rwxr-xr-x  1 czanik  admin  53432 Nov  5 17:42 libloggen_socket_plugin.dylib
-rwxr-xr-x  1 czanik  admin   1259 Nov  5 17:42 libloggen_socket_plugin.la
-rwxr-xr-x  1 czanik  admin  55648 Nov  5 17:42 libloggen_ssl_plugin.dylib
-rwxr-xr-x  1 czanik  admin   1244 Nov  5 17:42 libloggen_ssl_plugin.la
bash-3.2$

**Comment by Kokan** [comment]
It won't load those plugins because assumes suffix https://github.com/syslog-ng/syslog-ng/blob/master/tests/loggen/loggen_plugin.h#L33 to contains `_plusin.so`.
Could you please try with this branch? https://github.com/Kokan/syslog-ng/tree/macos-loggen

**Comment by czanik** [comment]
Tested https://github.com/syslog-ng/syslog-ng/pull/3832 on top of the latest git master snapshot, and loggen works as expected. Closing issue.
