### ISSUE TITLE
Remove "Proprietary Edition" Wording

### ISSUE THREAD

**Issue by blackbearwh** [syslog-ng/syslog-ng#3848]
## Documentation version
3.34.1 (but goes back 4 years)

## Incorrect section
https://github.com/syslog-ng/syslog-ng/blob/master/contrib/balabit-initscripts/init.d >> line 16

## Description of the problem
States "Proprietary edition." This is triggering our company's FOSS review red flags.

## Proposed solution
Remove "Proprietary edition."

**Comment by MrAnno** [comment]
Thanks for letting us know about this. #3849 will remove that comment.

Please note that `contrib` is mostly unmaintained and it contains contributed work.

Maintained init.d scripts/systemd service files can be found under the `packaging` folder.
