### ISSUE TITLE
persistent symlinks for file destinations

### ISSUE THREAD

**Issue by a-biardi** [syslog-ng/syslog-ng#3854]
## Description of the problem

Like many others, I use macros in file destinations (say, `/var/log/cron.${YEAR}${MONTH}`), but I also want to maintain a persistent symlink to the current logfile (that would be something like `/var/log/cron`) in order to have "easier" access if I'm grepping for something manually.

## Proposed solution
I have a patch ready and am preparing a PR in github for discussion and review.
Configuration file would look like this:

```
destination d_file_cron {
  file("/var/log/cron.${YEAR}${MONTH}" symlink-as("/var/log/cron"));
};
```

From a functional perspective, the "symlink_as" file inherits both
"create-dirs" and file ownership from its file destination (permissions
are not applicable to symlinks, at least on linux).

## Alternatives
None, really.

## Additional context
None

**Comment by gaborznagy** [comment]
Just for information: this topic was started on the mail-list:
https://lists.balabit.hu/pipermail/syslog-ng/2021-December/026350.html

**Comment by gaborznagy** [comment]
#3855  is merged.
