### ISSUE TITLE
syslog-ng reload steps

### ISSUE THREAD

**Issue by deepulikesbru** [syslog-ng/syslog-ng#3856]
# syslog-ng
## Platform

# Issue
Syslog-ng is writing the logs to local destination path given in syslog-ng config file even after deleting the configuration file.
Tried to delete the log many times but still the log is getting created. 

Could you please help me with the steps to  reload the configuration file? Thanks in Advance.

**Comment by deepulikesbru** [comment]
@Kokan Please help me

**Comment by Kokan** [comment]
Sure.
1. first of all locate the configuration file (it may differ) but likely located in `/etc/syslog-ng/syslog-ng.conf`.
    Note: you can verify that the config you see is the one syslog-ng sees via asking syslog-ng for the configuration it uses:
    syslog-ng-ctl config # this is going to print the active config
2. do some editing to your liking (and hopefully syslog-ng will agree)
3. syslog-ng-ctl reload # this should reload the new configuration
    Note: if your new configuration is invalid, the old one will be used
4. verify the new config via syslog-ng-ctl config # this should contain your modification
    alternativly syslog-ng-ctl config -v #does check if the current config is equal to the one on the disk

I hope this helps. If you feel like you are stuck, simply stop syslog-ng and start it again that should be a clean cut.

PS

Also do not forget to add the `@version: 3.35` as the first line in your main configuration file.

**Comment by MrAnno** [comment]
(Note: This question is about an older (and commercial) version of syslog-ng PE v6.0.21 on an AIX machine.
https://gitter.im/syslog-ng/syslog-ng?at=61b244de197fa95a1cb51c28)

**Comment by deepulikesbru** [comment]
Hi @Kokan 

Use the below steps to reload the config file.
/opt/syslog-ng/sbin/syslog-ng -f /opt/syslog-ng/etc/syslog-ng.conf     
stopsrc -s syslog-ng
startsrc -s syslog-ng

Could you please guide me to delete the files which were used previously in the configuration file. Files are getting created even after deleting the files.  Thanks in advance

**Comment by gaborznagy** [comment]
Dear @deepulikesbru,

as @MrAnno described this project is for the Open Source Edition for syslog-ng.
I would highly recommend you to contact One Identity Support https://support.oneidentity.com/syslog-ng-premium-edition/6.0.21.
As mentioned before, AIX is quite a rare platform and we don't do regular builds for AIX either.

We welcome any contribution whether it is a bug report or a pull request regardless of the source (if it affects syslog-ng OSE as well), but we would like keep this channel to support the Open Source Community.

**Comment by deepulikesbru** [comment]
Thank you for the support @gaborznagy I will contact the support.
