### ISSUE TITLE
Expired PGP key for the repositories at opensuse.org

### ISSUE THREAD

**Issue by smortex** [syslog-ng/syslog-ng#3868]
Hi @lbudai,

The .deb repositories you maintain on http://download.opensuse.org are signed with a key which has expired with the new year:

```sh-session
romain@desktop-fln40kq ~ % curl -s 'http://download.opensuse.org/repositories/home:/laszlo_budai:/syslog-ng/Debian_10/Release.key' | gpg --show-keys 
pub   rsa2048 2017-08-25 [SC] [expired: 2021-12-31]
      F20F51628D04901AD01175013B92A8D27CFDAEDD
uid                      home:laszlo_budai:syslog-ng OBS Project <home:laszlo_budai:syslog-ng@build.opensuse.org>

```

Can you update it's expiration date and replace it?  Thanks!

**Comment by MrAnno** [comment]
Hi,

FYI the OBS repository is discontinued: https://lists.balabit.hu/pipermail/syslog-ng/2021-June/026292.html

Please consider using the new APT repo (https://ose-repo.syslog-ng.com).

You can find installation steps here:
https://github.com/syslog-ng/syslog-ng#debianubuntu

**Comment by smortex** [comment]
Oh my… I was not aware of this! Let's update some puppet modules so that everyone use the up-to-date code!

Thanks @MrAnno!
