### ISSUE TITLE
High CPU after a few hours

### ISSUE THREAD

**Issue by Vladx71** [syslog-ng/syslog-ng#3914]
# syslog-ng
## Version of syslog-ng
syslog-ng 3 (3.35.1)
Config version: 3.35
Installer-Version: 3.35.1
Revision: 3.35.1-1
Compile-Date: Nov 10 2021 10:23:22
Module-Directory: /usr/lib/syslog-ng/3.35
Module-Path: /usr/lib/syslog-ng/3.35
Include-Path: /usr/share/syslog-ng/include
Available-Modules: kvformat,appmodel,afprog,json-plugin,confgen,cef,basicfuncs,pacctformat,sdjournal,hook-commands,afuser,csvparser,linux-kmsg-format,dbparser,syslogformat,affile,pseudofile,cryptofuncs,afsocket,regexp-parser,tags-parser,disk-buffer,timestamp,system-source
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: on
Enable-TCP-Wrapper: on
Enable-Linux-Caps: on
Enable-Systemd: on

## Platform
RETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian

## Debug bundle

# Issue
## Failure
After running for a few hours, syslog-ng starts consuming all CPU resources and based on output of syslog-ng-ctl stats stops processing logs. There are no error messages and the only solution is to restart service. After that it is ok again for a few hours

## Steps to reproduce
Nothing special, just run the service

## Configuration
Nothing very complicated. A few network source with a few hundred logsources and two network destinations with minimal filtering and not-reliable disk buffer. I have other instances with different OS (CentOS7) with very similar config and no problem at all

**Comment by bazsi** [comment]
Unfortunately this is not going to be enough information, so we should find
out what it is doing.

Considering that syslog-ng stops processing messages, it probably means
that the main loop starts spinning for some reason.

Can you run an strace on the spinning process for a while? So at least we
have a lead to find out what could be the cause.

Please run strace attached to all threads, with "-ttTs" options.

Thanks.

**Comment by Vladx71** [comment]
It seems increasing --fd-limit solved the issue. The only thing I dont't understand why it was ok for years and not ok for now. Maybe the reason is a new logsource -some crappy vmware stuff- which started to sending huge amount of logs, but I don't see how it can affect the --fd-limit. I'm closing this issue for now, but maybe it should be considered to increase the default value of --fd-limit
