### ISSUE TITLE
Error loading Python module; module='syslogng_kafka.kafkadriver', exception='ModuleNotFoundError

### ISSUE THREAD

**Issue by Palezvar** [syslog-ng/syslog-ng#3915]
# syslog-ng
## Version of syslog-ng
```
syslog-ng 3 (3.35.1)
Config version: 3.35
Installer-Version: 3.35.1
Revision: 3.35.1-1
Compile-Date: Nov 10 2021 10:23:22
Module-Directory: /usr/lib/syslog-ng/3.35
Module-Path: /usr/lib/syslog-ng/3.35
Include-Path: /usr/share/syslog-ng/include
Available-Modules: afuser,cryptofuncs,syslogformat,hook-commands,tags-parser,cef,system-source,kvformat,pacctformat,dbparser,afsocket,timestamp,json-plugin,confgen,sdjournal,basicfuncs,appmodel,regexp-parser,affile,afprog,pseudofile,csvparser,mod-python,disk-buffer,linux-kmsg-format
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: on
Enable-TCP-Wrapper: on
Enable-Linux-Caps: on
Enable-Systemd: on
```

## Platform
`Ubuntu 20.04 LTS`

## Debug bundle
`Attached`

# Issue
## Failure
I am trying to use Kafka as destination for syslong-ng 3.35. Conf file is attached. The systemctl service does not start because it complains as follows:

```
# syslog-ng -F
[2022-02-12T02:50:22.713840] Error loading Python module; module='syslogng_kafka.kafkadriver', exception='ModuleNotFoundError: No module named \'syslogng_kafka\''
ModuleNotFoundError: No module named 'syslogng_kafka'
[2022-02-12T02:50:22.724023] Error looking Python driver class; driver='syslog_to_kafka#0', class='syslogng_kafka.kafkadriver.KafkaDestination', exception='None'
[2022-02-12T02:50:22.724049] Error initializing message pipeline; plugin_name='python', location='/etc/syslog-ng/conf.d/kafka.conf:8:5'

```

## Input and output logs (if possible)
[syslog.debun.kubernetes-node1.2022-02-12_02-43.1498726.zip](https://github.com/syslog-ng/syslog-ng/files/8052581/syslog.debun.kubernetes-node1.2022-02-12_02-43.1498726.zip)
[kafka.zip](https://github.com/syslog-ng/syslog-ng/files/8052584/kafka.zip)

**Comment by bazsi** [comment]
The Kafka destination is not python based, rather it is using librdkafka
directly. But that's just an initial hint, I can't check the config at the
moment.

**Comment by MrAnno** [comment]
The relevant part of the configuration:

```
destination syslog_to_kafka {
    python(
        class("syslogng_kafka.kafkadriver.KafkaDestination")
            on-error("fallback-to-string")
            # ...
    );
};
```

This snippet is probably from https://syslogng-kafka.readthedocs.io/en/latest/installation.html, which is not maintained by us.

----

We have a native Kafka destination written in C (called `kafka-c()`), we'd recommend using it:
https://www.syslog-ng.com/community/b/blog/posts/kafka-destination-improved-with-template-support-in-syslog-ng

Docs:
https://www.syslog-ng.com/technical-documents/doc/syslog-ng-open-source-edition/3.33/administration-guide/40#TOPIC-1663306

**Comment by Palezvar** [comment]
[config files.zip](https://github.com/syslog-ng/syslog-ng/files/8062686/config.files.zip)

I uploaded the following files to the ticket:
1) syslog-ng.conf: I don't make any modifications on this file. It is the default file used in the Kubernetes pod when I pull the image from balabit/syslog-ng:3.35.1.
2) kafka.conf: This is the conf file I create and mount under /etc/syslog-ng/conf.d/ in the Kubernetes pod
3) syslogng-server-deployment.yaml: This is my deployment file for Kubernetes. You can see that I am actually including the content of kafka.conf as part of the file.

**Comment by MrAnno** [comment]
That is really unfortunate, but the default configuration of the Docker image does not include snippets from the conf.d folder. You can either replace the default config with yours, or you need to add something like this to the default config:

```
@include "/etc/syslog-ng/conf.d/*.conf"
```

**Comment by Palezvar** [comment]
Thank you very much. It all works now with my Kubernetes pod.
