### ISSUE TITLE
HTTP destination driver support gzip compression

### ISSUE THREAD

**Issue by ryanfaircloth** [syslog-ng/syslog-ng#3923]
## Description of the problem
Users facing metered egress charges can benefit from gzip compressed posts this is a feature of libcurl used by syslog-ng but needs to be exposed in the destination driver to enable.

**Comment by rfaircloth-splunk** [comment]
Reference code to encode with gzip and post
http://mattikariluoma.com/blog/cURL%20+%20gzip%20(Beating%20a%20Dead%20Horse).html
