### ISSUE TITLE
Dependency on systemd and containers

### ISSUE THREAD

**Issue by Bill-ColeUS** [syslog-ng/syslog-ng#3931]
## Description of the problem
I install syslog-ng on all of my docker and k8s containers. Unfortunately, the syslog-ng package available to RHEL and derivatives (AlmaLinux, Rocky, etc) have a hard dependency on systemd, thus systemd packages are forcibly installed, even though systemd is not being used.

## Proposed solution
Make systemd optional, if possible.

## Alternatives
Maybe it would be possible to split the part of syslog-ng that requires systemd into a separate package? That way the main syslog-ng will not pull systemd along with it.

## Additional context
syslog-ng is awesome :)

Thank you!

**Comment by czanik** [comment]
I'm not sure if I can solve this one. The syslog-ng package has two dependencies on systemd:

* reading the journal
* service management

Both are considered to be core requirements by Red Hat standards. So, I'll check these, but no promises for a quick solution or at all.

**Comment by czanik** [comment]
OK, it's most likely a no go. I just checked, and it's not just ```libsdjournal.so``` (the journal reader module) which is linked to ```libsystemd.so``` but also ```libsyslog-ng.so``` which is syslog-ng's core library. I could move libsdjournal into a sub-package to remove the dependency, but not libsyslog-ng

**Comment by bazsi** [comment]
The only way to disable that dependency would be to configure syslog-ng
with --disable-systemd

This would only make sense for a container specific build, but I would want
to avoid doing that. I haven't heard of any packages that would do that.

I find it strange that systemd could be optional within a rhel based
container. How is this solved by other similar rpm packages? I mean one
that has systemd related functions. Those do not depend on systemd?

The dependency of our journal source definitely needs systemd and that
makes sense.

The core library depends on systemd to report startup/reload status to
systemd. Btw this only needs the client library and not the entire daemon.
Isn't that the issue?

**Comment by Bill-ColeUS** [comment]
Thank you for taking the time to investigate this issue.

I understand that its not possible to remove the dependency on systemd.

To answer @bazsi, the containers do not use systemd and by default they replaced dnf with microdnf. Thus, there is no loading of anything related to systemd. Services are started by the container CMD option and/or entrypoint script.

Last time I checked the status of systemd, it was not a good match for containers, because it started a lot of extra services that are unusable by the nature of containers, like `tty`  getty login terminals, udev and others. I think there are some special container images that come with systemd, for those who require it.

**Comment by bazsi** [comment]
I understand that systemd would launch a number of services that are not needed for the container. I was just surprised to learn that it is not even part of the image.

But even if that's the case, there might be some trickery we can do to address this situation, so it's not impossible to solve this.

We have two dependencies on systemd, one is specified by the spec file explicitly:

```
%if %{with systemd}
BuildRequires: systemd-units
BuildRequires: systemd-devel
Requires(post): systemd-units
Requires(preun): systemd-units
Requires(postun): systemd-units
%endif
```

The BuildRequires line is OK, but why do we depend on systemd-units? @czanik do you have a hint here? because code-wise we definitely have nothing to do with systemd-units. We do provide our own unit file, yes, but we don't care about what other unit files are there. And systemd-units is provided by systemd, so that will definitely pull on the whole systemd.

The other dependency is an automatically discovered dependency on libsystemd, the client library I mentioned:

```
libsystemd.so.0()(64bit)
libsystemd.so.0(LIBSYSTEMD_209)(64bit)
```

But this is probably installed even in AlmaLinux if it installs into anything but containers....

I've checked:
```
bazsi@bzorp:~/Downloads$ docker run -ti almalinux:latest bash
[root@4a14732c1434 /]# rpm -qa | grep systemd
systemd-libs-239-51.el8.x86_64
systemd-pam-239-51.el8.x86_64
systemd-239-51.el8.x86_64
[root@4a14732c1434 /]# rpm -qil systemd-libs
Name        : systemd-libs
Version     : 239
Release     : 51.el8
Architecture: x86_64
Install Date: Fri Nov 12 13:11:26 2021
Group       : Unspecified
Size        : 4569558
License     : LGPLv2+ and MIT
Signature   : RSA/SHA256, Tue Nov  9 18:26:10 2021, Key ID 51d6647ec21ad6ea
Source RPM  : systemd-239-51.el8.src.rpm
Build Date  : Tue Nov  9 18:09:37 2021
Build Host  : 192-168-251-21.atm.cloudlinux.com
Relocations : (not relocatable)
Packager    : AlmaLinux Packaging Team <packager@almalinux.org>
Vendor      : AlmaLinux
URL         : http://www.freedesktop.org/wiki/Software/systemd
Summary     : systemd libraries
Description :
Libraries for systemd and udev.
/usr/lib/.build-id
/usr/lib/.build-id/1c/9ed23a82c69a20dec4e2431dc746f7582d7c7c
/usr/lib/.build-id/47/4b4c1b22173d30ecd659d4d37bef99b6ec723e
/usr/lib/.build-id/6d
/usr/lib/.build-id/6d/e6635e31ea962c09fa32100f3574ab91f1daca
/usr/lib/.build-id/d6/02f72249694868232b813af061e8345a852f3e
/usr/lib/.build-id/f4
/usr/lib/.build-id/f4/3ec0ea0408cee862ede97096865f4d5be7474e
/usr/lib64/libnss_myhostname.so.2
/usr/lib64/libnss_resolve.so.2
/usr/lib64/libnss_systemd.so.2
/usr/lib64/libsystemd.so.0
/usr/lib64/libsystemd.so.0.23.0
/usr/lib64/libudev.so.1
/usr/lib64/libudev.so.1.6.11
/usr/share/licenses/systemd
/usr/share/licenses/systemd/LICENSE.LGPL2.1
/usr/share/man/man8/libnss_myhostname.so.2.8.gz
/usr/share/man/man8/libnss_resolve.so.2.8.gz
/usr/share/man/man8/libnss_systemd.so.2.8.gz
```

This means that the default AlmaLinux container has both systemd-libs and systemd itself. 

OK, I guess you want to create trimmed down image. In that case, I think letting our dependency on systemd-units go, syslog-ng dependencies would be satisfied with only installing systemd-libs, which is much smaller at somewhat less than 5MB. 

Is that OK as a solution?

**Comment by czanik** [comment]
The systemd part of the package was done in the RHEL 7 times by one of the syslog-ng package co-maintainers and I not touched ever since. I guess that by that time it was a mandatory dependency. I'll try to create a test package without the systemd-units dependency for my syslog-ng git snapshot repo, which you can try. I'll let you know once it's available.

**Comment by Bill-ColeUS** [comment]
@bazsi  My appologies, I failed to mention that I am using the minimal tags (minimal, 8-minimal, 8.5-minimal-20211112), I suppose those containers differ from the full-sized images and don't come with systemd pre-installed.

Even a slight reduction to the dependency size is welcome.

Thank you all.

**Comment by czanik** [comment]
@Bill-ColeUS version 3.36.449 in my https://copr.fedorainfracloud.org/coprs/czanik/syslog-ng-githead/ repo now has the next three lines removed from the spec file:
```
Requires(post): systemd-units
Requires(preun): systemd-units
Requires(postun): systemd-units
```
I did a quick test, and the package still installs and works fine on a CentOS 8 Stream base system.

Let me know, if this change solves your problem in the minimal container. I would not be surprised if there were some warnings or errors during installation, as the pre/post scripts use systemd:
```
%post
ldconfig
%systemd_post syslog-ng.service

%preun
%systemd_preun syslog-ng.service

%postun
ldconfig
%systemd_postun_with_restart syslog-ng.service
```
I have to go now, and will check your results tomorrow.

**Comment by Bill-ColeUS** [comment]
I will test and report back to you. Thank you.

**Comment by Bill-ColeUS** [comment]
Sorry for the late reply.

I installed your copr and run dnf update to overwrite my existing packages with the newer 2.36.449. With the new version, there is no crash, it only complains about the old configuration file. Unfortunately, nothing seems to be sent to RabbitMQ, I am not sure why but I'm investigating...

```
# /usr/sbin/syslog-ng --cfgfile /etc/syslog-ng/syslog-ng.conf --control /var/lib/syslog-ng/syslog-ng.ctl --persist-file /var/lib/syslog-ng/syslog-ng.persist --pidfile /run/syslog-ng.pid --no-caps -F
[2022-03-03T09:14:04.605924] WARNING: Configuration file format is too old, syslog-ng is running in compatibility mode. Please update it to use the syslog-ng 3.35 format at your time of convenience. To upgrade the configuration, please review the warnings about incompatible changes printed by syslog-ng, and once completed change the @version header at the top of the configuration file; config-version='3.23'
[2022-03-03T09:14:04.644614] WARNING: The internal_queue_length stat counter has been renamed to internal_source.queued. The old name will be removed in future versions; config-version='3.23'
```

**Comment by czanik** [comment]
@Bill-ColeUS  Does it work now? Should I keep this change?

**Comment by Bill-ColeUS** [comment]
Yes its working beautifully and with less dependencies. Please keep this change if possible, so others can benefit.
