### ISSUE TITLE
subst feature does not allow dynamic data

### ISSUE THREAD

**Issue by rfaircloth-splunk** [syslog-ng/syslog-ng#3954]
Attempting to use subst to "snip" a small part of a field
subst('${.values.identifier}', "${.tmp.host}-", value('MESSAGE'));

the replace value is taken as a literial

**Comment by bazsi** [comment]
It does support templates and the syntax is:

subst('regexp', 'replacement template expression' value('MESSAGE'));

**Comment by rfaircloth-splunk** [comment]
thanks
