### ISSUE TITLE
RFC5424 metadata SDID added to all outbound messages

### ISSUE THREAD

**Issue by rfaircloth-splunk** [syslog-ng/syslog-ng#3980]
The .SDATA.metadata.sequence is being added to all 5424 events relayed or sent via http. While this addition to the format is valid some downstream systems do not properly obey the standard please provide a means to filter the sdata

**Comment by bazsi** [comment]
This is fixed here: https://github.com/syslog-ng/syslog-ng/pull/3928

**Comment by gaborznagy** [comment]
I'm closing this as #3928 fixed this behaviour.
