### ISSUE TITLE
syslog-ng with amqp support

### ISSUE THREAD

**Issue by nzubarev122** [syslog-ng/syslog-ng#3989]
how to syslog-ng with amqp support for centos 7 ?

**Comment by gaborznagy** [comment]
For building syslog-ng with amqp support, you need to install the `librabbitmq-devel` package.

If you need a built package, @czanik packages syslog-ng on Centos 7. Check out the blog about the [latest syslog-ng packages on RPM-based system](https://www.syslog-ng.com/community/b/blog/posts/installing-latest-syslog-ng-on-rhel-and-other-rpm-distributions).
