### ISSUE TITLE
Configuring custom signature hash for TLS communication

### ISSUE THREAD

**Issue by mohitvaid** [syslog-ng/syslog-ng#3992]
### Discussed in https://github.com/syslog-ng/syslog-ng/discussions/3983

<div type='discussions-op-text'>

<sup>Originally posted by **mohitvaid** April 12, 2022</sup>
Hi there,

As part of our TLS configuration, to be compliant with [NIAP](https://www.niap-ccevs.org/product/)... we need to be specific wrt to few specific ciphers, elliptic curves and signature hash,
Based on https://www.syslog-ng.com/technical-documents/doc/syslog-ng-open-source-edition/3.24/administration-guide/61#TOPIC-1298105

I can see we can configure the ciphers and the elliptic curves but unable to find capability to configure the signature hash algorithms.

Any pointers to achieve the same?</div>

**Comment by gaborznagy** [comment]
Hi!
Let's keep the conversation in https://github.com/syslog-ng/syslog-ng/discussions/3983, please.

I think this issue should be turned into a feature request to support configuring OpenSSL through [`SSL_CONF_cmd`](https://www.openssl.org/docs/man1.1.1/man3/SSL_CONF_cmd.html).
We've seen that multiple vendors support this not just rsyslog, e.g. nginx:
https://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_conf_command

**Comment by mohitvaid** [comment]
Creating feature request as suggested.
