### ISSUE TITLE
OCSP Support for TLS communication

### ISSUE THREAD

**Issue by mohitvaid** [syslog-ng/syslog-ng#4013]
## Description of the problem
OCSP Support for the TLS Communication

## Alternatives
Currently provided support for CRL needs client side intervention to keep the crl files updated in the crldir(),=,

## Additional context
We need to validate certification revocation to be NIAP compliant. Currently supported CRL feature needs crl files to be present in crldir(), which in turn needs these files to be kept updated always, if OCSP support can be added, would help quite a lot.

## Side Note

- **Can this change be accommodated in upcoming 3.7 release?**
- Can this support be extended to MQTT TLS as well? 

Discussion thread: https://github.com/syslog-ng/syslog-ng/discussions/4010

**Comment by mohitvaid** [comment]
@MrAnno created this enhancement based on https://github.com/syslog-ng/syslog-ng/discussions/4010.

**Comment by MrAnno** [comment]
I'm going to work on this soon. @mohitvaid Which side is more urgent for you (source, destination, both)?

**Comment by mohitvaid** [comment]
@MrAnno If possible, both will be more helpful as that would help with any unknowns in future. Thanks for considering this.

**Comment by mohitvaid** [comment]
@MrAnno are you planning to put this feature in 3.7, kindly share the plan. Thanks.

**Comment by MrAnno** [comment]
This won't fit into 3.37, maybe the next release. I'll let you know once the pull request is opened.

**Comment by mohitvaid** [comment]
@MrAnno Please check the feasibility to fit this in the upcoming release. Thanks.

**Comment by mohitvaid** [comment]
@MrAnno @OverOrion please update.

**Comment by MrAnno** [comment]
I've opened a PR that attempts to support OCSP stapling on the destination side (network, syslog, http destinations).

@mohitvaid Please take a look and give us some feedback: #4082

**Comment by mohitvaid** [comment]
Thanks, it's reviewed. Can this be merged?

**Comment by MrAnno** [comment]
We have a review and testing process. We will merge it when we are ready.

**Comment by mohitvaid** [comment]
> I'm going to work on this soon. @mohitvaid Which side is more urgent for you (source, destination, both)?

@MrAnno as there are very few or none supporting this on server side, any chance this is being into consideration?

**Comment by MrAnno** [comment]
The destination side of the OCSP support has been merged.

OCSP stapling on the source side is a more serious task, I don't have plans to implement this in the near future.
Contributions (pull requests, suggestions, etc.) are always welcome.
