### ISSUE TITLE
csv-parser(flags(strip-whitespace)) ignore "strip-whitespace"

### ISSUE THREAD

**Issue by Roffild** [syslog-ng/syslog-ng#4027]
# syslog-ng
## Version of syslog-ng
syslog-ng 3 (3.30.1)
Config version: 3.29
Installer-Version: 3.30.1

## Platform
alpine 3.15

I want to read the log myself. But I also want to parse the log. That's why I use JSON.
```
# input:
LOG:  starting PostgreSQL 14.2 on x86_64-pc-linux-musl, compiled by gcc (Alpine 10.3.1_git20211027) 10.3.1 20211027, 64-bit

# code:
parser {
	csv-parser(columns("PGSEVERITY", "PGMSG"), delimiters(":"), flags(strip-whitespace, greedy));
};
rewrite {
	set('$(format-json d="${R_ISODATE}" zlm="${PGSEVERITY}" m="${PGMSG}")', value("MESSAGE"));
};

# output:
{"zlm":"LOG","m":"  starting PostgreSQL 14.2 on x86_64-pc-linux-musl, compiled by gcc (Alpine 10.3.1_git20211027) 10.3.1 20211027, 64-bit","d":"2022-05-26T10:33:37+03:00"}
```
Spaces in `"  starting`

`csv-parser(flags(strip-whitespace))` ignore `strip-whitespace`

**Comment by bazsi** [comment]
It seems that the greedy column ignores strip-whitespace and basically all other similar processing (e.g. null-value).

so this indeed seems to be a bug.

**Comment by bazsi** [comment]
I just opened a PR to fix this.
