### ISSUE TITLE
Ubuntu 22.04 missing libjson-c4 repository after recent patch

### ISSUE THREAD

**Issue by impishskald** [syslog-ng/syslog-ng#4070]
Recently updated my syslog-ng server and libjson-c4 was upgraded to libjson-c5 and c4 was removed from the repository. Through troubleshooting I was trying to reinstall syslog-ng and ran into missing depends error below:

The following packages have unmet dependencies:
syslog-ng-core : Depends: libjson-c4 (>= 0.13.1) but it is not installable
                  Depends: libssl1.1 (>= 1.1.1) but it is not installable

From research it looks like libjson-c4 has been replaced in the Debian repositories by libjson-c5 is there a way to utilize the libjson-c5 version or how should I resolve this issue? FYI this was working on Ubuntu 22.04 Jammy up until the past week. I ran updates on the system to resolve another issue and after that I’m getting an error starting the daemon 

× syslog-ng.service - System Logger Daemon
     Loaded: loaded (/lib/systemd/system/syslog-ng.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Tue 2022-07-05 15:39:48 UTC; 4s ago
       Docs: man:syslog-ng(8)
    Process: 1342 ExecStart=/usr/sbin/syslog-ng -F $SYSLOGNG_OPTS (code=exited, status=2)
   Main PID: 1342 (code=exited, status=2)
     Status: "Starting up... (Tue Jul  5 15:39:48 2022"
        CPU: 29ms

Jul 05 15:39:48 <hostname> systemd[1]: syslog-ng.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jul 05 15:39:48 <hostname> systemd[1]: syslog-ng.service: Failed with result 'exit-code'.
Jul 05 15:39:48 <hostname> systemd[1]: Failed to start System Logger Daemon.
Jul 05 15:39:48 <hostname> systemd[1]: syslog-ng.service: Scheduled restart job, restart counter is at 5.
Jul 05 15:39:48 <hostname> systemd[1]: Stopped System Logger Daemon.
Jul 05 15:39:48 <hostname> systemd[1]: syslog-ng.service: Start request repeated too quickly.
Jul 05 15:39:48 <hostname> systemd[1]: syslog-ng.service: Failed with result 'exit-code'.
Jul 05 15:39:48 <hostname> systemd[1]: Failed to start System Logger Daemon.

**Comment by MrAnno** [comment]
Hi,

Did you update the distro version in `/etc/apt/sources.list.d/syslog-ng-ose.list` after the OS upgrade?

Please note that we only have nightly (unstable) packages for Ubuntu 22.04 ("`ubuntu-jammy`"), a stable release for 22.04 will only be available in the next syslog-ng release.

**Comment by impishskald** [comment]
It was installed on jammy, but I did attempt to point to the unstable repository and got the same error I used the following commands:

 echo "deb [arch=amd64] https://ose-repo.syslog-ng.com/apt/ nightly ubuntu-jammy" | sudo tee -a /etc/apt/sources.list.d/syslog-ng-ose.list
 sudo apt-cache search syslog-ng
sudo apt-get install syslog-ng-core

I still ran into the same missing depends issue.

**Comment by impishskald** [comment]
Well maybe this was fixed in last night's update because I just re-ran them and got different results. My install worked this morning.

**Comment by impishskald** [comment]
Yeah the latest build resolved that issue. Not fixing user error from importing in my old config file. Is there a way to generate a new "default" or as installed config file for syslog-ng.conf? I'm new to syslog-ng

**Comment by MrAnno** [comment]
Sure, you can find the default config here:
https://github.com/syslog-ng/syslog-ng/blob/master/packaging/debian/syslog-ng.conf

Alternatively, you can ask dpkg/apt to reinstall syslog-ng-core and replace your old configs with the default one:

```
$ systemctl stop syslog-ng
$ apt install --reinstall -o Dpkg::Options::="--force-confask,confnew,confmiss" syslog-ng-core
```

**Comment by impishskald** [comment]
Awesome, Thanks! I appreciate the quick response.

**Comment by MrAnno** [comment]
My pleasure.
