### ISSUE TITLE
syslog-ng RPM package is vulnerable to multiple CVE's due to old json-c dependency

### ISSUE THREAD

**Issue by bstanDISCO** [syslog-ng/syslog-ng#4072]
My current version of syslog-ng is vulnerable to multiple CVE's due to the following json-c dependency which wont allow me to 
`sudo dnf update`

Error:
 Problem: cannot install the best update candidate for package syslog-ng-3.23.1-2.el8.x86_64
  - nothing provides libjson-c.so.2()(64bit) needed by syslog-ng-3.31.2-1.el7.x86_64

Who can help me with this?

_Originally posted by @bstanDISCO in https://github.com/syslog-ng/syslog-ng/issues/4060#issuecomment-1176825129_

**Comment by bstanDISCO** [comment]
@czanik - I was told to contact you about updating the RPM repository to address this please?

**Comment by bstanDISCO** [comment]
@czanik  - I am using CentOS Linux 8 RHEL fedora

`$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"
[centos@localhost ]$ dnf install syslog-ng-http syslog-ng-logrotate
Error: This command has to be run with superuser privileges (under the root user on most systems).
[centos@localhost]$ sudo dnf install syslog-ng-http syslog-ng-logrotate
Last metadata expiration check: 0:13:47 ago on Thu 07 Jul 2022 09:12:26 PM UTC.
Package syslog-ng-logrotate-3.23.1-2.el8.x86_64 is already installed.
Error:
Problem: package syslog-ng-http-3.31.2-1.el7.x86_64 requires libsyslog-ng-3.31.so.0()(64bit), but none of the providers can be installed

package syslog-ng-http-3.31.2-1.el7.x86_64 requires syslog-ng(x86-64) = 3.31.2-1.el7, but none of the providers can be installed
cannot install the best candidate for the job
nothing provides libjson-c.so.2()(64bit) needed by syslog-ng-3.31.2-1.el7.x86_64
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
`

**Comment by czanik** [comment]
@bstanDISCO You are trying to install syslog-ng from my CentOS 7 repository on CentOS 8. You can see this from 'el7' in the syslog-ng package name. Make sure that you use the CentOS 8 repository on CentoS 8. For example: https://copr.fedorainfracloud.org/coprs/czanik/syslog-ng337/repo/epel-8/czanik-syslog-ng337-epel-8.repo

Re-open the bug, if you still see dependency problems using the correct repo.
