### ISSUE TITLE
el8 update dependency issues

### ISSUE THREAD

**Issue by bstanDISCO** [syslog-ng/syslog-ng#4074]
After updating our repo to the most current version, this is now my issue when running a "sudo dnf update" 

```
[centos@localhost]$ sudo dnf update
Last metadata expiration check: 0:40:33 ago on Fri 08 Jul 2022 07:47:46 PM UTC.
Error:
 Problem 1: cannot install the best update candidate for package syslog-ng-3.23.1-2.el8.x86_64
  - nothing provides libjson-c.so.4(JSONC_0.14)(64bit) needed by syslog-ng-3.37.1-1.el8.x86_64
 Problem 2: package syslog-ng-logrotate-3.37.1-1.el8.x86_64 requires syslog-ng(x86-64) = 3.37.1-1.el8, but none of the providers can be installed
  - cannot install the best update candidate for package syslog-ng-logrotate-3.23.1-2.el8.x86_64
  - nothing provides libjson-c.so.4(JSONC_0.14)(64bit) needed by syslog-ng-3.37.1-1.el8.x86_64
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)

```

**Comment by bstanDISCO** [comment]
I cant find this file anywhere online, seems like a typo almost? libjson-c.so.4(JSONC_0.14)(64bit)

Shouldnt this be libjson-c.so.5(JSONC_0.14)(64bit)- which doesnt exist for CentOS 8?

**Comment by czanik** [comment]
Oh, this thread somehow stayed under the radar until now.

I do not have any influence on the JSON version used during compilation. EPEL and Fedora Copr (where I compile my packages) always use the latest RHEL version to compile packages. If there is a breaking change between minor RHEL releases, then old syslog-ng packages do not run on new RHEL / CentOS / Rocky / Alma / etc. minor releases, and new syslog-ng packages do not run on older RHEL / etc. minor releases.
