### ISSUE TITLE
Why compiling syslog-ng so hardly?

### ISSUE THREAD

**Issue by zhengshuxin** [syslog-ng/syslog-ng#4090]
I've tried many times to compile the current version syslog-ng on CentOS7.6, but failed at last. Many years ago it's easy to build it, now it's too complex because it adds many features and is depedent on many third-party modules which makes the compiling process more complex and hardly. The errors I'v got show below:
```
make --no-print-directory all-recursive
  CCLD     modules/dbparser/pdbtool/pdbtool
./lib/.libs/libsyslog-ng.so: undefined reference to `SSL_CTX_set_keylog_callback'
./lib/.libs/libsyslog-ng.so: undefined reference to `OPENSSL_sk_value'
./lib/.libs/libsyslog-ng.so: undefined reference to `X509_get_extension_flags'
./lib/.libs/libsyslog-ng.so: undefined reference to `SSL_clear_options'
./lib/.libs/libsyslog-ng.so: undefined reference to `SSL_CTX_set_ciphersuites'
./lib/.libs/libsyslog-ng.so: undefined reference to `BN_get_rfc3526_prime_2048'
./lib/.libs/libsyslog-ng.so: undefined reference to `SSL_CTX_set_num_tickets'
./lib/.libs/libsyslog-ng.so: undefined reference to `SSL_set_options'
./lib/.libs/libsyslog-ng.so: undefined reference to `OPENSSL_sk_num'
./lib/.libs/libsyslog-ng.so: undefined reference to `ASN1_STRING_get0_data'
./lib/.libs/libsyslog-ng.so: undefined reference to `TLS_client_method'
./lib/.libs/libsyslog-ng.so: undefined reference to `SSL_CTX_set_options'
./lib/.libs/libsyslog-ng.so: undefined reference to `DH_set0_pqg'
./lib/.libs/libsyslog-ng.so: undefined reference to `TLS_server_method'
./lib/.libs/libsyslog-ng.so: undefined reference to `OPENSSL_sk_free'
collect2: error: ld returned 1 exit status
make[2]: *** [modules/dbparser/pdbtool/pdbtool] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

**Comment by zhengshuxin** [comment]
And how to disable openssl to avoid this compiling error?

**Comment by bazsi** [comment]
openssl is now a required dependency (and not just because of SSL support, we use random generators/hash algorithms, etc) as well.

If you can use docker on a build host, you can always compile syslog-ng using dbld, which uses docker to cater for all the required dependencies.

In the extracted syslog-ng source tree, try: 

```
./dbld/rules rpm-centos-7
```

which should give you an RPM, compiled for CentOS7. If you want to stick to compiling your own, look at the Dockerfile[https://github.com/syslog-ng/syslog-ng/blob/master/dbld/images/centos-7.dockerfile], it contains the recipe to build the CentOS7 based build image. The list of packages to install is in https://github.com/syslog-ng/syslog-ng/blob/master/dbld/packages.manifest, all packages with the "centos" qualifier should be installed.

**Comment by zhengshuxin** [comment]
I want to compile and use syslog-ng in physical machine, not in docker. How to compile syslog-ng ?

Thanks.

**Comment by MrAnno** [comment]
You can find the minimal required build dependencies and instructions here:
https://syslog-ng.gitbooks.io/getting-started/content/chapters/chapter_2/

**Comment by zhengshuxin** [comment]
> You can find the minimal required build dependencies and instructions here: https://syslog-ng.gitbooks.io/getting-started/content/chapters/chapter_2/

I tried and got the same error :(

**Comment by bazsi** [comment]
It's only the build that happens in docker, the result is a set of normal
rpm packages that you can install anywhere.

**Comment by zhengshuxin** [comment]
Ok, I'll try to build syslog-ng in docker, thanks again.

**Comment by MrAnno** [comment]
In the meantime, let me try to answer your main question:
> Why compiling syslog-ng so hardly?

I think it's not exclusively syslog-ng, the complexity comes from the fact that syslog-ng is a project written in C, and it requires a lot of third-party dependencies. Dependency management in the C or C++ world is not standardized, so it usually relies on the system's package management solution, or on other de-facto-standard detection mechanisms like `pkg-config`.

**Comment by zhengshuxin** [comment]
> In the meantime, let me try to answer your main question:
> 
> > Why compiling syslog-ng so hardly?
> 
> I think it's not exclusively syslog-ng, the complexity comes from the fact that syslog-ng is a project written in C, and it requires a lot of third-party dependencies. Dependency management in the C or C++ world is not standardized, so it usually relies on the system's package management solution, or on other de-facto-standard detection mechanisms like `pkg-config`.

Yes, the third-party dependencies are so hardly to build, but it's not a good idea that the syslog-ng is depending on so many third-party libraries which have different building ways.

**Comment by bazsi** [comment]
syslog-ng is composed of modules and you don't need dependencies for
uneeded modules.

There are some requirements that the core started to require over time,
such as openssl and json-c. But that's roughly it. Reimplementing the
features we get from those libraries would have been too much effort, not
to mention that cryptography is a pretty special knowledge that is easy to
get wrong.

The dependencies we build on are part of most (if not all) Linux
distributions, and we do provide an environment (e.g. docker) that gives
you a build environment trivially.

**Comment by MrAnno** [comment]
Feel free to reopen this issue if you have further questions.
