### ISSUE TITLE
syslog-ng crashed in g_assert() if template-escape(yes) is set

### ISSUE THREAD

**Issue by qsunchiu** [syslog-ng/syslog-ng#4100]
# syslog-ng
## Version of syslog-ng
syslog-ng 3 (3.37.1)
Config version: 3.35
Installer-Version: 3.37.1
Revision: 
Module-Directory: /usr/lib/syslog-ng
Module-Path: /usr/lib/syslog-ng
Include-Path: /usr/share/syslog-ng/include
Available-Modules: stardate,http,kvformat,appmodel,afsql,basicfuncs,dbparser,tags-parser,affile,azure-auth-header,pseudofile,syslogformat,json-plugin,disk-buffer,add-contextual-data,linux-kmsg-format,graphite,tfgetent,timestamp,system-source,xml,afsocket,confgen,afprog,csvparser,cryptofuncs,hook-commands,examples,rate-limit-filter,afuser,map-value-pairs,secure-logging,cef,sdjournal,regexp-parser
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: off
Enable-TCP-Wrapper: off
Enable-Linux-Caps: on
Enable-Systemd: on

## Platform
Ubuntu 18.04

## Debug bundle
N/A

# Issue
When template-escape(yes) is set in a template(), an assertion failure occurs in [_propagate_type()](https://github.com/syslog-ng/syslog-ng/blob/syslog-ng-3.37.1/lib/template/eval.c#L40).
It seems that the LogMessageValueType isn't returned if escape is set in [log_macro_expand()](https://github.com/syslog-ng/syslog-ng/blob/syslog-ng-3.37.1/lib/template/macros.c#L711).

## Failure
**
ERROR:lib/template/eval.c:40:_propagate_type: assertion failed: (elem_type != LM_VT_NONE)
Aborted (core dumped)

## Configuration
@version: 3.37
  
source src {
    systemd-journal(prefix(".SDATA.journald."));
    internal();
};

destination d_pipe {
        pipe("/tmp/local.fifo"
                        template("{\"hostname\": \"$HOST\"}")
                        template-escape(yes)
            );
};
log {
        source(src);
        destination(d_pipe);
};

**Comment by Kokan** [comment]
Thanks for the great bug report and the analysis. You are right, in case of escaping a macro type information is not presented. I did not follow in all its might the typing changes, but I think if `template-escape(yes)` requested that should be consider as string.

Would you be up to do the fix based on this ? If not I can open a PR for it.
