### ISSUE TITLE
system() source documentation should clarify that journald takes precedence over kmsg as well

### ISSUE THREAD

**Issue by grawity** [syslog-ng/syslog-ng#4112]
## Documentation version
All (up to 3.37)

## Incorrect section
https://www.syslog-ng.com/technical-documents/doc/syslog-ng-open-source-edition/3.37/administration-guide/28#TOPIC-1829013

## Description of the problem
The "Administration guide" section about the system() source talks about automatic detection of systemd-journal(), however, it fails to mention that journald is used instead of *both* /dev/log and /dev/kmsg. My understanding was that syslog-ng would read userspace messages from journald instead of listening on /dev/log, but that it would still receive kernel messages directly from the kernel using /dev/kmsg. Only after checking the source code, though, I learned that /dev/kmsg isn't used when journald is detected (presumably to avoid message duplication).

## Proposed solution
The system() section could say "reads both syslog and kernel messages directly from the systemd journal file using the `systemd-journal()` source, and does not listen on /dev/log nor read /proc/kmsg" (or something like that).

Additionally, I think the example could also be updated to directly list all variations, to avoid needing to guess the correct configuration for /dev/kmsg on modern kernels:

> With systemd:
> ```
> systemd-journal();
> ```
> Without systemd, on kernel 3.5 or newer:
> ```
> unix-dgram("/dev/log");
> file("/dev/kmsg" program-override("kernel") flags(kernel)
>      multi-line-mode(indented) keep-timestamp(no) format(linux-kmsg));
> ```
> Without systemd, on kernels older than 3.5:
> ```
> unix-dgram("/dev/log");
> file("/proc/kmsg" program-override("kernel") flags(kernel));
> ```

**Comment by bazsi** [comment]
@eldarnash could you check if this could be integrated into the axosyslog-core-docs project?

FYI: axosyslog-core-docs builds upon the original syslog-ng documentation as released by One Identity as Open Source, converts the whole thing into markdown for easier maintenance. You can find the published documentation here:

https://axoflow.com/docs/axosyslog-core/

The associated github project here: https://github.com/axoflow/axosyslog-core-docs

Please add a star to help spread the word. You can find the blog post detailing how we ended up here is in this post: https://axoflow.com/axosyslog-core-documentation-syslog-ng/

**Comment by HofiOne** [comment]
documentation is moved, added a new entry for this at

https://github.com/syslog-ng/syslog-ng.github.io/issues/128
