### ISSUE TITLE
Filter File_events

### ISSUE THREAD

**Issue by nidhin077** [syslog-ng/syslog-ng#4119]
# syslog-ng
## Version of syslog-ng
syslog-ng 3 (3.25.1)
Config version: 3.25
Installer-Version: 3.25.1
Revision: 3.25.1-3
## Platform
Ubuntu 20.04.4 LTS

## Issue
--------------

I'm trying to fetch a Syslog from a remote machine and transmit its contents to the master Syslog-ng server's TCP endpoint.  After that added syslog-ng.conf with osquery supported log reformating configurations and the logs entries successfully reached the Syslog table. I currently need to filter the file_event from the osquery, in order to meet the need. I followed the instructions in your document. However, it's not filtering. Please inspect, and let me know what adjustments I need to do in order to obtain the same.

## Configuration (Remote Configuration file)
@version: 3.5

@include "scl.conf"

@include "`scl-root`/system/tty10.conf"

#source s_local { system(); internal(); };
source s_local {
         system();
         internal();
         file("/var/log/auth.log");

};
#source s_auth { file("/var/log/auth.log");
#};

source s_osquery {
         filter { match("file_events" value("FIM")); };
         file("/var/log/osquery/osqueryd.results.log"
         program-override("osquery")
         flags(no-parse));
};

destination d_syslog_tcp {

syslog("10.10.10.15" transport("tcp") port(514)); };

#filter f_dbg { level(debug); };
#filter f_debug { level(debug) and not facility(file_events, file, news, mail); };
#filter f_file { match("file_events" value("FIM")); };

log {
 source(s_local);destination(d_syslog_tcp);source(s_osquery);
#filter(f_file);
};

**Comment by OverOrion** [comment]
Hi

I believe the attached configuration file is broken, a `filter` object should not be inside a `source` object.
Also a `filter` object should be between a `source` and a `destination` object like this:

```
filter f_basic {
  match("foo" value("MESSAGE"))
};

log {
  source { <some_source> };
  
  filter(f_basic);

  destination { <some_destination>  };

};
```

I think that  `f_file filter` is broken too, as there is no `FIM` macro. 

For possible macros see the ˙Hard versus soft macros` and `Macros of syslog-ng OSE` chapters.
For using the `match()` filter function, see `Filter functions / match()`.

**Comment by MrAnno** [comment]
This seems to be answered. Please reopen if you have further questions.
