### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by nidhin077** [syslog-ng/syslog-ng#4122]
## Platform
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

# Issue
----------

I'm experiencing the following error while installing Syslog-ng. I made an attempt to install the libssl version specified. However, nothing has changed. Please check and let me know how to resolve the same. 

The following packages have unmet dependencies:
 syslog-ng-core : Depends: libssl1.1 (>= 1.1.1) but it is not installable
 syslog-ng-mod-sql : Depends: libssl1.1 (>= 1.1.0) but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by OverOrion** [comment]
Hi,

May I ask for more information regarding your environment?

1. Have you added our APT repository?
2. What command did you use to install `syslog-ng`?
3. Were you running an older Ubuntu version, upgraded to 22.04.01, then `syslog-ng` broke?

I've just tried a clean install in a Docker container running Ubuntu 22.04 and it worked flawlessly.

**Comment by nidhin077** [comment]
Hi @OverOrion 

Yes, I have added the APT repository. The below command is used to install Syslog-ng.

apt install syslog-ng

**Comment by MrAnno** [comment]
This usually happens when a non-compatible component name is used in `/etc/apt/sources.list.d/syslog-ng-ose.list`.
Is it `stable ubuntu-jammy` in your case?

**Comment by nidhin077** [comment]
@MrAnno, I have removed the entry from Syslog-ng-ose.list, Now it's installed successfully. Thanks

**Comment by OverOrion** [comment]
I am closing this issue as it seems resolved.
If you feel otherwise, please feel free to reopen it.
