### ISSUE TITLE
pcre library is obsolate

### ISSUE THREAD

**Issue by mochrul** [syslog-ng/syslog-ng#4140]
## Description of the problem
Based on [this](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=999946) bug report, the PCRE library (which is for some reason called pcre3 in Debian) is abandoned and not maintained anymore. That library should not be used, especially when the input can come from an untrusted source.

## Proposed solution
There is a newer library implemented (pcre2), which should be used instead (documentation is here: https://pcre.org/current/doc/html/

**Comment by bazsi** [comment]
thanks for the report. interesting.

**Comment by czanik** [comment]
Fedora also plans to retire the pcre package and any packages still depending on it: https://fedoraproject.org/wiki/PcreRetirement

**Comment by david-geiger** [comment]
Hi,

Mageia Linux also planned to drop old pcre library

Regards,
David

**Comment by czanik** [comment]
Any update on this? Syslog-ng is one of a very small number of packages which did not yet switch to pcre2. Syslog-ng is the only package on my Fedora system, which still uses the old pcre package. Fedora 38 already planned to drop the pcre package. As pcre is a mandatory dependency of syslog-ng, the drop of pcre would also mean the drop of syslog-ng from Fedora...

**Comment by mochrul** [comment]
Same in Debian. Actually, the pcre2 dependency bug severity was raised to a release critical one, which means that syslog-ng will be dropped from testing very soon. I mean 15. July. That is just a bit more than a week from now.

**Comment by bazsi** [comment]
I have a draft branch now which uses pcre2 and make check runs successfully. I need to clean it up.

I don't think we have another release planned by 15th of July but we could add this to the Debian package for the time being. Would that be acceptable?

**Comment by bazsi** [comment]
The PR in #4537 should update syslog-ng to use PCRE2. Although a review of that would be very useful, this is already getting into a shape that allows syslog-ng to be built with PCRE2.

By fetching the patch from here: https://github.com/syslog-ng/syslog-ng/commit/cb6de08dc9078644d48ca536b5660e406b1a50d6.patch you can patch syslog-ng at packaging time.

Also, the PR is building a source tarball with the patch incorporated, here:
https://github.com/syslog-ng/syslog-ng/actions/runs/5498481386/jobs/10019971809?pr=4537

@czanik @mochrul does this work for you?

**Comment by czanik** [comment]
OpenSUSE Leap and Tumbleweed seems to be OK. There is no pcre2 for SLES 12 SP5, not even among unofficial packages, as far as I can see :/ If supporting both pcre and pcre2 in the same sources is not possible, then it means that OSE 4.2.0 is the last version compiling on SLES 12.

Up next: Fedora / RHEL and FreeBSD testing.

**Comment by czanik** [comment]
Fedora / RHEL / FreeBSD: everything seems to be OK.

In all cases I used the latest syslog-ng git snapshot, applied the patch, generated a tgz, and used the resulting tgz for compiling syslog-ng.

As far as I know I have until end of August to update the syslog-ng package to pcre2. If I learn that there is an earlier date, I can also go the patching the 4.2.0 release sources route.

**Comment by MrAnno** [comment]
Fixed by #4537.

@mochrul Can you help get syslog-ng back into Debian testing, please?

https://tracker.debian.org/news/1445295/syslog-ng-removed-from-testing/
