### ISSUE TITLE
Previous http destnation is still active after updating to new one

### ISSUE THREAD

**Issue by deepasoni27** [syslog-ng/syslog-ng#4156]
# syslog-ng
## Version of syslog-ng
CFS:default@S123T1200500004(B10:bn) [~]$ syslog-ng --version
syslog-ng 3 (3.34.1)
Config version: 3.33
Installer-Version: 3.34.1
Revision:
Compile-Date: Sep  8 2022 17:16:33
Module-Directory: /usr/lib/syslog-ng 
Module-Path: /usr/lib/syslog-ng 
Include-Path: /usr/share/syslog-ng/include
Available-Modules: xml,syslogformat,tfgetent,mod-python,examples,json-plugin,hook-commands,kvformat,http,afuser,regexp-parser,add-contextual-data,afprog
,afstomp,dbparser,azure-auth-header,pseudofile,disk-buffer,timestamp,afsocket,basicfuncs,system-source,cryptofuncs,tags-parser,stardate,confgen,appmodel
,graphite,cef,map-value-pairs,affile,linux-kmsg-format,csvparser,secure-logging
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: on
Enable-TCP-Wrapper: off
Enable-Linux-Caps: on
Enable-Systemd: off

## Platform
#80~18.04.1-Ubuntu SMP Mon May 23 20:32:04 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

## Debug bundle

# Issue
## Failure
First we configured http url https://logstream.firstnet.cloud.taranawireless.com
Later changed it to dummy.com

Earlier we were using syslog-ng version 3.26 .In this it was working fine, only latest configured http destination was active.
But with version upgrade to 3.34,  more than one active destination it is showing.

CFS:default@S123T1200500004(B10:bn) [~]$ sudo syslog-ng-ctl stats                                                                                       
SourceName;SourceId;SourceInstance;State;Type;Number                                                                                                    
global;payload_reallocs;;a;processed;20534                                                                                                              
dst.http;d_http_bulk#0;http,https://logstream.firstnet.cloud.taranawireless.com;a;eps_last_1h;1
dst.http;d_http_bulk#0;http,dumy.com;a;eps_last_24h;0
destination;d_var_log_syslog;;a;processed;21721
destination;d_extra_logs_alarms;;a;processed;52
source;s_kernel;;a;processed;626
center;;received;a;processed;21825
dst.http;d_http_bulk#0;http,https://logstream.firstnet.cloud.taranawireless.com;a;eps_since_start;1
dst.http;d_http_bulk#0;http,dumy.com;a;eps_last_1h;0
destination;d_var_log_messages;;a;processed;21721
destination;d_var_log_audit;;a;processed;78
dst.http;d_http_bulk#0;http,dumy.com;a;dropped;0
dst.http;d_http_bulk#0;http,dumy.com;a;processed;6
dst.http;d_http_bulk#0;http,dumy.com;a;queued;8
dst.http;d_http_bulk#0;http,dumy.com;a;written;0
dst.http;d_http_bulk#0;http,https://logstream.firstnet.cloud.taranawireless.com;o;batch_size_avg;1272
center;;queued;a;processed;65316
dst.http;d_http_bulk#0;http,dumy.com;a;msg_size_max;209
dst.http;d_http_bulk#0;http,dumy.com;a;eps_since_start;0
dst.http;d_http_bulk#0;http,dumy.com;a;msg_size_avg;195
dst.http;d_http_bulk#0;http,https://logstream.firstnet.cloud.taranawireless.com;a;eps_last_24h;1
dst.http;d_http_bulk#0;http,https://logstream.firstnet.cloud.taranawireless.com;o;batch_size_max;2621
global;scratch_buffers_bytes;;a;queued;1792
dst.http;d_http_bulk#0;http,https://logstream.firstnet.cloud.taranawireless.com;o;msg_size_avg;260
destination;d_extra_logs_boot;;a;processed;0
dst.http;d_http_bulk#0;http,https://logstream.firstnet.cloud.taranawireless.com;a;dropped;0
dst.http;d_http_bulk#0;http,https://logstream.firstnet.cloud.taranawireless.com;a;processed;18942
dst.http;d_http_bulk#0;http,https://logstream.firstnet.cloud.taranawireless.com;a;queued;0
dst.http;d_http_bulk#0;http,https://logstream.firstnet.cloud.taranawireless.com;a;written;21713
dst.http;d_http_bulk#0;http,https://logstream.firstnet.cloud.taranawireless.com;o;msg_size_max;1673
global;msg_clones;;a;processed;21329
source;s_dev_log;;a;processed;21199
global;sdata_updates;;a;processed;0
destination;d_http_bulk;;a;processed;21721
dst.http;d_http_bulk#0;http,dumy.com;a;batch_size_max;0
global;scratch_buffers_count;;a;queued;8                                                                                                                
destination;d_extra_logs_errors;;a;processed;23                                                                                                         
dst.http;d_http_bulk#0;http,dumy.com;a;batch_size_avg;0

$ gdb syslog-ng
 run
-->

**Comment by MrAnno** [comment]
Sorry, I overlooked this issue.

The old `https://logstream.firstnet.cloud.taranawireless.com/` entries are technically not active.
They are displayed by ` syslog-ng-ctl stats`, but they are orphaned counters; you can remove them with the `--remove-orphans` stats option.

Feel free to reopen this issue if I missed something.
