### ISSUE TITLE
3.37 and earlier documentation should recommend calling `syslog-ng-ctl reopen` instead of `syslog-ng-ctl reload` after log rotation

### ISSUE THREAD

**Issue by ElectricRCAircraftGuy** [syslog-ng/syslog-ng#4166]
## Documentation version

3.17 through 3.37, etc. (it's always been this way)

## Incorrect section

https://www.syslog-ng.com/technical-documents/doc/syslog-ng-open-source-edition/3.37/administration-guide/36#TOPIC-1829044

> Also, after rotating the log files, reload syslog-ng OSE using the `syslog-ng-ctl reload` command, or use another method to send a `SIGHUP` to syslog-ng OSE.

## Description of the problem

Although `syslog-ng-ctl reload` does work, [@furiel says here](https://github.com/syslog-ng/syslog-ng/issues/1774#issuecomment-346624252) that is it now recommended to use the lighter-weight `syslog-ng-ctl reopen` command instead. `syslog-ng-ctl --help` confirms this, when it says:

> reopen               Re-open of log destination files

## Proposed solution

As I state here: https://github.com/syslog-ng/syslog-ng/issues/1774#issuecomment-1270517815, I think it makes more sense to write something like this in the documentation:

> Also, after rotating the log files, you need to cause `syslog-ng` to reopen the destination log files since it will otherwise continue writing to the now-rotated-and-renamed file descriptors instead of to the new log files created by `logrotate`. The best way to cause `syslog-ng` to do this is by calling `syslog-ng-ctl reopen` after performing log rotation. You can also send the `syslog-ng` process the `SIGUSR1` kill signal, [as shown here](https://github.com/syslog-ng/syslog-ng/issues/1774#issuecomment-1270517815) (`pid="$(cat /var/run/syslog-ng.pid)" kill -SIGUSR1 $pid`), to evoke this same behavior.
> 
> Prior to the existence of the `reopen` command, the old recommendation was to do a call to the heavier `syslog-ng-ctl reload` command, or otherwise send a `SIGHUP` signal to `syslog-ng`.

**Comment by remote007** [comment]
hi @ElectricRCAircraftGuy , is this issue open for contribution

**Comment by ElectricRCAircraftGuy** [comment]
@remote007 , I don't know. I'm just a user of, not a contributor to nor maintainer of, this repo.

**Comment by HofiOne** [comment]
documentation is moved, if this is still an issue please add your issue report here

https://github.com/syslog-ng/syslog-ng.github.io/pulls

TIA!
