### ISSUE TITLE
Wrong references in manpages

### ISSUE THREAD

**Issue by Programmist11180** [syslog-ng/syslog-ng#4172]
## Documentation version

3.38
## Incorrect section

NOTES in manpages
## Description of the problem

Wrong references in manpages - references №1 and №3 ("The  Administrator Guide") points to https://www.balabit.com  that redirects to https://www.oneidentity.com  .  There is no "The  Administrator Guide" on this website.
## Proposed solution

Change references to correct. For example, to https://www.syslog-ng.com/technical-documents/list/syslog-ng-open-source-edition/3.37

**Comment by Gauravjadhav22** [comment]
I want to work on this issue please assign me this issue..

**Comment by gomathishankar37** [comment]
Is this issue still Open? Can i work on this issue?

Thanks

**Comment by bazsi** [comment]
Just go ahead and submit a PR.

**Comment by HofiOne** [comment]
Documentation is moved to github-io, if this's still an issue, please 
- report here https://github.com/syslog-ng/syslog-ng.github.io/issues
- add your PR here ttps://github.com/syslog-ng/syslog-ng.github.io
