### ISSUE TITLE
MAP_ANONYMOUS undefined on older macOS

### ISSUE THREAD

**Issue by jmroot** [syslog-ng/syslog-ng#4199]
# syslog-ng
3.38.1

## Platform
macOS 10.10

# Issue
## Failure
Build fails thus:
```
lib/secret-storage/nondumpable-allocator.c:96:57: error: use of undeclared identifier 'MAP_ANONYMOUS'
  gpointer area = mmap(NULL, len, PROT_READ|PROT_WRITE, MAP_ANONYMOUS|MAP_PRIVATE, -1, 0);
                                                        ^
1 error generated.
```

## Input and output logs (if possible)
https://build.macports.org/builders/ports-10.10_x86_64-builder/builds/199959/steps/install-port/logs/stdio

## Discussion

`MAP_ANONYMOUS` used to be called `MAP_ANON` on older macOS versions, so the fix is simple:
```
#ifndef MAP_ANONYMOUS
#define MAP_ANONYMOUS MAP_ANON
#endif
```

Not sure if a compat header would be warranted when this is the only place it's used in the codebase.

**Comment by MrAnno** [comment]
@jmroot Would you like to open a pull request with the fix?
