### ISSUE TITLE
Support for PROXY Protocol v2

### ISSUE THREAD

**Issue by g-psantos** [syslog-ng/syslog-ng#4205]
## Description of the problem

The application supports only PROXY protocol version 1 (see [here](https://www.syslog-ng.com/technical-documents/doc/syslog-ng-open-source-edition/3.36/administration-guide/22#TOPIC-1768565)). Certain infrastructure services, such as AWS Network Load Balancers, support only PROXY protocol version 2 (see [here](https://docs.aws.amazon.com/elasticloadbalancing/latest/network/load-balancer-target-groups.html#proxy-protocol)). This prevents syslog-ng from recording accurate information about the source of logs.

_Note that AWS Classic Load Balancers supported version 1 of the protocol but those have been deprecated by AWS in favor of Elastic Load Balancers._

## Proposed solution

Add syslog-ng support for PROXY protocol version 2.

## Alternatives

1. In AWS, the Network Load Balancer can be configured to "preserve client IP", which means syslog-ng records the correct IP address for **in-VPC** clients. However, if syslog-ng is shared with other VPCs via AWS PrivateLink, the Load Balancer's IP address is recorded instead.
2. Record identifying attributes in client TLS certificates as a replacement for IP addresses as a means of identification.

**Comment by bazsi** [comment]
This sounds like a good idea in general. Can you help me with some more details how you would use this? 
What clients do send messages to syslog-ng through this load balancer service? 


Also

**Comment by bazsi** [comment]
Yup, send it to my email at

***@***.***

**Comment by bazsi** [comment]
github seems to have removed my email address from my last message. It is bazsi77 at the domain gmail.com, hopefully this one works. I submitted a PR that should solve this missing piece, let me know if that works.

**Comment by g-psantos** [comment]
Thanks for the quick turnaround on this! I saw you got my email on the other address anyway.

I don't have a good way to test the PR with our current infrastructure (we don't build from source) but I'll try to deploy a small test environment this week or next to see what happens.

**Comment by bazsi** [comment]
This was already merged and released with 4.1
