### ISSUE TITLE
Debian update problem, Python compatibility

### ISSUE THREAD

**Issue by czanik** [syslog-ng/syslog-ng#4259]
I tried to update a Debian system running 3.38.1 to 4.0.1, both coming from the https://ose-repo.syslog-ng.com/apt/. I ran into two problems:

- SCL is no more part of the core package, and it's not recommended by that package either. Which means that syslog-ng did not start. I had a minimal install, just syslog-ng-core, syslog-ng-mod-http, syslog-ng-mod-geoip2 and syslog-ng-mod-python. I had to install syslog-ng-scl manually

- Earlier I asked if Python support in 4.0 is backwards compatible with earlier versions and I was assured that it is. Using the config from https://www.syslog-ng.com/community/b/blog/posts/analyzing-apache-httpd-logs-in-syslog-ng I ran into this error:

```
[2022-12-23T11:15:18.159679] Module loaded and initialized successfully; module='syslogformat'
[2022-12-23T11:15:18.159876] python: importing Python module; module='_syslogng_main', filename='/etc/syslog-ng/syslog-ng.conf{python-global-code:19}'
[2022-12-23T11:15:18.159915] python-parser: Error initializing Python parser, class is not a subclass of LogParser; parser='p_resolver', class='SngResolver', class-repr='<class \'_syslogng_main.SngResolver\'>'
[2022-12-23T11:15:18.159933] Error initializing message pipeline; plugin_name='python', location='/etc/syslog-ng/conf.d/apache.conf:52:5'
```

**Comment by bazsi** [comment]
On Fri, Dec 23, 2022, 11:34 Peter Czanik ***@***.***> wrote:

> I tried to update a Debian system running 3.38.1 to 4.0.1, both coming
> from the https://ose-repo.syslog-ng.com/apt/. I ran into two problems:
>
>    -
>
>    SCL is no more part of the core package, and it's not recommended by
>    that package either. Which means that syslog-ng did not start. I had a
>    minimal install, just syslog-ng-core, syslog-ng-mod-http,
>    syslog-ng-mod-geoip2 and syslog-ng-mod-python. I had to install
>    syslog-ng-scl manually
>    -
>
>
>
The main "syslog-ng" package depends on it, while core does not. This was a
compromise we agreed with the official Debian maintainers.

**Comment by czanik** [comment]
OK. I try not to say anything, others find some of my RPM packaging decisions odd :-) Added info about syslog-ng-scl to the Debian/Ubuntu blog at: https://www.syslog-ng.com/community/b/blog/posts/installing-the-latest-syslog-ng-on-ubuntu-and-other-deb-distributions

Thanks, with @version:3.38 my Python code works again. I try hard not to make it 4.0 compatible before Christmas :-)

**Comment by bazsi** [comment]
It's just a base class change, as instructed by the error message (or
warning if you are using 3.38 as config version).
