### ISSUE TITLE
Regression in `rawrequest` extraction with Apache SCL

### ISSUE THREAD

**Issue by smortex** [syslog-ng/syslog-ng#4274]
# syslog-ng
## Version of syslog-ng
4.0.1

## Platform
Debian

## Debug bundle
n/a

# Issue
## Failure
When an Apache HTTP VirtualHost receive an HTTPS connection, it returns an 400 response code and logs something like this:

```
main:80 152.89.196.211 "-" - [23/Dec/2022:19:04:19 +0100] "\x16\x03\x01" 400 226 "-" "-"
```

The raw request `\x16\x03\x01` is extracted by apache SCL and available as `prefix.rawrequest`.

We updated from syslog-ng-3.38.1-1 to syslog-ng-4.0.1-1 on 2022-12-23. I just realize today that we have some surprising values in our rawrequests:

* On syslog-ng-3.38.1-1, rawrequest was `\x16\x03\x01`. Result of searching for "\\x16\\x03\\x01" in OpenSearch Dashboards:
  ![Result of searching for "\\x16\\x03\\x01" in OpenSearch Dashboards](https://user-images.githubusercontent.com/148721/211170097-05914556-e5e7-4926-84a6-dccc50c8c496.png)
* On syslog-ng-4.0.1-1, rawrequest is `x16x03x01`. Result of searching for "x16x03x01" in OpenSearch Dashboards:
  ![Result of searching for "x16x03x01" in OpenSearch Dashboards](https://user-images.githubusercontent.com/148721/211170159-db3c7929-48a4-4e9a-b8f9-1eeabc0bffa2.png)

The `\` have been stripped-out and shouldn't. This looks like a regression in syslog-ng-4.0.

This is likely related to #4228 (but I have not confirmed it, I am writing this issue so it does not get lost and might start to have a look when the weekend is over).

## Steps to reproduce
Setup an Apache HTTP server and try to access it using HTTPS.  Parse the log with apache SCL.

## Configuration

```
source s_apache_access {
    wildcard-file(
        base_dir(
            /var/log/apache2
        ),
        filename_pattern(
            *access.log
        ),
        flags(
            no-parse
        ),
        program_override(
            "apache"
        )
    );
};

parser p_apache {
    apache-accesslog-parser(
        prefix(
            "apache."
        )
    );
};

log {
    source(s_apache_access);
    source(s_apache_access_ssl);
    parser(p_apache);
    parser(p_apache_geoip);
    rewrite(r_apache_geoip);
    rewrite(r_apache_bytes);
    destination(d_riemann);
};

```

## Input and output logs (if possible)
n/a

**Comment by bazsi** [comment]
Thanks for the report. I am sure this is related to #4228. Sorry for the
regression.

I am sure we can add support for \xFF sequences in the csv-parser() so this
format is processed correctly as well.
