### ISSUE TITLE
syslog-ng.conf parsing issue with syslog-ng-mod-http

### ISSUE THREAD

**Issue by srawls1740** [syslog-ng/syslog-ng#4283]
Getting the following error on debian 11.6 on x86_64 when using version 4.0.1-1:

Error parsing config, syntax error, unexpected LL_IDENTIFIER, expecting '}' in /etc/syslog-ng/syslog-ng.conf:247:3-247:21:
243     
244     # Elasticsearch
245     
246     destination d_elastic {
247--->   elasticsearch-http(
247--->   ^^^^^^^^^^^^^^^^^^
248         index("${index_name}-${R_YEAR}${R_MONTH}${R_DAY}")
249         type("")
250         url("http://127.0.0.1:9200/_bulk")
251         persist-name("elastic")
252         workers(10)

If I downgrade to 3.38-1, the syslog-ng starts normally with no errors. No other change is made to the config.

**Comment by bazsi** [comment]
Please install syslog-ng-scl or use the main syslog-ng package which
depends on it

**Comment by bazsi** [comment]
You are welcome.
