### ISSUE TITLE
configure syslog-ng.conf through the web ui

### ISSUE THREAD

**Issue by GREATwo** [syslog-ng/syslog-ng#4284]
I want to configure syslog-ng.conf through the web session. What should I do

**Comment by HofiOne** [comment]
You might want to take a look at this https://www.syslog-ng.com/community/b/blog/posts/web-interfaces-for-your-syslog-server-an-overview

**Comment by GREATwo** [comment]
> You might want to take a look at this https://www.syslog-ng.com/community/b/blog/posts/web-interfaces-for-your-syslog-server-an-overview



I mean to configure the syslog-ng.conf file through the web interface, not to display and analyze the logs collected

**Comment by bazsi** [comment]
Hi,

I don't know any good tools in that area, honestly, which I find kind of
sad. I am in the process of creating a management layer for log Management
tools (such as syslog-ng), but not as open source and it's in its infancy.

On the other hand I just had a chat with ChatGPT about syslog-ng and it
gave me very usable answers with config snippets how to work with the
syslog-ng language.

Just try it, ask questions, it will respond with examples and even if not
always 100 accurate it can help you navigate the syslog-ng config language
much easier.

Hth,

Bazsi

**Comment by bazsi** [comment]
This could be a good entry for our discussion page, but I am closing it as an issue.
