### ISSUE TITLE
Support Open Telemetry (OTLP) destination

### ISSUE THREAD

**Issue by ryanfaircloth** [syslog-ng/syslog-ng#4286]
## Description of the problem
An increasing number of backend analytics systems support the use of OTLP protocol this would provide a "industry standard" means of forwarding data to third party systems and reduce the dependency on custom or less efficient http

## Proposed solution
Provide a OTLP proto destination
## Alternatives
I considered output of RFC5424 to a otel collector however that increases complexity as some data manipulation is required in each tier

**Comment by dseomn** [comment]
Looks like this is done? https://syslog-ng.github.io/admin-guide/070_Destinations/157_OpenTelemetry/README
