### ISSUE TITLE
syslog name resolution does not support multiple host for a dns Query.

### ISSUE THREAD

**Issue by Himanshu54** [syslog-ng/syslog-ng#4296]
# syslog-ng
## Version of syslog-ng
all: latest

## Platform
CentOS

## Debug bundle

# Issue
## Failure
```
Hostname resolution does not account for multiple hosts in (gethostbyname(name))-> h_addr_list
Instead just takes in h_addr, which causes stickiness for the destination in case of multiple hosts behind the dns alias.
```

## Steps to reproduce
Not required . Evident from the code https://github.com/syslog-ng/syslog-ng/blob/master/lib/host-resolve.c#L202

**Comment by bazsi** [comment]
The resolver randomizes the address pointed to by h_addr in this case, at least as far as I remember, so it should pick a random IP from those available. Isn't this what you experience?

**Comment by Himanshu54** [comment]
In our case out of 8 only 4 are recieving traffic and the 4 which are receiving  are not evenly distributed. I know that I cannot depend on dns resolution for balancing but the difference is quite huge.

My assertion is that since I am caching the dns response for 30 min , it actually never checks w/ resolver after initial dns query since the hosts are healthy throughout.

`syslog-ng.conf`
```
    keep_hostname (yes);

    chain_hostnames(yes);
    bad_hostname("[^[:print:]]");

    dns_cache(yes);
    dns_cache_expire(1800);
    dns_cache_expire_failed(30);
    dns_cache_size(100000);
```

**Comment by Himanshu54** [comment]
Also from man pages for `gethostbyname`
```
The hostent structure is defined in <netdb.h> as follows:

           struct hostent {
               char  *h_name;            /* official name of host */
               char **h_aliases;         /* alias list */
               int    h_addrtype;        /* host address type */
               int    h_length;          /* length of address */
               char **h_addr_list;       /* list of addresses */
           }
           #define h_addr h_addr_list[0] /* for backward compatibility */

       The members of the hostent structure are:
```
@bazsi It just says it points to 1st record , I am not sure where it randomise the record.

**Comment by Himanshu54** [comment]
From same man page
```
The gethostbyname*() and gethostbyaddr*() functions are obsolete.  Applications should use getaddrinfo(3) and getnameinfo(3) instead
```

**Comment by bazsi** [comment]
it's probably the resolver that randomizes the entries, running a small test program:

```
$ gcc dns.c
$ ./a.out 
104.26.3.85
$ ./a.out 
104.26.2.85
$ ./a.out 
172.67.71.160
$ ./a.out 
172.67.71.160
$ ./a.out 
104.26.3.85
$ ./a.out 
104.26.3.85
$ ./a.out 
104.26.2.85
$ ./a.out 
104.26.3.85
$ ./a.out 
104.26.3.85
$ ./a.out 
172.67.71.160
```

This is the source:
```
#include <sys/types.h>
#include <sys/socket.h>
#include <netdb.h>
#include <stdio.h>
#include <netinet/in.h>
#include <arpa/inet.h>


int main()
{

  struct hostent *h = gethostbyname("telex.hu");
  
  printf("%s\n", inet_ntoa(*(struct in_addr *) h->h_addr));
}
```
bazsi@bzorp:~/src$ host telex.hu
telex.hu has address 172.67.71.160
telex.hu has address 104.26.3.85
telex.hu has address 104.26.2.85
telex.hu has IPv6 address 2606:4700:20::681a:355
telex.hu has IPv6 address 2606:4700:20::ac43:47a0
telex.hu has IPv6 address 2606:4700:20::681a:255
telex.hu mail is handled by 1 aspmx.l.google.com.
telex.hu mail is handled by 10 alt3.aspmx.l.google.com.
telex.hu mail is handled by 10 alt4.aspmx.l.google.com.
telex.hu mail is handled by 5 alt1.aspmx.l.google.com.
telex.hu mail is handled by 5 alt2.aspmx.l.google.com.


It's not completely random, probably depends on the current time. But syslog-ng indeed resolves that DNS record relatively rarely, as we keep those connections alive.

**Comment by Himanshu54** [comment]
Thanks @bazsi 
I did run the given dns.c for our dns query and the response do contains all the hosts in random distribution.
I mentioned earlier 

> My assertion is that since I am caching the dns response for 30 min , it actually never checks w/ resolver after initial dns query since the hosts are healthy throughout.

Is this plausible. I will probably would have to walk through cache implementation to check if it takes the same host forever if the host healthy but if you already know the answer, that would be helpful.

**Comment by bazsi** [comment]
On Tue, Jan 31, 2023, 14:20 himanhsu ***@***.***> wrote:

> Thanks @bazsi <https://github.com/bazsi>
> I did run the given dns.c for our dns query and the response do contains
> all the hosts in random distribution.
> I mentioned earlier
>
> My assertion is that since I am caching the dns response for 30 min , it
> actually never checks w/ resolver after initial dns query since the hosts
> are healthy throughout.
>
> Is this plausible. I will probably would have to walk through cache
> implementation to check if it takes the same host forever if the host
> healthy but if you already know the answer, that would be helpful.
>
Iirc syslog-ng resolves the hostname every time it reconnects. But a
connection can be alive for days or more. We don't terminate it ourselves.

You could define multiple destinations and load balance messages to the
destination from within syslog-ng using filters. Each destination would
have a different primary IP while using the rest of the cluster as fallback
IPs. Wouldn't that work for you?

**Comment by Himanshu54** [comment]
@bazsi 
Thanks for the clarification.
