### ISSUE TITLE
apt-mirror can't open index file (Packages.gz missing)

### ISSUE THREAD

**Issue by debtamas** [syslog-ng/syslog-ng#4309]
Hi!

Can you tell me why the "Package.gz" is missing?
Example:
https://ose-repo.syslog-ng.com/apt/dists/stable/ubuntu-jammy/binary-amd64/Packages
https://ose-repo.syslog-ng.com/apt/dists/stable/ubuntu-jammy/binary-amd64/Packages.gz  *** missing
https://ose-repo.syslog-ng.com/apt/dists/stable/debian-buster/binary-amd64/Packages
https://ose-repo.syslog-ng.com/apt/dists/stable/debian-buster/binary-amd64/Packages.gz *** missing

The (Package.gz|(Package.xz|(Package.bz2) file is required.

**Comment by bazsi** [comment]
I am not sure, those files are automatically generated, as a part of our ci.

@alltilla can you check this?

**Comment by MrAnno** [comment]
AFAIK we did not generate the compressed format in the first iteration as it was marked as optional in the [Debian Repository Format](https://wiki.debian.org/DebianRepository/Format).

I see no problem with adding the compressed version.
