### ISSUE TITLE
plug in sql not found

### ISSUE THREAD

**Issue by bonj1987** [syslog-ng/syslog-ng#4310]
i am getting this when i start my syslog.. any ideas?

Error parsing destination, destination plugin sql not found in /etc/syslog-ng/syslog-ng.conf

**Comment by czanik** [comment]
Make sure that syslog-ng on your hosts supports it. SQL destination support is usually available in a separate sub-package, like syslog-ng-sql (rpm) or syslog-ng-mod-sql (deb), or in case of FreeBSD, you need to compile syslog-ng from ports.

**Comment by bonj1987** [comment]
ok makes sense. im running syslog-ng via the port i got from cygwin. i am not sure if anyone ported that sql  module over as well.

**Comment by MrAnno** [comment]
The Cygwin-packaged version of syslog-ng is extremely old and does not seem to contain too many modules.
[syslog-ng-3.2.5-3](https://www.cygwin.com/cgi-bin2/package-cat.cgi?file=x86_64%2Fsyslog-ng%2Fsyslog-ng-3.2.5-3&grep=syslog-ng)

**Comment by bonj1987** [comment]
wonder if anyone will upgrade it in the near future?

**Comment by bazsi** [comment]
I think cygwin is a community project, IIRC it was sponsored by RedHat. You should ask the maintainer of the syslog-ng project in there.

As an alternative, you could run syslog-ng under WSL, that's a more viable way of running it.
