### ISSUE TITLE
Peer did not provide a certificate

### ISSUE THREAD

**Issue by abrahambinu** [syslog-ng/syslog-ng#4343]
I am trying to integrate Trendmicro Apex Central syslogs to a rsyslog server (version 8.2102) which would further forward it to a SIEM. 
I have added below settings in remote_tls.conf
![image006](https://user-images.githubusercontent.com/44813706/221195117-dbd94a4f-cf8d-4efe-9291-90e6f7a56cba.png)

When I try to connect from ApexCentral console. Test connection shows successful.
![image008](https://user-images.githubusercontent.com/44813706/221194855-afff45b7-c6b8-4e7c-a839-2da6ceb8f144.png)

But still we are getting peer did not provide a certificate and a reset flag sent from rsyslog server to firewall IP.
![image007](https://user-images.githubusercontent.com/44813706/221195608-1a0fe620-e1c5-4e02-a654-3166ec7eb371.png)

Tcpdump is showing below TLS handshake.
![image009](https://user-images.githubusercontent.com/44813706/221196090-d7a27dea-66b7-4089-ba0e-800d2b3fce13.png)
![image010](https://user-images.githubusercontent.com/44813706/221196212-3e3007e2-8e84-44c7-9020-bae79d5641a3.png)

Can you help us troubleshoot the peer did not provide certificate issue. Certificates are updated in remote_global.conf file.

10.85.5.103 is rsyslog server and 10.81.0.69 is internal firewall IP

**Comment by bazsi** [comment]
You are probably on the wrong forum, as this is the syslog-ng github and not rsyslog :)
