### ISSUE TITLE
loggen problem on Rocky Linux 8

### ISSUE THREAD

**Issue by czanik** [syslog-ng/syslog-ng#4349]
While trying to use ```loggen``` on Rocky Linux 8 to a network source I ran into an interesting problem:

```
[root@localhost usr]# loggen -i -S 127.0.0.1 514​
error [loggen_helper.c:resolve_address_using_getaddrinfo:109] name lookup error (127.0.0.1:514​): Servname not supported for ai_socktype
error [socket_plugin.c:active_thread_func:332] can not connect to 127.0.0.1:514​ (0x55d3aab11000)
Total runtime = 0.500187, count = 0
```

Sending logs to /dev/log using ```loggen -xD /dev/log``` works.

First I ran into this problem with a 4.0.1.199 (git snapshot), but then 3.37.1 had the same problem. Firewall is disabled on the host. Same command works on Ubuntu. ```strace``` does not show anything useful (at least to me :-) ):

```
futex(0x7fe46e213f58, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x7fe46af25168, FUTEX_WAIT_PRIVATE, 0, {tv_sec=4, tv_nsec=999999224}error [loggen_helper.c:resolve_address_using_getaddrinfo:109] name lookup error (192.168.1.1:514​): Servname not supported for ai_socktype
error [socket_plugin.c:active_thread_func:332] can not connect to 192.168.1.1:514​ (0x560ccbb28000)
) = 0
futex(0x7fe46af25178, FUTEX_WAKE_PRIVATE, 2147483647) = 1
futex(0x7fe46af25180, FUTEX_WAKE_PRIVATE, 1) = 1
write(2, "Total runtime = 2e-06, count = 0"..., 33Total runtime = 2e-06, count = 0
) = 33
close(3)                                = 0
exit_group(0)                           = ?
+++ exited with 0 +++
```

**Comment by czanik** [comment]
Alma Linux 8 also with all the latest updates, just like my Rocky Linux installation, works as expected using the exact same syslog-ng package. Any suggestions what to check?

**Comment by bazsi** [comment]
The name resolver returns an error for the IP/port combination you are
using.

Does anything else trying to use the network work?

Does this help?


https://askubuntu.com/questions/742613/network-applications-throwing-servname-not-supported-for-ai-socktype

**Comment by czanik** [comment]
Sorry, the problem was something completely different :-) I copied the command line from a PDF. I cannot see the difference between the copy & paste and what I type, but the first fails the second one works. For all other testing I typed the command line from memory. Now, that I typed also in my Rocky 8 vm, it worked just fine. Closing.
