### ISSUE TITLE
Incorrect link in CONTRIBUTING.md

### ISSUE THREAD

**Issue by albert-github** [syslog-ng/syslog-ng#4358]
https://github.com/syslog-ng/syslog-ng/blob/1ca36ddeea8cb432ac5015bcec0d6c48880a1e1b/CONTRIBUTING.md?plain=1#L12

Either this link `(#reporting-issues)` should be `(#reporting-bugs)` (and maybe the title of the link should be changed as well)

or

the header `### Reporting bugs` should be `### Reporting issues`

**Comment by alltilla** [comment]
Thanks for the heads-up :)
Would you like to open a PR with a fix, or should we do it?

Cheers,
Attila

**Comment by albert-github** [comment]
Best that you do it.
