### ISSUE TITLE
patterndb inconsistent type hints for different parts of xml file 

### ISSUE THREAD

**Issue by erempel** [syslog-ng/syslog-ng#4403]
It seems that the patterndb-6.xsd requires that in the <values> section that the integer type hints be specified with the types of int32 or int64 while in the in the <examples> <test_values> the type hing must use the type of integer.

         <rule id="FLARE-3698" class="zmwatch" provider="UVic">
            <patterns>
               <pattern>INF ['zma -m @NUMBER:camera@' starting at @ESTRING:time:,@ pid = @NUMBER:pid@]</pattern>
            </patterns>
            <values>
               <value name="PATTERNID" type="int64">3698</value>
            </values>
            <examples>
               <example>
                  <test_message program="zmwatch">INF ['zma -m 13' starting at 14/11/16 21:28:13, pid = 27714]</test_message>
                  <test_values>
                     <test_value name="time" type="string">14/11/16 21:28:13</test_value>
                     <test_value name="pid" type="integer">27714</test_value>
                     <test_value name="camera" type="integer">13</test_value>
                  </test_values>
               </example>
            </examples>
         </rule>

**Comment by bazsi** [comment]
Hmm those should each be aliases for each other.

**Comment by erempel** [comment]
If I try to use integer type hint in the values section I get the error

[xerr@pangolin bin]$ /bin/pdbtool test --validate /tmp/patterns.xml
Error parsing pattern database file; filename='/tmp/patterns.xml', error='/tmp/patterns.xml:14:60: Error compiling value template, rule=FLARE-3161, name=PATTERNID, value=3161, error=Unknown type specified in type hinting: integer'

**Comment by bazsi** [comment]
I have found the issue, sorry for broking this. Submitting a PR in a moment.
