### ISSUE TITLE
Unable to write to disk buffer file

### ISSUE THREAD

**Issue by AkinoMush1** [syslog-ng/syslog-ng#4430]
# syslog-ng
## Version of syslog-ng
4.0.1

## Platform
linux

## Debug bundle

# Issue
## Failure
Messge can't write to disk buffer file(syslog-ng-00000.rqf).

## Steps to reproduce
1. Set the disk buffer in destination. Set up A server and B server for sending messages from A to B.
2. When close B, the message is successfully written to the disk buffer file of A.
3. When B reconnects, the messages in the disk buffer file are successfully resent to B.
4. When close the B server again, the message cannot continue to be stored in the disk buffer file of A.
5. I have to delete the file and restart syslog-ng to write again.

## Configuration

```
@version: 4.0
@include "scl.conf"

options {
    flush_lines (0);
    time_reopen (10);
    log_fifo_size (1000);
    chain_hostnames (off);
    use_dns (no);
    use_fqdn (no);
    create_dirs (no);
    keep_hostname (yes);
};

source s_sys {
    system();
    internal();
    # udp(ip(0.0.0.0) port(514));
};

destination d_cons { file("/dev/console"); };
destination d_mesg { file("/var/log/messages"); };
destination d_auth { file("/var/log/secure"); };
destination d_mail { file("/var/log/maillog" flush_lines(10)); };
destination d_spol { file("/var/log/spooler"); };
destination d_boot { file("/var/log/boot.log"); };
destination d_cron { file("/var/log/cron"); };
destination d_kern { file("/var/log/kern"); };
destination d_mlal { usertty("*"); };

filter f_kernel     { facility(kern); };
filter f_default    { level(info..emerg) and
                        not (facility(mail)
                        or facility(authpriv)
                        or facility(cron)); };
filter f_auth       { facility(authpriv); };
filter f_mail       { facility(mail); };
filter f_emergency  { level(emerg); };
filter f_news       { facility(uucp) or
                        (facility(news)
                        and level(crit..emerg)); };
filter f_boot   { facility(local7); };
filter f_cron   { facility(cron); };

#log { source(s_sys); filter(f_kernel); destination(d_cons); };
log { source(s_sys); filter(f_kernel); destination(d_kern); };
log { source(s_sys); filter(f_default); destination(d_mesg); };
log { source(s_sys); filter(f_auth); destination(d_auth); };
log { source(s_sys); filter(f_mail); destination(d_mail); };
log { source(s_sys); filter(f_emergency); destination(d_mlal); };
log { source(s_sys); filter(f_news); destination(d_spol); };
log { source(s_sys); filter(f_boot); destination(d_boot); };
log { source(s_sys); filter(f_cron); destination(d_cron); };

@include "/etc/syslog-ng/conf.d/*.conf"

destination d_threat_master_host {
    syslog(
        "192.168.1.1"
        transport("tcp")
        port(514)
        template(t_threat_master)
        disk-buffer(
            mem-buf-size(10000)
            disk-buf-size(2000000)
            reliable(yes)
        )
        persist-name("persist_threat_master")
    );
};
```

**Comment by bazsi** [comment]
Is this the full config? I don't see the destination d_threat_master_host being added to any log path, which means that
no messages will be sent to that server.

Could you grab the internal logs of syslog-ng while it is exhibiting this problem? Try running syslog-ng in the foreground (-F) and with internal logs going to stderr (-e), possibly increasing the log level to debug (-d) and capture the stderr and copy/paste here.

**Comment by AkinoMush1** [comment]
full config:

destination d_threat_master_host {
    syslog(
        "192.168.151.54"
        transport("tcp")
        port(514)
        template(t_threat_master)
        disk-buffer(
            mem-buf-size(10000)
            disk-buf-size(2000000)
            reliable(yes)
        )
        persist-name("persist_threat_master")
    );
};

source s_threat_master {
   file(
        "/data/ddi3/log/named/threat.log"
        follow-freq(1)
        flags(no-parse)
        persist-name("persist_threat_master")
   );
};

log {
    source(s_threat_master);
    destination(d_threat_master_host);
};

log:
1、Close 54 server for the first time
![image](https://user-images.githubusercontent.com/59603977/232424882-4b84282e-5764-4d3f-8526-f442a9b48cd4.png)
![image](https://user-images.githubusercontent.com/59603977/232425043-fdb99d78-1019-4868-a769-b31b92d869fd.png)
write to disk buffer file successfully

**Comment by bazsi** [comment]
There was a couple of fixes to dqtool recently, if you are running dqtool in parallel to a syslog-ng instance touching the same file, it can "corrupt" the disk queue file, renaming to have a "corrupted" suffix in its filename. These are not released yet, but are already merged to master. Will become 4.2.0.

If this happens, syslog-ng can restart the queue file.

I am not saying this is happening here, but could be. You could use "syslog-ng-ctl stats" to query the amount of messages stored in the destination's queue.

If you don't use dqtool to confirm reception of messages does the same thing happen?

Also, in your point 3. I can see an "Outgoing message" line from syslog-ng, are you sure it is not sending those messages?

**Comment by AkinoMush1** [comment]
I don't use dqtool to confirm reception of messages , but the same thing happen again.

Yes, I'm sure it is not sending those messages. Because I have closed the 54 server, but it still generates the "Outgoing message".

**Comment by bazsi** [comment]
What do you mean on "closed" the server? Do you stop the receiving application, shut down that computer, or power it off?

If the connection is in established state, and the destination is removed from the network without closing the connection first, then syslog-ng may not receive a TCP level response (e.g. an ACK) to the message it sends.

In that case syslog-ng may still be able to send a few messages, until the breakage of the connection can be detected.

Can this be a problem in your case? Look at "netstat -ant" output on the client computer (or tcpdump) to see the connection state and the size of the send queue.

syslog-ng sends TCP keep alive data frames to the server regularly to recognize this fact, as early as possible, but let me first know how that 54 server shuts down, if we are on the right path.

**Comment by AkinoMush1** [comment]
Thank you for your reply, the problem has been solved. It is caused by the tcp connection status.
