### ISSUE TITLE
high memory usage of add-contextual-data

### ISSUE THREAD

**Issue by gpfei** [syslog-ng/syslog-ng#4439]
# syslog-ng
## Version of syslog-ng

4.1.1

## Platform

OpenEuler 22.04 LTS (similar with CentOS 9)

## Steps to reproduce

generate a large csv file, for example, about 1M lines and 100M bytes.

## Configuration

```
parser p_foo {
    add-contextual-data(
        selector("$someField"),
        database("/etc/syslog-ng/conf.d/large-db.csv"),
    );
};
```

## command

`LD_PRELOAD=/usr/lib64/libjemalloc.so.2 syslog-ng -F -p /var/run/syslogd.pid`

## Input and output logs (if possible)

`RES` value of `syslog-ng` in `top` output is about 1.3 GB, which is far more than expected.

Thanks.

**Comment by bazsi** [comment]
I've just opened a PR to decrease the memory use somewhat in #4444 still not perfect, but seems much better for me.

**Comment by bazsi** [comment]
This should have been improved by the merge of #4444. Closing.
