### ISSUE TITLE
`grouping-by()`, `group-lines()`: persist name is dependent on the number of times it gets cloned

### ISSUE THREAD

**Issue by alltilla** [syslog-ng/syslog-ng#4443]
# syslog-ng
## Version of syslog-ng
4.1.1

# Issue
`group-lines()` and `grouping-by()` filters' persist names depend on how many times they are getting cloned.

When cloning such a parser, the `clone_id` of the cloned instance gets the one from `self`,  and `self`'s `clone_id` is incremented. This is done so the original instance can be cloned multiple times without 2 of its clones having the same `clone_id`. https://github.com/syslog-ng/syslog-ng/blob/syslog-ng-4.1.1/modules/correlation/groupingby.c#L539

Let's say we have a config, where the parser instance gets cloned 2 times. It has `clone_id=2` in its persist name and stores its values in the persist with that name. We add another reference/user of the parser in the config, and reload. Now it gets `clone_id=3`, and it won't find its persist entry from before reload and starts a new, however the new clone gets an already filled persist entry.

We should fix this issue, while still guaranteeing that no 2 clones get the same `clone_id`.

**Comment by Saharshjain78** [comment]
We can proceed by Generate a unique identifier for the cloned instance, Increasing the self's unique_id (not clone_id)
Can you please assign me the issue?
