### ISSUE TITLE
syslog-ng -s prints warning, if Python support is installed but venv not initialized

### ISSUE THREAD

**Issue by czanik** [syslog-ng/syslog-ng#4471]
Version 4.2.0 of syslog-ng shows a warning message when ```syslog-ng -s``` is run, if Python support is installed, but virtualenv is not initialized. My RPM packages use Python dependencies from the system Python installation:
```
czplaptop:~ # syslog-ng -s
[2023-05-12T12:25:00.518004] python: private virtualenv is not initialized, use the `syslog-ng-update-virtualenv' script to initialize it or make sure all required Python dependencies are available in the system Python installation; path='/var/lib/syslog-ng/python-venv'
```
The problem is, that quite a few users run ```syslog-ng -s``` in scripts before restarting syslog-ng, and those fail if there is any output from syslog-ng.

**Comment by MrAnno** [comment]
That's the side-effect of the confgen part of the HYPR audit trail source.

I think we should somehow make the Python dependency optional when the HYPR SCL is not used directly in the configuration.

In the meantime, excluding the HYPR source from packaging, or simply not installing python-modules can be a workaround.

**Comment by bazsi** [comment]
I think that will not fix it. If the system Python is used with system installed pacakges that warning is displayed regardless of hypr being on the system or not. At least that's my recollection.

**Comment by bazsi** [comment]
Our RPMs install dependencies in the postinst script, I think the one Peter builds do not.

**Comment by bazsi** [comment]
this is the culprit:
```
  const gchar *private_venv_path = get_installation_path_for(SYSLOG_NG_PYTHON_VENV_DIR);
  if (!_py_is_virtualenv_valid(private_venv_path))
    {
      msg_warning("python: private virtualenv is not initialized, use the `syslog-ng-update-virtualenv' "
                  "script to initialize it or make sure all required Python dependencies are available in "
                  "the system Python installation",
                  evt_tag_str("path", private_venv_path));
      return NULL;
    }
```

I guess if this was not msg_warning() but msg_debug() it will not be visible, less discoverable too though. But I think it is perfectly valid to deploy syslog-ng with system installed Python dependencies, so it should not be a warning.

@czanik as a workaround, can you change this to an msg_debug() to see if it fixes the issue?

**Comment by MrAnno** [comment]
Sorry for my confusion.

> this is the culprit:

This warning message is not shown when Python is loaded with `@module mod-python use-virtualenv(no)`.

Can't we just make this flag available as a compile-time configure option as well?
