### ISSUE TITLE
missing `cmake/print_config_summary.cmake` in 4.2.0 release tarball file

### ISSUE THREAD

**Issue by chenrui333** [syslog-ng/syslog-ng#4473]
👋 it looks like `cmake/print_config_summary.cmake` file is missing in the 4.2.0 release tarball, which caused the unknown command issue. Thanks!

**Comment by alltilla** [comment]
Hi Rui Chen,
Thanks for the heads up!

This might be related to https://github.com/syslog-ng/syslog-ng/pull/4428. @HofiOne can you take a look please? Thanks!

**Comment by MrAnno** [comment]
@HofiOne EXTRA_DIST needs to be updated:
https://github.com/syslog-ng/syslog-ng/blob/master/cmake/Makefile.am#L1

**Comment by HofiOne** [comment]
thanks, https://github.com/syslog-ng/syslog-ng/pull/4474
