### ISSUE TITLE
dbld make fails in ubuntu 20.04.6 lts

### ISSUE THREAD

**Issue by madhavane-y** [syslog-ng/syslog-ng#4492]
Hi people, I need to use syslog-ng with java support. And by my understanding from the docs, i need to compile syslog ose with java support flags (--enable-java --enable-java-modules). 

I have been trying for few days now. I have given the correct configure options and used dbld/rules script and created a docker image with ubuntu-focal as base with java support enabled. But i can't, for the love of my life, figure out how to release a deb package. If i try deb-ubuntu-focal target, i get the following error

[syslog-ng-error.txt](https://github.com/syslog-ng/syslog-ng/files/11539767/syslog-ng-error.txt)

My use case: I am trying to centralise logging from my docker containers into a syslog docker container on the same host. I need java for overriding the class so that i can send the logs to a remote destination, which unfortunately only supports http calls.

If someone has any other suggestion to solve my case, I'm all ears!

Have been reading docs, code and forums for clues, to no avail. I'm not savvy with make and C, so any help is appreciated.
Also sorry if this is out of norms. I'm a recent CS grad turned developer, not experienced with git etiquette.

**Comment by alltilla** [comment]
Hi @madhavane-y 

Thank you for the detailed question.

APT packages built from the master branch (nightly) and stable releases are available here, if that is enough for you: https://github.com/syslog-ng/syslog-ng#debianubuntu
If you have local changes, you can generate ubuntu-focal packages with: `dbld/rules package-ubuntu-jammy`

However as you mention your use case, java might not be the best solution for you IMO. If the remote destination is a HTTP server, it is recommended to use the `http()` destination and form your HTTP request with the `body()` and `headers()` options.
It is a lot faster than the java binding, and you can skip the building on your own part, as it is available in the `syslog-ng-mod-http` package. You can even enable batching with the `body-prefix()`, `body-suffix()` and `delimiter()` options.

You can see some examples of using the `http()` destination in these files:
```
$ git grep "http *(" | grep "\.conf" | grep -o "^[^:]*" | uniq
scl/discord/discord.conf
scl/elasticsearch/elastic-http.conf
scl/logscale/logscale.conf
scl/slack/slack.conf
scl/splunk/splunk.conf
scl/sumologic/sumologic.conf
scl/telegram/telegram.conf
```

Documentation: https://www.syslog-ng.com/technical-documents/doc/syslog-ng-open-source-edition/3.36/administration-guide/39#TOPIC-1768633

The documentation could be out of date unfortunately. You can use [syslog-ng-cfg-helper](https://github.com/alltilla/syslog-ng-cfg-helper) to list all the available options:
<details>

```
$ syslog-ng-cfg-helper -c destination -d http
http(
    accept-redirects(<yesno>)
    azure-auth-header(
        <path>(<string>)
        content-type(<string>)
        method(<string>)
        secret(<string>)
        workspace-id(<string>)
    )
    batch-bytes(<nonnegative-integer>)
    batch-lines(<nonnegative-integer>)
    batch-timeout(<positive-integer>)
    body(<template-content>)
    body-prefix(<string>)
    body-suffix(<string>)
    ca-dir(<string>)
    ca-file(<path>)
    cert-file(<path>)
    cipher-suite(
        <empty>
        <string>
        tls12-and-older(<string>)
        tls13(<string>)
    )
    delimiter(<string>)
    disk-buffer(
        compaction(<yesno>)
        dir(<string>)
        disk-buf-size(<number>)
        mem-buf-length(<nonnegative-integer>)
        mem-buf-size(<nonnegative-integer>)
        prealloc(<yesno>)
        qout-size(<nonnegative-integer>)
        reliable(<yesno>)
        truncate-size-ratio(
            <float>
            <nonnegative-integer>
        )
    )
    flush-bytes(<nonnegative-integer>)
    flush-lines(<nonnegative-integer>)
    flush-timeout(<positive-integer>)
    frac-digits(<nonnegative-integer>)
    headers(<string-list>)
    hook-commands(
        setup(<string>)
        shutdown(<string>)
        startup(<string>)
        teardown(<string>)
    )
    http-test-slots(
        header(<string>)
    )
    internal(<yesno>)
    key-file(<path>)
    local-time-zone(<string>)
    log-fifo-size(<positive-integer>)
    method(<string>)
    ocsp-stapling-verify(<yesno>)
    on-error(<string>)
    password(<string>)
    peer-verify(<yesno>)
    persist-name(<string>)
    proxy(<string>)
    python-http-header(
        class(<string>)
        loaders(<string-list>)
        mark-errors-as-critical(<yesno>)
        options(
            <empty>
            <string>
            <string> => <float>
            <string> => <number>
            <string> => <python-yesno>
            <string> => <string>
            <string> => [ <string-list> ]
            LogTemplate(<string>)
        )
    )
    response-action(
        <empty>
        <positive-integer> => disconnect
        <positive-integer> => drop
        <positive-integer> => retry
        <positive-integer> => success
    )
    retries(<positive-integer>)
    send-time-zone(<string>)
    ssl-version(<string>)
    throttle(<nonnegative-integer>)
    time-reopen(<positive-integer>)
    time-zone(<string>)
    timeout(<nonnegative-integer>)
    tls(
        <empty>
        ca-dir(<string>)
        ca-file(<path>)
        cert-file(<path>)
        cipher-suite(
            <empty>
            <string>
            tls12-and-older(<string>)
            tls13(<string>)
        )
        key-file(<path>)
        ocsp-stapling-verify(<yesno>)
        peer-verify(<yesno>)
        ssl-version(<string>)
        use-system-cert-store(<yesno>)
    )
    ts-format(<string>)
    url(<string-list>)
    use-system-cert-store(<yesno>)
    user(<string>)
    user-agent(<string>)
    workers(<positive-integer>)
)
```

</details>

Don't worry, your question is not out of norms at all, I am sorry that there were not enough information online for you to tackle this problem. The documentation is a bit of a mess right now, but we are working on that, too. If you would like to you can chat with syslog-ng developers and users on the Axoflow Discord, you can find me there, too:

[![Axoflow Discord Server](https://discordapp.com/api/guilds/1082023686028148877/widget.png?style=banner2)](https://discord.gg/E65kP9aZGm)

Hope these help :)

Cheers,
Attila

**Comment by madhavane-y** [comment]
Hi @alltilla thanks for the quick and rather detailed response. I'll try out this destination.
Thanks for the configuration helper too!

Seeing the version in the repo v4+ not matching the [docs](https://www.syslog-ng.com/technical-documents/doc/syslog-ng-open-source-edition/3.37/administration-guide), anything im missing? I saw axoflow blog about syslog-ng 4.2 release, while the docs linked above only mentions 3.37 as latest OSE version. Is this intentional?

Thanks again for responding!

**Comment by alltilla** [comment]
The doc under syslog-ng.com is maintained by One Identity and it has not been updated since 3.37, which was released a year ago. Axoflow is working on providing a documentation to [AxoSyslog](https://github.com/axoflow/axosyslog-docker) which uses syslog-ng as its core.

You can refer to the 3.37 doc regarding the `http()` destination, because not much have changed, but I hope I can provide you doc for more recent versions in the short future. Until then you can reach us on Discord and we can help you out if needed :)
