### ISSUE TITLE
4.2 pdbtool --validate return codes different for version 6 db file

### ISSUE THREAD

**Issue by erempel** [syslog-ng/syslog-ng#4498]
I have a pattern database file that produces warnings of

Rule conflict! Multiple rules match this message

When the patterndb file is version="4" the pdbtool --validate has a return code 0, but when the same patterndb file is version="6" the return code is 2.

I am unable to find documentation on the return codes  so I am unable to evaluate how "correct" this is or how use the return code programmatically.

Is this a bug or a feature? Only documentation will decide!

**Comment by bazsi** [comment]
Thanks for the report. Good news is that one identity added a more liberal
license to the docs, so it can be improved.

  if (failed_to_load || failed_to_validate)
    return 1;
  if (failed_to_match)
    return 2;

failed_to_match is set if:

* An example message is matching the wrong rule, OR
* the value or the type of an expected value does not match

Considering that v6 introduced type support, this is probably the second
case. But that should also display what pdbtool does not like.

**Comment by erempel** [comment]
I think I see what i happening.
You are correct that there are a few actual errors that did not show up with a V4 pttern database.

If I have two patterns like

hello @STRING:myname@
hello @NUMBER:myid@

with tests that include test values the variables myname and myid, they will both match the test message with the numbrer, such as

hello 1234

In a v4 database this results in the warning
 Rule conflict! Multiple rules match this message, list of IDs follow
but no actual errors.

In a v6 database the same warning occurs but ALSO the error of

 Wrong match name='myname', value='', type='null', expected='1234', expected_type='string'

so it seems that when a test message is matched by a second pattern that the variables of the second pattern are also verified (or perhaps just type checked) when they should not be.

I think that behaviour might be unintended.

**Comment by bazsi** [comment]
I have a reproducer, posting it here if I get distracted I know where to continue it from:

```
<patterndb version="6" pub_date="2009-09-01">
  <ruleset name="su" id="RS-d2fae001-a7f6-4e39-ae62-5658906fe48c">
    <pattern>prog</pattern>
    <rules>
      <rule id="1" class="unknown" provider="UVic">
        <patterns>
           <pattern>hello @STRING:myname@</pattern>
	   <pattern>hello @NUMBER:myid@</pattern>
        </patterns>
        <examples>
          <example>
            <test_message program="prog">hello 1234</test_message>
            <test_values>
               <test_value name="PROGRAM" type="string">prog</test_value>
               <test_value name="myid" type="int">1234</test_value>
            </test_values>
          </example>
          <example>
            <test_message program="prog">hello foobar</test_message>
            <test_values>
               <test_value name="PROGRAM" type="string">prog</test_value>
               <test_value name="myname" type="string">foobar</test_value>
            </test_values>
          </example>
        </examples>
      </rule>
    </rules>
  </ruleset>
</patterndb>
```


Testing message: program='prog' message='hello foobar'
 Match name='.classifier.rule_id', value='1', type='string', expected='1'
 Match name='PROGRAM', value='prog', type='string', expected='prog'
 Match name='myname', value='foobar', type='string', expected='foobar'
Testing message: program='prog' message='hello 1234'
 Rule conflict! Multiple rules match this message, list of IDs follow
  1
  1
 Match name='.classifier.rule_id', value='1', type='string', expected='1'
 Match name='PROGRAM', value='prog', type='string', expected='prog'
 Wrong match name='myid', value='', type='null', expected='1234', expected_type='int'


Indeed the second example message seems to validate the expected values of the first sample.

**Comment by bazsi** [comment]
looking at my reproducer again. I was wrong, was too quick to post it here. It seems that due to the conflict both of the patterns above match, the input is not enough to differentiate between the two (STRING would consume 1234, it's not more specific). If I change the order of the two patterns, moving @NUMBER@ to be first and @STRING@ second, it works:

```
<patterndb version="6" pub_date="2009-09-01">
  <ruleset name="su" id="RS-d2fae001-a7f6-4e39-ae62-5658906fe48c">
    <pattern>prog</pattern>
    <rules>
      <rule id="1" class="unknown" provider="UVic">
        <patterns>
	   <pattern>hello @NUMBER:myid@</pattern>
           <pattern>hello @STRING:myname@</pattern>
        </patterns>
        <examples>
          <example>
            <test_message program="prog">hello 1234</test_message>
            <test_values>
               <test_value name="PROGRAM" type="string">prog</test_value>
               <test_value name="myid" type="int">1234</test_value>
            </test_values>
          </example>
          <example>
            <test_message program="prog">hello foobar</test_message>
            <test_values>
               <test_value name="PROGRAM" type="string">prog</test_value>
               <test_value name="myname" type="string">foobar</test_value>
            </test_values>
          </example>
        </examples>
      </rule>
    </rules>
  </ruleset>
</patterndb>
```

Testing message: program='prog' message='hello foobar'
 Match name='.classifier.rule_id', value='1', type='string', expected='1'
 Match name='PROGRAM', value='prog', type='string', expected='prog'
 Match name='myname', value='foobar', type='string', expected='foobar'
Testing message: program='prog' message='hello 1234'
 Rule conflict! Multiple rules match this message, list of IDs follow
  1
  1
 Match name='.classifier.rule_id', value='1', type='string', expected='1'
 Match name='PROGRAM', value='prog', type='string', expected='prog'
 Match name='myid', value='1234', type='int', expected='1234'

**Comment by bazsi** [comment]
When patterns overlap, db-parser() has a hard time choosing the right one, and will use the first pattern, unless it does not match. Hence the ordering between overlapping patterns should be so that a more restrictive parser comes first and then the more general one.

I am not sure I reproduced the same issue that you had though. Can you help me improve the example above so I can be sure I am fixing your exact problem?

**Comment by bazsi** [comment]
If I set the version to v4, it still fails for the same reason (also removing the type attributes). They would only work if the string value of the @NUMBER@ would be equal to the value parsed by @STRING@. In that case only the type would be different.

```
Testing message: program='prog' message='hello 1234'
 Rule conflict! Multiple rules match this message, list of IDs follow
  1
  2
 Wrong match name='.classifier.rule_id', value='1', type='string', expected='2', expected_type='string'
 Match name='PROGRAM', value='prog', type='string[unchecked]', expected='prog'
 Wrong match name='myid', value='', type='null', expected='1234', expected_type='null'
Testing message: program='prog' message='hello foobar'
 Match name='.classifier.rule_id', value='1', type='string', expected='1'
 Match name='PROGRAM', value='prog', type='string[unchecked]', expected='prog'
 Match name='myname', value='foobar', type='string[unchecked]', expected='foobar'
```

Or am I missing something?

**Comment by erempel** [comment]
No, you're not missing anything. Turns our I am missing something.

We have all of our patterns in a database and have a program that extracts them into the pattern db file. We have "improved" the ordering of our patterns by creating a  "static text length" attribute by stripping all of the @...@ parser text from the patterns and counting the remaining characters. Longer static text lengths now go first, which is a good thing, but it has produced the outcome of this ticket, which is not an issue with syslog-ng but a self created issue with our extraction.

Back to the drawing board for extracting our database into the pattern db xml file.

sorry to waste your time.
