### ISSUE TITLE
patternDB failes to cast hexadecimal values in example test values

### ISSUE THREAD

**Issue by erempel** [syslog-ng/syslog-ng#4532]
syslog-ng 4.2.0
RHEL 8.8

# Issue
The patternDB example test values fail to cast a hexadecimal number as integer.
hex values can be parsed with the  @NUMBER@ parser which should map to a single "type hint" of integer.

none of the patterndb processing of the log message occur. None of the tags are applied, none of the values are applied and not correlation is processed.

## Steps to reproduce

1. make any patterndb rule that has a @NUMBER@ parser that parses a hexadecimal number and create an example test value with a type hint of integer.
2. start syslog-ng with a configuration that uses the patterndb.
3. log a log line that get's matched by the pattern in the patterndb.

Error message is logged

syslog.err syslog-ng[2399664]: Casting error; value='0xC000006A', type-hint='integer'

**Comment by bazsi** [comment]
The PR above should fix this problem. Thanks for reporting it.
