### ISSUE TITLE
Behavour of in-list() matching

### ISSUE THREAD

**Issue by leakyzinc** [syslog-ng/syslog-ng#4545]
# syslog-ng
## Version of syslog-ng
syslog-ng 4 (4.2.0)
Config version: 4.2
Installer-Version: 4.2.0
Revision:
Compile-Date: Jun  8 2023 07:08:50
Module-Directory: /usr/lib64/syslog-ng
Module-Path: /usr/lib64/syslog-ng
Include-Path: /usr/share/syslog-ng/include
Available-Modules: affile,afprog,afsocket,afstomp,afuser,basicfuncs,confgen,cryptofuncs,csvparser,linux-kmsg-format,syslogformat,system-source,add-contextual-data,appmodel,cef,correlation,disk-buffer,examples,graphite,hook-commands,json-plugin,kvformat,map-value-pairs,metrics-probe,pacctformat,pseudofile,rate-limit-filter,regexp-parser,sdjournal,stardate,tags-parser,tfgetent,timestamp,xml
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: on
Enable-TCP-Wrapper: on
Enable-Linux-Caps: on
Enable-Systemd: on

## Platform
Oracle Linux Server 7.9

# Issue
Use of in-list() and how it matches values.  Requirement is to forward on logs received from 100s of devices to another syslog server by a list of source IP addresses.  Source devices sending to syslog is constantly changing.  Currently using a large (and unmanagable) filter with many OR netmask statements;

filter f_devices { (
netmask("192.168.0.10/32") or 
netmask("192.168.0.20/32") or 
netmask("192.168.0.30/32") or 
netmask("192.168.0.40/32") or 
netmask("192.168.0.50/32") or
...
...
); };

Thought to use in-list() instead and automatically populate and keep up-to-date a file with a simple list of IPs, each on a line;

devices.list contains;

192.168.0.10
192.168.0.20
192.168.0.30
...

filter f_devices { in-list("/etc/syslog-ng/conf.d/devices.list", value("HOST"));};

log {source(s_net); filter(f_devices); destination(d_anothersyslogserver};};

The issue is that a host with IP of 192.168.0.1 would be incorrectly matched because 192.168.0.10 is present in the list - assuming in-list() is doing a string comparison and matching as soon as all the characters of the field value (host) are found in an item in the list.

Appreciate this feature might not be intended for use in this way but I thought an interesting observation.  Is this a bug that can be fixed or is there any settings I can use to affect the behaviour of how in-list() matches strings?

**Comment by leakyzinc** [comment]
I believe I may have worked out the problem.  Was testing with a single entry in the list file of "192.168.30.10" but there wasn't a carriage return at the end of the line.  I think syslog-ng was forwarding on everything instead and that the logs from device 192.168.30.1 were the bulk of what was coming in skewed my understanding of the problem.

Adding the carriage return to all entries in the list file makes it behave as I'd like it to.

**Comment by bazsi** [comment]
Thanks for letting that know. Your tip should be useful in the documentation. @fekete-robert
