### ISSUE TITLE
Panos parser not working

### ISSUE THREAD

**Issue by Navsamr** [syslog-ng/syslog-ng#4547]
I am using syslog-ng version 3.23.1 on Linux 8.  I am testing syslog configuration for PanOS data source and created following configuration and when I try to restart syslog-ng service it is failing with below message.

/etc/syslog-ng/conf.d/pasos.conf
source s_panosonly { udp(port(514) flags(no-parse,store-raw-message)); };
template t_jsonfile {
    template("$(format-json --scope rfc5424 --scope dot-nv-pairs
        --rekey .* --shift 1 --scope nv-pairs --key ISODATE)\n\n");
};
parser p_panos { panos-parser(); };
filter f_panos { message("<hostname>"); };
destination d_frompanos {
    file("/opt/syslog-ng/syslog/PaloAlto/$HOST/$R_YEAR/$R_MONTH/$HOST_$R_DAY.log"" template(t_jsonfile));
}
log { source(s_panosonly); filter(f_panos); parser(p_panos); destination(d_frompanos); };

Error Message -
 Plugin module not found in 'module-path'; module-path='/usr/lib64/syslog-ng', module='http'
Error parsing parser expression, parser plugin panos-parser not found in /etc/syslog-ng/conf.d/panos.conf:8:18-8:30:
3      

Upon reading more on syslog-ng documentation, got to know that panos template is supported in syslog-ng version 3.29.  I am trying to install latest version of syslog-ng but the link provided in the documentation takes me no where and looks like the latest or last version of syslog-ng supported on Linux 8 Epel 8 is 3.23.  Can you guide me on further steps to install the latest package or how to use pasos parser with existing one?

I get below outputs when I try to access the link provided in wget - https://copr.fedorainfracloud.org/coprs/czanik/syslog-ng336/repo/epel-8/czanik-syslog-ng42-epel-8.repo

I cannot wget directly from the server as we don't have internet access.  Best way is to download the rpm and install it on the server manaully.

[copr:copr.fedorainfracloud.org:czanik:syslog-ng336]
name=Copr repo for syslog-ng336 owned by czanik
baseurl=https://download.copr.fedorainfracloud.org/results/czanik/syslog-ng336/epel-8-$basearch/
type=rpm-md
skip_if_unavailable=True
gpgcheck=1
gpgkey=https://download.copr.fedorainfracloud.org/results/czanik/syslog-ng336/pubkey.gpg
repo_gpgcheck=0
enabled=1
enabled_metadata=1

**Comment by bazsi** [comment]
You could probably just copy the scl file from the later version of syslog-ng, back to the version you already have. The latest version is here:

https://github.com/syslog-ng/syslog-ng/blob/master/scl/paloalto/panos.conf
