### ISSUE TITLE
Can't build on macOS

### ISSUE THREAD

**Issue by shgubar** [syslog-ng/syslog-ng#4591]
# syslog-ng 
Version of syslog-ng
3.35.1

## Platform
macOS 10.6.8

## Debug bundle
  CC       lib/transport/libsyslog_ng_la-transport-udp-socket.lo
lib/transport/transport-udp-socket.c: In function ‘_extract_dest_ip4_addr_from_cmsg’:
lib/transport/transport-udp-socket.c:65: error: ‘IP_PKTINFO’ undeclared (first use in this function)
lib/transport/transport-udp-socket.c:65: error: (Each undeclared identifier is reported only once
lib/transport/transport-udp-socket.c:65: error: for each function it appears in.)
lib/transport/transport-udp-socket.c:74: error: dereferencing pointer to incomplete type
lib/transport/transport-udp-socket.c: In function ‘log_transport_udp_setup_fd’:
lib/transport/transport-udp-socket.c:196: error: ‘IP_PKTINFO’ undeclared (first use in this function)
lib/transport/transport-udp-socket.c:201: error: ‘IPV6_RECVPKTINFO’ undeclared (first use in this function)
make[2]: *** [lib/transport/libsyslog_ng_la-transport-udp-socket.lo] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

Please help. What am I doing wrong?

**Comment by HofiOne** [comment]
I'm not sure that such an old macOS (OSX) version was ever supported, anyway.
The oldest macOS version I have is 10.7 unfortunately, maybe I could use a VM later on, but first of all, please add more details.
- please provide the git hash of the syslog-ng version you are trying to build
- what options are you using for building
- what is the exact compiler you tried to use
- what is the method you are trying to use for building
- where do you get the required dependencies from
- etc.
TIA!

**Comment by MrAnno** [comment]
`IP_PKTINFO` is available starting from macOS 10.7 ([link](https://newosxbook.com/src.jl?tree=xnu-1699.32.7&file=/bsd/netinet/udp_usrreq.c)).

macOS is currently supported in a "best-effort" manner, we've never tried such old versions.
Please consider upgrading.

**Comment by MrAnno** [comment]
I'm marking this issue as "not planned". Feel free to reopen, if you have further questions or if you want to work on the compatibility of older macOS versions.

**Comment by shgubar** [comment]
Thank you very much for the answers.

I want to explain the situation and, if possible, still help.

Another licensed software product is installed on this server, which is why I can't upgrade the system. In addition, there are a few more admin tools that I can't update either.

How I tried to install - I used the McPorts package to install additional utilities. There was a need to collect system logs from other computers for further analysis. Syslog-ng has a flexible setting that allows me to avoid unwanted messages, that's why I wouldn't want to use the built-in syslog.

If there is such an opportunity (perhaps it is saved somewhere), provide me with a source for compatibility with this system.

I am infinitely grateful in advance to anyone who responds and can help.

**Comment by MrAnno** [comment]
Thank you for explaining your situation.

[syslog-ng 3.26.1](https://github.com/syslog-ng/syslog-ng/releases/tag/syslog-ng-3.26.1) was the last release where `IP_PKTINFO` was not used in our sources. You can try compiling that version, but that's quite old and I'm not sure if you would succeed with the compilation.

(If that doesn't work out for you and patching syslog-ng is an option for you, I'd try to help you resolve the compatibility issues on top of the latest syslog-ng version.)

**Comment by shgubar** [comment]
> [syslog-ng 3.26.1](https://github.com/syslog-ng/syslog-ng/releases/tag/syslog-ng-3.26.1) was the last release where `IP_PKTINFO` was not used in our sources. You can try compiling that version, but that's quite old and I'm not sure if you would succeed with the compilation.

I tried the version you suggested.
Here are the steps that were taken:
1) Download and extract
2) In working directory - `./configure` - Success
3) Than - `make` - Error:

```
 root # make
make --no-print-directory all-recursive
  CC       modules/native/modules_native_libsyslog_ng_native_connector_a-native-grammar.o
  CC       modules/native/modules_native_libsyslog_ng_native_connector_a-native-parser.o
  CC       modules/native/modules_native_libsyslog_ng_native_connector_a-parser.o
  AR       modules/native/libsyslog-ng-native-connector.a
  CC       lib/eventlog/src/lib_eventlog_src_libevtlog_la-evtrec.lo
  CC       lib/eventlog/src/lib_eventlog_src_libevtlog_la-evtfmt.lo
  CC       lib/eventlog/src/lib_eventlog_src_libevtlog_la-evtout.lo
  CC       lib/eventlog/src/lib_eventlog_src_libevtlog_la-evtstr.lo
  CC       lib/eventlog/src/lib_eventlog_src_libevtlog_la-evtctx.lo
  CC       lib/eventlog/src/lib_eventlog_src_libevtlog_la-evttags.lo
  CC       lib/eventlog/src/lib_eventlog_src_libevtlog_la-evtsyslog.lo
  CCLD     lib/eventlog/src/libevtlog.la
  CC       lib/secret-storage/lib_secret_storage_libsecret_storage_la-secret-storage.lo
  CC       lib/secret-storage/lib_secret_storage_libsecret_storage_la-nondumpable-allocator.lo
lib/secret-storage/nondumpable-allocator.c: In function ‘_mmap’:
lib/secret-storage/nondumpable-allocator.c:96: error: ‘MAP_ANONYMOUS’ undeclared (first use in this function)
lib/secret-storage/nondumpable-allocator.c:96: error: (Each undeclared identifier is reported only once
lib/secret-storage/nondumpable-allocator.c:96: error: for each function it appears in.)
make[2]: *** [lib/secret-storage/lib_secret_storage_libsecret_storage_la-nondumpable-allocator.lo] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

Same result with next versions: `3.25 - 15.1`

**Comment by MrAnno** [comment]
@shgubar Could you try compiling the following patch?

https://github.com/MrAnno/syslog-ng/commits/old-macos/

Tarball:
https://github.com/MrAnno/syslog-ng/suites/15483212308/artifacts/884197520

I'd start without modules first:
```
./configure --disable-all-modules
```

If you prefer to chat more interactively, you are welcome to join our Discord server:
https://discord.gg/E65kP9aZGm
My username is @MrAnno there as well.

**Comment by shgubar** [comment]
Thank you very much for your help.
I will try the proposed option.

**Comment by MrAnno** [comment]
We've discussed and debugged this on Discord.

Since only minimal modifications are required to support older macOS versions, I've decided to prepare a few patches to make syslog-ng work on such systems (at least the core and a few modules of syslog-ng).

I'll open a PR soon.

**Comment by shgubar** [comment]
Maybe it will be useful to someone.
Steps:
1. Install `ivykis` (source was dowloaded before):
```
cd ivykis-0.42.4/
make
make install
if bash:
export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig/
if tcsh:
setenv PKG_CONFIG_PATH /usr/local/lib/pkgconfig/
```
2. Configure, build and install `syslog-ng` (without snmp - too old library - I don't use this):
```
cd syslog-ng-build
./configure --with-ivykis=system --disable-afsnmp --prefix /Users/user/syslog-ng
make
make install
cd /Users/user/syslog-ng
edit for your needs ./etc/syslog-ng.conf
sbin/syslog-ng -Fev -f ./etc/syslog-ng.conf
````
Done
