### ISSUE TITLE
Runtime configuration check capability

### ISSUE THREAD

**Issue by pepov** [syslog-ng/syslog-ng#4592]
## Description of the problem
In order to verify that a configuration is syntactically valid I can already run syslog-ng with the `-s` flag. I would like to check if the configuration is semantically valid as well and that syslog-ng can actually start with the given config.

## Proposed solution
I propose to have a similar flag, but one that allows syslog-ng to initialize fully and then quit cleanly if everything is correct.

## Alternatives
I can already start syslog-ng with a given timeout so that I can test the configuration, however that is not completely reliable. If we set it too low, than it might fail on an otherwise valid configuration, or if we set it too high it will be slow.

## Additional context
This feature would be leveraged by the logging operator in it's automatic config check feature:
https://github.com/kube-logging/logging-operator/issues/1432

**Comment by bernisys** [comment]
I'm not sure if i understood the use-case correctly but I would be interested as well in a similar feature.

I found that the syntax check and also the "--preprocess-into" option sometimes are not enough to see clearly, if the daemon would start up properly. It seems that some additional things are done right after the config-preprocessing is finished. And failure to do this is only captured in a full startup, which you cannot do in a simple manner when port-listeners are involved as those cannot be bound as long as the original daemon is still running and blocking those ports (which is what you actually want in some cases, to serve logs as long as possible, preserving consistency between major changes in the config).

One solution can be to use the container version and simply fire up a second container, could parse the output to check if the daemon would come up properly, and if yes, you simply exchange the containers. But i think having a more thorough evaluation inside syslog-ng would be a more elegant solution.

**Comment by pepov** [comment]
We are running this in kubernetes and we run the config check as a separate pod, so the port bindings are no problem. We already have a workaround that leverages the `timeout` command, but it's not ideal and parsing logs wouldn't be very robust either.

**Comment by bazsi** [comment]
I have opened a PR that should solve this issue.
