### ISSUE TITLE
patterndb not reloaded when changed

### ISSUE THREAD

**Issue by erempel** [syslog-ng/syslog-ng#4594]
From https://copr-be.cloud.fedoraproject.org/results/czanik/syslog-ng-stable/epel-8-x86_64
syslog-ng-4.3.1-1.el8.x86_64

Red Hat Enterprise Linux release 8.8 (Ootpa)

# Issue
Previous versions of syslog-ng would automatically reload any patterndb parsers if they changed on disk and would log a syslog message:

Log pattern database reloaded; file='/opt/flare/etc/patterndb_patterns.xml', version='4', pub_date='2009-09-01', location='/etc/syslog-ng/syslog-ng.server.conf:178:2'

This latest version does not .

## Failure
When the patterndb parser file is modified, no reload log message is produced (and I assume the patterndb is not reloaded).

## Steps to reproduce
Make any patterndb file and reference it in a patterndb parser.
While syslog-ng is running with the patterndb loaded, modify the parser.xml file (simple touch used to be sufficient).
Monitor the syslog stream for the reload message.

**Comment by bazsi** [comment]
Thanks for the feedback and the fix :)
