### ISSUE TITLE
syslog-ng 4.2, weird pid logging

### ISSUE THREAD

**Issue by Sargastic** [syslog-ng/syslog-ng#4597]
# syslog-ng
## Version of syslog-ng
4.2.0

## Platform
Gentoo Linux on a raspberry pi *32 bits* (I think this point is important)

# Issue
Switched to 4.2 on several computers, including 32-bit Raspberry Pis.
And the PID logging (whatever the log) is just... weird (two last lines). Loosk like an integer size problem :

```
Aug 20 11:08:26 start-stop-daemon[29517]: Will stop /usr/sbin/syslog-ng
Aug 20 11:08:26 start-stop-daemon[29517]: Will stop PID 1871
Aug 20 11:08:26 syslog-ng[1871]: syslog-ng shutting down; version='4.0.1'
Aug 20 11:08:26 start-stop-daemon[29517]: Sending signal 15 to PID 1871
Aug 20 11:08:27 syslog-ng[29557]: syslog-ng starting up; version='4.2.0'
Aug 20 11:08:27 syslog-ng[29557]: Syslog connection established; fd='17', server='AF_INET(192.168.XX:YY:514)', local='AF_INET(0.0.0.0:0)'
Aug 20 11:11:40 squid[295948544]: Squid Parent: squid-1 process 2166 exited with status 0
Aug 20 11:11:42 squid[295948544]: Squid Parent: will start 1 kids
```

PID logging  is okay on 64 bit kernels, as far as we checked.

## Steps to reproduce
Run syslog-ng 4.2 on a 32 bit kernel ?

**Comment by Sargastic** [comment]
Syslog-ng seems to log **itself** properly, though (last line) :

```
Aug 21 11:07:33 sshd[1530558720]: Accepted publickey for ...
Aug 21 11:07:33 sshd[1530558720]: pam_unix(sshd:session): session opened for user XXX(uid=NNN) by XXX(uid=NNN)
Aug 21 11:07:46 su[1530558720]: (to ZZZ) XXX on pts/0
Aug 21 11:07:46 su[1530558720]: pam_unix(su-l:session): session opened for user ZZZ(uid=NNN) by XXX(uid=NNN)
Aug 21 11:15:18 syslog-ng[15602]: Syslog connection established; fd='22', server='AF_INET(192.168.XXX.YYY:514)', local='AF_INET(0.0.0.0:0)'
```

**Comment by bazsi** [comment]
Hmm.. we are using SCM_CREDENTIALS to get the pid value, which is enabled by the so-passcred() option for unix-dgram() unix-stream() sources, which is on by default.

**Comment by bazsi** [comment]
All i am saying is you can disable this behaviour. Do you happen to know
the actual pid for a log message in the sample?

**Comment by Sargastic** [comment]
> All i am saying is you can disable this behaviour. Do you happen to know the actual pid for a log message in the sample?
> 

Sorry for the delay in answering, was out of the office for some days.

Not sure real pid numbers will be useful (but I can be utterly wrong) : it's the same number (here 3442392576) whatever the process (except for syslog-ng itself, where pid is correct) : 
```
Sep  1 04:05:21 start-stop-daemon[3442392576]: Will stop PID 1983
Sep  1 04:05:21 start-stop-daemon[3442392576]: Sending signal 1 to PID 1983
Sep  1 04:05:22 start-stop-daemon[3442392576]: Will stop PID 1874
Sep  1 04:05:22 start-stop-daemon[3442392576]: Sending signal 1 to PID 1874
Sep  1 04:05:22 syslog-ng[1874]: Reliable disk-buffer state loaded; filename='/var/log/syslog-buffer/syslog-ng-00000.rqf', number_of_messages='0'
Sep  1 04:05:22 syslog-ng[1874]: Reliable disk-buffer state loaded; filename='/var/log/syslog-buffer/syslog-ng-00000.rqf', number_of_messages='0'
Sep  1 04:05:22 syslog-ng[1874]: Configuration reload request received, reloading configuration;
Sep  1 04:05:22 syslog-ng[1874]: Configuration reload finished;
Sep  1 04:05:24 su[3442392576]: (to man) root on none
Sep  1 04:05:24 su[3442392576]: pam_unix(su:session): session opened for user man(uid=13) by (uid=0)
Sep  1 04:05:29 su[3442392576]: pam_unix(su:session): session closed for user man
Sep  1 05:01:01 su[3442392576]: (to logcheck) root on none
Sep  1 09:45:59 sshd[3442392576]: Accepted publickey for ...
Sep  1 09:45:59 sshd[3442392576]: pam_unix(sshd:session): session opened for user ...
Sep  1 09:46:17 su[3442392576]: (to root) XXX on pts/0
Sep  1 09:46:17 su[3442392576]: pam_unix(su-l:session): session opened for user ...
```
sshd are : 
```
# ps ax | grep sshd
 1395 ?        Ss     0:00 sshd: XXX [priv]
 1399 ?        S      0:00 sshd: XXX@pts/0
 1942 ?        Ss     0:00 sshd: /usr/sbin/sshd -o PidFile=/run/sshd.pid -f /etc/ssh/sshd_config [listener] 0 of 10-100 startups
```

And (current) su is : 
```
# ps ax | grep su
 1404 pts/0    S      0:00 su -
```

**Comment by MrAnno** [comment]
@Sargastic Does this problem go away with version syslog-ng v4.1.1?

(I've fixed a possible `CMSG_DATA` alignment issue in 4.2.0, I'm just wondering if that had anything to do with this issue.)

**Comment by Sargastic** [comment]
> @Sargastic Does this problem go away with syslog-ng v4.1.1?

**YES**

Just downgraded to 4.1.1-r2 (as per Gentoo naming) on one machine. No more weird pid logging : 

```
Sep  2 22:20:33 start-stop-daemon[3451287040]: Will stop /usr/sbin/syslog-ng
Sep  2 22:20:33 start-stop-daemon[3451287040]: Will stop PID 1791
Sep  2 22:20:33 start-stop-daemon[3451287040]: Sending signal 15 to PID 1791
Sep  2 22:20:33 syslog-ng[1791]: syslog-ng shutting down; version='4.2.0'
Sep  2 22:20:34 syslog-ng[8667]: syslog-ng starting up; version='4.1.1'
Sep  2 22:20:34 syslog-ng[8667]: Syslog connection established; fd='17', server='AF_INET(192.168.22.3:514)', local='AF_INET(0.0.0.0:0)'
Sep  2 22:25:01 crond[10967]: pam_unix(crond:session): session opened for user ...
Sep  2 22:25:01 CROND[10967]: pam_unix(crond:session): session closed for user ...

Sep  2 22:56:06 ntpd[1989]: DNS: dns_probe: ntp.xxx, cast_flags:8, flags:101
Sep  2 22:56:07 ntpd[1989]: DNS: dns_check: processing ntp.xxx, 8, 101
Sep  2 22:56:07 ntpd[1989]: DNS: Pool skipping: 192.168.yyy
Sep  2 22:56:07 ntpd[1989]: DNS: Pool skipping: 192.168.yyy
Sep  2 22:56:07 ntpd[1989]: DNS: dns_take_status: ntp.xxx=>good, 8

```

**Comment by MrAnno** [comment]
My guess would be 7f27334066c2a93ba93c05f8847be7ca8e16496c from #4441.
I'll take a deeper look soon.

**Comment by Sargastic** [comment]
> My guess would be [7f27334](https://github.com/syslog-ng/syslog-ng/commit/7f27334066c2a93ba93c05f8847be7ca8e16496c) from #4441. I'll take a deeper look soon.

If we may be helpful to test some patches, feel free to ask.

**Comment by Sargastic** [comment]
A small bit of data that could be useful : the bug appears on 5.X kernels, but **not** on 6.X kernels. We have one Raspberrypi 32 bit running kernel 6.1.21, and pids are properly logged.

**Comment by rtgill82** [comment]
I'm still getting invalid PIDs under kernel version 6.1.57 with syslog-ng versions >= 4.2 on 32-bit systems.

**Comment by MilanDadok** [comment]
same here (64bit kernel, 32bit user space, gentoo), 4.4.0

some strace output - recvmsg  have MSG_CTRUNC flag 

[pid  1321] <... recvmsg resumed>
	{msg_name=0xf5efcfcc, msg_namelen=128 => 0, 
		msg_iov=[{iov_base="<86>Dec 22 08:17:06 sshd[1318]: pam_unix(sshd:session): session opened for user root(uid=0) by root(uid=0)", iov_len=65536}], 
		msg_iovlen=1, 
		msg_control=[
			{cmsg_len=20, cmsg_level=SOL_SOCKET, cmsg_type=SO_TIMESTAMPNS_OLD, cmsg_data={tv_sec=1703229426, tv_nsec=630620156}}, 
			{cmsg_len=12, cmsg_level=SOL_SOCKET, cmsg_type=SCM_CREDENTIALS}], 
		msg_controllen=32, msg_flags=MSG_CTRUNC}, 0) = 106
[pid  1321] openat(AT_FDCWD, "/proc/1970995200/cmdline", O_RDONLY|O_LARGEFILE <unfinished ...>

after next patch
--- syslog-ng-4.4.0/modules/afsocket/transport-unix-socket.c.org        2023-12-22 08:36:53.403882931 +0100
+++ syslog-ng-4.4.0/modules/afsocket/transport-unix-socket.c    2023-12-22 08:37:43.578094163 +0100
@@ -219,7 +219,7 @@
   struct iovec iov[1];
   struct sockaddr_storage ss;
 #if defined(SYSLOG_NG_HAVE_CTRLBUF_IN_MSGHDR)
-  gchar ctlbuf[32];
+  gchar ctlbuf[CMSG_SPACE(32)];
   msg.msg_control = ctlbuf;
   msg.msg_controllen = sizeof(ctlbuf);
 #endif

recvmsg is not truncated and PID is correct again
Dec 22 08:52:10 gb sshd[7952]: pam_unix(sshd:session): session opened for user root(uid=0) by root(uid=0)

**Comment by bazsi** [comment]
Thanks a lot @MilanDadok, I've just opened a PR to fix this issue. It seems that we had a problem on 64 bits as well, but that was not that apparent, as on 64 bits the entire SCM_CREDENTIALS cmsg was outside of the control buffer.

I don't think CMSG_SPACE is the macro we need to use, we supply a buffer that should be large enough for all anciliary messages. CMSG_SPACE should be used when constructing a control message, it adds the header/alignment etc to the size of the payload. In our case, we are receiving cmsg and we just have to make sure that our buffer is large enough.

I've bumped it to 256 bytes, which should be plenty.

I also added a warning message if MSG_CTRUNC is set so this case can be detected in the future.

As an extra step, I've removed some code duplication.

**Comment by PyBonnetainNesterenko** [comment]
> Thanks a lot @MilanDadok, I've just opened a PR to fix this issue. It seems that we had a problem on 64 bits as well, but that was not that apparent, as on 64 bits the entire SCM_CREDENTIALS cmsg was outside of the control buffer.

As far as our tests go (on Pi3/arm/32 bits and X86/64 bits), this PR solves the problem. No adverse effect found.
Thanks !
