### ISSUE TITLE
Fetch uptime from host or convert SYSUPTIME to days hours minutes seconds

### ISSUE THREAD

**Issue by faisalchishtii** [syslog-ng/syslog-ng#4650]
# syslog-ng
## Version of syslog-ng
syslog-ng 3 (3.30.1)

## Platform
Containerised (Kubernetes). We are using syslog-ng in our Kubernetes cluster.

## Questions

- There is a requirement to have uptime printed along with our logs. We considered using $SYSUPTIME but it provides the time elapsed since the syslog-ng process started, which means if pod restarts this time will be reset. How can we fetch the uptime from the host if the logs do not have uptime information?

- If I want to convert $SYSUPTIME to days, hours, minutes seconds format. Is it possible to do so?

**Comment by alltilla** [comment]
Currently there is no way to get the system's uptime, but `sysinfo()` could be used to do so and we could create a macro with it. https://man7.org/linux/man-pages/man2/sysinfo.2.html

Converting seconds to days, hours, minutes and seconds can be done with template functions like `$(%)`, `$(-)`, ... See https://axoflow.com/docs/axosyslog-core/chapter-manipulating-messages/customizing-message-format/reference-template-functions/#template-function-numerical

**Comment by bazsi** [comment]
I think it should be easier to inject the appropriate value via an environment variable, something like this:

export HOST_UPTIME=`uptime | cut -c 2-9`

And in the syslog-ng config, a rewrite rule, such as:

set("`HOST_UPTIME`" value("HOST_UPTIME"));

then a macro named $HOST_UPTIME would be available on your logpath. Does this help?

**Comment by faisalchishtii** [comment]
@bazsi How do I ensure that HOST_UPTIME is upto date all the time?

**Comment by faisalchishtii** [comment]
@alltilla Is it possible to achieve via a custom script that can fetch uptime. or maybe just read /proc/uptime and update a field using some rewrite rule. Is this possible without syslog-ng needing any enhancements?

**Comment by alltilla** [comment]
You could add the SYSUPTIME macro's value to the host's uptime calculated at syslog-ng startup, as the SYSUPTIME macro gets updated runtime.

**Comment by bazsi** [comment]
Sorry, stupid me. You are right.

**Comment by faisalchishtii** [comment]
@alltilla Got it but how do I fetch the host's uptime from the syslog-ng pod?

**Comment by bazsi** [comment]
I started syslog-ng with this command line (e.g. exporting the host's uptime at the time of start):

$ HOSTUPTIME=`cut -d'.' -f1 /proc/uptime` sbin/syslog-ng  -Fef etc/syslog-ng-uptime.conf

And then I used this configuration:

```
@version: current

log {
        source { tcp(port(2000) flags(no-parse)); };

        rewrite { set("$(/ $(+ ${SYSUPTIME}0 `HOSTUPTIME`000) 1000)" value("TOTAL_UPTIME")); };
        rewrite { set("$(/ $TOTAL_UPTIME 3600):$(/ $(% $TOTAL_UPTIME 3600) 60):$(% $TOTAL_UPTIME 60)"); };

        destination { stdout(); };
};
```

The first rewrite rule sets $TOTAL_UPTIME to be the sum of $SYSUPTIME (the syslog-ng startup time) and $HOST_UPTIME (the environment variable which contains the host uptime at the time of syslog-ng start).

The 2nd rewite rule turns seconds into hours:mins:seconds

**Comment by bazsi** [comment]
While it would make sense to add a $HOSTUPTIME macro, I think the original issue is addressed already.

Closing this one, please file another one for the enhancement
