### ISSUE TITLE
GRPC modules on FreeBSD using GCC

### ISSUE THREAD

**Issue by czanik** [syslog-ng/syslog-ng#4653]
When I try to compile GRPC-based modules of syslog-ng 4.4.0 on FreeBSD 13.2 using GCC, compilation is actually successful, but loading the modules fails:
```
root@fb132:~/syslog-ng-grpc # syslog-ng -V
syslog-ng 4 (4.4.0)
Config version: 4.2
Installer-Version: 4.4.0
Revision: 
Compile-Date: Sep 29 2023 12:20:46
Module-Directory: /usr/local/lib/syslog-ng
Module-Path: /usr/local/lib/syslog-ng
Include-Path: /usr/local/share/syslog-ng/include
Error opening plugin module; module='loki', error='/usr/local/lib/libgrpc-protos.so.0: Undefined symbol "_ZNK6google8protobuf7Message11GetTypeNameB5cxx11Ev"'
Error opening plugin module; module='otel', error='/usr/local/lib/syslog-ng/libotel.so: Undefined symbol "_ZN6google8protobuf8internal26fixed_address_empty_stringB5cxx11E"'
Available-Modules: http,json-plugin,add-contextual-data,affile,afprog,afsocket,afstomp,afuser,appmodel,azure-auth-header,basicfuncs,cef,confgen,cryptofuncs,csvparser,correlation,disk-buffer,examples,graphite,hook-commands,kvformat,linux-kmsg-format,map-value-pairs,metrics-probe,pseudofile,regexp-parser,secure-logging,stardate,syslogformat,system-source,tags-parser,tfgetent,timestamp,xml,rate-limit-filter
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: off
Enable-TCP-Wrapper: off
Enable-Linux-Caps: off
Enable-Systemd: off
```

**Comment by bazsi** [comment]
This is either because your protoc compiler and the associated libs are not the same version OR some kind of ABI related change in gcc.

Let's try to  fix clang first, e.g. #4739

**Comment by bazsi** [comment]
To resolve this we would need to auto detect the c++ library for the system and include that check in configure.

**Comment by czanik** [comment]
It's not just a FreeBSD problem: MacOS and Gentoo Linux also use CLANG

**Comment by czanik** [comment]
If auto-detection is difficult, then linking with libstc++ could be default and a ```--with-clang``` or something similar could be used manually to use libc++ instead. Not nice, but still better than the current situation.

**Comment by HofiOne** [comment]
we dropped gcc support on BSD based OSes, clang must be used
