### ISSUE TITLE
How to use the Oracle sql driver?

### ISSUE THREAD

**Issue by Wernfried** [syslog-ng/syslog-ng#4687]
I try to sent my log messages to an Oracle database, however at startup it says:

    [2023-10-25T14:49:47.638825] No such DBI driver; type='oracle'

```
destination d_oracle {
   sql(
      type(oracle),
      database("TDHCP01"),
      username("RADIUS_HFC"),
      password("secret"),
      table("RADACCT_HFC_IPDATA"),
      columns("TS", "IP", "CLIENTMAC", "OPTION82", "SID", "LEASE_END"),
      values("${TS}", "${IP}", "${CLIENTMAC}", "${OPTION82}", "${SID}", "${LEASE_END}" ),
...
   );
};
```

Environment variables `ORACLE_HOME` and `LD_LIBRARY_PATH` are set.
I think the drivers are installed:

```
echo $ORACLE_HOME
/opt/app/oracle/product/12.1.0/client_1
echo $LD_LIBRARY_PATH
/opt/app/oracle/product/12.1.0/client_1/lib


# rpm -qa syslog-ng*
syslog-ng-4.4.0-1.el7.x86_64
syslog-ng-http-4.4.0-1.el7.x86_64
syslog-ng-sql-4.4.0-1.el7.x86_64
syslog-ng-smtp-4.4.0-1.el7.x86_64
syslog-ng-mongodb-4.4.0-1.el7.x86_64

# rpm -qa libdbi*
libdbi-0.9.0-19.el7.x86_64
libdbi-drivers-0.9.0-5.el7.x86_64
libdbi-dbd-sqlite-0.9.0-5.el7.x86_64

syslog-ng --version
syslog-ng 4 (4.4.0)
Config version: 4.2
Installer-Version: 4.4.0
Revision: 
Compile-Date: Sep 26 2023 06:22:47
Module-Directory: /usr/lib64/syslog-ng
Module-Path: /usr/lib64/syslog-ng
Include-Path: /usr/share/syslog-ng/include
Available-Modules: add-contextual-data,affile,afprog,afsocket,afstomp,afuser,appmodel,basicfuncs,cef,confgen,correlation,cryptofuncs,csvparser,disk-buffer,examples,graphite,hook-commands,json-plugin,kvformat,linux-kmsg-format,map-value-pairs,metrics-probe,pacctformat,pseudofile,rate-limit-filter,regexp-parser,sdjournal,stardate,syslogformat,system-source,tags-parser,tfgetent,timestamp,xml,afsql,afsmtp,azure-auth-header,http,afmongodb
```

It there a special `libdbi-dbd-oracle` driver? On Fedora I did not find any: https://copr.fedorainfracloud.org/coprs/czanik/syslog-ng43/build/6210454/

Built Packages:
    libdbi-dbd-mysql 0.9.0
    libdbi-dbd-pgsql 0.9.0
    libdbi-dbd-sqlite 0.9.0
    libdbi-drivers 0.9.0
    libdbi-drivers-debuginfo 0.9.0

On the same machine we also use Perl script to insert data into Oracle, so the Oracle drivers seems to be installed properly.

Do you have any help?
Wernfried

**Comment by czanik** [comment]
You are right, Oracle support is missing. The libdbi-drivers package needs to be compiled with Oracle support. However, that needs closed source Oracle libraries, and those are not allowed in Copr, the build service, where I compile my packages.

If you want, you can modify the libdbi-drivers package to support Oracle, but I cannot help in that (I do not have an Oracle environment).

Closing with "not planned".
