### ISSUE TITLE
Provide a json format for internal logging useful with container (standard out)

### ISSUE THREAD

**Issue by ryanfaircloth** [syslog-ng/syslog-ng#4693]
## Description of the problem
The current format is semi structured plain text it would be easier to handle the logs in json format

## Proposed solution
Provide a output format where MSG is json 

## Alternatives
No changes and continue as is

**Comment by bazsi** [comment]
For now I would create a separate "tracing" output that would describe how messages are changed in a structured format that could be sent to something like jaeger. But that would be a distinct functionality from internal logs. So I am closing this as not planned.
