### ISSUE TITLE
Stats counter underflow after `query get --reset`

### ISSUE THREAD

**Issue by HofiOne** [syslog-ng/syslog-ng#4696]
# Issue
## Failure
The customer reported odd numbers in the syslog-ng stat output regarding eps and queue counters.
The eps counter normalized after a couple of hours.

The queue size change is part of the eps calculation therefore, the high eps numbers should be the result of the queue counter underflow.

The customer observed this behavior is related to the command they executed:
`/opt/syslog-ng/sbin/syslog-ng-ctl query get  "dst.net*" --reset`

Reproduction showed the above command can reset the queue counter, while the `/opt/syslog-ng/sbin/syslog-ng-ctl stats --reset` command can not, the queue stat underflowed e.g. `1111111111111111111111111111111111111111111111111111101011100100`
Once the queue counter is reset it easily underflows and breaks other statistics like memory and eps.

## Steps to reproduce
Have a destination with a disk buffer and the buffer should not be empty.
Then execute /opt/syslog-ng/sbin/syslog-ng-ctl query get  "dst.net*" --reset
Make sure more messages are sent than received after the command is executed.

```
## Configuration
options {
    stats-level(1);
};

source s_net {
    network(transport(udp));
    network(transport(TCP));
    syslog();
};

destination d_destination {
        network(
                "172.16.0.13"
                port(514)
                transport(tcp)
                disk-buffer(
                    disk-buf-size(50000000)
                    reliable(no)
                )
        );
};

log {
    source(s_net);
    destination(d_destination);
};
```

## Input and output logs (if possible)

```
/opt/syslog-ng/sbin/syslog-ng-ctl query get  "dst.net*"  --reset
dst.network.d_fsc1_hrn_2#0.tcp,172.16.0.13:514.processed=15097
dst.network.d_fsc1_hrn_2#0.tcp,172.16.0.13:514.eps_since_start=0
dst.network.d_fsc1_hrn_2#0.tcp,172.16.0.13:514.eps_last_1h=0
dst.network.d_fsc1_hrn_2#0.tcp,172.16.0.13:514.memory_usage=18446744073709433816
dst.network.d_fsc1_hrn_2#0.tcp,172.16.0.13:514.truncated_count=0
dst.network.d_fsc1_hrn_2#0.tcp,172.16.0.13:514.queued=18446744073709533332
dst.network.d_fsc1_hrn_2#0.tcp,172.16.0.13:514.dropped=0
dst.network.d_fsc1_hrn_2#0.tcp,172.16.0.13:514.msg_size_avg=252
dst.network.d_fsc1_hrn_2#0.tcp,172.16.0.13:514.eps_last_24h=0
dst.network.d_fsc1_hrn_2#0.tcp,172.16.0.13:514.msg_size_max=252
dst.network.d_fsc1_hrn_2#0.tcp,172.16.0.13:514.truncated_bytes=0
dst.network.d_fsc1_hrn_2#0.tcp,172.16.0.13:514.written=33381
```
or
```
dst.network.d_dllslgdgr1#0.tcp,100.82.52.15:514.dropped=0
dst.network.d_dllslgdgr1#0.tcp,100.82.52.15:514.eps_last_1h=5124095576025735
dst.network.d_dllslgdgr1#0.tcp,100.82.52.15:514.processed=64016
dst.network.d_dllslgdgr1#0.tcp,100.82.52.15:514.queued=26495
dst.network.d_dllslgdgr1#0.tcp,100.82.52.15:514.written=37521
dst.network.d_dllslgdgr2#0.tcp,100.82.52.16:514.dropped=0
dst.network.d_dllslgdgr2#0.tcp,100.82.52.16:514.eps_last_1h=5124095576026121
dst.network.d_dllslgdgr2#0.tcp,100.82.52.16:514.processed=63622
dst.network.d_dllslgdgr2#0.tcp,100.82.52.16:514.queued=228
dst.network.d_dllslgdgr2#0.tcp,100.82.52.16:514.written=63387
```

**Comment by bazsi** [comment]
This seems to be the documented behaviour. 

https://www.syslog-ng.com/technical-documents/doc/syslog-ng-open-source-edition/3.36/administration-guide/111

So query --reset would reset all counters that are queried. The others excludes queued counters.

I don't see an easy fix that wouldn't break the documentation as well. The same exclusion of the queued counter could work in the query get case but that's a change in behaviour (although probably for the better).
