### ISSUE TITLE
systemd-journal() namespace() possible problem

### ISSUE THREAD

**Issue by czanik** [syslog-ng/syslog-ng#4704]
Maybe it's not a bug, but a question of interpretation. The 4.4.0 release notes says:
```
Using multiple systemd-journal() sources are now possible as long as each source uses a unique
systemd namespace. The namespace can be configured with the namespace() option, which has a
default value of "*".
```
And the following config throws an error:
```
czplaptop:/etc/syslog-ng/conf.d # cat journal.conf
source s_mynamespace {systemd-journal(namespace(mynamespace));};
destination d_mynamespace {file("/var/log/mynamespace");};
log {source(s_mynamespace); destination(d_mynamespace);};

source s_yournamespace {systemd-journal(namespace(mynamespace));};
destination d_yournamespace {file("/var/log/yournamespace");};
log {source(s_yournamespace); destination(d_yournamespace);};

source s_defnamespace {systemd-journal(namespace(""));};
destination d_defnamespace {file("/var/log/defnamespace");};
log {source(s_defnamespace); destination(d_defnamespace);};
```
It is:
```
czplaptop:/etc/syslog-ng/conf.d # syslog-ng -F
[2023-11-06T15:12:10.713801] systemd-journal namespace already in use; namespace='mynamespace'
[2023-11-06T15:12:10.713846] The configuration must not contain more than one systemd-journal() source with the same namespace() option;
[2023-11-06T15:12:10.713856] Error initializing journal_reader;
[2023-11-06T15:12:10.713890] Error initializing message pipeline; plugin_name='systemd-journal', location='/etc/syslog-ng/conf.d/journal.conf:5:25'
```
But if I remove the offending entries from the configuration and instead of that I enable the system() source, there is no error. Even if that has systemd-journal(namespace("*")), which includes both the default namespace and the namespace ```mynamespace```. So, it's unique by name, but not unique by content.

**Comment by bazsi** [comment]
The reason we have been limited to one systemd-source() instance in the past is that we need to keep track on where we in the journal. This position information (also called our bookmark) is saved into our syslog-ng.persist file with a unique identifier (also called the persist name).

Each of the source drivers needing bookmarking has to have a unique persist name.

Usually we include a key configuration element in the persist name, such as the bind port or IP address.

In the case of the journal source, there's no driver option that would make it unique, thus the number of instances were limited to one. (just a side note is that we have recently added making it possible to specify the persist-name() to various drivers but interestingly, systemd-journal() is not one of them).

The namespace option is added to the persist-name, causing them to be unique and allowing multiple systemd-journal() instances to co-exist.

There's no inherent limitation in the driver why it could not work in multiple instances though. If we added persist-name() support you could fire up any number of journal sources which would emit the same set of records and would have a separate position in syslog-ng.persist.

So albeit it would have been great if we added persist-name() support the last time, I think the current behaviour works as intended.
