### ISSUE TITLE
Enable TLS 1.3 support for MQTT communications

### ISSUE THREAD

**Issue by techpavan** [syslog-ng/syslog-ng#4734]
## Description of the problem

Some security focused environments might need to strictly limit the communication protocols to their choice - say TLS 1.3 in few cases and TLS 1.2 in others where regulatory compliance are mandated.

Currently, when tried with tls configuration by configuring _ssl-options_ - it looked to be an unsupported option. Though _ssl-version_ was supported, it did not accept _tlsv1_3_, it just works till _tlsv1_2_.

## Proposed solution
Add support for _tlsv1_3_ for _ssl-version_

## Additional context
**Our setup:** Syslog-ng process running locally accepting multiple sources like UDP, file system and having destination MQTT remote syslog server. The communication with remote MQTT server is authenticated with mutual TLS.

We are using v4.3.1, but seems like even 4.5.0 too does not support TLS 1.3: https://github.com/syslog-ng/syslog-ng/blob/59fcb8191821cb406532a172fcfa183099effcb0/modules/mqtt/mqtt-options.c#L190

**Comment by alltilla** [comment]
Hello @techpavan!

Thanks for the enhancement idea.

We are using the paho.mqtt.c lib to send and receive mqtt messages. Unfortunately it does not yet support TLS 1.3.

* https://github.com/eclipse/paho.mqtt.c/blob/master/src/MQTTClient.h#L654
* https://github.com/eclipse/paho.mqtt.c/issues/1058
* https://github.com/eclipse/paho.mqtt.c/pull/430

When it receives TLS 1.3 support, we will follow it up in syslog-ng, too.

**Comment by techpavan** [comment]
Hi @alltilla , Thanks for the update. This seems to be running since long on Paho. Hope it will get picked up soon as TLS 1.3 is gaining more traction.

**Comment by alltilla** [comment]
Closing this issue as we are blocked by paho.mqtt.c. We will try to follow-up their changes if/when TLS 1.3 gets added, but if we miss it, feel free to reopen this issue. Thanks!
