### ISSUE TITLE
symlink-as does not relink when the filename changes 

### ISSUE THREAD

**Issue by FenderDOOD** [syslog-ng/syslog-ng#4738]
# syslog-ng
## Version of syslog-ng
3.38 all the way to 4.5

## Platform
OracleLinux-7.9 and AlmaLinux-9.3

## Debug bundle
Not Included for security/privacy reasons.

# Issue
## BUG
Our syslog-ng system is setup to swap out the output file every 6 minutes (1 hour / 10). We wanted a link called 'current' to point to the file currently being written.  However, when the new file is opened, the link is not moved to the new file. Also I if delete the 'current' link, the link will be recreated when syslog-ng opens the new file. It seems to me that there may be a missing 'force' for the symlink command call?   

The relevant config lines are:
<pre>
destination d_my_output_file { file(
    "/var/log/${LOGHOST}_${C_YEAR}-${C_MONTH}-${C_DAY}-${C_HOUR}_$(/ ${C_MIN} 6).events"
    symlink-as("/var/log/current")
    template("'${LOGHOST}','${HOST}','<${TAG}>${S_DATE} ${HOST} ${MSGHDR}${MSG}'\n") template-escape(no)
    # template("'${LOGHOST}','${HOST}','${RAWMSG}'\n") template-escape(no)
    owner("my_user")
    group("my_user")
    perm(0644)
    create-dirs(yes)
    flags("no-multi-line")
); };

log { source(s_remote_tcp);      destination(d_my_output_file); };
</pre>

## Steps to reproduce
I have tested the same configuration on syslog-ng version 3.38 to 4.5 on both AlmaLinux9 and Oracle Linux, both of which had SELinux turned of to be sure it was not causing issues with syslog-ng.

**Comment by bazsi** [comment]
I tested this use-case with the configuration below:

```
@version: current

log {
	source { tcp(port(2000)); };

	destination { file("file.$MIN" symlink-as("current")); };
};
```

And it does seem to work:

```
[2023-12-02T11:45:00.403780] Initializing destination file writer; template='file.$MIN', filename='file.45', symlink_as='current'
[2023-12-02T11:45:00.404001] affile_open_file; path='file.45', fd='16'
[2023-12-02T11:45:00.404021] file_opener_symlink; filename='current', target='file.45'
[2023-12-02T11:45:00.404133] Creating symlink; filename='current', target='file.45'

```

It'd be great if the symlink was updated via rename() (e.g. mv command) as that would not leave a small window where the symlink does not exist, but that should not be a huge issue, at least depending on how you use that symlink.

**Comment by FenderDOOD** [comment]
Apologies for taking so long to test and respond.  

Thanks for getting to this so quickly.  I appreciate your time and attention.

I used your config and it worked. So then I added line by line of my config until it broke. The breaking lines, which I added together  are:

```
    owner("my_user")
    group("my_user")
```

It appears that the root user (syslog-ng runs as root), is not allowed to delete the symlink owned by 'my_user'. I'm not sure that this is expected or desired behavior. But now I'm not sure it's a syslog-ng thing.  The file must be owned by 'my_user' since 'my_user' performs file operations on the output later, and we don't want other non-privileged accounts to be able to write or delete these files.  Do you have any suggestions?

Thanks again for your time.

**Comment by bazsi** [comment]
Ok this might be a capability issue. Syslog-ng manages capabilities so that it's not running as full root. This means that normally we restrict ourselves to minimal caps and only enable them as needed.

You can disable this using the --no-caps command line option, which may fix your issue.

The other cause might be selinux or a similar LSM.

**Comment by FenderDOOD** [comment]
Thank for that... I'll try that and reply back when I can.
