### ISSUE TITLE
Why is the data not in order when sent to Kafka

### ISSUE THREAD

**Issue by Designxiaozai** [syslog-ng/syslog-ng#4740]
Why is the data not in order when sent to Kafka
May I ask if there are any relevant parameters that can be set
I have tried various versions of syslog-ng, but there are no relevant parameters

**Comment by bazsi** [comment]
Kafka doesn't ensure ordering, especially between partitions. To put messages into partitions you will need to specify a key() to the Kafka destination.

The c implementation of the Kafka destination is recommended, more information is here:

https://axoflow.com/docs/axosyslog-core/chapter-destinations/configuring-destinations-kafka-c/

**Comment by Designxiaozai** [comment]
thank you
