### ISSUE TITLE
Mutliarchitecture container build

### ISSUE THREAD

**Issue by MarkusGnigler** [syslog-ng/syslog-ng#4758]
## Description of the problem
Is it possible to add a buildstep for building multiarchitecture container images?

## Proposed solution
I think there is only a setup step of buildx missing in the `.github/workflows/publish-docker-image.yml`.

```
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
```

If desired, i can create a pr.

Thank you

**Comment by bazsi** [comment]
We started separating containers and helm charts into a separate repo, where multiarch is already enabled:

https://github.com/axoflow/axosyslog

It's also alpine based and has a number enhancements over the one in the syslog-ng repo, plus helm charts for kubernetes.

The upstream container image and helm charts have always been somewhat of an afterthought.

**Comment by MarkusGnigler** [comment]
Thanks a lot for the hint in the right direction.

Is it somewhere documented?
