### ISSUE TITLE
How many ports can syslog ng support at most

### ISSUE THREAD

**Issue by kslz** [syslog-ng/syslog-ng#4762]
Is there a limit on the number of configured ports for syslog ng?

**Comment by bazsi** [comment]
There's no inherent limit, I'd think give enough RAM it could open all of the ports that are still available on your system.

Or did you mean the number of parallel connections?

**Comment by kslz** [comment]
> There's no inherent limit, I'd think give enough RAM it could open all of the ports that are still available on your system.
> 
> Or did you mean the number of parallel connections?

thank you that's all I need
