### ISSUE TITLE
syslog-ng kafka example format on site not working with 4.3

### ISSUE THREAD

**Issue by mx3338** [syslog-ng/syslog-ng#4769]
Hello all!

I pulled this example for using kafka from here (https://support.oneidentity.com/technical-documents/syslog-ng-open-source-edition/3.38/administration-guide/42#TOPIC-2026281)

attempting to validate the syntax leaves me with this error
Error parsing config, syntax error, unexpected LL_IDENTIFIER, expecting '}' in /usr/share/syslog-ng/include/scl/kafka/kafka.conf:25:5-25:12:
20      #
21      #############################################################################
22      
23      @define kafka-implementation kafka-java
24      block destination kafka(...) {
25---->     `kafka-implementation`(`__VARARGS__`);
25---->     ^^^^^^^
26      };

Included from /etc/syslog-ng/syslog-ng.conf:33:3-33:79:
28          internal();
29          # udp(ip(0.0.0.0) port(514));
30      };
31      
32      destination d_kafka {
33---->   kafka(bootstrap-servers("1.2.3.4:9092,192.168.0.2:9092") topic("{MYTOPIC}"));
33---->   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
34      };

considering it was copied from the site as a test to make i wasn't missing something, i'm a little confused as to why this wouldn't work. Am i missing something?

**Comment by bazsi** [comment]
As a workaround, try using kafka-c instead of simply kafka.

Or add a 

`@define kafka-implementation katka-c`

To your config. I think the issue is is that we default to the old java based implementation which is not available in your build. The c based is better anyway.
