### ISSUE TITLE
bump lib/ivykis to v0.43

### ISSUE THREAD

**Issue by ThomasDevoogdt** [syslog-ng/syslog-ng#4801]
Hi,

The [ivykis](https://github.com/buytenh/ivykis) lib made a release yesterday: [v0.43](https://github.com/buytenh/ivykis/releases/tag/v0.43).
A compile fix is carried along in [this](https://github.com/buildroot/buildroot/blob/master/package/syslog-ng/0001-fix-build-on-uclibc.patch) buildroot patch.

Is it possible to sync the bazsi [fork](https://github.com/bazsi/ivykis) and bump it in syslog-ng?

In theory, I could do it myself but I think that reviewing the fork sync PR and another PR here would take as much time from your side as just doing it yourself. This issue can for my sake be closed immediately.

Thx in advance,

Thomas

**Comment by bazsi** [comment]
Hi,

I already opened a PR to go back to ivykis upstream.

https://github.com/syslog-ng/syslog-ng/pull/4798

Once that's merged the reference to the bazsi fork will be gone.

**Comment by czanik** [comment]
Just packaged ivykis 0.43 for Fedora / RHEL. I did a few tests: syslog-ng compiled with 0.42.4 worked fine with 0.43, and syslog-ng compiled with 0.43 also seems to work OK. No full tests suite, just some manual tests on Fedora 39.

**Comment by ThomasDevoogdt** [comment]
Thx for the bump!
