### ISSUE TITLE
mqtt: need support a wildcards and a mechanism to recognize the topic from which the message was received

### ISSUE THREAD

**Issue by JedaiRussia** [syslog-ng/syslog-ng#4818]
## Description of the problem
In the current implementation of the mqtt module, it is not possible to subscribe to topics using MQTT Wildcards `($, +, #)`. The mechanism for receiving messages from the MQTT broker does not indicate the topic from which the message was received. Using MQTT Wildcards and getting the name of the topic, it will be possible to fully use the MQTT broker as a source.

## Proposed solution
1. Implement the ability to subscribe to topics using MQTT Wildcards. 
2.  Add an option to the mqtt source that controls the ability to attach the topic name to the text of the received message, or alternatively generate JSON with the keys "topic" and "message" when receiving a message.

**Comment by bazsi** [comment]
I think with #4824 you'd be able to do this by subscribing to the '#' topic and using the new $MQTT_TOPIC name-value pair to query the actual topic where the message was received from.

**Comment by alltilla** [comment]
Tested #4824:

```
@version: 4.6

log {
  source { mqtt(topic("#")); };
  destination { stdout(template("$MQTT_TOPIC - $MESSAGE\n")); };
};
```

```
mosquitto_pub -h localhost -t my-topic -m my-message
```

```
./sbin/syslog-ng -Fe
[2024-02-12T13:40:01.168262] syslog-ng starting up; version='4.6.0.83.gf6eae6f.dirty'
my-topic - my-message
my-topic - my-message
my-topic - my-message
```
