### ISSUE TITLE
default-network-drivers() is not getting fortigate logs hostname ($HOST) correctly

### ISSUE THREAD

**Issue by pwnjack** [syslog-ng/syslog-ng#4867]
# syslog-ng
## Version of syslog-ng
syslog-ng 4 (4.6.0)
Config version: 4.2
Installer-Version: 4.6.0
Revision:
Compile-Date: Jan 26 2024 09:03:13
Module-Directory: /usr/lib64/syslog-ng
Module-Path: /usr/lib64/syslog-ng
Include-Path: /usr/share/syslog-ng/include
Available-Modules: add-contextual-data,affile,afprog,afsocket,afstomp,afuser,appmodel,basicfuncs,cef,confgen,correlation,cryptofuncs,csvparser,disk-buffer,examples,graphite,hook-commands,json-plugin,kvformat,linux-kmsg-format,map-value-pairs,metrics-probe,pacctformat,pseudofile,rate-limit-filter,regexp-parser,sdjournal,stardate,syslogformat,system-source,tags-parser,tfgetent,timestamp,xml

## Platform
NAME="Red Hat Enterprise Linux"
VERSION="8.9 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.9"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.9 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8::baseos"

# Issue
## Failure
When using the $HOST macro to write the filename its failing to parse properly the "devname=HOSTNAME1" field and using the network host actually sending the logs instead.

## Steps to reproduce

    cat fortigate_log.txt | nc -4 -n -v 127.0.0.1 514

    ls -l /var/log/sources
    -rw-r-----. 1 root root 27989 Mar 22 10:50 localhost.log

It should be:

    -rw-r-----. 1 root root 27989 Mar 22 10:50 HOSTNAME1.log

## Configuration
        @version: 4.2
        @include "scl.conf"
        
        source s_network {
            default-network-drivers(
                flags(no-parse, store-raw-message)
            );
        };
        
        destination d_destination {
            file(
                "/var/log/sources/${HOST}.log"
                template("${RAWMSG}\n")
                create_dirs(yes)
            );
        };
        
        log {
            source(s_network);
            destination(d_destination);
        };

## Input and output logs (if possible)

    <189>date=2024-03-20 time=17:03:13 devname="HOSTNAME1" devid="REDACTED" eventtime=1710950593069066435 tz="+0100" logid="0000000015" type="traffic" subtype="forward" level="notice" vd="root" srcip=REDACTED srcport=36892 srcintf="gen2" srcintfrole="undefined" dstip=REDACTED dstport=443 dstintf="gen2" dstintfrole="undefined" srccountry="Reserved" dstcountry="Germany" sessionid=145154130 proto=6 action="start" policyid=10 policytype="policy" poluuid="REDACTED" policyname="REDACTED" service="HTTPS" trandisp="noop" duration=0 sentbyte=0 rcvdbyte=0 sentpkt=0 rcvdpkt=0 appcat="unscanned"

I noticed it works well with other log formats like PaloAlto etc. Am I missing something here or is this normal?

Thanks in advance for helping.

**Comment by bazsi** [comment]
the default-network-drivers() source uses so called application adapters that help syslog-ng parse non-standard formats. 

The one for Fortigate is here: https://github.com/syslog-ng/syslog-ng/blob/master/scl/fortigate/fortigate.conf

As I see, it does not override $HOST at the moment, so it stays the syslog-ng default, e.g. the one resolved from the sending IP address.

This PR has an untested fix for this case: https://github.com/syslog-ng/syslog-ng/pull/4884

can you check if it works and report back? thanks

**Comment by bazsi** [comment]
I quickly tested this and it works nicely.

**Comment by bazsi** [comment]
@pwnj

**Comment by pwnjack** [comment]
> @pwnjack indeed the FortiGate documentation does not mention devname, how come your fortigate does have that? is this a specific configuration?

Not entirely sure why, maybe is tied to the Fortinet version, but you can see it mentioned in this [manual](https://fortinetweb.s3.amazonaws.com/docs.fortinet.com/v2/attachments/4a9d18e2-e112-11ec-bb32-fa163e15d75b/FortiOS_7.0.6_Log_Reference.pdf) (page 80).
