### ISSUE TITLE
Syslog-ng stops writing logs to a file from a custom systemd-journald namespace after a server restart

### ISSUE THREAD

**Issue by kastakhov** [syslog-ng/syslog-ng#4917]
# syslog-ng
## Version of syslog-ng
Tested with:
syslog-ng 3.30.1
syslog-ng 4.3.1
syslog-ng 4.7.1 (with separated journald source for custom namespace)

## Platform
Ubuntu Focal (20.04)

```shell
kastakhov@devvm-14-79:~$ systemd --version
systemd 245 (245.4-4ubuntu3.22)
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid

kastakhov@devvm-14-79:~$ syslog-ng --version
syslog-ng 4 (4.7.1)
Config version: 4.2
Installer-Version: 4.7.1
Revision: 4.7.1-1test0
Compile-Date: Apr 22 2024 14:37:08
Module-Directory: /usr/lib/syslog-ng/4.7
Module-Path: /usr/lib/syslog-ng/4.7
Include-Path: /usr/share/syslog-ng/include
Available-Modules: azure-auth-header,http,afsql,afsnmp,secure-logging,kafka,afmongodb,affile,afprog,afsocket,afuser,appmodel,basicfuncs,cef,confgen,cryptofuncs,csvparser,disk-buffer,hook-commands,json-plugin,kvformat,linux-kmsg-format,map-value-pairs,pacctformat,pseudofile,rate-limit-filter,regexp-parser,sdjournal,syslogformat,system-source,tags-parser,tfgetent,timestamp
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: on
Enable-TCP-Wrapper: on
Enable-Linux-Caps: on
Enable-Systemd: on
```

# Issue

Syslog-ng stops writing logs to a file from a custom systemd-journald namespace after a server restart and starts writing them again only after the syslog-ng service is restarted.

Logs from default namespace are written into a file without an issue.

## Steps to reproduce

With the next steps are valid for syslog-ng 4.7.1. But should work for another versions as well (with small adjustment in filter and log blocks).

1. Create simple script for printing logs (i.e. /root/test_script.sh) with following content:

```shell
#!/usr/bin/env bash

x=1
echo "PID is $$"
while true
do
    echo "$(date) x is ${x}"
    x=$(( x + 1 ))
    sleep 1
done
```

2. Make it executable

```shell
chmod +x /root/test_script.sh
```

3. Create custom journald namespace (i.e. /etc/systemd/journald@test.conf):

```ini
[Journal]
Storage=volatile
ForwardToSyslog=yes
ForwardToWall=no
ReadKMsg=no
SystemMaxUse=256M
RuntimeMaxUse=256M
```

4. Create new systemd service (i.e. /usr/lib/systemd/system/test-syslog-ng.service):

```ini
[Unit]
Description=Test systemd unit with custom namespace
After=syslog-ng.service

[Service]
Type=simple
ExecStart=/root/test_script.sh

LogExtraFields=UNIT=%n
LogNamespace=test

[Install]
WantedBy=multi-user.target
```

5. Update syslog config and restart the syslog-ng service.
6. Enable and start the systemd unit.

```shell
systemctl enable --now  test-syslog-ng.service
```

7. Verify logs are going into log file:

```shell
cat /var/log/test-syslog-ng.service.log
```

9. Reboot the server.

10. Verify that the logs are not present in /var/log/test-syslog-ng.service.log, but present in service status.

```shell
systemctl status test-syslog-ng.service
tail -f /var/log/test-syslog-ng.service.log
```

11. Restart syslog-ng service and repeat step 10. Now logs are being written into log file.

## Configuration
Tested on original ubuntu/debian syslog-ng config file with adding the next code block into config file.

```
source s_journald_test {
    systemd-journal(
        namespace("test")
        prefix("journald.test.")
        match-boot(yes)
    );
};

filter f_test_services {
    match("^test.*.service$", value("journald.test.UNIT"));
};

destination d_test_services {
    file(
        "/var/log/${journald.test.UNIT}.log"
        owner("root")
        group("users")
        perm(0644)
    );
};

log {
    source(s_journald_test);
    filter(f_test_services);
    destination(d_test_services);
};
```

**Comment by kastakhov** [comment]
Have no idea what happened, but now I cannot reproduce it even with steps above...
Will open new one in case I'll find a stable way for reproducing.

**Comment by bazsi** [comment]
thanks @kastakhov
