### ISSUE TITLE
Unexpected behavior with multiple conditions including 'not' in the filter

### ISSUE THREAD

**Issue by qsunchiu** [syslog-ng/syslog-ng#4980]
# syslog-ng
## Version of syslog-ng
syslog-ng 4 (4.7.0)
Config version: 4.2
Installer-Version: 4.7.0.591.g7685b4c.dirty
Revision: 
Module-Directory: /usr/lib/syslog-ng
Module-Path: /usr/lib/syslog-ng
Include-Path: /usr/share/syslog-ng/include
Available-Modules: add-contextual-data,azure-auth-header,cryptofuncs,metrics-probe,timestamp,csvparser,system-source,examples,affile,map-value-pairs,basicfuncs,json-plugin,syslogformat,confgen,stardate,cef,appmodel,rate-limit-filter,afsocket,xml,tags-parser,linux-kmsg-format,secure-logging,afsql,afprog,disk-buffer,regexp-parser,hook-commands,correlation,tfgetent,cloud_auth,pseudofile,kvformat,graphite,sdjournal,afuser,http
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: off
Enable-TCP-Wrapper: off
Enable-Linux-Caps: on
Enable-Systemd: on

## Platform
Ubuntu 20.04

## Debug bundle
N/A

# Issue
## Failure
There is an unexpected behavior when using multiple conditions in a filter, particularly when one of the conditions includes a "not" statement. For example, consider the following filter configuration:
```
filter f_filter {
    not facility(auth);
    program(xxx);
};
```

The original intended behavior, as described in commit [d468efc463ceb0a8117fe18d789361f6c3ce7724](https://github.com/syslog-ng/syslog-ng/commit/d468efc463ceb0a8117fe18d789361f6c3ce7724), is that the conditions should be combined using an AND operation. The expected configuration should be functionally equivalent to:
```
filter f_filter {
    not facility(auth) and program(xxx);
};
```
However, the current behavior seems that the conditions are combined using an OR operation, which results in incorrect filtering. The filter behaves as if it is equivalent to:
```
filter f_filter {
    not facility(auth) or program(xxx);
};
```

This issue seems to have been introduced by commit [6d74e60c4b2b51e9842ccab23902803b9ff8de2b](https://github.com/syslog-ng/syslog-ng/commit/6d74e60c4b2b51e9842ccab23902803b9ff8de2b). In this commit, the 'not' keyword was moved from lib/filter/filter-expr-grammar.ym to lib/cfg-grammar.y. However, the semicolon (';') was not moved accordingly. Previously, the semicolon's precedence was higher than 'not', but after the change, the precedence of the semicolon is now lower than 'not', resulting in this unexpected behavior.

## Configuration
@Version: 4.2

source src {
    systemd-journal(prefix(".SDATA.journald."));
    internal();
};

filter f_filter {
    not facility(auth);
    program(xxx);
};

destination d_destination {
    file("/var/log/xxx.log");
};

log {
    source(src);
    filter(f_filter);
    destination(d_destination);
};

**Comment by MrAnno** [comment]
Hi @qsunchiu,

Thank you for the excellent bug report. You are absolutely right. We've fixed the precedence of ';', it should be the same as before:

https://github.com/axoflow/axosyslog/pull/122

Please note that we work in the [AxoSyslog](https://github.com/axoflow/axosyslog) repo from now on, we don't know whether the bugfix will be backported to the syslog-ng repo.

If you need Debian packages to test the fix, please let us know.

**Comment by qsunchiu** [comment]
Thank you for fixing it. Testing it in Ubuntu 20.04 is not necessarily for me. However, is there any possibility that the fix will be ported back to the syslog-ng repo in a future release, such as version 4.8 or later?

**Comment by bazsi** [comment]
we plan to release 4.8 of axosyslog in around a month, where this was merged already.

there was a fork between axosyslog and syslog-ng recently, thus those who produced the last 6-7 releases have  stopped producing syslog-ng releases and will be doing the same under the axosyslog umbrella instead. see https://axoflow.com/axosyslog-syslog-ng-fork/

wthether a fix will be picked up by the syslog-ng project and when a release will be produced I don't know.

Hope this helps.

**Comment by czanik** [comment]
Yes, we plan to fix it in the next syslog-ng release.

**Comment by qsunchiu** [comment]
Thank you for planning to address this in the next syslog-ng release. I appreciate your response and look forward to the update.
