### ISSUE TITLE
Config failing with kafka and template

### ISSUE THREAD

**Issue by mockthebear** [syslog-ng/syslog-ng#4984]
# syslog-ng
## Version of syslog-ng
syslog-ng-4.5.0-1.el9.x86_64
syslog-ng-kafka-4.5.0-1.el9.x86_64

## Platform
Oracle Linux Server release 9.3

## Debug bundle

$ syslog-ng -s -d
syslog-ng: The -d/--debug option no longer implies -e/--stderr, if you want to redirect internal() source to stderr please also include -e/--stderr option
Error parsing within destination, syntax error, unexpected KW_TEMPLATE in /usr/share/syslog-ng/include/scl/kafka/kafka.conf:25:37-25:45:
20      #
21      #############################################################################
22      
23      @define kafka-implementation kafka-java
24      block destination kafka(...) {
25---->     `kafka-implementation`(`__VARARGS__`);
25---->                                     ^^^^^^^^
26      };

Included from /etc/syslog-ng/conf.d/syslog-kafka.conf:56:3-60:4:
51        );
52      };
53      
54      destination d_csv_redpanda {
55      
56---->   kafka(
56---->   ^^^^^^^
57----> 	bootstrap-servers("gpd-redpanda1:9092")
58----> 	topic("access-log-stg")
59----> 	template(template_csv_format)
60---->   );
61      };

Included from /etc/syslog-ng/syslog-ng.conf:68:1-68:1:
63      #log { source(s_sys); filter(f_cron); destination(d_cron); };
64      
65      
66      # Source additional configuration files (.conf extension only)
67      @include "/etc/syslog-ng/conf.d/*.conf"
68----> 
68----> ^
69      
70      # vim:ft=syslog-ng:ai:si:ts=4:sw=4:et:

# Issue
## Steps to reproduce
Including the `template` in to the destiation with kafka breaks everything.
It works if using like, network or unix-stream

## Configuration
```
source remote514_default
{   
    tcp( port(514) so_keepalive(yes) max-connections(1000) so_rcvbuf(16777216) log_fetch_limit(200) log_iw_size(200) );
};

template template_csv_format {
    template("\"${YEAR}-${MONTH}-${DAY} ${HOUR}:${MIN}:${SEC}-03:00\",\"${HOST}\",${MSG}\n");
    template_escape(no);
};

filter f_csv_nginx_access {
    program("^nginx_data$");
};

log {
	source(remote514_default);
    filter(f_csv_nginx_access);
	destination(d_csv);
	flags(flow-control);
};


@define kafka-implementation kafka-c


destination d_csv {

  kafka(
    bootstrap-servers("gpd-redpanda1:9092")
    topic("access-log-stg")
    template(template_csv_format)
  );
};
```

**Comment by HofiOne** [comment]
Hi,
In the kafka-c version the `template()` option has been renamed to `message()`

https://syslog-ng.github.io/admin-guide/070_Destinations/100_Kafka-c/000_Shifting_from_Java_to_C

Please give it a try with that one.

**Comment by mockthebear** [comment]
Oh thank you. I wasn't aware of that documentation o github.io
I was following this one:
https://www.syslog-ng.com/technical-documents/doc/syslog-ng-open-source-edition/3.21/administration-guide/39#TOPIC-1197830

**Comment by HofiOne** [comment]
nop, hopefully, that outdated version will be updated in the near future as well
