### ISSUE TITLE
Is loki destination actually implemented?

### ISSUE THREAD

**Issue by AliMoeen** [syslog-ng/syslog-ng#5017]
I am trying to create a loki destination, explained here:

https://syslog-ng.github.io/admin-guide/070_Destinations/125_Loki/README#example-loki-destination-configuration

I used it in a config file like this:

```
@version: 4.7


source s_network {
    network();
    network(transport(udp));
};

destination d_tmplog {
    file("/tmplog/$YEAR$MONTH$DAY$HOUR-$MIN-$HOST.log");
    stdout();
};

destination d_loki {
	loki(
		url("v145:3100")
		labels(
			"forwarder" => "syslog-ng"
			"app" => "$PROGRAM",
			"host" => "$HOST",
		)

		workers(16)
		batch-timeout(10000)
		batch-lines(1000)
	);
}

log {
    source(s_network);
    destination(d_tmplog);
    destination(d_docker);
	destination(d_loki);
};

log {
	source {
		system();
		internal();
	};
	destination {
		file("/tmplog/internal/$YEAR$MONTH$DAY$HOUR-$MIN-$HOST.log");
	}
};

options { 
	create-dirs();
};

```

However, `syslog-ng` gives me this error:

```
2024-07-13 11:37:18.071330227  Error parsing config, syntax error, unexpected LL_IDENTIFIER, expecting '}' in /config/syslog-ng.conf:15:2-15:6:
2024-07-13 11:37:18.071333262  10          file("/tmplog/$YEAR$MONTH$DAY$HOUR-$MIN-$HOST.log");
2024-07-13 11:37:18.071334158  11          stdout();
2024-07-13 11:37:18.071334950  12      };
2024-07-13 11:37:18.071335735  13
2024-07-13 11:37:18.071336584  14      destination d_loki {
2024-07-13 11:37:18.071337277  15---->  loki(
2024-07-13 11:37:18.071338004  15---->  ^^^^
2024-07-13 11:37:18.071338774  16               url("v145:3100")
2024-07-13 11:37:18.071339512  17               labels(
2024-07-13 11:37:18.071340366  18                       "forwarder" => "syslog-ng"
2024-07-13 11:37:18.071341158  19                       "app" => "$PROGRAM",
2024-07-13 11:37:18.071341943  20                       "host" => "$HOST",

```

Am I missing anything the config file or Is loki destination actually implemented?

**Comment by czanik** [comment]
Yes, it is. But it might not be available on your platform (anything older than RHEL 9) or you do not have the related sub-package installed. In most Linux distros the syslog-ng package is modular. Loki support is available in a sub-package, like syslog-ng-loki, or similar.

**Comment by AliMoeen** [comment]
Answer:

Thanks to @czanik 


I have been using a poorly developed container.


A better one is here, that includes loki module:

https://github.com/axoflow/axosyslog/pkgs/container/axosyslog/242944932?tag=latest

**Comment by salzig** [comment]
ha, just had the same question/problem with `syslog-ng 4 (4.8.1)` as installed from Debian trixie repository. 

```
Package: syslog-ng
Version: 4.8.1-5
…
Package: syslog-ng-mod-http
Version: 4.8.1-5
```

**Comment by HofiOne** [comment]
> Edit: the Debian package doesn't come with all modules, and they are also not available for installation. What's avaialble?
> 
> ```
> # syslog-ng -V
> syslog-ng 4 (4.8.1)
> Config version: 4.2
> Installer-Version: 4.8.1
> Revision: 4.8.1-5
> Compile-Date: May 10 2025 11:12:49
> Module-Directory: /usr/lib/syslog-ng/4.8
> Module-Path: /usr/lib/syslog-ng/4.8
> Include-Path: /usr/share/syslog-ng/include
> Available-Modules: json-plugin,pseudofile,tfgetent,xml,pacctformat,csvparser,graphite,afmongodb,riemann,afprog,http,timestamp,kafka,correlation,secure-logging,cef,disk-buffer,kvformat,mod-python.cpython-313-x86_64-linux-gnu,stardate,hook-commands,afamqp,confgen,syslogformat,tags-parser,add-contextual-data,afsnmp,rate-limit-filter,afsql,basicfuncs,examples,appmodel,afuser,azure-auth-header,map-value-pairs,cryptofuncs,redis,afstomp,regexp-parser,affile,afsocket,linux-kmsg-format,sdjournal,geoip2-plugin,system-source
> Enable-Debug: off
> Enable-GProf: off
> Enable-Memtrace: off
> Enable-IPv6: on
> Enable-Spoof-Source: on
> Enable-TCP-Wrapper: on
> Enable-Linux-Caps: on
> Enable-Systemd: on
> ```

@salzig this is the sorted module list of the above mentioned latest official docker image version

```
add-contextual-data
afamqp
affile
afmongodb
afprog
afsmtp
afsnmp
afsocket
afsql
afstomp
afuser
appmodel
azure-auth-header
basicfuncs
bigquery
cef
clickhouse
cloud_auth
confgen
correlation
cryptofuncs
csvparser
disk-buffer
examples
geoip2-plugin
graphite
hook-commands
http
json-plugin
kafka
kvformat
linux-kmsg-format
loki
map-value-pairs
metrics-probe
mod-python
mqtt
otel
pacctformat
pseudofile
pubsub
rate-limit-filter
redis
regexp-parser
riemann
sdjournal
secure-logging
stardate
syslogformat
system-source
tags-parser
tfgetent
timestamp
xml

```

What modules are you missing here?

**Comment by salzig** [comment]
> What modules are you missing here?

I tried to use the Debian package, not a container image.

**Comment by HofiOne** [comment]
> > What modules are you missing here?
> 
> I tried to use the Debian package, not a container image.

Oh, I see, my bad, @AliMoen talked about a container issue, as it turned out, so I thought you had an issue with the container image as well.

What is the source of the binary package you are trying to use?

Official debian repo?

Or our repo?

As you mentioned, "Debian trixie repository", my bet is the official repo.

As @czanik mentioned, package maintainers provide the supported modules in separate packages usually. It is their choice what packages they provide.

[Here](https://packages.debian.org/search?searchon=sourcenames&keywords=syslog-ng) I cannot see the GRPC modules, so modules that depend on GRPC (like loki) are not available on Debian (from the official repo)

Please try our binary repo as described [here](https://github.com/syslog-ng/syslog-ng?tab=readme-ov-file#installation-from-binaries)
Currently, only bookworm images can be found there, but I'm pretty sure it will work on Trixie as well.
In the near future, when [this PR](https://github.com/syslog-ng/syslog-ng/pull/5409) is merged, there will also be Trixie images in our repository with all the available modules.

Also, you can try to build your own version using [this DBLD image](https://github.com/syslog-ng/syslog-ng/pkgs/container/dbld-debian-trixie)

You can run it like:

```
docker run -it --rm ghcr.io/syslog-ng/dbld-debian-trixie:latest bash
```

You can build syslog-ng with all modules, like:

```
cd /source
git clone https://github.com/syslog-ng/syslog-ng.git .
cmake --install-prefix    $PWD/build/install      -B build . -Wno-dev -DCMAKE_EXPORT_COMPILE_COMMANDS=OFF  -DCMAKE_BUILD_TYPE=Debug -DIVYKIS_SOURCE=system -DENABLE_JAVA=OFF -DENABLE_JAVA_MODULES=OFF -DBUILD_TESTING=OFF -DENABLE_FORCE_GNU99=ON -DSUMMARY_LEVEL=0 -DENABLE_EXTRA_WARNINGS=ON -Werror
cmake --build ./build -j$(nproc) --target install
```

You can find the built product in the `/source/build/install` directory

**Comment by salzig** [comment]
you can pretty much replicate my current setup by 
```
❯ docker run -it debian:trixie bash -c "apt update && apt install -y syslog-ng && syslog-ng -V"
…
syslog-ng 4 (4.8.1)
Config version: 4.2
Installer-Version: 4.8.1
Revision: 4.8.1-5
Compile-Date: May 10 2025 11:12:49
Module-Directory: /usr/lib/syslog-ng/4.8
Module-Path: /usr/lib/syslog-ng/4.8
Include-Path: /usr/share/syslog-ng/include
Available-Modules: affile,afprog,afsocket,afuser,appmodel,basicfuncs,cef,confgen,correlation,cryptofuncs,csvparser,disk-buffer,hook-commands,json-plugin,kvformat,linux-kmsg-format,map-value-pairs,pacctformat,pseudofile,rate-limit-filter,regexp-parser,sdjournal,syslogformat,system-source,tags-parser,tfgetent,timestamp,afsql,afmongodb,add-contextual-data,afamqp,examples,geoip2-plugin,graphite,azure-auth-header,http,mod-python.cpython-313-x86_64-linux-gnu,kafka,redis,riemann,secure-logging,afsnmp,afstomp,xml,stardate
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: on
Enable-TCP-Wrapper: on
Enable-Linux-Caps: on
Enable-Systemd: on
```

**Comment by HofiOne** [comment]
> you can pretty much replicate my current setup by
> 

No, I did not.
My setup is based on our DBLD image that has all the required developer package dependencies to be able to build syslog-ng from source.
That container has no syslog-ng binary installed in it.


> As I understand it, they don't bundle all modules into packages. So some are missing.


Yes, that is what I wanted to tell you, when I said 
```
As @czanik mentioned, package maintainers provide the supported modules in separate packages usually. It is their choice what packages they provide.

Here I cannot see the GRPC modules, so modules that depend on GRPC (like loki) are not available on Debian (from the official repo)
```
;)
