### ISSUE TITLE
Syslog-ng Service crashes in g_hash_table_lookup function after syslog-ng-ctl reload

### ISSUE THREAD

**Issue by JJ-Law** [syslog-ng/syslog-ng#5018]
# syslog-ng
## Version of syslog-ng
syslog-ng 4.6

## Platform
Ubuntu 20.04.6 LTS (Focal Fossa)
Syslog-ng is running in docker container built using alpine:3.19.0

# Issue
## Failure
The Syslog-ng service crashes after adding remote Syslog servers to the configuration, reloading with `syslog-ng-ctl reload`, and sending a log event to the remote server over a TLS connection.

## Steps to reproduce
1. On the client, add a remote Syslog server to the configuration.
2. Use the command `syslog-ng-ctl` reload to reload the configuration.
3. Verify that the reload shows `Config reload successful`.
4. Send a log event to the remote server.
5. Run `ps -ef` and observe that the Syslog-ng service is missing.
6. Running `syslog-ng-ctl reload` command now shows `Error connecting control socket, socket='/usr/local/syslog-ng/var/syslog-ng.ctl', error='Connection refused'`

Tracing in GDB reveals a crash occurring in `g_hash_table_lookup`.
![image](https://github.com/user-attachments/assets/838d1dfd-0f15-4aef-84b4-4fd42ede9d46)

The issue does not occur if the service is restarted instead of reloaded.

## Configuration
`@version: 4.6
@include "scl.conf"
options{
	frac_digits(3);
	log_fifo_size (10000);
  use_dns(no);
};
source s_internal {
    internal();
};
source s_udp {
  udp(
    ip(0.0.0.0) 
    port(514)  
	  flags(no-parse)
  );
};
parser p_filename {
  regexp-parser(
    patterns('CEF:0\|[^|]+\|(?<app_dir>[^\.]+)\.(?<app_id>[^|]+)\|[^|]+\|[^|]+\|[^|]+\|[^|]+\|[^|]+')
  );
};
filter f_platform {
	match('^.*CEF:0\|[^|]+\|(platform.1000)\|[^|]+\|[^|]+\|[^|]+\|[^|]+\|[^|]+' value("MSG"));
};
filter f_apps {
	not match('^.*CEF:0\|[^|]+\|(platform.1000)\|[^|]+\|[^|]+\|[^|]+\|[^|]+\|[^|]+' value("MSG"));
};
template t_audit {
  template("${C_UNIXTIME} ${HOST} ${MESSAGE}\n");
};
destination d_app_audit {
  file("/var/log/audit/apps/${app_dir}/audit/${app_dir}_audit_trail.log"
  create-dirs(yes)
	template(t_audit)
  );
};
destination d_platform_audit {
  file("/var/log/audit/platform/audit/platform_audit_trail.log"
  create-dirs(yes)
	template(t_audit)  
  );
};
destination d_internal_logs {
    file("/var/log/audit/platform/audit/internal.log");
};
log {
  source(s_udp);	
	filter(f_platform);
	destination(d_platform_audit);
};
log {
  source(s_udp);	
  parser(p_filename);    	
	filter(f_apps);
  destination(d_app_audit);
};
log {
    source(s_internal);
    destination(d_internal_logs);
};

destination collector_1 {
    network(
        "192.168.233.134"
        port(6514)
        transport("tls")
        template(t_audit)
        tls(
            ca-dir("/trusted_store/")
            key-file("/certs/pwi_key.pem")
            cert-file("/certs/pwi_cert.pem")
            peer-verify(required-trusted)
            cipher-suite("ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256")
            ssl-options(no-sslv2, no-sslv3, no-tlsv1, no-tlsv11)
        )  
    );
};
log {
    source(s_udp);
    destination(collector_1);
};`

**Comment by MrAnno** [comment]
Hi @JJ-Law,

Thank you for the bug report.

This happens because, by default, TLS connections are kept alive during reloads and there is a lifetime bug related to the `SignalSlotConnector` of the `TLSVerifier` (the connector instance should be updated during reload).

Until a fix is implemented, you can add the ` keep-alive(no)` option to your TLS destinations as a workaround to avoid the crash.

**Comment by HofiOne** [comment]
Hi @JJ-Law,

I tried to reproduce this issue but had no success with it.

Either this is already fixed (though I could not find between the latest fixes), or my reproduction steps are wrong.

Could you please 
1. retry using the latest syslog-ng 4.8 version
2. give a simplified config and a bit more details to the reproduction steps

Thanks in advance!

**Comment by MrAnno** [comment]
This hasn't been fixed yet, the reproduction requires a TLS destination with `keep-alive(yes)`, an open connection (`openssl s_server` is perfect as a receiver), and initiating a reload while that connection is open.

Sending one single message before the reload may be necessary, I don't fully remember.

**Comment by HofiOne** [comment]
I'm using 2 syslog-ng instances

- the first acts as a TLS client (routes a local file to a TLS network destination, the server IP/port)
- the second is a TLS server (a TLS network source that reads the client-targeted IP/port)

both using `keep-alive(yes)`

tried

1. simply force reload the client config during an active connection, then send a message again
2. the same as in case one but before it, added a new client TLS destination)
3. the same as in case one but befoew it, added a new server TLS source, restarted the server then added a new client TLS destination, and finally send a message again

none of these reproduced the issue
(but the third one led to a new, unrelated crash, I will create a separate issue for that later on)

**Comment by JJ-Law** [comment]
> I'm using 2 syslog-ng instances
> 
> * the first acts as a TLS client (routes a local file to a TLS network destination, to the server IP/port)
> * the second is a TLS server (a TLS network source that reads the client-targeted IP/port)
> 
> both using `keep-alive(yes)`
> 
> tried
> 
> 1. simply force reload the client config during an active connection, then send a message again
> 2. the same as in case one but before it, added a new client TLS destination
> 3. the same as in case one but before it, added a new server TLS source, restarted the server then added a new client TLS destination (and at the end sent a message again)
> 
> none of these reproduced the issue (but the third one led to a new, [unrelated crash](https://github.com/syslog-ng/syslog-ng/issues/5085))
> 
> EDIT: It seems it is a Linux issue (it does not happen somehow on e.g. macOS where I've tested up to now) EDIT2: No, it just logs a NULL ptr assertation instead of crashing (so g_free maintains the freed ptr nicely on macOS), but behaves the same otherwise

Hi @HofiOne,

Sorry for the late response. 

I have tested again on syslog-ng version 4.8 and can confirm that the issue still persists. 
Also, to clarify, I am using Ubuntu OS. 

I noticed that you have merged the commits and closed the ticket - could you let me know if this fixes the issue and in which version of syslog-ng the can the fix be expected?

Thank you!

**Comment by HofiOne** [comment]
Hi @JJ-Law,

As we go in a rolling-release mode you can build your own version from the latest master branch that has the fix already (via the merge you saw)
Because of the rolling-release the next syslog-ng version will automatically contain the fix (4.8.1 or 4.9 will be the next one).

**Comment by kvmnd** [comment]
> Hi [@JJ-Law](https://github.com/JJ-Law),
> 
> Thank you for the bug report.
> 
> This happens because, by default, TLS connections are kept alive during reloads and there is a lifetime bug related to the `SignalSlotConnector` of the `TLSVerifier` (the connector instance should be updated during reload).
> 
> Until a fix is implemented, you can add the `keep-alive(no)` option to your TLS destinations as a workaround to avoid the crash.

Hi @MrAnno , I stumbled on this comment while searching about another problem that I'm having.
Mind you that right now I'm on an older version (3.36).
I'm playing around with CRLs and I noticed that if I'm connected to a server with TLS and I'm verifying the server certificate with a CA file and everything is working fine, if I put a CRL file for that CA in the corresponding folder and reload with syslog-ng-ctl reload, the CRL file is not read.
I know it because in my case it would fail with "CRL expired".
And I already know that generally speaking I'm doing it correctly because if the CRL is there since the start or if I stop/start the service from my init system, it correctly reads the CRL and fails.
So this is only happening on a reload.

So I wanted to know if what you were referring about TLS connection being kept alive might explain what I'm seeing and if the issue has been solved in the mean time.

**Comment by MrAnno** [comment]
@kvmnd, yes that's correct. When `keep-alive(yes)` is set (this is the default), connections are kept alive during reload, there will be no renegotiation or reconnection.

If you want your CRLs to be taken into account, either restart syslog-ng or configure `keep-alive(no)` in your destination.
