### ISSUE TITLE
modules/affile: NULL deference

### ISSUE THREAD

**Issue by nivelus** [syslog-ng/syslog-ng#5025]
# syslog-ng
## Version of syslog-ng
master

# Issue
https://github.com/syslog-ng/syslog-ng/blob/db14ca637471ce08a4c80fbb6e215654c3ee34d3/modules/affile/affile-dest.c#L523
This line is wrong: it pass NULL to function that will dereference the pointer.  It can cause crash. Is it safe to remove the call or there is copy-paste error and we should provide non-NULL argument?

**Comment by HofiOne** [comment]
Thanks for the report!

https://github.com/syslog-ng/syslog-ng/pull/5031 should address it (at least the possible crash part)
