### ISSUE TITLE
lib/cfg-argc.c -- NULL dereference

### ISSUE THREAD

**Issue by nivelus** [syslog-ng/syslog-ng#5026]
# syslog-ng
## Version of syslog-ng
master

# Bug
https://github.com/syslog-ng/syslog-ng/blob/db14ca637471ce08a4c80fbb6e215654c3ee34d3/lib/cfg-block.c#L75
This line is wrong: `cfg_args_is_accepting_varargs` doesn't check for NULL, but `defs` can be NULL here.

**Comment by HofiOne** [comment]
Thanks for the report!

https://github.com/syslog-ng/syslog-ng/pull/5032 should address it
