### ISSUE TITLE
500 - Internal server error.

### ISSUE THREAD

**Issue by asidler** [syslog-ng/syslog-ng#5036]
## Documentation version
Syslog-ng Open Source Edition - All versions

## Incorrect section
n/a

## Description of the problem
'Internal server error' on the whole syslog-ng open source edition documentation since several days
https://www.syslog-ng.com/technical-documents/list/syslog-ng-open-source-edition/
![image](https://github.com/user-attachments/assets/7050ce93-b1f6-4742-a73a-986a5b57a9da)

## Proposed solution

n/a

**Comment by HofiOne** [comment]
Please use the new, up-to-date documentation instead at https://syslog-ng.github.io/

**Comment by asidler** [comment]
> Please use the new, up-to-date documentation instead at https://syslog-ng.github.io/

Thank you very much for the update. We were not aware of the new location.

Maybe you could update the link on https://www.syslog-ng.com/ ;-)

![image](https://github.com/user-attachments/assets/6e889a3d-ac19-445b-bc89-86b4665075e7)

or add a redirect or a simple link from the old t the new location.
