### ISSUE TITLE
compiling 4.8.0 on Fedora i686 failed

### ISSUE THREAD

**Issue by czanik** [syslog-ng/syslog-ng#5040]
I am preparing the update for Fedora Rawhide. All other platforms are OK, but on i686 compiling the 4.8.0 release fails:
```
  libtool:   error: unsupported hardcode properties See the libtool documentation for more information. Fatal configuration error.
make[2]: *** [Makefile:15964: modules/examples/libexamples.la] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [Makefile:31528: all-recursive] Error 1
make: *** [Makefile:13653: all] Error 2
error: Bad exit status from /var/tmp/rpm-tmp.4HbW5y (%build)
RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.4HbW5y (%build)
Child return code was: 1
EXCEPTION: [Error('Command failed: \n # /usr/bin/systemd-nspawn -q -M 88fff2f683244ef6a10c3e621b878b8a -D /var/lib/mock/f41-build-52567406-6280775/root -a -u mockbuild --capability=cap_ipc_lock --bind=/tmp/mock-resolv.619ot2lu:/etc/resolv.conf --bind=/dev/btrfs-control --bind=/dev/mapper/control --bind=/dev/fuse --bind=/dev/loop-control --bind=/dev/loop0 --bind=/dev/loop1 --bind=/dev/loop2 --bind=/dev/loop3 --bind=/dev/loop4 --bind=/dev/loop5 --bind=/dev/loop6 --bind=/dev/loop7 --bind=/dev/loop8 --bind=/dev/loop9 --bind=/dev/loop10 --bind=/dev/loop11 --console=pipe --setenv=TERM=vt100 --setenv=SHELL=/bin/bash --setenv=HOME=/builddir --setenv=HOSTNAME=mock --setenv=PATH=/usr/bin:/bin:/usr/sbin:/sbin \'--setenv=PROMPT_COMMAND=printf "\\033]0;<mock-chroot>\\007"\' \'--setenv=PS1=<mock-chroot> \\s-\\v\\$ \' --setenv=LANG=C.UTF-8 --resolv-conf=off bash --login -c \'/usr/bin/rpmbuild -bb --noclean --target i686 --nodeps /builddir/build/SPECS/syslog-ng.spec\'\n', 1)]
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/mockbuild/trace_decorator.py", line 93, in trace
    result = func(*args, **kw)
             ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mockbuild/util.py", line 612, in do_with_status
    raise exception.Error("Command failed: \n # %s\n%s" % (cmd_pretty(command, env), output), child.returncode)
mockbuild.exception.Error: Command failed: 
 # /usr/bin/systemd-nspawn -q -M 88fff2f683244ef6a10c3e621b878b8a -D /var/lib/mock/f41-build-52567406-6280775/root -a -u mockbuild --capability=cap_ipc_lock --bind=/tmp/mock-resolv.619ot2lu:/etc/resolv.conf --bind=/dev/btrfs-control --bind=/dev/mapper/control --bind=/dev/fuse --bind=/dev/loop-control --bind=/dev/loop0 --bind=/dev/loop1 --bind=/dev/loop2 --bind=/dev/loop3 --bind=/dev/loop4 --bind=/dev/loop5 --bind=/dev/loop6 --bind=/dev/loop7 --bind=/dev/loop8 --bind=/dev/loop9 --bind=/dev/loop10 --bind=/dev/loop11 --console=pipe --setenv=TERM=vt100 --setenv=SHELL=/bin/bash --setenv=HOME=/builddir --setenv=HOSTNAME=mock --setenv=PATH=/usr/bin:/bin:/usr/sbin:/sbin '--setenv=PROMPT_COMMAND=printf "\033]0;<mock-chroot>\007"' '--setenv=PS1=<mock-chroot> \s-\v\$ ' --setenv=LANG=C.UTF-8 --resolv-conf=off bash --login -c '/usr/bin/rpmbuild -bb --noclean --target i686 --nodeps /builddir/build/SPECS/syslog-ng.spec'

```

You can find the full build logs at: https://koji.fedoraproject.org/koji/taskinfo?taskID=121075069

**Comment by czanik** [comment]
Note: I worked around this problem with ```--disable-example-modules``` for now, so it's not urgent anymore. It could be yet another 32 bit problem, and all major distros dropped 32 bit support for primary architectures.

**Comment by HofiOne** [comment]
Could you please add to the description the `configure` line you used when the issue came?

**Comment by czanik** [comment]
This is what I found in https://kojipkgs.fedoraproject.org//work/tasks/5069/121075069/build.log (the build was done on the Koji build service of Fedora):
```
+ ./configure --build=i686-redhat-linux-gnu --host=i686-redhat-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib --libexecdir=/usr/libexec --localstatedir=/var --runstatedir=/run --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --prefix=/usr --sysconfdir=/etc/syslog-ng --localstatedir=/var/lib/syslog-ng --datadir=/usr/share --with-module-dir=/usr/lib/syslog-ng --with-systemdsystemunitdir=/usr/lib/systemd/system --with-ivykis=system --with-mongoc=system --with-embedded-crypto --enable-manpages --enable-ipv6 --enable-spoof-source --with-linux-caps=auto --enable-sql --enable-kafka --enable-mqtt --enable-json --enable-ssl --enable-smtp --enable-geoip --enable-shared --disable-static --enable-dynamic-linking --enable-systemd --enable-redis --enable-amqp --enable-python --with-python=3 --with-python-packages=system --disable-java --disable-java-modules --enable-afsnmp --enable-riemann
```

**Comment by czanik** [comment]
It also broke the x86_64 builds for Amazon Linux 2023, so it's not a 32bit issue...

**Comment by czanik** [comment]
And Aarch64 (64bit ARM) builds for Amazon Linux 2023 are broken too. Yet again, I'll use the ```--disable-example-modules``` option for configure to work around this problem.

**Comment by HofiOne** [comment]
gcc or clang, both?

**Comment by czanik** [comment]
These are all GCC-only environments. There is no eBPF, so clang is not installed in the build environment.

**Comment by HofiOne** [comment]
just some notes:

you can use `--enable-all-modules` and disable the not needed ones instead, it gives you
- a shorter and more readable command line
- knowledge of what is explicitly enabled or disabled, as the autoconfigure is disabled that way, and modules that are not disabled, but have missing dependencies, will cause errors during the configure pass

I assume grpc is turned off as well, what about the other c++ modules?

I'm curious, as I usually test the builds on ARM64 Ubuntu as well, but I cannot see such issues.

**Comment by czanik** [comment]
No C++ modules on 32bit Fedora and Amazon Linux 23 (which is a very heavily modified Fedora Linux), due to missing dependencies.

**Comment by HofiOne** [comment]
Is it the same issue you mentioned in the original issue entry?
If not, please link the build issues as you did the first time.

**Comment by czanik** [comment]
I deleted the builds (and thus the logs), but it was the same error message at the exact same location.

**Comment by czanik** [comment]
Closing it for now. I'll reopen this if there is an actual user report from these platforms missing the examples module.

**Comment by bkuhls** [comment]
> No C++ modules on 32bit Fedora and Amazon Linux 23 

and no c++ modules with non-c++ toolchains from the buildroot project.

Since the bump from 4.7.3 to 4.8.1 the buildroot autobuilders fail with toolchains without c++ support:
https://autobuild.buildroot.net/results/dd2/dd2b1dedbd92280dac01ae4d6454ef7eb08cc539/build-end.log
```
  CXXLD    modules/examples/libexamples.la
libtool:   error: unsupported hardcode properties See the libtool documentation for more information. Fatal configuration error.
make[3]: *** [Makefile:16017: modules/examples/libexamples.la] Error 1
```
Please note CXXLD in the log.

I could track down the problem to https://github.com/syslog-ng/syslog-ng/commit/163c894563c9f5536c5e91222c9efda64031b08c
Reverting only the change in modules/examples/Makefile.am 
```
if ENABLE_CPP
-nodist_EXTRA_modules_examples_libexamples_la_SOURCES = force-cpp-linker-with-default-stdlib.cpp
+modules_examples_libexamples_la_LIBADD += -lstdc++
 endif
```
fixed the problem:
```
  CCLD     modules/examples/libexamples.la
```
Sorry that I can not provide a proper fix than this revert, my knowledge about autoconf is limited.

**Comment by HofiOne** [comment]
We have made numerous changes to the 32-bit target build, and we have a CI target that runs on a 32-bit machine (although, as far as I recall, it is Debian-based). In any case, could you please try building from the latest develop branch (which will become the next release soon, so it is worth giving it a try)?
