### ISSUE TITLE
Use debian:stable instead of debian:testing as base docker image

### ISSUE THREAD

**Issue by ikheifets-splunk** [syslog-ng/syslog-ng#5055]
@czanik we discuss today that official `syslog-ng docker image` using [as base image debian:testing](https://github.com/syslog-ng/syslog-ng/blob/master/docker/Dockerfile#L24). It would be good if we will use `stable/latest` instead of `testing`.

Also I just wanna highlight that `debian:latest`have [23 low severity CVEs](https://hub.docker.com/layers/library/debian/latest/images/sha256-b1ae8b5bfaa9afa86b50c2a151a442d832c4449cf3731bddf8a728e5628ebb59?context=explore). Probably have a sense to discuss alternatives for base docker image

**Comment by ikheifets-splunk** [comment]
@czanik ok, I understood! I have yet another question regarding debian, it seems that `debian:latest` [have lots of CVEs](https://hub.docker.com/layers/library/debian/latest/images/sha256-b1ae8b5bfaa9afa86b50c2a151a442d832c4449cf3731bddf8a728e5628ebb59?context=explore) Probably have a sense use as a base docker image something like [fedora](https://hub.docker.com/layers/library/fedora/latest/images/sha256-a0f4dffd30e0af6e53f57533e79a9e32699d37d8e850132ff89f612d6ea8a300?context=explore) or [alpine](https://hub.docker.com/layers/library/alpine/latest/images/sha256-eddacbc7e24bf8799a4ed3cdcfa50d4b88a323695ad80f317b6629883b2c2a78?context=explore), they are more secure. What do you think?

**Comment by czanik** [comment]
@ikheifets-splunk No ETA yet, but I plan to work on an RPM-based container image soon. Once it is well tested and received some community feedback, we can also do regular builds of it. However, not as a replacement for the current ```balabit/syslog-ng``` image, but as an addition. Too many people have long existing processes to use that Debian-based image. If we can believe the Docker hub statistics, there are 50+ million downloads of it.
