### ISSUE TITLE
mongodb driver uses wrong authentication database at MongoDB Atlas

### ISSUE THREAD

**Issue by Wernfried** [syslog-ng/syslog-ng#5096]
I setup a mongodb destination like this:

```
destination d_mongo_noop {
   mongodb(
      uri('mongodb+srv://dev.******.mongodb.net/raw-1?readPreference=primaryPreferred&tls=true&authSource=$external&authMechanism=MONGODB-X509&tlsCertificateKeyFile=/opt/mediation/certs/client.syslog-ng.pem&tlsCAFile=/etc/ssl/certs/ca-bundle.crt')
      collection('tdube04mipmed0.ignored')
      batch-lines(100)
      batch-timeout(10)
      workers(1)
      bulk(yes)
      bulk_unordered(yes)
      bulk_bypass_validation(yes)
      write_concern(acked)
      value-pairs(
         pair("di", "${.FN.dstip}${.HW.DestinationIP}")
         pair("rb", int64("0${.FN.rcvdbyte}${.HW.RcvBytes}"))
         pair("dp", int32("${.FN.dstport}${.HW.DestinationPort}"))
         pair("t0", datetime("${BEGINTIME}${.HW.BeginTime}"))
         pair("si", "${.FN.srcip}${.HW.SourceIP}")
         pair("a", "${.FN.action}${ACTION}")
         pair("f", "${.FN.devname}${.HW.devname}")
         pair("sb", int64("0${.FN.sentbyte}${.HW.SendBytes}"))
         pair("n", "${.FN.trandisp}${TRANDISP}")
         pair("p", "${PROTOCOL}")
         pair("t", datetime("${ENDTIME}${.HW.EndTime}"))
         pair("sp", int32("${.FN.srcport}${.HW.SourcePort}"))
      )
      frac-digits(3)
      time-zone("Europe/Zurich")
      persist-name('noop')
   );
};
```

When I start syslog-ng then it raises a warning
```
2024/09/12 11:12:17.0627: [20061]:  WARNING:       mongoc: Cannot override URI option "authSource" from TXT record "authSource=admin"
``` 
syslog-ng starts, however it does not connect to MongoDB and all log messages are queued and later they are dropped.

Connection is authenticated by x.509 certificate (rather than username+password where `authSource` defaults to `admin`), thus `authSource=$external&authMechanism=MONGODB-X509` must be set in URI.

Note, this error appears only when I connect to MongoDB Atlas (i.e. MongoDB cloud service). When I run MongoDB on-premise, i.e. URI like this:

```
destination d_mongo_noop {
   mongodb(
      uri('mongodb://tdube04mipmed1:27017,tdube04mipmed0:27017/raw-01?readPreference=primaryPreferred&tls=true&authSource=$external&authMechanism=MONGODB-X509&tlsCertificateKeyFile=/opt/mediation/certs/client.syslog-ng.pem&tlsCAFile=/etc/ssl/certs/ca-bundle.crt')
...
}
```

then it works fine without any warning/error.

```
syslog-ng --version
syslog-ng 4 (4.3.1)
Config version: 4.2
Installer-Version: 4.3.1
Revision: 
Compile-Date: Jul 31 2023 08:01:35
Module-Directory: /usr/lib64/syslog-ng
Module-Path: /usr/lib64/syslog-ng
Include-Path: /usr/share/syslog-ng/include
Available-Modules: timestamp,xml,afsmtp,azure-auth-header,afmongodb,add-contextual-data,affile,afprog,afsocket,afstomp,afuser,appmodel,basicfuncs,cef,confgen,correlation,cryptofuncs,csvparser,disk-buffer,examples,graphite,hook-commands,json-plugin,kvformat,linux-kmsg-format,map-value-pairs,metrics-probe,pacctformat,pseudofile,rate-limit-filter,regexp-parser,sdjournal,stardate,syslogformat,system-source,tags-parser,tfgetent,http,afsql
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: on
Enable-TCP-Wrapper: off
Enable-Linux-Caps: on
Enable-Systemd: on
```

See [Connection String Formats](https://www.mongodb.com/docs/manual/reference/connection-string/#connection-string-formats) and [Authenticate with a x.509 Certificate](https://www.mongodb.com/docs/manual/tutorial/configure-x509-client-authentication/#authenticate-with-a-x-509-certificate) for details.

**Comment by HofiOne** [comment]
Hi @Wernfried,
Thanks for the report, I will check this once I get a proper environment to test it, but it will not be very soon, sorry.

**Comment by Wernfried** [comment]
Looks like this issue is not caused by syslog-ng, the error is at [mongo-c-driver](https://github.com/mongodb/mongo-c-driver), see [src/libmongoc/src/mongoc/mongoc-uri.c](https://github.com/mongodb/mongo-c-driver/blob/8a85033b212dabf140442dd094f636ef2d44b8e5/src/libmongoc/src/mongoc/mongoc-uri.c)

I created a ticket for Mongo-C Driver: https://jira.mongodb.org/browse/CDRIVER-5712

**Comment by HofiOne** [comment]
@Wernfried Thanks for the follow-up. If you do not mind I will close this ticket for now. Feel free to reopen it or add further comments on the results of the Mongo-C Driver ticket.
Thanks!
