### ISSUE TITLE
afsnmp module does not build with clang: `clang: error: unknown argument: '-3cda-11ee-b8ac-16228a05f5d2/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.7.Internal.sdk/System/Library/Frameworks/'`

### ISSUE THREAD

**Issue by barracuda156** [syslog-ng/syslog-ng#5104]
Clang is doing something strange here:
```
  [ 71%] Building C object modules/afsnmp/CMakeFiles/afsnmp.dir/afsnmpdest.c.o
  cd /opt/local/var/macports/build/_Users_runner_work_powerpc-ports_powerpc-ports_ports_sysutils_syslog-ng-devel/syslog-ng-devel/work/build/modules/afsnmp && /usr/bin/clang -DGLIB_VERSION_MIN_REQUIRED=GLIB_VERSION_2_68 -D_GNU_SOURCE=1 -D_LARGEFILE64_SOURCE=1 -D__APPLE_USE_RFC_3542 -Dafsnmp_EXPORTS -I/opt/local/var/macports/build/_Users_runner_work_powerpc-ports_powerpc-ports_ports_sysutils_syslog-ng-devel/syslog-ng-devel/work/build -I/opt/local/var/macports/build/_Users_runner_work_powerpc-ports_powerpc-ports_ports_sysutils_syslog-ng-devel/syslog-ng-devel/work/syslog-ng-71a2e4ce91b5028f7d40bd7299414c50d891582c/modules/afsnmp -I/opt/local/var/macports/build/_Users_runner_work_powerpc-ports_powerpc-ports_ports_sysutils_syslog-ng-devel/syslog-ng-devel/work/build/modules/afsnmp -I/opt/local/var/macports/build/_Users_runner_work_powerpc-ports_powerpc-ports_ports_sysutils_syslog-ng-devel/syslog-ng-devel/work/syslog-ng-71a2e4ce91b5028f7d40bd7299414c50d891582c/lib -I/opt/local/var/macports/build/_Users_runner_work_powerpc-ports_powerpc-ports_ports_sysutils_syslog-ng-devel/syslog-ng-devel/work/build/lib -isystem /opt/local/include -isystem /opt/local/include/json-c -isystem /opt/local/var/macports/build/_Users_runner_work_powerpc-ports_powerpc-ports_ports_sysutils_syslog-ng-devel/syslog-ng-devel/work/syslog-ng-71a2e4ce91b5028f7d40bd7299414c50d891582c/lib/eventlog/src -isystem /opt/local/include/glib-2.0 -isystem /opt/local/lib/glib-2.0/include -isystem /opt/local/libexec/openssl3/include -pipe -I/opt/local/libexec/openssl3/include -Os -DNDEBUG -I/opt/local/libexec/openssl3/include -isystem/opt/local/include -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -std=gnu99 -arch x86_64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -mmacosx-version-min=12.0 -fPIC -DNETSNMP_ENABLE_IPV6 -fno-strict-aliasing -g -Os -pipe -DBUILD=174 -DMACOSX_DEPLOYMENT_TARGET=12.7 --sysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -iframeworkwithsysroot /System/Library/Frameworks/-3cda-11ee-b8ac-16228a05f5d2/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.7.Internal.sdk/System/Library/PrivateFrameworks/ -3cda-11ee-b8ac-16228a05f5d2/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.7.Internal.sdk/System/Library/Frameworks/ -iwithsysroot /usr/local/libressl/include -L/AppleInternal/Library/BuildRoots/bc10cbcd-3cda-11ee-b8ac-16228a05f5d2/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.7.Internal.sdk/usr/local/libressl/lib -Udarwin21 -Ddarwin21=darwin21 -I. -I/usr/local/include -Wshadow -Wno-stack-protector -Wno-unused-parameter -Wno-variadic-macros -Wimplicit-function-declaration -Wnested-externs -Wstrict-prototypes -Wswitch-default -Wimplicit-int -Wall -Wuninitialized -Wdeprecated -Wdeprecated-declarations -Woverflow -Wdouble-promotion -Wfloat-equal -Wpointer-arith -Wpointer-sign -Wmissing-format-attribute -Wold-style-definition -Wundef -Wignored-qualifiers -Wfloat-conversion -Wbad-function-cast -MD -MT modules/afsnmp/CMakeFiles/afsnmp.dir/afsnmpdest.c.o -MF CMakeFiles/afsnmp.dir/afsnmpdest.c.o.d -o CMakeFiles/afsnmp.dir/afsnmpdest.c.o -c /opt/local/var/macports/build/_Users_runner_work_powerpc-ports_powerpc-ports_ports_sysutils_syslog-ng-devel/syslog-ng-devel/work/syslog-ng-71a2e4ce91b5028f7d40bd7299414c50d891582c/modules/afsnmp/afsnmpdest.c
  clang: error: unknown argument: '-3cda-11ee-b8ac-16228a05f5d2/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.7.Internal.sdk/System/Library/Frameworks/'
  make[2]: *** [modules/afsnmp/CMakeFiles/afsnmp.dir/afsnmpdest.c.o] Error 1
  make[2]: Leaving directory `/opt/local/var/macports/build/_Users_runner_work_powerpc-ports_powerpc-ports_ports_sysutils_syslog-ng-devel/syslog-ng-devel/work/build'
  make[1]: *** [modules/afsnmp/CMakeFiles/afsnmp.dir/all] Error 2
  make[1]: *** Waiting for unfinished jobs....
```
From: https://github.com/barracuda156/powerpc-ports/actions/runs/10876896823/job/30177474516

**Comment by barracuda156** [comment]
GRPC modules also fail, only with Clang.
```
  /opt/local/var/macports/build/_Users_runner_work_powerpc-ports_powerpc-ports_ports_sysutils_syslog-ng-devel/syslog-ng-devel/work/syslog-ng-71a2e4ce91b5028f7d40bd7299414c50d891582c/modules/grpc/otel/filterx/object-otel-kvlist.cpp:321:21: error: assigning to 'guint64 (*)(FilterXDict *)' (aka 'unsigned long (*)(FilterXDict_ *)') from incompatible type 'uint64_t (FilterXDict *)' (aka 'unsigned long long (FilterXDict_ *)'): different return type ('guint64' (aka 'unsigned long') vs 'uint64_t' (aka 'unsigned long long'))
    321 |   self->super.len = _len;
        |                     ^~~~
  /opt/local/var/macports/build/_Users_runner_work_powerpc-ports_powerpc-ports_ports_sysutils_syslog-ng-devel/syslog-ng-devel/work/syslog-ng-71a2e4ce91b5028f7d40bd7299414c50d891582c/modules/grpc/otel/filterx/object-otel-kvlist.cpp:392:53: warning: 'MutableRepeatedPtrField' is deprecated: Please use GetMutableRepeatedFieldRef() instead [-Wdeprecated-declarations]
    392 |       auto repeated_fields = reflectors.reflection->MutableRepeatedPtrField<KeyValue>(message, reflectors.fieldDescriptor);
        |                                                     ^
  /opt/local/include/google/protobuf/message.h:886:24: note: 'MutableRepeatedPtrField' has been explicitly marked deprecated here
    886 |   RepeatedPtrField<T>* MutableRepeatedPtrField(Message* msg,
        |                        ^
  /opt/local/var/macports/build/_Users_runner_work_powerpc-ports_powerpc-ports_ports_sysutils_syslog-ng-devel/syslog-ng-devel/work/syslog-ng-71a2e4ce91b5028f7d40bd7299414c50d891582c/modules/grpc/otel/filterx/object-otel-kvlist.cpp:392:53: warning: 'MutableRepeatedPtrField<opentelemetry::proto::common::v1::KeyValue>' is deprecated: Please use GetMutableRepeatedFieldRef() instead [-Wdeprecated-declarations]
    392 |       auto repeated_fields = reflectors.reflection->MutableRepeatedPtrField<KeyValue>(message, reflectors.fieldDescriptor);
        |                                                     ^
  /opt/local/include/google/protobuf/message.h:885:3: note: 'MutableRepeatedPtrField<opentelemetry::proto::common::v1::KeyValue>' has been explicitly marked deprecated here
    885 |   PROTOBUF_DEPRECATED_MSG("Please use GetMutableRepeatedFieldRef() instead")
        |   ^
  /opt/local/include/google/protobuf/port_def.inc:340:54: note: expanded from macro 'PROTOBUF_DEPRECATED_MSG'
    340 | # define PROTOBUF_DEPRECATED_MSG(msg) __attribute__((deprecated(msg)))
        |                                                      ^
. . .
  /opt/local/var/macports/build/_Users_runner_work_powerpc-ports_powerpc-ports_ports_sysutils_syslog-ng-devel/syslog-ng-devel/work/syslog-ng-71a2e4ce91b5028f7d40bd7299414c50d891582c/modules/grpc/bigquery/bigquery-worker.cpp:241:12: error: no matching function for call to 'type_cast_to_int64'
    241 |       if (!type_cast_to_int64(value.str, -1, &v, NULL))
        |            ^~~~~~~~~~~~~~~~~~
  /opt/local/var/macports/build/_Users_runner_work_powerpc-ports_powerpc-ports_ports_sysutils_syslog-ng-devel/syslog-ng-devel/work/syslog-ng-71a2e4ce91b5028f7d40bd7299414c50d891582c/lib/logmsg/type-hinting.h:48:10: note: candidate function not viable: no known conversion from 'int64_t *' (aka 'long long *') to 'gint64 *' (aka 'long *') for 3rd argument
     48 | gboolean type_cast_to_int64(const gchar *value, gssize value_len, gint64 *out, GError **error);
        |          ^                                                        ~~~~~~~~~~~
  /opt/local/var/macports/build/_Users_runner_work_powerpc-ports_powerpc-ports_ports_sysutils_syslog-ng-devel/syslog-ng-devel/work/syslog-ng-71a2e4ce91b5028f7d40bd7299414c50d891582c/modules/grpc/bigquery/bigquery-worker.cpp:252:12: error: no matching function for call to 'type_cast_to_int64'
    252 |       if (!type_cast_to_int64(value.str, -1, &v, NULL))
        |            ^~~~~~~~~~~~~~~~~~
  /opt/local/var/macports/build/_Users_runner_work_powerpc-ports_powerpc-ports_ports_sysutils_syslog-ng-devel/syslog-ng-devel/work/syslog-ng-71a2e4ce91b5028f7d40bd7299414c50d891582c/lib/logmsg/type-hinting.h:48:10: note: candidate function not viable: no known conversion from 'int64_t *' (aka 'long long *') to 'gint64 *' (aka 'long *') for 3rd argument
     48 | gboolean type_cast_to_int64(const gchar *value, gssize value_len, gint64 *out, GError **error);
        |          ^                                                        ~~~~~~~~~~~
  /opt/local/var/macports/build/_Users_runner_work_powerpc-ports_powerpc-ports_ports_sysutils_syslog-ng-devel/syslog-ng-devel/work/syslog-ng-71a2e4ce91b5028f7d40bd7299414c50d891582c/modules/grpc/otel/otel-protobuf-parser.cpp:405:67: warning: format specifies type 'unsigned long long' but the argument has type 'guint64' (aka 'unsigned long') [-Wformat]
    405 |   std::snprintf(number_buf, G_N_ELEMENTS(number_buf), "%" PRIu64, time_unix_nano);
        |                                                        ~~~~~~~~~  ^~~~~~~~~~~~~~
  /opt/local/var/macports/build/_Users_runner_work_powerpc-ports_powerpc-ports_ports_sysutils_syslog-ng-devel/syslog-ng-devel/work/syslog-ng-71a2e4ce91b5028f7d40bd7299414c50d891582c/modules/grpc/otel/otel-protobuf-parser.cpp:416:67: warning: format specifies type 'unsigned long long' but the argument has type 'guint64' (aka 'unsigned long') [-Wformat]
    416 |   std::snprintf(number_buf, G_N_ELEMENTS(number_buf), "%" PRIu64, observed_time_unix_nano);
        |                                                        ~~~~~~~~~  ^~~~~~~~~~~~~~~~~~~~~~~
  3 errors generated.
  make[2]: *** [modules/grpc/bigquery/CMakeFiles/bigquery-cpp.dir/bigquery-worker.cpp.o] Error 1
  make[2]: Leaving directory `/opt/local/var/macports/build/_Users_runner_work_powerpc-ports_powerpc-ports_ports_sysutils_syslog-ng-devel/syslog-ng-devel/work/build'
  make[1]: *** [modules/grpc/bigquery/CMakeFiles/bigquery-cpp.dir/all] Error 2
```

LLVM clangs also fail. Perhaps, it is an issue with Apple’s libc++.

**Comment by HofiOne** [comment]
> Clang is doing something strange here:
> 
> ```
>   [ 71%] Building C object modules/afsnmp/CMakeFiles/afsnmp.dir/afsnmpdest.c.o
>   cd /opt/local/var/macports/build/_Users_runner_work_powerpc-ports_powerpc-ports_ports_sysutils_syslog-ng-devel/syslog-ng-devel/work/build/modules/afsnmp && /usr/bin/clang -DGLIB_VERSION_MIN_REQUIRED=GLIB_VERSION_2_68 -D_GNU_SOURCE=1 -D_LARGEFILE64_SOURCE=1 -D__APPLE_USE_RFC_3542 -Dafsnmp_EXPORTS -I/opt/local/var/macports/build/_Users_runner_work_powerpc-ports_powerpc-ports_ports_sysutils_syslog-ng-devel/syslog-ng-devel/work/build -I/opt/local/var/macports/build/_Users_runner_work_powerpc-ports_powerpc-ports_ports_sysutils_syslog-ng-devel/syslog-ng-devel/work/syslog-ng-71a2e4ce91b5028f7d40bd7299414c50d891582c/modules/afsnmp -I/opt/local/var/macports/build/_Users_runner_work_powerpc-ports_powerpc-ports_ports_sysutils_syslog-ng-devel/syslog-ng-devel/work/build/modules/afsnmp -I/opt/local/var/macports/build/_Users_runner_work_powerpc-ports_powerpc-ports_ports_sysutils_syslog-ng-devel/syslog-ng-devel/work/syslog-ng-71a2e4ce91b5028f7d40bd7299414c50d891582c/lib -I/opt/local/var/macports/build/_Users_runner_work_powerpc-ports_powerpc-ports_ports_sysutils_syslog-ng-devel/syslog-ng-devel/work/build/lib -isystem /opt/local/include -isystem /opt/local/include/json-c -isystem /opt/local/var/macports/build/_Users_runner_work_powerpc-ports_powerpc-ports_ports_sysutils_syslog-ng-devel/syslog-ng-devel/work/syslog-ng-71a2e4ce91b5028f7d40bd7299414c50d891582c/lib/eventlog/src -isystem /opt/local/include/glib-2.0 -isystem /opt/local/lib/glib-2.0/include -isystem /opt/local/libexec/openssl3/include -pipe -I/opt/local/libexec/openssl3/include -Os -DNDEBUG -I/opt/local/libexec/openssl3/include -isystem/opt/local/include -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -std=gnu99 -arch x86_64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -mmacosx-version-min=12.0 -fPIC -DNETSNMP_ENABLE_IPV6 -fno-strict-aliasing -g -Os -pipe -DBUILD=174 -DMACOSX_DEPLOYMENT_TARGET=12.7 --sysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -iframeworkwithsysroot /System/Library/Frameworks/-3cda-11ee-b8ac-16228a05f5d2/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.7.Internal.sdk/System/Library/PrivateFrameworks/ -3cda-11ee-b8ac-16228a05f5d2/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.7.Internal.sdk/System/Library/Frameworks/ -iwithsysroot /usr/local/libressl/include -L/AppleInternal/Library/BuildRoots/bc10cbcd-3cda-11ee-b8ac-16228a05f5d2/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.7.Internal.sdk/usr/local/libressl/lib -Udarwin21 -Ddarwin21=darwin21 -I. -I/usr/local/include -Wshadow -Wno-stack-protector -Wno-unused-parameter -Wno-variadic-macros -Wimplicit-function-declaration -Wnested-externs -Wstrict-prototypes -Wswitch-default -Wimplicit-int -Wall -Wuninitialized -Wdeprecated -Wdeprecated-declarations -Woverflow -Wdouble-promotion -Wfloat-equal -Wpointer-arith -Wpointer-sign -Wmissing-format-attribute -Wold-style-definition -Wundef -Wignored-qualifiers -Wfloat-conversion -Wbad-function-cast -MD -MT modules/afsnmp/CMakeFiles/afsnmp.dir/afsnmpdest.c.o -MF CMakeFiles/afsnmp.dir/afsnmpdest.c.o.d -o CMakeFiles/afsnmp.dir/afsnmpdest.c.o -c /opt/local/var/macports/build/_Users_runner_work_powerpc-ports_powerpc-ports_ports_sysutils_syslog-ng-devel/syslog-ng-devel/work/syslog-ng-71a2e4ce91b5028f7d40bd7299414c50d891582c/modules/afsnmp/afsnmpdest.c
>   clang: error: unknown argument: '-3cda-11ee-b8ac-16228a05f5d2/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.7.Internal.sdk/System/Library/Frameworks/'
>   make[2]: *** [modules/afsnmp/CMakeFiles/afsnmp.dir/afsnmpdest.c.o] Error 1
>   make[2]: Leaving directory `/opt/local/var/macports/build/_Users_runner_work_powerpc-ports_powerpc-ports_ports_sysutils_syslog-ng-devel/syslog-ng-devel/work/build'
>   make[1]: *** [modules/afsnmp/CMakeFiles/afsnmp.dir/all] Error 2
>   make[1]: *** Waiting for unfinished jobs....
> ```
> 
> From: https://github.com/barracuda156/powerpc-ports/actions/runs/10876896823/job/30177474516

I've met this one earlier, just cannot recall what the solution was :S
I'll follow up once I can remember.

**Comment by HofiOne** [comment]
> LLVM clangs also fail. Perhaps, it is an issue with Apple’s libc++.

Force using c++ 17 solved this one for me on some systems (that is strange because on my main ARM64 Sonoma latest machine the `set(CMAKE_CXX_STANDARD 11 CACHE STRING "C++ standard")` is working perfectly (though I'm using homebrew)

**Comment by HofiOne** [comment]
No, it is something else, something very strange!
The issue is that the  `type_cast_to_int64` function can not be found, which is in `type-hinting.h`.
That header is included correctly with `extern "C"` guards in the `bigquery-worker.cpp`, but seems sometimes it cannot be found either.

I experienced the same now on my Sonoma ARM64 VM, but not on my also Sonoma ARM64 main machine.
This is extremely surprising for me as those have the
- same OS version
- same clang version
- same source and configure options
- same everything...
the only difference is that the VM uses MacPorts whilst the main machine has brew that should not cause this kind of error

I'm trying to figure out the reason now...

**Comment by HofiOne** [comment]
https://github.com/syslog-ng/syslog-ng/pull/5105 should fix these

**Comment by HofiOne** [comment]
> > Clang is doing something strange here:
> > ```
> >   [ 71%] Building C object modules/afsnmp/CMakeFiles/afsnmp.dir/afsnmpdest.c.o
> >   cd /opt/local/var/macports/build/_Users_runner_work_powerpc-ports_powerpc-ports_ports_sysutils_syslog-ng-devel/syslog-ng-devel/work/build/modules/afsnmp && /usr/bin/clang -DGLIB_VERSION_MIN_REQUIRED=GLIB_VERSION_2_68 -D_GNU_SOURCE=1 -D_LARGEFILE64_SOURCE=1 -D__APPLE_USE_RFC_3542 -Dafsnmp_EXPORTS -I/opt/local/var/macports/build/_Users_runner_work_powerpc-ports_powerpc-ports_ports_sysutils_syslog-ng-devel/syslog-ng-devel/work/build -I/opt/local/var/macports/build/_Users_runner_work_powerpc-ports_powerpc-ports_ports_sysutils_syslog-ng-devel/syslog-ng-devel/work/syslog-ng-71a2e4ce91b5028f7d40bd7299414c50d891582c/modules/afsnmp -I/opt/local/var/macports/build/_Users_runner_work_powerpc-ports_powerpc-ports_ports_sysutils_syslog-ng-devel/syslog-ng-devel/work/build/modules/afsnmp -I/opt/local/var/macports/build/_Users_runner_work_powerpc-ports_powerpc-ports_ports_sysutils_syslog-ng-devel/syslog-ng-devel/work/syslog-ng-71a2e4ce91b5028f7d40bd7299414c50d891582c/lib -I/opt/local/var/macports/build/_Users_runner_work_powerpc-ports_powerpc-ports_ports_sysutils_syslog-ng-devel/syslog-ng-devel/work/build/lib -isystem /opt/local/include -isystem /opt/local/include/json-c -isystem /opt/local/var/macports/build/_Users_runner_work_powerpc-ports_powerpc-ports_ports_sysutils_syslog-ng-devel/syslog-ng-devel/work/syslog-ng-71a2e4ce91b5028f7d40bd7299414c50d891582c/lib/eventlog/src -isystem /opt/local/include/glib-2.0 -isystem /opt/local/lib/glib-2.0/include -isystem /opt/local/libexec/openssl3/include -pipe -I/opt/local/libexec/openssl3/include -Os -DNDEBUG -I/opt/local/libexec/openssl3/include -isystem/opt/local/include -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -std=gnu99 -arch x86_64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -mmacosx-version-min=12.0 -fPIC -DNETSNMP_ENABLE_IPV6 -fno-strict-aliasing -g -Os -pipe -DBUILD=174 -DMACOSX_DEPLOYMENT_TARGET=12.7 --sysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -iframeworkwithsysroot /System/Library/Frameworks/-3cda-11ee-b8ac-16228a05f5d2/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.7.Internal.sdk/System/Library/PrivateFrameworks/ -3cda-11ee-b8ac-16228a05f5d2/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.7.Internal.sdk/System/Library/Frameworks/ -iwithsysroot /usr/local/libressl/include -L/AppleInternal/Library/BuildRoots/bc10cbcd-3cda-11ee-b8ac-16228a05f5d2/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.7.Internal.sdk/usr/local/libressl/lib -Udarwin21 -Ddarwin21=darwin21 -I. -I/usr/local/include -Wshadow -Wno-stack-protector -Wno-unused-parameter -Wno-variadic-macros -Wimplicit-function-declaration -Wnested-externs -Wstrict-prototypes -Wswitch-default -Wimplicit-int -Wall -Wuninitialized -Wdeprecated -Wdeprecated-declarations -Woverflow -Wdouble-promotion -Wfloat-equal -Wpointer-arith -Wpointer-sign -Wmissing-format-attribute -Wold-style-definition -Wundef -Wignored-qualifiers -Wfloat-conversion -Wbad-function-cast -MD -MT modules/afsnmp/CMakeFiles/afsnmp.dir/afsnmpdest.c.o -MF CMakeFiles/afsnmp.dir/afsnmpdest.c.o.d -o CMakeFiles/afsnmp.dir/afsnmpdest.c.o -c /opt/local/var/macports/build/_Users_runner_work_powerpc-ports_powerpc-ports_ports_sysutils_syslog-ng-devel/syslog-ng-devel/work/syslog-ng-71a2e4ce91b5028f7d40bd7299414c50d891582c/modules/afsnmp/afsnmpdest.c
> >   clang: error: unknown argument: '-3cda-11ee-b8ac-16228a05f5d2/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.7.Internal.sdk/System/Library/Frameworks/'
> >   make[2]: *** [modules/afsnmp/CMakeFiles/afsnmp.dir/afsnmpdest.c.o] Error 1
> >   make[2]: Leaving directory `/opt/local/var/macports/build/_Users_runner_work_powerpc-ports_powerpc-ports_ports_sysutils_syslog-ng-devel/syslog-ng-devel/work/build'
> >   make[1]: *** [modules/afsnmp/CMakeFiles/afsnmp.dir/all] Error 2
> >   make[1]: *** Waiting for unfinished jobs....
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > From: https://github.com/barracuda156/powerpc-ports/actions/runs/10876896823/job/30177474516
> 
> I've met this one earlier, just cannot recall what the solution was :S I'll follow up once I can remember.



> > Clang is doing something strange here:
> > ```
> >   [ 71%] Building C object modules/afsnmp/CMakeFiles/afsnmp.dir/afsnmpdest.c.o
> >   cd /opt/local/var/macports/build/_Users_runner_work_powerpc-ports_powerpc-ports_ports_sysutils_syslog-ng-devel/syslog-ng-devel/work/build/modules/afsnmp && /usr/bin/clang -DGLIB_VERSION_MIN_REQUIRED=GLIB_VERSION_2_68 -D_GNU_SOURCE=1 -D_LARGEFILE64_SOURCE=1 -D__APPLE_USE_RFC_3542 -Dafsnmp_EXPORTS -I/opt/local/var/macports/build/_Users_runner_work_powerpc-ports_powerpc-ports_ports_sysutils_syslog-ng-devel/syslog-ng-devel/work/build -I/opt/local/var/macports/build/_Users_runner_work_powerpc-ports_powerpc-ports_ports_sysutils_syslog-ng-devel/syslog-ng-devel/work/syslog-ng-71a2e4ce91b5028f7d40bd7299414c50d891582c/modules/afsnmp -I/opt/local/var/macports/build/_Users_runner_work_powerpc-ports_powerpc-ports_ports_sysutils_syslog-ng-devel/syslog-ng-devel/work/build/modules/afsnmp -I/opt/local/var/macports/build/_Users_runner_work_powerpc-ports_powerpc-ports_ports_sysutils_syslog-ng-devel/syslog-ng-devel/work/syslog-ng-71a2e4ce91b5028f7d40bd7299414c50d891582c/lib -I/opt/local/var/macports/build/_Users_runner_work_powerpc-ports_powerpc-ports_ports_sysutils_syslog-ng-devel/syslog-ng-devel/work/build/lib -isystem /opt/local/include -isystem /opt/local/include/json-c -isystem /opt/local/var/macports/build/_Users_runner_work_powerpc-ports_powerpc-ports_ports_sysutils_syslog-ng-devel/syslog-ng-devel/work/syslog-ng-71a2e4ce91b5028f7d40bd7299414c50d891582c/lib/eventlog/src -isystem /opt/local/include/glib-2.0 -isystem /opt/local/lib/glib-2.0/include -isystem /opt/local/libexec/openssl3/include -pipe -I/opt/local/libexec/openssl3/include -Os -DNDEBUG -I/opt/local/libexec/openssl3/include -isystem/opt/local/include -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -std=gnu99 -arch x86_64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -mmacosx-version-min=12.0 -fPIC -DNETSNMP_ENABLE_IPV6 -fno-strict-aliasing -g -Os -pipe -DBUILD=174 -DMACOSX_DEPLOYMENT_TARGET=12.7 --sysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -iframeworkwithsysroot /System/Library/Frameworks/-3cda-11ee-b8ac-16228a05f5d2/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.7.Internal.sdk/System/Library/PrivateFrameworks/ -3cda-11ee-b8ac-16228a05f5d2/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.7.Internal.sdk/System/Library/Frameworks/ -iwithsysroot /usr/local/libressl/include -L/AppleInternal/Library/BuildRoots/bc10cbcd-3cda-11ee-b8ac-16228a05f5d2/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.7.Internal.sdk/usr/local/libressl/lib -Udarwin21 -Ddarwin21=darwin21 -I. -I/usr/local/include -Wshadow -Wno-stack-protector -Wno-unused-parameter -Wno-variadic-macros -Wimplicit-function-declaration -Wnested-externs -Wstrict-prototypes -Wswitch-default -Wimplicit-int -Wall -Wuninitialized -Wdeprecated -Wdeprecated-declarations -Woverflow -Wdouble-promotion -Wfloat-equal -Wpointer-arith -Wpointer-sign -Wmissing-format-attribute -Wold-style-definition -Wundef -Wignored-qualifiers -Wfloat-conversion -Wbad-function-cast -MD -MT modules/afsnmp/CMakeFiles/afsnmp.dir/afsnmpdest.c.o -MF CMakeFiles/afsnmp.dir/afsnmpdest.c.o.d -o CMakeFiles/afsnmp.dir/afsnmpdest.c.o -c /opt/local/var/macports/build/_Users_runner_work_powerpc-ports_powerpc-ports_ports_sysutils_syslog-ng-devel/syslog-ng-devel/work/syslog-ng-71a2e4ce91b5028f7d40bd7299414c50d891582c/modules/afsnmp/afsnmpdest.c
> >   clang: error: unknown argument: '-3cda-11ee-b8ac-16228a05f5d2/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.7.Internal.sdk/System/Library/Frameworks/'
> >   make[2]: *** [modules/afsnmp/CMakeFiles/afsnmp.dir/afsnmpdest.c.o] Error 1
> >   make[2]: Leaving directory `/opt/local/var/macports/build/_Users_runner_work_powerpc-ports_powerpc-ports_ports_sysutils_syslog-ng-devel/syslog-ng-devel/work/build'
> >   make[1]: *** [modules/afsnmp/CMakeFiles/afsnmp.dir/all] Error 2
> >   make[1]: *** Waiting for unfinished jobs....
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > From: https://github.com/barracuda156/powerpc-ports/actions/runs/10876896823/job/30177474516
> 
> I've met this one earlier, just cannot recall what the solution was :S I'll follow up once I can remember.

This one was an SDK issue as I can remember, just like this https://github.com/orgs/Homebrew/discussions/5216
(funny fact, both came up with compiling the afsnmp module)

The latter could be fixed by using gcc14, but the one you run into can be solved only by using a newer SDK version, AFAIK
