### ISSUE TITLE
Issues with geoip2

### ISSUE THREAD

**Issue by AlexLamond** [syslog-ng/syslog-ng#5126]
# syslog-ng
## Version of syslog-ng
3.38.1

## Platform
Debian GNU/Linux 12 (bookworm)

## Issue

Hi. I am receiving syslog data from a Unifi device in the format like so:

```
Incoming log entry; input='<13>Sep 23 16:55:34 UCG-Ultra [LAN_IN-RET-20015] DESCR="Log All" IN=br3 OUT=eth4 MAC=
****** SRC=192.168.3.99 DST=1.1.1.1 LEN=60 TOS=00 PREC=0x00 TTL=127 ID=4202 PROTO=ICMP TYPE=8 CODE=0 ID=1 SEQ=18 MARK=1a0000 \x0a'
```

The kv parser is working without issue and is able to convert this to JSON KV pairs, however I have major issues with the Geoip2 system. It simply refuses to work no matter what I do. Most of the time I am greeted with the errors

```
[2024-09-23T16:55:43.452212] geoip2(): getaddrinfo failed; gai_error='Name or service not known', ip='', location='/etc/syslog-ng/syslog-ng.conf:10:19'
[2024-09-23T16:55:43.452224] geoip2(): maxminddb error; error='Unknown error code', ip='', location='/etc/syslog-ng/syslog-ng.conf:10:19'
```

Is there something wrong with my configuration, or is there something wrong with geoip2? I have tried a number of variations of code from guides online but have so far not been able to get it to work

## Configuration

```
@version: 3.37
@include "scl.conf"

source s_tcp {
    udp(ip(0.0.0.0) port(514));
};

parser p_kv {kv-parser(prefix(".kv.")); };

parser p_geoip2 { geoip2( "${kv.SRC}", prefix( "geoip2." ) database( "/etc/syslog-ng/GeoCity.mmdb" ) ); };

destination d_mesg { file("/var/log/syslogmessages.json"
        template("$(format-json --scope dot-nv-pairs --scope rfc5424)\n"));
 };

log {
  source(s_tcp);
  parser(p_kv);
  parser(p_geoip2);
  destination(d_mesg);
};

```

**Comment by HofiOne** [comment]
> ```
> [2024-09-23T16:55:43.452212] geoip2(): getaddrinfo failed; gai_error='Name or service not known', ip='', location='/etc/syslog-ng/syslog-ng.conf:10:19'
> [2024-09-23T16:55:43.452224] geoip2(): maxminddb error; error='Unknown error code', ip='', location='/etc/syslog-ng/syslog-ng.conf:10:19'
> ```

This log snippet shows that the parsed `ip` field passed to the `geoip` resolution is empty.

I suggest first, please start `syslog-ng` with the `-Fdevt` parameters and check the detailed logs on how the incoming messages are parsed, and for further possible issue logs about the message parsing and processing.
