### ISSUE TITLE
The underscore in tag names from the XML parser should be possible to turn off

### ISSUE THREAD

**Issue by czanik** [syslog-ng/syslog-ng#5140]
While working with FreeBSD audit logs, the XML parser generates name-value pairs, where the name of the tags start with an underscore ```_```
```
"fbaudit.record.subject._uidit-uid":"root"
```
It looks ugly / confusing, however there does not seem to be a way to remove it later in templates.

It would be nice to have an option to disable the underscore for tags.

**Comment by HofiOne** [comment]
Duplication of https://github.com/syslog-ng/syslog-ng/issues/5139

**Comment by HofiOne** [comment]
The underscore denotes an XML attribute in the flat representation; without it, it would be impossible to reconstruct the original structure and reproduce the correct XML version of the stored data.

A possible improvement would be to introduce an option to customize the character used to denote the attribute.
