### ISSUE TITLE
Error invoking seek on file; filename='/dev/kmsg', error='Invalid argument (22)' also with syslog-ng-4.8.1

### ISSUE THREAD

**Issue by jospezial** [syslog-ng/syslog-ng#5159]
# syslog-ng
## Version of syslog-ng
First seen with 4.8.0 but still with 4.8.1

## Platform
Gentoo
Linux jlgentoo 6.12.0-rc3 #1 SMP PREEMPT_DYNAMIC Mon Oct 14 05:26:53 CEST 2024 x86_64 AMD Athlon(tm) II X2 255 Processor AuthenticAMD GNU/Linux

# Issue
## Failure

```Error invoking seek on file; filename='/dev/kmsg', error='Invalid argument (22)'```
is added to /var/log/messages
## Steps to reproduce

I mostly see it when I plug an USB device.
## Configuration

```
@version: 4.8
#
# Syslog-ng default configuration file for Gentoo Linux

# https://bugs.gentoo.org/426814
@include "scl.conf"

options {
        threaded(yes);
        chain_hostnames(no);

        # The default action of syslog-ng is to log a STATS line
        # to the file every 10 minutes.  That's pretty ugly after a while.
        # Change it to every 12 hours so you get a nice daily update of
        # how many messages syslog-ng missed (0).
        stats(freq(43200));
        # The default action of syslog-ng is to log a MARK line
        # to the file every 20 minutes.  That's seems high for most
        # people so turn it down to once an hour.  Set it to zero
        # if you don't want the functionality at all.
        mark_freq(3600);
};

source src { system(); internal(); };

destination messages { file("/var/log/messages"); };

# By default messages are logged to tty12...
destination console_all { file("/dev/tty12"); };
# ...if you intend to use /dev/console for programs like xconsole
# you can comment out the destination line above that references /dev/tty12
# and uncomment the line below.
#destination console_all { file("/dev/console"); };

log { source(src); destination(messages); };
log { source(src); destination(console_all); };
```
I was hoping it was fixed with #5058 but no.

**Comment by jospezial** [comment]
See also #5057

**Comment by HofiOne** [comment]
Hi, thanks for the report, we will investigate it.

**Comment by PerfMonk** [comment]
Same problem here on RedcoreLinux kernel 6.11.5 and syslog-ng version 4.8.1.  Watching thread for eventual solution.

**Comment by HofiOne** [comment]
@jospezial @PerfMonk @zen2 could any of you please start syslog-ng with params `syslog-ng -devt` params and attach the full output log here (I'm curious what polling methods ivykis uses on those systems, on mine there is no similar issue currently)

**Comment by navid-zamani** [comment]
@HofiOne: Like this?

[Log of `syslog-ng -devt` on affected system](https://github.com/user-attachments/files/17679011/syslog-ng_-devt.log)

**Comment by HofiOne** [comment]
perfect, thank you!

**Comment by navid-zamani** [comment]
@HofiOne: [IV_EXCLUDE_POLL_METHOD="epoll-timerfd" syslog-ng -devt.log](https://github.com/user-attachments/files/17679281/IV_EXCLUDE_POLL_METHOD.epoll-timerfd._syslog-ng_-devt.log)

**Comment by HofiOne** [comment]
> @HofiOne: [IV_EXCLUDE_POLL_METHOD="epoll-timerfd" syslog-ng -devt.log](https://github.com/user-attachments/files/17679281/IV_EXCLUDE_POLL_METHOD.epoll-timerfd._syslog-ng_-devt.log)

@navid-zamani thanks!

these are all the methods ivykis currently supports

`IV_EXCLUDE_POLL_METHOD="port-timer port dev_poll epoll-timerfd epoll kqueue ppoll poll"`

you can turn off all of them with the line above, then removing them one by one can help you to find a working method (if there's any)

could you be that kind and try this, let us see if there is any working one?

also, could you please answer the [enhanced questions above](https://github.com/syslog-ng/syslog-ng/issues/5159#issuecomment-2464697422)?

**Comment by navid-zamani** [comment]
> also, could you please answer the [enhanced questions above](https://github.com/syslog-ng/syslog-ng/issues/5159#issuecomment-2464697422)?

* I’m running Gentoo. Does that count as built myself?  
* Here’s the ebuild (basically contains everything that’s different from just basic configure and make): [syslog-ng-4.8.1.ebuild](https://gitweb.gentoo.org/repo/gentoo.git/tree/app-admin/syslog-ng/syslog-ng-4.8.1.ebuild)  
And here’s what USE flags it was built with and all the necessary related system infos: [emerge --info syslog-ng](https://github.com/user-attachments/files/17679551/emerge.--info.syslog-ng.txt)  
It’s just a standard installation though. I didn’t set anything.
* ivykis version 0.43.1

> could you be that kind and try this, let us see if there is any working one?

I can’t right now, but if I find the time, I’ll try it in the next 48 hours.

.

Also, if you edit comments after I’ve replied, I can’t see that. :)

**Comment by HofiOne** [comment]
> > also, could you please answer the [enhanced questions above](https://github.com/syslog-ng/syslog-ng/issues/5159#issuecomment-2464697422)?
> 
>     * I’m running Gentoo. Does that count as built myself?
> 
>     * Here’s the ebuild (basically contains everything that’s different from just basic configure and make): [syslog-ng-4.8.1.ebuild](https://gitweb.gentoo.org/repo/gentoo.git/tree/app-admin/syslog-ng/syslog-ng-4.8.1.ebuild)
>       And here’s what USE flags it was built with and all the necessary related system infos: [emerge --info syslog-ng](https://github.com/user-attachments/files/17679551/emerge.--info.syslog-ng.txt)
>       It’s just a standard installation though. I didn’t set anything.
> 
>     * ivykis version 0.43.1
> 

thanks for the answers

> 
> > could you be that kind and try this, let us see if there is any working one?
> 
> I can’t right now, but if I find the time, I’ll try it in the next 48 hours.
> 

never mind, I will add a bit more detailed check on if the file is readable before calling the seek on it, that will eliminate the error message

thanks for your help!

**Comment by thulle** [comment]
Tried the patch on top of 4.8.1 and it works great to fix the issue. 
Corsair PSU:s with USB reconnects as a new device after every poll, which triggered the issue, so I had the error every 5th second in the logs. Now entirely gone.

**Comment by HofiOne** [comment]
> Tried the patch on top of 4.8.1 and it works great to fix the issue. Corsair PSU:s with USB reconnects as a new device after every poll, which triggered the issue, so I had the error every 5th second in the logs. Now entirely gone.

nice to hear it, thank you for testing it out!
it will be merged on Monday hopefully.
thank you for all your feedback!

**Comment by PerfMonk** [comment]
I'm still having the error messages from syslog-ng.  Is the patch pushed in production or is it available somewhere ?
I'm on Redcore linux with syslog-ng 4.8.1 (2024-10-18 12:21:23),  ivykis 0.43.1 (2024-09-28 11:57:10).

**Comment by czanik** [comment]
The fix is already merged to git master, but not yet available as part of a release. Should be part of 4.8.2, no release date set in stone yet.
If you run Fedora / RHEL / openSUSE / SLES, then you can use my git snapshot repos: https://www.syslog-ng.com/community/b/blog/posts/rpm-packages-from-syslog-ng-git-head/
