### ISSUE TITLE
syslog-ng.conf is not a man page, but refers to links that are broken and lead to the equivalent of a blank page.

### ISSUE THREAD

**Issue by navid-zamani** [syslog-ng/syslog-ng#5160]
## Documentation version

I just checked the xml the man is based on in this repository, seconds ago. It’s the same as what I’ve installed (4.8.0).

## Incorrect section

All of it. Esp. the notes and the description.

## Description of the problem

It’s not a man page. It’s just an abstract, and refers to some URLs in the notes for the actual job that the man page is there for. And those URLs lead to hollow coprorat vomit that, in its usefulness for documenting things, is even worse than about:blank. As it typical for everything coprorat.

## Proposed solution

Disband Balabit, the business, and leave syslog-ng to humans… But in lack of that: Create an actual man page that actually documents the configuration of syslog-ng, … or leave the open source community and head back to Ferengon.  
Either is fine with us. 😋  
(Shoutout to the maintainer of this. I don’t mean you, unless you cooperate with them. In the latter case, ask me what my grandpa did to the local Gielemännchen after the war. ;)

**Comment by czanik** [comment]
Thank you for the comment. We are aware of the problem, and have plans fixing it, even if not short term. Of course, pull requests are welcome!
