### ISSUE TITLE
timeQuality isSynced is missing from sdata

### ISSUE THREAD

**Issue by pzoleex** [syslog-ng/syslog-ng#529]
Cisco routers can specify some additional information in their timestamp:
- whether the timestamp is accurate
- whether the sender has TZ information

this should be added to SDATA when ietf-syslog protocol is used. PE already knows it:

```
<38>1 1990-01-01T14:45:22+02:00 localhost prg00000 1234 - [timeQuality isSynced="0" tzKnown="1"] test message
```

```
config:
@version: 3.7
options{
};
source s_syslog{syslog(port(1112)
);};

destination d_syslog_file{file("/tmp/output_syslog.txt"
flags(syslog-protocol)
);};

log{
source(s_syslog);
destination(d_syslog_file);
};
options{threaded(yes);};
```

message:

```
echo "73 <38>1 1990-01-01T14:45:22+02:00 localhost prg00000 1234 - - test message" | /opt/syslog-ng/bin/loggen 127.0.0.1 1112 -d -R -
```

**Comment by ihrwein** [comment]
Just some useful information:

> Cisco IOS uses a special convention for time prefixes to indicate the accuracy of the time stamp. If dot character appears before the date, it means that the local time was synchronized at some point via NTP, but currently no NTP servers are available. The asterisk character in front of the date means that the local time is not authoritative, i.e. NTP servers are not setup.

**Comment by dnsjts** [comment]
According to the clarification by @pzoleex , the question (or one of the questions) is what should we do, if it is unknown whether the clock of the sender is in sync, or not.
The answers are quite different in the two versions (assume is not in sync, versus do not assume anything), and we should choose one in order to push forward the merge.

**Comment by bazsi** [comment]
Well, yes but this is communicated by the Cisco routers in the rfc3164 format and then pe can convert this on rfc5424 output.

**Comment by dnsjts** [comment]
Indeed, but it is not communicated by the non-Cisco devices.
When we convert these messages, should we add the isSynced=0 to the SDATA, or not? (PE adds this, OSE doesn't.)

**Comment by bazsi** [comment]
I think we should only add this if we have the information.

**Comment by gaborznagy** [comment]
I'm closing this. I don't think our opinion changed that `isSynced` should be added by default.
