### ISSUE TITLE
Idea: enable -Wundef and refactor conflicting #if usage to #ifdef

### ISSUE THREAD

**Issue by bkil-syslogng** [syslog-ng/syslog-ng#956]
The compiler can help us detect misconfiguration if we never use undefined symbols. This means that we should always `#define` a configuration option, even if it is `FALSE` (`0`).

An alternative would be to alter some of the condition checks to use `#ifdef` instead. Because in some cases, both of them could look nice, we probably need to either stick to one convention or the other, or start using a prefixing convention to help differentiate between a macro for which a value check is needed vs. an existence check.

Caught one in #954 (and some others in the past)

**Comment by Kokan** [comment]
Closes #2806
