### ISSUE TITLE
Enterprise ID in format-json keys

### ISSUE THREAD

**Issue by MrAnno** [syslog-ng/syslog-ng#973]
Hi,

Is it a right behavior that syslog-ng looks for an [enterpriseId](https://tools.ietf.org/html/rfc5424#section-7.2.2) while it is tokenizing keys in `format-json`?

```
$(format-json asd@1234.56.678=${PROGRAM});
```

Actual result:

``` json
{  
   "asd@1234.56.678":"syslog-ng"
}
```

In my opinion, the tokenizer shouldn't skip a string that looks like an enterpriseId:

``` json
{  
   "asd@1234":{  
      "56":{  
         "678":"syslog-ng"
      }
   }
}
```

**Comment by bazsi** [comment]
Hi,

Yes it is intended.

commit e26d407d5d5a77e167797faa69aae2429c380325
Author: Gergely Nagy <algernon@balabit.hu>
Date:   Thu Dec 5 12:27:03 2013 +0100

    value-pairs: Handle SDATA enterprise IDs correctly

    RFC5424 SDATA IDs are of the form "[win@18372.4 foo=bar]", which
    translates to "sdata.win@18372.4.foo=bar" internally. In this case, we
    should not split the "4" into a separate object, but treat it as part of
    the sdata ID.

    To do this, the name splitting was enhanced, and instead of splitting by
    every dot, it will look for @ too, and only split a token off after
    that, if a dot is followed by a non-number. A test case to verify the
    behaviour is also included.

    Signed-off-by: Tibor Benke <btibi@balabit.hu>
    Signed-off-by: Gergely Nagy <algernon@balabit.hu>


-- 
Bazsi

**Comment by ihrwein** [comment]
Elasticsearch 2.0 doesn't support fields names with dots:

https://www.elastic.co/guide/en/elasticsearch/reference/2.0/breaking_20_mapping_changes.html#_field_names_may_not_contain_dots

This is a breaking change from their side (and perfectly reasonable). One solution would be what @MrAnno proposed, one other is replacing dots with underscores (with has performance impact).

I don't know what is the preferred way from the users perspective. I hope @czanik or @faxm0dem (or anyone) can give us some hints :)

**Comment by bazsi** [comment]
I agree it is reasonable, on the other hand  asd@1234.56.678 is a single
field and it'd be an error to create a tree from that. Value-pairs is able
to do a replace on key values and that was added exactly for this reason,
but I agree that it is not intuitive enough.

Probably we should add a switch to format-json (on by default) that causes
dots to be mapped to underscores in keys.


-- 
Bazsi

**Comment by faxm0dem** [comment]
dots are indeed forbidden in ES2
If I understand this issue correctly the proposed change is *not* to deserialize `a@1.2.3` into `{a@1: {1:{2: 3}}}`?

**Comment by bazsi** [comment]
I would do it as a@1_2_3

I guess numbers wouldn't be accepted in object notation either.

-- 
Bazsi

**Comment by faxm0dem** [comment]
as far as ES is concerned, numbers are okay for key names (I just tested it).
`a@1_2_3` seems good to me, but please don't do this for all keys: I'm relying on the current `format-json`'s object deflation behaviour

**Comment by MrAnno** [comment]
Hi @faxm0dem,

> If I understand this issue correctly the proposed change is not to deserialize a@1.2.3 into {a@1: {1:{2: 3}}}?

The **current** implementation deserializes `asd@1234.56.678=syslog-ng` into `{"asd@1234.56.678":"syslog-ng"}`. This is because syslog-ng doesn't tokenize anything that looks like an enterprise ID (`name@<private enterprise number>`).

I was just wondering whether it is the proper behavior. The key of the JSON object is typed manually in the config file, so I thought syslog-ng should _not_ detect enterprise IDs here.

**Comment by faxm0dem** [comment]
I'd say it's the user's responsibility to do the right thing here, but I'm not sure what's the best course of action

**Comment by czanik** [comment]
By default I'd tokenize all keys, including enterprise ID. This would make it consistent and make it work out of the box with ES2.
Using "." or "_" should be a user configurable option.
