### ISSUE TITLE
Make the length of the SDATA param-value adjustable

### ISSUE THREAD

**Issue by MrAnno** [syslog-ng/syslog-ng#998]
The SDATA param-value length is not limited in [RFC 5424](https://tools.ietf.org/html/rfc5424#section-6.3). Based on [this commit](https://github.com/balabit/syslog-ng/commit/bf69c41f696e7d94e424a40f5979bd5efcb33179), I think it is a good idea to make it configurable.

**Comment by juhaszviktor** [comment]
:+1:

My opinion is, that allocating 64KB on stack not the best. We should allocate it in the heap, especially we make it configurable

**Comment by bazsi** [comment]
Well, this is used on a per message fast path, doing an allocation at every invocation is a bad idea.

Allocating it once and reusing it might work but take care about threads preferably in a way that avoids locks.

**Comment by MrAnno** [comment]
Closing, as `65535` seemed to be enough as an SDATA length for everyone since then.

Feel free to comment on this issue if this limitation causes problems in your use case, and I will reopen it.
